# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Red Hat, Inc.
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# András Bögöly <ebogoly@gmail.com>, 2011.
# Arpad Biro <biro_arpad@yahoo.com>, 2004-2007.
# dcantrel <dcantrell@redhat.com>, 2011.
# Dimitris Glezos <glezos@indifex.com>, 2011.
# Gabor Mako <makgab@m-info.hu>, 2011.
# Gabor SUVEG <gabor@suveg.hu>, 2004.
# Máté Gelei <gelei.mate1@gmail.com>, 2011.
# Peter Borsa <peter.borsa@gmail.com>, 2011.
#   <ptr@ulx.hu>, 2011-2012.
# Zoltan Hoppár <hopparz@gmail.com>, 2011-2012.
msgid ""
msgstr ""
"Project-Id-Version: Anaconda\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2013-01-07 16:55-0800\n"
"PO-Revision-Date: 2013-01-04 23:55+0000\n"
"Last-Translator: Brian Lane <bcl@redhat.com>\n"
"Language-Team: Hungarian <trans-hu@lists.fedoraproject.org>\n"
"Language: hu\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"

#: anaconda:344
#, c-format
msgid ""
"%s requires %s MB of memory to install, but you only have %s MB on this "
"machine.\n"
msgstr ""
"%s szükséges %s MB memória a telepítéshez, de csak %s MB elérhető ezen a "
"gépen.\n"

#: anaconda:346
#, c-format
msgid ""
"The %s graphical installer requires %s MB of memory, but you only have %s MB."
msgstr ""
"A %s grafikus telepítő %s MB memóriát igényel, de csak %s MB a telepített."

#: anaconda:351
msgid "Not enough RAM"
msgstr "Nincs elég RAM"

#: anaconda:352
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""
" Próbálja ki a szöveges módú telepítő futtatását ezzel:\n"
"\n"
"\"/ usr / bin / liveinst-T\"\n"
"\n"
"root terminálból."

#: anaconda:355
msgid " Starting text mode."
msgstr "Szöveges mód indítása."

#: anaconda:382 pyanaconda/rescue.py:268 pyanaconda/rescue.py:301
#: pyanaconda/rescue.py:314 pyanaconda/rescue.py:382 pyanaconda/rescue.py:398
#: pyanaconda/rescue.py:409
msgid "OK"
msgstr "OK"

#: anaconda:484
msgid ""
"Text mode provides a limited set of installation options. It does not allow "
"you to specify your own partitioning layout or package selections. Would you "
"like to use VNC mode instead?"
msgstr ""
"A szöveges mód korlátozott telepítési lehetőségeket biztosít. Nincs "
"lehetőség saját kezű particionálásra vagy csomagválasztásra. Szeretné inkább "
"a VNC módot használni?"

#: anaconda:508
msgid "DISPLAY variable not set. Starting text mode."
msgstr "DISPLAY változó nincs beállítva. Szöveges mód indítása."

#: anaconda:516
msgid "Graphical installation is not available. Starting text mode."
msgstr "Grafikus telepítés nem érhető el. Szöveges mód indítása."

#: anaconda:627
#, c-format
msgid "Please ssh install@%s to begin the install."
msgstr ""
"Kérem alkalmazza az ssh install@%s parancsot a telepítés megkezdéséhez."

#: anaconda:629
msgid "Please ssh install@<host> to continue installation."
msgstr ""
"Kérem alkalmazza az ssh install@<host> parancsot a telepítés folytatásához."

#: pyanaconda/bootloader.py:239
msgid "/boot filesystem"
msgstr "/boot fájlrendszer"

#: pyanaconda/bootloader.py:388
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following raid levels: %s."
msgstr ""
"A RAID tömbnek ami tartalmazza '%s' részt legalább a következő raid szintek "
"közül egyre szüksége van: %s. "

#: pyanaconda/bootloader.py:396
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following metadata "
"versions: %s."
msgstr ""
"A '%s' RAID beállításoknak a következő metaadat verziók egyikét kell "
"tartalmaznia: %s."

#: pyanaconda/bootloader.py:404
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following device types: %s."
msgstr ""
"A '%s' RAID beállításoknak a következő eszköztípusok egyikét kell "
"tartalmaznia: %s."

#: pyanaconda/bootloader.py:420
#, python-format
msgid "%s must have one of the following disklabel types: %s."
msgstr "%s a következő lemezcímkék egyikét kell tartalmaznia: %s."

#: pyanaconda/bootloader.py:432
#, python-format
msgid "%s cannot be of type %s."
msgstr "%s nem lehet %s. típusú"

#: pyanaconda/bootloader.py:438
#, python-format
msgid "%s must be mounted on one of %s."
msgstr "%s csatolva kell hogy legyen a az egyikhez: %s"

#: pyanaconda/bootloader.py:450
#, python-format
msgid "%s must be between %d and %d MB in size"
msgstr "%s %d és %d MB között kell lennie méretben"

#: pyanaconda/bootloader.py:455
#, python-format
msgid "%s must not be smaller than %dMB."
msgstr "%s nem lehet kisebb, mint %d MB."

#: pyanaconda/bootloader.py:464
#, python-format
msgid "%s must not be larger than %dMB."
msgstr "%s nem lehet nagyobb, mint %d MB."

#: pyanaconda/bootloader.py:482
#, python-format
msgid "%s must be within the first %dMB of the disk."
msgstr "A %s a lemez első %dMB-ján belül kell legyen."

#: pyanaconda/bootloader.py:492
#, python-format
msgid "%s must be on a primary partition."
msgstr "%s az elsődleges partícíón kell hogy legyen."

#: pyanaconda/bootloader.py:616 pyanaconda/bootloader.py:706
#, python-format
msgid "%s cannot be on an encrypted block device."
msgstr "%s nem lehet titkosított blokkeszközön. "

#: pyanaconda/bootloader.py:664
#, python-format
msgid "%s cannot be of type %s"
msgstr "%s nem lehet %s típusú"

#: pyanaconda/bootloader.py:1585
#, python-format
msgid ""
"%s may not have enough space for grub2 to embed core.img when using the %s "
"filesystem on %s"
msgstr ""
"Előfordulhat, h itt: %s nincs elegendő szabad területe a grub2 számára, hogy "
"befogadja a core.img fájlt ha %s használ %s fájlrendszeren"

#: pyanaconda/cmdline.py:66
msgid "Completed"
msgstr "Kész"

#: pyanaconda/cmdline.py:74
msgid "In progress"
msgstr "Folyamatban"

#: pyanaconda/cmdline.py:87
#, python-format
msgid ""
"(%s)\n"
"Command line mode requires all choices to be specified in a kickstart "
"configuration file."
msgstr ""
"(%s)\n"
"A parancssoros módhoz minden választást meg kell adni a kickstart "
"konfigurációs fájlban."

#: pyanaconda/cmdline.py:104
#, python-format
msgid ""
"The following error was found while parsing the kickstart configuration "
"file:\n"
"\n"
"%s"
msgstr ""
"A következő hiba merült fel a kickstart konfigurációs fájl értelmezése "
"közben:\n"
"\n"
"%s"

#: pyanaconda/cmdline.py:113
#, python-format
msgid ""
"(%s)\n"
"%s"
msgstr ""
"(%s)\n"
"%s"

#: pyanaconda/cmdline.py:126 pyanaconda/cmdline.py:131
#: pyanaconda/cmdline.py:137 pyanaconda/cmdline.py:142
#: pyanaconda/ui/tui/hubs/summary.py:58
msgid "Can't have a question in command line mode!"
msgstr "Nem lehet kérdezni parancssoros módban!"

#: pyanaconda/cmdline.py:161
#, python-format
msgid "In interactive step can't continue. (%s)"
msgstr "Interaktív lépésben nem folytatódhat. (%s)"

#: pyanaconda/constants.py:57
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""
"Kezeletlen kivétel történt.  A legvalószínűbb, hogy ez programhiba.  Kérem, "
"másolja ki a kivétel teljes szövegét, és adjon fel egy hibabejelentést"

#: pyanaconda/constants.py:63
msgid " with the provider of this software."
msgstr " e szoftver szállítójának."

#: pyanaconda/constants.py:67
#, python-format
msgid " against anaconda at %s"
msgstr " anaconda tárggyal %s helyen"

#: pyanaconda/constants.py:95
msgid "Start VNC"
msgstr "VNC indítása"

#: pyanaconda/constants.py:96
msgid "Use text mode"
msgstr "Szöveges mód használata"

#: pyanaconda/install.py:59
msgid "Configuring installed system"
msgstr "Telepített rendszer beállítása"

#: pyanaconda/install.py:71
msgid "Writing network configuration"
msgstr "Hálózati beállítások rögzítése"

#: pyanaconda/install.py:75
msgid "Creating users"
msgstr "Felhasználók hozzáadása"

#: pyanaconda/install.py:82
msgid "Running post install scripts"
msgstr "Zárótelepítési szkriptek futtatása"

#: pyanaconda/install.py:130 pyanaconda/packaging/livepayload.py:133
#: pyanaconda/packaging/yumpayload.py:1631
msgid "Performing post-install setup tasks"
msgstr "Telepítés utáni konfigurációs feladatok végrehajtása"

#: pyanaconda/install.py:134
msgid "Installing bootloader"
msgstr "Rendszerbetöltő telepítése"

#: pyanaconda/installclass.py:68
msgid "Install on System"
msgstr "Telepítés a rendszerre"

#: pyanaconda/installinterfacebase.py:51
msgid "Error Setting Up Repository"
msgstr "Hiba a tároló beállítása közben"

#: pyanaconda/installinterfacebase.py:52
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Installation can not continue."
msgstr ""
"A következő hiba merült fel a telepítési tároló beállítása során:\n"
"\n"
"%(e)s\n"
"\n"
"A telepítés itt megszakad."

#: pyanaconda/installinterfacebase.py:58
msgid "Exit installer"
msgstr "Kilépés a telepítőből"

#: pyanaconda/installinterfacebase.py:62
#, python-format
msgid ""
"The installation was stopped due to what seems to be a problem with your "
"hardware. The exact error message is:\n"
"\n"
"%s.\n"
"\n"
" The installer will now terminate."
msgstr ""
"A telepítés megállt valószínűleg hardverhiba miatt. A pontos hibaüzenet a "
"következő:\n"
"\n"
"%s.\n"
"\n"
"A telepítő most bezárul."

#: pyanaconda/installinterfacebase.py:65
msgid "Hardware Error Encountered"
msgstr "Hardver hiba lépett fel"

#: pyanaconda/installinterfacebase.py:69 pyanaconda/yuminstall.py:263
#: pyanaconda/yuminstall.py:409 pyanaconda/yuminstall.py:835
#: pyanaconda/yuminstall.py:1013 pyanaconda/yuminstall.py:1018
#: pyanaconda/yuminstall.py:1055 pyanaconda/yuminstall.py:1107
#: pyanaconda/yuminstall.py:1113 pyanaconda/yuminstall.py:1269
#: pyanaconda/yuminstall.py:1284 pyanaconda/yuminstall.py:1339
#: pyanaconda/yuminstall.py:1534 pyanaconda/yuminstall.py:1567
#: pyanaconda/yuminstall.py:1590
msgid "_Exit installer"
msgstr "_Kilépés a telepítőből"

#: pyanaconda/iutil.py:898
msgid "the device containing /boot"
msgstr "az eszköz tartalmaz /boot könyvtárat"

#: pyanaconda/iutil.py:900
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from %s to continue installation."
msgstr ""
"Leállás után, kérjük, végezzen el egy kézi IPL-t %s-től a telepítés "
"folytatásához."

#: pyanaconda/kickstart.py:155
#, python-format
msgid "Escrow certificate %s requires the network."
msgstr "Aláírt igazolás szükséges a %s hálózat eléréséhez."

#: pyanaconda/kickstart.py:163
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"A következő hiba lépett fel, míg a letéti igazolás letöltés alatt volt:\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:482
#, python-format
msgid "%s is missing. Cannot setup firewall."
msgstr "%s hiányzik. Így a tűzfal nem állítható be."

#: pyanaconda/kickstart.py:1466
msgid "Running pre-installation scripts"
msgstr "Telepítés előkészítési szkriptek futtatása"

#: pyanaconda/network.py:94
msgid "Hostname cannot be None or an empty string."
msgstr "Kiszolgáló neve nem lehet None, vagy üres szöveg."

#: pyanaconda/network.py:97
msgid "Hostname must be 255 or fewer characters in length."
msgstr "A gazdanév legfeljebb 255 jelből állhat."

#: pyanaconda/network.py:103
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or "
"'0-9'"
msgstr ""
"A gazda név első betűje az „a-z”, „A-Z” vagy „0-9” intervallumban kell "
"legyen."

#: pyanaconda/network.py:111
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.', "
"parts between periods must contain something and cannot start or end with "
"'-'."
msgstr ""
"Kiszolgáló nevek csak 'a-z', 'A-Z', '0-9', '-', or '.' karaktereket "
"tartalmazhatnak, és a vesszővel ellátott részek közt tartalmazniuk kell "
"valamit, és nem kezdődhetnek vagy végződhetnek '-' jellel."

#: pyanaconda/network.py:168
msgid "IP address is missing."
msgstr "IP cím hiányzik."

#: pyanaconda/network.py:172
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""
"IPv4 cím 4 darab, 0 és 255 közé eső, egymástól ponttal elválasztott számot "
"kell tartalmazzon."

#: pyanaconda/network.py:175
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr "„%s” nem érvényes IPv6 cím."

#: pyanaconda/network.py:177
#, python-format
msgid "'%s' is an invalid IP address."
msgstr "„%s” érvénytelen IP cím."

#: pyanaconda/platform.py:58
msgid "bootloader device"
msgstr "rendszertöltő eszköz"

#: pyanaconda/platform.py:59
msgid "RAID Device"
msgstr "RAID eszköz"

#: pyanaconda/platform.py:60
msgid "First sector of boot partition"
msgstr "A rendszerindító rész első szektora"

#: pyanaconda/platform.py:158 pyanaconda/platform.py:341
msgid "Master Boot Record"
msgstr "Master Boot Record"

#: pyanaconda/platform.py:194
msgid "EFI System Partition"
msgstr "EFI rendszer partíció"

#: pyanaconda/platform.py:223
msgid "Apple EFI Boot Partition"
msgstr "Apple EFI boot partíció"

#: pyanaconda/platform.py:248
msgid "PReP Boot Partition"
msgstr "PReP Boot Partició"

#: pyanaconda/platform.py:271
msgid "Apple Bootstrap Partition"
msgstr "Apple Bootstrap Partició"

#: pyanaconda/platform.py:300
msgid "DASD"
msgstr "DASD"

#: pyanaconda/platform.py:301
msgid "zFCP"
msgstr "zFCP"

#: pyanaconda/platform.py:366
msgid "U-Boot Partition"
msgstr "U-Boot partícíó"

#: pyanaconda/product.py:54
#, python-format
msgid "%(productName)s %(productVersion)s INSTALLATION"
msgstr "%(productName)s %(productVersion)s TELEPÍTÉS"

#: pyanaconda/rescue.py:171 pyanaconda/rescue.py:290 pyanaconda/rescue.py:375
#, python-format
msgid "Run %s to unmount the system when you are finished."
msgstr "A(z) %s futtatása a rendszer leválasztásához ha végzett."

#: pyanaconda/rescue.py:174
msgid "When finished please exit from the shell and your system will reboot."
msgstr ""
"Amint elkészült, kérem lépjen ki a rendszerhéjból, és a rendszer újra fog "
"indulni."

#: pyanaconda/rescue.py:188
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr "Nem találom a futtatandó /bin/sh-t!  Nem indítok parancssort"

#: pyanaconda/rescue.py:224 pyanaconda/rescue.py:297 pyanaconda/rescue.py:307
#: pyanaconda/rescue.py:378 pyanaconda/rescue.py:409
msgid "Rescue"
msgstr "Mentés"

#: pyanaconda/rescue.py:225
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.  \n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""
"A mentési rendszer megpróbálja megtalálni a Linux telepítését és csatolja "
"majd a %s könyvtár alá. Ezek után bármilyen szükséges változtatást megtehet "
"a rendszerén. Ha ezzel a lépéssel kívánja folytatni válassza a 'Tovább' "
"opciót. Továbbá felcsatolhatja a fájlrendszereit csak olvasható módban, az "
"eredeti írható-olvasható mód helyett ha a 'Csak olvasható'-t válassza. \n"
"\n"
"Ha bármilyen okból ez az eljárás problémás jelentene választhatja a "
"'Kihagyás' opciót, és ezzel minden művelet nélkül azonnal parancssorba "
"kerül.\n"
"\n"

#: pyanaconda/rescue.py:235 pyanaconda/storage/devicetree.py:96
msgid "Continue"
msgstr "Folytatás"

#: pyanaconda/rescue.py:235 pyanaconda/rescue.py:241
msgid "Read-Only"
msgstr "Csak olvasható"

#: pyanaconda/rescue.py:235 pyanaconda/rescue.py:237
msgid "Skip"
msgstr "Kihagyás"

#: pyanaconda/rescue.py:265
msgid "System to Rescue"
msgstr "Mentendő rendszer"

#: pyanaconda/rescue.py:266
msgid "Which device holds the root partition of your installation?"
msgstr "Melyik rész tartalmazza a meglévő rendszer root partícióját?"

#: pyanaconda/rescue.py:268 pyanaconda/rescue.py:272
msgid "Exit"
msgstr "Kilépés"

#: pyanaconda/rescue.py:287 pyanaconda/rescue.py:372
msgid "The system will reboot automatically when you exit from the shell."
msgstr "A rendszer automatikusan újraindul, amikor kilép a parancssorból."

#: pyanaconda/rescue.py:298
#, python-format
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions. %s"
msgstr ""
"A rendszerének voltak nem tiszta fájlrendszerei, amelyeket úgy döntött, nem "
"csatlakoztat.  Nyomja meg az entert, hogy a parancsértelmezőbe jusson, "
"ahonnan fsck-t indíthat és csatolhatja a partícióit. %s"

#: pyanaconda/rescue.py:308
#, python-format
msgid ""
"Your system has been mounted under %(rootPath)s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"
msgstr ""
"A rendszer csatlakoztatva lett ide: %(rootPath)s .\n"
"\n"
"Nyomja meg az <Enter>-t hogy a parancsértelmezőbe jusson. Ha szeretné, hogy "
"a rendszere a root környezetet elkészítse, adja ki ezt a parancsot:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"

#: pyanaconda/rescue.py:379
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell."
msgstr ""
"Hiba történt a csatolási művelet részét vagy egészét érintően a "
"rendszerében. Néhányukat talán fel lehet csatolni ide: %s.\n"
"\n"
"Nyomja meg az <Enter>-t hogy a parancsértelmezőbe jusson."

#: pyanaconda/rescue.py:387
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr "Nincs semmilyen Linux partíciója.  Újraindulás.\n"

#: pyanaconda/rescue.py:391
msgid " The system will reboot automatically when you exit from the shell."
msgstr "A rendszer automatikusan újraindul, amikor kilép a parancssorból."

#: pyanaconda/rescue.py:395
msgid "Rescue Mode"
msgstr "Mentő mód"

#: pyanaconda/rescue.py:396
#, python-format
msgid "You don't have any Linux partitions. Press return to get a shell.%s"
msgstr ""
"Nem rendelkezik semmilyen Linux partícióval. Térjen vissza enterrel, hogy "
"terminált kaphasson. %s"

#: pyanaconda/rescue.py:408
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "A rendszer becsatolva %s ponton."

#: pyanaconda/vnc.py:61
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr " %(productName)s %(productVersion)s telepítése"

#: pyanaconda/vnc.py:118
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr " %(productName)s %(productVersion)s telepítése a %(name)s kiszolgálóra"

#: pyanaconda/vnc.py:137
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "Csatlakozás %s gazdán levő vnc ügyfélhez..."

#: pyanaconda/vnc.py:151
msgid "Connected!"
msgstr "Kapcsolódva!"

#: pyanaconda/vnc.py:154
msgid "Will try to connect again in 15 seconds..."
msgstr "Újabb próbálkozás 15 másodperc múlva..."

#: pyanaconda/vnc.py:160
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] "Feladom a kapcsolódási kísérletet %d próbálkozás után!\n"
msgstr[1] "Feladom a kapcsolódási kísérletet %d próbálkozás után!\n"

#: pyanaconda/vnc.py:171
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""
"Kérem csatlakozzon a vnc ügyféllel %s gazdához, hogy megkezdje a telepítést."

#: pyanaconda/vnc.py:173
#, python-format
msgid ""
"Please manually connect your vnc client to <IP ADDRESS>:%s to begin the "
"install. Switch to the shell (Ctrl-B 2) and run 'ip addr' to find the <IP "
"ADDRESS>."
msgstr ""

#: pyanaconda/vnc.py:178
msgid "Starting VNC..."
msgstr "VNC indítása..."

#: pyanaconda/vnc.py:220
msgid "The VNC server is now running."
msgstr "A VNC kiszolgáló elindult."

#: pyanaconda/vnc.py:224
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Ön egy figyelő vncviewerhez csatlakozást választja. \n"
"Ez nem igényel beállított jelszót.  Ha beállít egy jelszót, \n"
"akkor azt használni fogom, amennyiben a csatlakozás \n"
"a vncviewerhez sikertelen\n"
"\n"

#: pyanaconda/vnc.py:229
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"FIGYELEM!!! A VNC kiszolgáló JELSZÓ NÉLKÜL működik!\n"
"Használhatja a vncpassword=<jelszó> rendszerindító \n"
"beállítást, ha biztonságossá szeretné tenni a kiszolgálót.\n"
"\n"

#: pyanaconda/vnc.py:233
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"Ön vnc futtatását választja jelszóval. \n"
"\n"

#: pyanaconda/vnc.py:235
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"Ismeretlen hiba.  Kilépés. \n"
"\n"

#: pyanaconda/vnc.py:255
msgid ""
"VNC password provided was not at least 6 characters long.\n"
"Please enter a new one.  Leave blank for no password."
msgstr ""
"A megadott VNC jelszó nem volt min. 6 karakter hosszú.\n"
"Kérem adjon meg egy újat. Vagy hagyja ütesen jelszó elhagyásához."

#: pyanaconda/yuminstall.py:87
#, python-format
msgid "%s MB"
msgstr "%s MB"

#: pyanaconda/yuminstall.py:90
#, python-format
msgid "%s KB"
msgstr "%s kB"

#: pyanaconda/yuminstall.py:92
#, python-format
msgid "%s Byte"
msgid_plural "%s Bytes"
msgstr[0] "%s Byte"
msgstr[1] "%s Bájt"

#: pyanaconda/yuminstall.py:134 pyanaconda/ui/gui/hubs/progress.glade:83
msgid "Preparing to install"
msgstr "Telepítés előkészítése"

#: pyanaconda/yuminstall.py:135 pyanaconda/packaging/yumpayload.py:1536
msgid "Preparing transaction from installation source"
msgstr "Tranzakció előkészítése a telepítési forrásból"

#: pyanaconda/yuminstall.py:170
#, python-format
msgid "<b>Upgrading %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>Frissítés alatt %(pkgStr)s</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:173
#, python-format
msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>Telepítés %(pkgStr)s</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:218
#, python-format
msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgstr[0] "Befejezett csomagok: %(donepkgs)d / %(numpkgs)d"
msgstr[1] "Befejezett csomagok: %(donepkgs)d / %(numpkgs)d"

#: pyanaconda/yuminstall.py:232
#, python-format
msgid "<b>Cleaning up %s</b>"
msgstr "<b>Takarítás%s</b>"

#: pyanaconda/yuminstall.py:252
msgid "cpio"
msgstr "cpio"

#: pyanaconda/yuminstall.py:254
msgid "unpack"
msgstr "kicsomagol"

#: pyanaconda/yuminstall.py:256
msgid "script"
msgstr "szkript"

#: pyanaconda/yuminstall.py:257
msgid "Error Installing Package"
msgstr "Csomag telepítése meghiúsult"

#: pyanaconda/yuminstall.py:258
#, python-format
msgid ""
"A %s error occurred when installing the %s package.  This could indicate "
"errors when reading the installation media.  Installation cannot continue."
msgstr ""
"%s hiba történt amikor telepítésre került a %s csomag.  Ez olvasási hibát is "
"jelenthet a telepítési forrásról.  Telepítés nem folytatódhat."

#: pyanaconda/yuminstall.py:406
msgid "Wrong Disc"
msgstr "Rossz lemez"

#: pyanaconda/yuminstall.py:407
#, python-format
msgid "That's not the correct %s disc."
msgstr "Ez nem a megfelelő %s lemez."

#: pyanaconda/yuminstall.py:564
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr "%r tároló neve hiányzik a beállításban, ID kerül felhasználásra"

#: pyanaconda/yuminstall.py:830 pyanaconda/yuminstall.py:1264
msgid "No Network Available"
msgstr "Nincs elérhető hálózat"

#: pyanaconda/yuminstall.py:831 pyanaconda/yuminstall.py:1265
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""
"Néhány szoftver tárolóhoz hálózat kell, de a hálózat engedélyezése közben "
"hiba történt ."

#: pyanaconda/yuminstall.py:919 pyanaconda/yuminstall.py:921
msgid "Re_boot"
msgstr "Újrain_dítás"

#: pyanaconda/yuminstall.py:919
msgid "_Eject"
msgstr "L_emez kiadása"

#: pyanaconda/yuminstall.py:921 pyanaconda/yuminstall.py:1284
#: pyanaconda/yuminstall.py:1339 pyanaconda/yuminstall.py:1567
msgid "_Retry"
msgstr "Újr_a"

#: pyanaconda/yuminstall.py:924 pyanaconda/yuminstall.py:1011
#: pyanaconda/yuminstall.py:1016 pyanaconda/yuminstall.py:1289
#: pyanaconda/yuminstall.py:1349 pyanaconda/yuminstall.py:1561
#: pyanaconda/yuminstall.py:1583 pyanaconda/storage/zfcp.py:375
#: pyanaconda/ui/tui/__init__.py:38
msgid "Error"
msgstr "Hiba"

#: pyanaconda/yuminstall.py:925
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""
"%s fájlt nem sikerült megnyitni.  Valószínűleg hiányzó fájl, sérült csomag, "
"vagy sérült hordozó okozta.  Kérem ellenőrizze a telepítő forrást.\n"
"\n"
"Ha kilép, a rendszer töredékkel teli marad, s emiatt újbóli telepítést "
"igényel.\n"
"\n"

#: pyanaconda/yuminstall.py:972
msgid "Retrying"
msgstr "Újrapróbálás"

#: pyanaconda/yuminstall.py:972
msgid "Retrying download."
msgstr "Letöltés újrapróbálása."

#: pyanaconda/yuminstall.py:1007
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr "Az átvitel végrehajtása alatt hiba történt a következő okból: %s\n"

#: pyanaconda/yuminstall.py:1018 pyanaconda/yuminstall.py:1113
#: pyanaconda/yuminstall.py:1536 pyanaconda/yuminstall.py:1590
msgid "_Back"
msgstr "_Vissza"

#: pyanaconda/yuminstall.py:1051
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s.\n"
msgstr "A tranzakció hibás futásának a következő oka lehet: %s.\n"

#: pyanaconda/yuminstall.py:1053 pyanaconda/yuminstall.py:1105
#: pyanaconda/yuminstall.py:1110
msgid "Error Running Transaction"
msgstr "Hiba az átvitel végrehajtása alatt"

#: pyanaconda/yuminstall.py:1059 pyanaconda/yuminstall.py:1060
msgid "file conflicts"
msgstr "fájl ütközés"

#: pyanaconda/yuminstall.py:1061
msgid "older package(s)"
msgstr "régebbi csomag(ok)"

#: pyanaconda/yuminstall.py:1062
msgid "insufficient disk space"
msgstr "nem elegendő szabad lemezterület"

#: pyanaconda/yuminstall.py:1063
msgid "insufficient disk inodes"
msgstr "nincs elég inode"

#: pyanaconda/yuminstall.py:1064
msgid "package conflicts"
msgstr "csomag ütközés"

#: pyanaconda/yuminstall.py:1065
msgid "package already installed"
msgstr "már telepített csomag"

#: pyanaconda/yuminstall.py:1066
msgid "required package"
msgstr "szükséges csomag"

#: pyanaconda/yuminstall.py:1067
msgid "package for incorrect arch"
msgstr "nem megfelelő architektúrához készült csomag"

#: pyanaconda/yuminstall.py:1068
msgid "package for incorrect os"
msgstr "nem megfelelő operációs rendszerhez készült csomag"

#: pyanaconda/yuminstall.py:1082 pyanaconda/packaging/yumpayload.py:1364
msgid "You need more space on the following file systems:\n"
msgstr "Több szabad helyre van szüksége az alábbi fájlrendszereken:\n"

#: pyanaconda/yuminstall.py:1095
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""
"Fájlütközés történt a telepítendő csomagokat ellenőrzése alatt:\n"
"%s\n"

#: pyanaconda/yuminstall.py:1098
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): "
"%s.\n"
msgstr "Az átvitel végrehajtása alatt hiba történt a következő miatt: %s\n"

#: pyanaconda/yuminstall.py:1290
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""
"Nem sikerült beolvasni a csoportinformációt a tárolókból. A probléma a "
"telepítési fa felépítésében lépett fel."

#: pyanaconda/yuminstall.py:1339
msgid "Edit"
msgstr "Szerkesztés"

#: pyanaconda/yuminstall.py:1344 pyanaconda/yuminstall.py:1534
#: pyanaconda/ui/gui/spokes/storage.glade:43
#: pyanaconda/ui/gui/spokes/storage.glade:952
#: widgets/src/StandaloneWindow.c:53
msgid "_Continue"
msgstr "_Tovább"

#: pyanaconda/yuminstall.py:1350 pyanaconda/yuminstall.py:1562
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""
"Nem lehet beolvasni a csomagleírásokat. Ezt okozhatja a repodata mappa "
"hiánya.  Kérem ellenőrizze, hogy jól készítették-e el a telepítő fát.\n"
"\n"
"%s"

#: pyanaconda/yuminstall.py:1538
msgid "Warning"
msgstr "Figyelmeztetés"

#: pyanaconda/yuminstall.py:1539
msgid ""
"Some of the packages you have selected for install are missing "
"dependencies.  You can exit the installation, go back and change your "
"package selections, or continue installing these packages without their "
"dependencies.  If you continue, these packages may not work correctly due to "
"missing components."
msgstr ""
"Néhány telepítésre kiválasztott csomagnak hiányzó függőségei vannak.  "
"Kiléphet a telepítésből, és megváltoztathatja a csomagkijelölést, vagy "
"folytathatja a függőségek telepítése nélkül.  A folytatja, ezek a csomagok "
"nem biztos, hogy működni fognak a hiányzó részek miatt."

#: pyanaconda/yuminstall.py:1584
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""
"A kiválasztott csomagoknak %d MB szabad hely kell, de nincs elég elérhető.  "
"Megváltoztathatja az összeállítást, vagy kiléphet a telepítőből."

#: pyanaconda/yuminstall.py:1669
msgid "Post Upgrade"
msgstr "Zárófrissítés"

#: pyanaconda/yuminstall.py:1670
msgid "Performing post-upgrade configuration"
msgstr "Zárófrissítés beállításainak végrehajtása"

#: pyanaconda/yuminstall.py:1672
msgid "Post Installation"
msgstr "Zárótelepítés"

#: pyanaconda/yuminstall.py:1673
msgid "Performing post-installation configuration"
msgstr "Zárótelepítés beállításainak végrehajtása"

#: pyanaconda/yuminstall.py:1832
msgid "Installation Starting"
msgstr "Kezdődik a telepítés"

#: pyanaconda/yuminstall.py:1833
msgid "Starting installation process"
msgstr "Telepítési folyamat indul"

#: pyanaconda/yuminstall.py:1871
msgid "Dependency Check"
msgstr "Függőség ellenőrzés"

#: pyanaconda/yuminstall.py:1872
msgid "Checking dependencies in packages selected for installation"
msgstr "A telepítésre kiválasztott csomagok közötti függőségek ellenőrzése"

#: pyanaconda/yuminstall.py:1928 pyanaconda/yuminstall.py:1944
msgid "Retrieving installation information."
msgstr "Telepítő információk beszerzése."

#: pyanaconda/yuminstall.py:1930 pyanaconda/yuminstall.py:1946
#, python-format
msgid "Retrieving installation information for %s."
msgstr "Telepítő információk beszerzése %s számára."

#: pyanaconda/yuminstall.py:1931 pyanaconda/yuminstall.py:1947
msgid "Installation Progress"
msgstr "Telepítés állapota"

#: pyanaconda/installclasses/fedora.py:35
msgid "_Fedora"
msgstr "_Fedora"

#: pyanaconda/installclasses/fedora.py:36
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. You can optionally select a different set of "
"software now."
msgstr ""
"Az alap %s telepítés tartalmaz egy szoftver-összeállítást, ami alkalmas "
"általános internet használatra. Ha szeretné, opcionálisan választhat másik "
"szoftvereket most."

#: pyanaconda/installclasses/fedora.py:45
msgid "Graphical Desktop"
msgstr "Grafikus Asztal"

#: pyanaconda/installclasses/fedora.py:50
msgid "Software Development"
msgstr "Szoftver fejlesztés"

#: pyanaconda/installclasses/fedora.py:56
msgid "Web Server"
msgstr "Web kiszolgáló"

#: pyanaconda/installclasses/fedora.py:60 pyanaconda/installclasses/rhel.py:39
msgid "Minimal"
msgstr "Minimális"

#: pyanaconda/installclasses/rhel.py:28
msgid "Red Hat Enterprise Linux"
msgstr "Red Hat Enterprise Linux"

#: pyanaconda/installclasses/rhel.py:29
#, python-format
msgid ""
"The default installation of %s is a minimum install. You can optionally "
"select a different set of software now."
msgstr ""
"A %s alap telepítése  az a minimális telepítés. Ha kívánja, választhat más "
"szoftver-összeállítást most."

#: pyanaconda/packaging/livepayload.py:72
#: pyanaconda/packaging/livepayload.py:90
msgid "Installing software"
msgstr "Szoftverek telepítése"

#: pyanaconda/packaging/yumpayload.py:1300
msgid "Starting package installation process"
msgstr "Csomagtelepítési eljárás indítása"

#: pyanaconda/packaging/yumpayload.py:1556
msgid "Upgrading"
msgstr "Frissítés"

#: pyanaconda/packaging/yumpayload.py:1558
msgid "Installing"
msgstr "Telepítés"

#: pyanaconda/storage/__init__.py:974
msgid "This partition is holding the data for the hard drive install."
msgstr "E rész tartalmazza a merevlemezes telepítéshez szükséges adatokat."

#: pyanaconda/storage/__init__.py:979
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "LDL DASD részt nem lehet törölni."

#: pyanaconda/storage/__init__.py:985
#, python-format
msgid "This device is part of the RAID device %s."
msgstr "E rész a %s RAID eszközhöz tartozik."

#: pyanaconda/storage/__init__.py:988
msgid "This device is part of a RAID device."
msgstr "E rész egy RAID eszközhöz tartozik."

#: pyanaconda/storage/__init__.py:991
msgid "This device is part of an inconsistent LVM Volume Group."
msgstr "Ez az eszköz része egy nem összefüggő LVM kötetcsoportnak."

#: pyanaconda/storage/__init__.py:996
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "Ez az eszköz „%s” LVM kötet csoporthoz tartozik."

#: pyanaconda/storage/__init__.py:999
msgid "This device is part of a LVM volume group."
msgstr "E rész egy LVM kötetcsoporthoz tartozik."

#: pyanaconda/storage/__init__.py:1015
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""
"Ez az eszköz olyan kiterjesztett rész, ami nem törölhető logikai részeket "
"tartalmaz:\n"
"\n"

#: pyanaconda/storage/__init__.py:1262 pyanaconda/ui/gui/spokes/custom.py:1006
msgid "You must create a new filesystem on the root device."
msgstr "Létre kell hoznia egy új fájlrendszer a root eszközön."

#: pyanaconda/storage/__init__.py:1450
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr "Nem adta meg a root partíciót (/), ami nélkül %s nem telepíthető."

#: pyanaconda/storage/__init__.py:1455
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"A gyökér rész mérete kisebb 250 MB-nál, ami általában nem elég %s "
"telepítéséhez."

#: pyanaconda/storage/__init__.py:1469
msgid ""
"This platform requires /boot on a dedicated partition or logical volume.  If "
"you do not want a /boot volume, you must place / on a dedicated non-LVM "
"partition."
msgstr ""
"Ez a platform egy külön /boot partíciót igényel egy erre megjelölt "
"partíción, vagy logikai köteten.  Ha nem szeretne külön /boot kötetet, egy "
"nem LVM partíció / könyvtárába kell telepítenie."

#: pyanaconda/storage/__init__.py:1478
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"Az Ön %(mount)s particiója nem éri el a %(size)s MB ami kevesebb mint az "
"ajánlott normál %(productName)s telepítéshez."

#: pyanaconda/storage/__init__.py:1488
#, python-format
msgid ""
"Your %(mount)s partition is too small for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"A %(mount)s partíciód túl kicsi a %(format)s formázáshoz (megengedett méret "
"%(minSize)d MB és %(maxSize)d MB közötti)"

#: pyanaconda/storage/__init__.py:1493
#, python-format
msgid ""
"Your %(mount)s partition is too large for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"A %(mount)s partíciód túl nagy a %(format)s formázáshoz (megengedett méret "
"%(minSize)d MB és %(maxSize)d MB közötti)"

#: pyanaconda/storage/__init__.py:1520
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""
"Telepítés USB eszközre.  Ez a megoldás működésképtelen rendszert is "
"eredményezhet."

#: pyanaconda/storage/__init__.py:1523
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""
"Telepítés FireWire eszközre.  Ez a megoldás működésképtelen rendszert is "
"eredményezhet."

#: pyanaconda/storage/__init__.py:1529
msgid "you have not created a bootloader stage1 target device"
msgstr "Nem készített egy rendszertöltő stage1 céleszközt"

#: pyanaconda/storage/__init__.py:1538
msgid "You have not created a bootable partition."
msgstr "Nem csinált rendszerindító részt."

#: pyanaconda/storage/__init__.py:1559
#, python-format
msgid ""
"Your BIOS-based system needs a special partition to boot with %s's new disk "
"label format (GPT). To continue, please create a 1MB 'BIOS Boot' type "
"partition."
msgstr ""
"Az Ön BIOS alapú rendszere igényli egy speciális partició kialakítását %s új "
"lemezcimke formátumával (GPT). A folytatáshoz, kérem készítsen egy 1Mbyte "
"'BIOS Boot' típusú particiót."

#: pyanaconda/storage/__init__.py:1572
#, python-format
msgid ""
"You have not specified a swap partition.  %(requiredMem)s MB of memory is "
"required to continue installation without a swap partition, but you only "
"have %(installedMem)s MB."
msgstr ""
"Nem adott meg egy swap partíciót.  %(requiredMem)s MB memória szükséges a "
"telepítés folytatásához  swap nélkül, de csak %(installedMem)s MB elérhető."

#: pyanaconda/storage/__init__.py:1578
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"Nem adott meg swap partíciót.  Erre nincs mindig szükség, de a legtöbb "
"esetben jelentősen növelheti a teljesítményt."

#: pyanaconda/storage/__init__.py:1584
msgid ""
"At least one of your swap devices does not have a UUID, which is common in "
"swap space created using older versions of mkswap. These devices will be "
"referred to by device path in /etc/fstab, which is not ideal since device "
"paths can change under a variety of circumstances. "
msgstr ""
"Legalább egy - a swap eszközök közül nem rendelkezik UUID-vel, ami "
"megszokott ha az régebbi verziójú mkswap programmal készült. Ezek az "
"eszközök egyenként fognak hivatkozni az /etc/fstab fájlban, ami nem ideális "
"amióta az eszközök elérési útjai számtalan ok miatt megváltozhatnak. "

#: pyanaconda/storage/__init__.py:1594
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""
"Ez a csatoló pont érvénytelen.  %s mappának a / fájlrendszerben kell lennie."

#: pyanaconda/storage/__init__.py:1598
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "%s csatoló pontnak linuxos fájlrendszerben kell lennie."

#: pyanaconda/storage/__init__.py:3199
#, python-format
msgid "Linux on %s"
msgstr "Linux %s rendszeren"

#: pyanaconda/storage/__init__.py:3204
msgid "Unknown Linux"
msgstr "Ismeretlen Linux"

#: pyanaconda/storage/__init__.py:3206
#, python-format
msgid "%(product)s Linux %(version)s for %(arch)s"
msgstr "%(product)s Linux %(version)s %(arch)s architektúrára"

#: pyanaconda/storage/dasd.py:159
msgid "Formatting DASD Device"
msgid_plural "Formatting DASD Devices"
msgstr[0] "DASD eszköz formázása"
msgstr[1] "DASD eszközök formázása"

#: pyanaconda/storage/dasd.py:160
#, python-format
msgid "Preparing %d DASD device for use with Linux..."
msgid_plural "Preparing %d DASD devices for use with Linux..."
msgstr[0] "Felkészülés %d DASD eszköz Linux-al való használatára..."
msgstr[1] "Felkészülés %d DASD eszköz Linux-al való használatára..."

#: pyanaconda/storage/deviceaction.py:419
#, python-format
msgid "Creating %(type)s on %(device)s"
msgstr " A %(type)s létrehozása itt: %(device)s "

#: pyanaconda/storage/deviceaction.py:559
#, python-format
msgid "Resizing filesystem on %(device)s"
msgstr "A %(device)s fájlrendszer átméretezése "

#: pyanaconda/storage/deviceaction.py:608
#, python-format
msgid "Migrating filesystem on %(device)s"
msgstr "A %(device)s fálrendszer migrálása"

#: pyanaconda/storage/devicelibs/lvm.py:310
#, python-format
msgid "vginfo failed for %s"
msgstr "vginfo sikertelen %s eszközre"

#: pyanaconda/storage/devicelibs/lvm.py:339
#, python-format
msgid "lvs failed for %s"
msgstr "lvs sikertelen %s eszközre"

#: pyanaconda/storage/devices.py:2672
#, python-format
msgid "A RAID%(raidLevel)d set requires at least %(minMembers)d member"
msgid_plural "A RAID%(raidLevel)d set requires at least %(minMembers)d members"
msgstr[0] ""
"A RAID%(raidLevel)d beállítás megkövetel legalább %(minMembers)d tömbelemet"
msgstr[1] ""
"A RAID%(raidLevel)d beállítás megkövetel legalább %(minMembers)d tömbelemet"

#: pyanaconda/storage/devicetree.py:96
msgid "Back"
msgstr "Vissza"

#: pyanaconda/storage/devicetree.py:105
msgid "Confirm"
msgstr "Megerősítés"

#: pyanaconda/storage/devicetree.py:106
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""
"Biztosan ki akarja hagyni a jelszó megadását %s eszközhöz?\n"
"\n"
"Ha átugorja e lépést, az eszköz tartalma elérhetetlen lesz a telepítés "
"közben."

#: pyanaconda/storage/fcoe.py:110
msgid "FCoE not available"
msgstr "FCoE nem elérhető"

#: pyanaconda/storage/formats/fs.py:104
msgid "filesystem configuration missing a type"
msgstr "fájlrendszer beállításból hiányzik a típus"

#: pyanaconda/storage/formats/fs.py:483
#, python-format
msgid "Unknown return code: %d."
msgstr "Ismeretlen visszatérési kód: %d."

#: pyanaconda/storage/formats/fs.py:504
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr ""
" %(type)s fájlrendszer ellenőrzés meghiúsult ezen az eszközön %(device)s: "

#: pyanaconda/storage/formats/fs.py:511
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair.  Before restarting installation, "
"reboot to rescue mode or another system that allows you to repair the "
"filesystem interactively.  Restart installation after you have corrected the "
"problems on the filesystem."
msgstr ""
"Hibák mint ezek is, általában azt jelentik, hogy probléma adódott a "
"fájlrendszerrel, ami felhasználói közbeavatkozást kíván a javításhoz. "
"Mielőtt újraindítaná a telepítést, indítson újra mentési módban vagy más "
"rendszerrel, ami lehetővé teszi fájlrendszer interaktív javítását. Csak "
"akkor indítson újra, ha már kijavította  problémákat a fájlrendszerben."

#: pyanaconda/storage/formats/fs.py:519
msgid "Unrecoverable Error"
msgstr "Helyrehozhatatlan hiba"

#: pyanaconda/storage/formats/fs.py:883
msgid "File system errors left uncorrected."
msgstr "A fájlrendszer hibái javítatlanok maradtak."

#: pyanaconda/storage/formats/fs.py:884
msgid "Operational error."
msgstr "Műveleti hiba."

#: pyanaconda/storage/formats/fs.py:885
msgid "Usage or syntax error."
msgstr "Kezelési vagy szintaxis hiba."

#: pyanaconda/storage/formats/fs.py:886
msgid "e2fsck cancelled by user request."
msgstr "e2fsck megszakítva felhasználói kérésre."

#: pyanaconda/storage/formats/fs.py:887
msgid "Shared library error."
msgstr "Megosztott könyvtár hiba."

#: pyanaconda/storage/formats/fs.py:1062
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""
"Javítható hibát észlelt a rendszer, vagy dosfsck felfedezett egy belső "
"összeférhetetlenséget."

#: pyanaconda/storage/formats/fs.py:1064
msgid "Usage error."
msgstr "Felhasználási hiba."

#: pyanaconda/storage/formats/luks.py:48
msgid "Encrypted"
msgstr "Titkosított"

#: pyanaconda/storage/iscsi.py:123
msgid "Unable to change iSCSI initiator name once set"
msgstr ""
"Nem sikerült megváltoztatni iSCSI iniciátor nevét egyszer beállításra került"

#: pyanaconda/storage/iscsi.py:125
msgid "Must provide an iSCSI initiator name"
msgstr "Meg kell adnia egy iSCSI iniciátor nevet"

#: pyanaconda/storage/iscsi.py:293
msgid "iSCSI not available"
msgstr "iSCSI nem érhető el"

#: pyanaconda/storage/iscsi.py:295
msgid "No initiator name set"
msgstr "Nincs kezdeményező név beállítva"

#: pyanaconda/storage/iscsi.py:334
msgid "Logging in to iSCSI node"
msgstr "Bejelentkezés az iSCSI-csomópontba"

#: pyanaconda/storage/iscsi.py:335
#, python-format
msgid "Logging in to iSCSI node %s"
msgstr "Bejelentkezés az iSCSI-csomópontba %s"

#: pyanaconda/storage/iscsi.py:369
msgid "No iSCSI nodes discovered"
msgstr "Nincs felfedezett iSCSI csomópont"

#: pyanaconda/storage/iscsi.py:391
msgid "No new iSCSI nodes discovered"
msgstr "Nem találtam új iSCSI elemeket"

#: pyanaconda/storage/iscsi.py:394
msgid "Could not log in to any of the discovered nodes"
msgstr "Bejeletkezés nem lehetséges egyetlen felfedezett csomópontra sem"

#: pyanaconda/storage/partitioning.py:291
msgid "No usable disks selected"
msgstr "Nincs felhasználható lemez kiválasztva"

#: pyanaconda/storage/partitioning.py:299
msgid "Not enough free space on disks for automatic partitioning"
msgstr "Nincs elég szabad tárhely a lemezeken az automatikus particionáláshoz"

#: pyanaconda/storage/partitioning.py:629
msgid "unable to allocate aligned partition"
msgstr "összekapcsolt partíció felosztása nem lehetséges"

#: pyanaconda/storage/partitioning.py:637
msgid "requested size exceeds maximum allowed"
msgstr "a kért méret túllép a maximálisan engedélyezettnél"

#: pyanaconda/storage/partitioning.py:728
msgid "can't allocate partitions without platform data"
msgstr "a partíciók nem meghatározhatóak platformadatok nélkül"

#: pyanaconda/storage/partitioning.py:739
#, python-format
msgid "disk %s inaccessible"
msgstr "%s lemez elérhetetlen"

#: pyanaconda/storage/partitioning.py:793
#, python-format
msgid ""
"partition is too small for %(format)s formatting (allowable size is "
"%(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"partíció túl kicsi a %(format)s formázáshoz (a megengedhető méret az "
"%(minSize)d MB - %(maxSize)d MB terjedhet)"

#: pyanaconda/storage/partitioning.py:798
#, python-format
msgid ""
"partition is too large for %(format)s formatting (allowable size is "
"%(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"partíció túl nagy a %(format)s formázáshoz (a megengedhető méret az "
"%(minSize)d MB - %(maxSize)d MB terjedhet)"

#: pyanaconda/storage/partitioning.py:1039
msgid "not enough free space on disks"
msgstr "nincs elegendő szabad tárhely a lemezeken"

#: pyanaconda/storage/partitioning.py:1060
msgid "not enough free space after creating extended partition"
msgstr "nincs elegendő szabad terület a kiterjesztett partíció elkészülte után"

#: pyanaconda/storage/partitioning.py:1232
msgid "cannot reclaim more than request has grown"
msgstr "több nem nyerhető vissza mint a megnőtt igények"

#: pyanaconda/storage/partitioning.py:1412
msgid "DiskChunk requests must be of type PartitionRequest"
msgstr "DiskChunk kéréseknek PartitionRequest típusúaknak kell lennie"

#: pyanaconda/storage/partitioning.py:1425
msgid "partitions allocated outside disklabel limits"
msgstr "a partíciók a lemezcím határain kívül esik "

#: pyanaconda/storage/partitioning.py:1505
msgid "VGChunk requests must be of type LVRequest"
msgstr "VGChunk kéréseknek LVRequest típusúnak kell lennie"

#: pyanaconda/storage/partitioning.py:1934
msgid "not enough space for LVM requests"
msgstr "kevés tárhely az LVM igényekhez"

#: pyanaconda/storage/zfcp.py:51
msgid "You have not specified a device number or the number is invalid"
msgstr "Nem adott meg eszközszámot, vagy a szám érvénytelen"

#: pyanaconda/storage/zfcp.py:53
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr "Nem adott meg WWPN port nevet, vagy a név érvénytelen."

#: pyanaconda/storage/zfcp.py:55
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr "Nem adott meg FCP LUN számot, vagy a szám érvénytelen."

#: pyanaconda/storage/zfcp.py:133
#, python-format
msgid "zFCP device %s not found, not even in device ignore list."
msgstr "%s zFCP eszköz nem található, még a mellőzött eszközlistán sem."

#: pyanaconda/storage/zfcp.py:143
#, python-format
msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
msgstr "A zFCP eszköz nem beállítható %(devnum)s online (%(e)s) ."

#: pyanaconda/storage/zfcp.py:154
#, python-format
msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
msgstr ""
"Hiba: Nem lehet %(wwpn)s WWPN-t hozzáadni a zFCP eszközhöz %(devnum)s "
"(%(e)s). "

#: pyanaconda/storage/zfcp.py:161
#, python-format
msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
msgstr "%(wwpn)s WWPN nem található az zFCP eszközben %(devnum)s."

#: pyanaconda/storage/zfcp.py:176
#, python-format
msgid ""
"Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"Hiba: %(fcplun)s LUN nem hozzáadható a %(wwpn)s WWPN zFCP eszközön "
"%(devnum)s (%(e)s). "

#: pyanaconda/storage/zfcp.py:182
#, python-format
msgid ""
"LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already configured."
msgstr ""
"%(fcplun)s LUN a WWPN %(wwpn)s az %(devnum)s zFCP eszközön már beállított."

#: pyanaconda/storage/zfcp.py:194
#, python-format
msgid ""
"Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on zFCP "
"device %(devnum)s (%(e)s)."
msgstr ""
"Nem sikerült a hibás %(fcplun)s LUN attribútum kiolvasása %(wwpn)s WWPN-en "
"zFCP eszközön %(devnum)s (%(e)s). "

#: pyanaconda/storage/zfcp.py:203
#, python-format
msgid ""
"Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
"again."
msgstr ""
"%(fcplun)s LUN a WWPN %(wwpn)s a zFCP eszközön %(devnum)s nem sikerült "
"eltávolítani újra. "

#: pyanaconda/storage/zfcp.py:260
#, python-format
msgid ""
"Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s "
"%(fcplun)s (%(e)s)."
msgstr ""
"Precízen nem törölhető a zFCP SCSI eszköze %(devnum)s %(wwpn)s %(fcplun)s "
"(%(e)s). "

#: pyanaconda/storage/zfcp.py:269
#, python-format
msgid ""
"Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"Hiba: %(fcplun)s LUN nem eltávolítható a %(wwpn)s WWPN zFCP eszközön "
"%(devnum)s (%(e)s). "

#: pyanaconda/storage/zfcp.py:287
#, python-format
msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
msgstr ""
"Hiba: WWPN %(wwpn)s nem eltávolítható az zFCP eszközről %(devnum)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:313
#, python-format
msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
msgstr "Hiba: zFCP eszköz %(devnum)s kikapcsolva (%(e)s), nem beállítható."

#: pyanaconda/ui/lib/space.py:33
#, python-format
msgid ""
"Not enough space in filesystems for the current software selection. An "
"additional %s is needed."
msgstr ""
"Nincs elegendő tárhely a kiválasztott jelenlegi szoftver-összeállításhoz. "
"További %s szükséges."

#: pyanaconda/ui/tui/hubs/progress.py:37
msgid "Installation Hub"
msgstr "Telepítési Központ"

#: pyanaconda/ui/tui/hubs/progress.py:117
msgid "\tInstallation complete.  Press return to quit"
msgstr "\tTelepítés befejeződött.  Nyomjon entert kilépéshez"

#: pyanaconda/ui/tui/hubs/summary.py:32
msgid "Install hub"
msgstr "Telepítési központ"

#: pyanaconda/ui/tui/hubs/summary.py:38
msgid "Starting automated install"
msgstr "Automatizált telepítés indítása"

#: pyanaconda/ui/tui/hubs/__init__.py:43
msgid "Default HUB title"
msgstr "Alapértelmezett HUB cím"

#: pyanaconda/ui/tui/hubs/__init__.py:104
#: pyanaconda/ui/tui/simpleline/base.py:301
msgid "c"
msgstr "c"

#: pyanaconda/ui/tui/hubs/__init__.py:107
msgid "Please complete all spokes before continuing"
msgstr "Kérem fejezzen be minden fokozatot mielőtt folytatja"

#: pyanaconda/ui/tui/simpleline/base.py:306
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/simpleline/base.py:308
msgid "Do you really want to quit?"
msgstr "Biztos hogy ki akar lépni?"

#: pyanaconda/ui/tui/simpleline/base.py:407
msgid "  Please make your choice from above ['q' to quit | 'c' to continue]: "
msgstr "Kérem válasszon fentről ['q' kilépéshez | 'c' a folytatáshoz]:"

#: pyanaconda/ui/tui/spokes/askvnc.py:32
msgid "VNC"
msgstr "VNC"

#: pyanaconda/ui/tui/spokes/askvnc.py:43
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""
"Az X nem tudott elindulni az Ön gépén.  El szeretné indítani a VNC-t, hogy "
"egy másik gépről csatlakozni lehessen ehhez a géphez - a grafikus módú "
"telepítés indításához, vagy inkább szöveges módban szeretné folytatni a "
"telepítést?"

#: pyanaconda/ui/tui/spokes/askvnc.py:95
msgid "VNC Password"
msgstr "VNC jelszó"

#: pyanaconda/ui/tui/spokes/askvnc.py:104
msgid ""
"Please provide VNC password. You will have to type it twice. \n"
"Leave blank for no password"
msgstr ""
"Kérem adja meg a VNC jelszavát. Kétszer kell begépelnie.\n"
"Ha nem kíván jelszót, hagyja üresen."

#: pyanaconda/ui/tui/spokes/askvnc.py:123
#: pyanaconda/ui/tui/spokes/password.py:64
msgid "Password: "
msgstr "Jelszó:"

#: pyanaconda/ui/tui/spokes/askvnc.py:124
#: pyanaconda/ui/tui/spokes/password.py:65
msgid "Password (confirm): "
msgstr "Jelszó (erősítse meg):"

#: pyanaconda/ui/tui/spokes/askvnc.py:127
msgid "Passwords do not match!"
msgstr "Jelszavak nem egyeznek!"

#: pyanaconda/ui/tui/spokes/askvnc.py:130
msgid "The password must be at least six characters long."
msgstr "A jelszó legalább 6 karakter hosszú kell legyen."

#: pyanaconda/ui/tui/spokes/password.py:35
msgid "Set root password"
msgstr "Állítsa be a root jelszavát"

#: pyanaconda/ui/tui/spokes/password.py:49
msgid "Password is set."
msgstr "Jelszó beállítva."

#: pyanaconda/ui/tui/spokes/password.py:51
msgid "Root account is disabled."
msgstr "Root jelszó kikapcsolva."

#: pyanaconda/ui/tui/spokes/password.py:53
msgid "Password is not set."
msgstr "Jelszó nincs beállítva."

#: pyanaconda/ui/tui/spokes/password.py:58
msgid "Please select new root password. You will have to type it twice."
msgstr "Kérem válasszon új root jelszót. Kétszer kell majd megadnia."

#: pyanaconda/ui/tui/spokes/password.py:76
#, python-format
msgid "You have provided a weak password: %s. "
msgstr "Gyenge jelszót adott meg: %s."

#: pyanaconda/ui/tui/spokes/password.py:77
msgid ""
"\n"
"Would you like to use it anyway?"
msgstr ""
"\n"
"Ennek ellenére mindenképp alkalmazza?"

#: pyanaconda/ui/tui/spokes/storage.py:47
msgid "Use All Space"
msgstr "Használja fel az összes tárhelyet"

#: pyanaconda/ui/tui/spokes/storage.py:48
msgid "Replace Existing Linux system(s)"
msgstr "Cserélje le a meglévő Linux rendszer(eke)t"

#: pyanaconda/ui/tui/spokes/storage.py:49
msgid "Use Free Space"
msgstr "Szabad tárhelyet használja fel"

#: pyanaconda/ui/tui/spokes/storage.py:92
msgid "Install Destination"
msgstr "Telepítési cél"

#: pyanaconda/ui/tui/spokes/storage.py:120
#: pyanaconda/ui/gui/spokes/storage.py:439
msgid "No disks selected"
msgstr "Nincsenek kiválasztott lemezek"

#: pyanaconda/ui/tui/spokes/storage.py:127
#: pyanaconda/ui/gui/spokes/storage.py:446
msgid "Error checking storage configuration"
msgstr "Hiba a tárolóeszközök összeállításának ellenőzésekor"

#: pyanaconda/ui/tui/spokes/storage.py:130
#: pyanaconda/ui/gui/spokes/storage.py:448
msgid "Automatic partitioning selected"
msgstr "Automata particionálás kiválasztva"

#: pyanaconda/ui/tui/spokes/storage.py:132
#: pyanaconda/ui/gui/spokes/storage.py:450
msgid "Custom partitioning selected"
msgstr "Egyéni particionálás kiválasztva"

#: pyanaconda/ui/tui/spokes/storage.py:168
#: pyanaconda/ui/gui/spokes/storage.py:582
msgid ""
"No disks detected.  Please shut down the computer, connect at least one "
"disk, and restart to complete installation."
msgstr ""
"Nincsenek lemezek kiválasztva. Kérem állítsa le a számítógépét, "
"csatlakoztasson legalább egy lemezt, és indítsa újra a teljes telepítési "
"folyamatot."

#: pyanaconda/ui/tui/spokes/storage.py:170
#: pyanaconda/ui/gui/spokes/storage.py:584
msgid "No disks selected; please select at least one disk to install to."
msgstr ""
"Nincs egyetlen lemez se kiválasztva; kérem legalább egy lemezt válasszon "
"amire telepítene"

#: pyanaconda/ui/tui/spokes/storage.py:185
#: pyanaconda/ui/gui/spokes/source.py:671
#: pyanaconda/ui/gui/spokes/storage.py:514
msgid "Probing storage..."
msgstr "Tárolók tesztelése..."

#: pyanaconda/ui/tui/spokes/storage.py:263
msgid "Generating updated storage configuration"
msgstr "Frissített tárhely információk előállítása"

#: pyanaconda/ui/tui/spokes/storage.py:268
#, python-format
msgid "storage configuration failed: %s"
msgstr "taroló összeállítás sikertelen: %s"

#: pyanaconda/ui/tui/spokes/storage.py:277
#: pyanaconda/ui/gui/spokes/storage.py:307
msgid "Checking storage configuration..."
msgstr "Tárolóeszközök összeállításának ellenőzése..."

#: pyanaconda/ui/tui/spokes/storage.py:311
msgid "Autopartitioning Options"
msgstr "Automata particionálási opciók"

#: pyanaconda/ui/tui/spokes/storage.py:342
msgid ""
"Installation requires partitioning of your hard drive.  Select what space to "
"use for the install target."
msgstr ""
"A telepítés megkívánja a merevlemez felosztását. Válasszon területet amit "
"telepítési célként használ majd fel."

#: pyanaconda/ui/tui/spokes/time.py:30
msgid "Timezone settings"
msgstr "Időzóna beállítások"

#: pyanaconda/ui/tui/spokes/time.py:53 pyanaconda/ui/tui/spokes/time.py:55
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:379
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:384
#, python-format
msgid "%s timezone"
msgstr "%s időzóna"

#: pyanaconda/ui/tui/spokes/time.py:57
msgid "Timezone is not set."
msgstr "Időzóna nincs beállítva"

#: pyanaconda/ui/tui/spokes/time.py:65
#, python-format
msgid "Available timezones in region %s"
msgstr "Elérhető időzónák a régióban %s"

#: pyanaconda/ui/tui/spokes/time.py:68
msgid "Available regions"
msgstr "Elérhető régiók"

#: pyanaconda/ui/tui/spokes/time.py:131
msgid ""
"Please select the timezone.\n"
"Use numbers or type names directly [b to region list, q to quit]: "
msgstr ""
"Kérem válasszon időzónát.\n"
"Használjon számokat vagy gépelje be a neveket közvetlenül [b a régió "
"listáért, q a kilépéshez]:"

#: pyanaconda/ui/tui/spokes/__init__.py:44
msgid "Default spoke title"
msgstr "Alapértelmezett fokozat neve"

#: pyanaconda/ui/tui/spokes/__init__.py:54
msgid "testing status..."
msgstr "Állapot tesztelése"

#: pyanaconda/ui/tui/__init__.py:58
msgid "Press enter to exit."
msgstr "Nyomjon entert a kilépéshez"

#: pyanaconda/ui/tui/__init__.py:67
msgid "Question"
msgstr "Kérdés"

#: pyanaconda/ui/tui/__init__.py:90
msgid "Please respond 'yes' or 'no': "
msgstr "Kérem válaszoljon 'igen'-nel vagy 'nem'-mel:"

#: pyanaconda/ui/tui/__init__.py:93
msgid "yes"
msgstr "igen"

#: pyanaconda/ui/tui/__init__.py:98
msgid "no"
msgstr "nem"

#: pyanaconda/ui/gui/__init__.py:144
msgid "_Exit Installer"
msgstr "Kilépés a t_elepítőből"

#: pyanaconda/ui/gui/__init__.py:153 pyanaconda/ui/gui/spokes/software.py:333
#: pyanaconda/ui/gui/spokes/storage.py:770 pyanaconda/ui/gui/main.glade:36
#: pyanaconda/ui/gui/hubs/summary.glade:77 widgets/src/StandaloneWindow.c:52
msgid "_Quit"
msgstr "Kilépés"

#: pyanaconda/ui/gui/__init__.py:169
msgid "_No"
msgstr "_Nem"

#: pyanaconda/ui/gui/__init__.py:169
msgid "_Yes"
msgstr "Igen"

#: pyanaconda/ui/gui/categories/__init__.py:44
msgid "DEFAULT TITLE"
msgstr "ALAPÉRTELMEZETT CÍMKE"

#: pyanaconda/ui/gui/categories/localization.py:31
msgid "LOCALIZATION"
msgstr "LOKALIZÁCIÓ"

#: pyanaconda/ui/gui/categories/software.py:31
msgid "SOFTWARE"
msgstr "SZOFTVER"

#: pyanaconda/ui/gui/categories/storage.py:32
msgid "STORAGE"
msgstr "TÁROLÓ"

#: pyanaconda/ui/gui/categories/user_settings.py:32
msgid "USER SETTINGS"
msgstr "FELHASZNÁLÓI BEÁLLÍTÁSOK"

#: pyanaconda/ui/gui/hubs/__init__.py:226
msgid ""
"When all items marked with this icon are complete, installation will "
"automatically continue."
msgstr ""
"Amikor az összes elem ezzel az ikonnal készre jelölődik, a telepíés "
"automatikusan folytatódik."

#: pyanaconda/ui/gui/hubs/__init__.py:228
msgid ""
"Please complete items marked with this icon before continuing to the next "
"step."
msgstr ""
"Kérem fejezze be az ezzel az ikonnal jelölt következő elemeket mielőtt "
"folytatná a következő lépéssel."

#: pyanaconda/ui/gui/hubs/progress.py:254
msgid "Complete!"
msgstr "Kész!"

#: pyanaconda/ui/gui/spokes/custom.py:99
#, python-format
msgid "New %s %s Installation"
msgstr "Új %s %s telepítés"

#: pyanaconda/ui/gui/spokes/custom.py:100
msgid "Create a new volume group ..."
msgstr "Új kötetcsoport készítése..."

#: pyanaconda/ui/gui/spokes/custom.py:101
msgid ""
"Storage configuration reset due to unrecoverable error. Click for details."
msgstr ""
"Tároló összeállítás alaphelyzetbe állt egy helyrehozhatatlan hiba miatt. "
"Kat\n"
"tintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:103
msgid "Device reconfiguration failed. Click for details."
msgstr "Az eszköz újraparaméterezése sikertelen. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:106
msgid "Please enter a valid mountpoint."
msgstr "Kérem adjon meg egy érvényes csatolási pontot."

#: pyanaconda/ui/gui/spokes/custom.py:107
msgid "That mount point is invalid. Try something else?"
msgstr "Ez a csatolási pont érvénytelen. Megpróbálja másképp?"

#: pyanaconda/ui/gui/spokes/custom.py:108
msgid "That mount point is already in use. Try something else?"
msgstr "Ez a csatolási pont már használatban van. Megpróbál másikat?"

#: pyanaconda/ui/gui/spokes/custom.py:120
msgid "LVM"
msgstr "LVM"

#: pyanaconda/ui/gui/spokes/custom.py:121
msgid "RAID"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.py:122
msgid "Standard Partition"
msgstr "Szabványos partíció"

#: pyanaconda/ui/gui/spokes/custom.py:123
msgid "BTRFS"
msgstr "BTRFS"

#: pyanaconda/ui/gui/spokes/custom.py:124
#: pyanaconda/ui/gui/spokes/custom.glade:2088
#: pyanaconda/ui/gui/spokes/custom.glade:2289
#: pyanaconda/ui/gui/spokes/lib/resize.glade:140
msgid "Disk"
msgstr "Lemez"

#: pyanaconda/ui/gui/spokes/custom.py:439
#: pyanaconda/ui/gui/spokes/custom.glade:389
msgid "MANUAL PARTITIONING"
msgstr "KÉZI PARTICIONÁLÁS"

#: pyanaconda/ui/gui/spokes/custom.py:636
#, python-format
msgid "%d storage device selected"
msgid_plural "%d storage devices selected"
msgstr[0] "%d tárolóeszköz kiválasztva"
msgstr[1] "%d tárolóeszköz kiválasztva"

#: pyanaconda/ui/gui/spokes/custom.py:789
#: pyanaconda/ui/gui/spokes/network.py:585
#: pyanaconda/ui/gui/spokes/network.py:1001
msgid "Unknown"
msgstr "Ismeretlen"

#: pyanaconda/ui/gui/spokes/custom.py:818
msgid ""
"The 'swap' area on your computer is used by the operating\n"
"system when running low on memory."
msgstr ""
"A 'swap' terület az operációs rendszer által akkor\n"
"kerül felhasználásra amikor kevés a memóriája."

#: pyanaconda/ui/gui/spokes/custom.py:821
msgid ""
"The 'boot' area on your computer is where files needed\n"
"to start the operating system are stored."
msgstr ""
"A 'boot' terület a számítógépén azokat a fájlokat tartal-\n"
"mazzák amivel a tárolt operációs rendszert elindíthatja."

#: pyanaconda/ui/gui/spokes/custom.py:824
msgid ""
"The 'root' area on your computer is where core system\n"
"files and applications are stored."
msgstr ""
"A 'root' terület az a rész a gépén, ami rendszer \n"
"fő részeit és az alkalmazásait tárolja."

#: pyanaconda/ui/gui/spokes/custom.py:827
msgid ""
"The 'home' area on your computer is where all your personal\n"
"data is stored."
msgstr ""
"A 'home' terület a gépén a az terület ahol a\n"
"személyes fájljai s adatai kerülnek tárolásra."

#: pyanaconda/ui/gui/spokes/custom.py:830
msgid ""
"The BIOS boot partition is required to enable booting\n"
"from GPT-partitioned disks on BIOS hardware."
msgstr ""
"A BIOS boot particiója szükséges ahhoz, hogy bootolhasson\n"
"egy GPT-re particionált lemezről egy BIOS hardveren."

#: pyanaconda/ui/gui/spokes/custom.py:833
msgid ""
"The PReP boot partition is required as part of the\n"
"bootloader configuration on some PPC platforms."
msgstr ""
"A PReP boot partíció szükséges a rendszertöltő\n"
"konfiguráció részeként néhány PPC platformon."

#: pyanaconda/ui/gui/spokes/custom.py:995
#, python-format
msgid "/boot/efi must be on a device of type %s"
msgstr "/boot/efi számára %s típusú eszközön kell lennie"

#: pyanaconda/ui/gui/spokes/custom.py:999
#, python-format
msgid "%s must be on a device of type %s"
msgstr "%s számára %s típusú eszközön kell lennie"

#: pyanaconda/ui/gui/spokes/custom.py:1002
#: pyanaconda/ui/gui/spokes/custom.py:1004
#, python-format
msgid "%s cannot be encrypted"
msgstr "%s nem titkosítható"

#: pyanaconda/ui/gui/spokes/custom.py:1008
#, python-format
msgid "Devices of type %s require a valid RAID level selection."
msgstr "Az %s típusú eszközök érvényes RAID szint kiválasztását igénylik."

#: pyanaconda/ui/gui/spokes/custom.py:1014
msgid ""
"The RAID level you have selected requires more disks than you currently have "
"selected."
msgstr ""
"A kiválasztott RAID szintje több lemezt igényel, mint amit jelenleg "
"kiválasztott."

#: pyanaconda/ui/gui/spokes/custom.py:1173
msgid "Device resize request failed. Click for details."
msgstr "Eszköz átméretezési kérése meghiúsult. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:1227
#, python-format
msgid "Specified name %s already in use."
msgstr "A megadott %s név már használatban van."

#: pyanaconda/ui/gui/spokes/custom.py:1294
msgid "Device reformat request failed. Click for details."
msgstr "Eszköz újraformázási kérése meghiúsult. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:1558
msgid "This file system does not support labels."
msgstr "Ez a fájlrendszer nem támogatja a cimkéket."

#: pyanaconda/ui/gui/spokes/custom.py:1576
msgid "This file system may not be resized."
msgstr "Ez a fájlrendszer nem átméretezhető."

#: pyanaconda/ui/gui/spokes/custom.py:1848
#, python-format
msgid "Added new %s to existing container %s."
msgstr "Egy új %s került hozzáadásra a meglévő %s gyűjtőhöz."

#: pyanaconda/ui/gui/spokes/custom.py:1856
msgid "Failed to add new device. Click for details."
msgstr "Új eszköz hozzáadása sikertelen. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:1862
msgid "Invalid partition size set. Use a valid integer."
msgstr "Érvénytelen partíciós méret. Adjon meg valós egész értéket."

#: pyanaconda/ui/gui/spokes/custom.py:1882
msgid "Device removal request failed. Click for details."
msgstr "Eszköz eltávolitási kérése meghiúsult. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:2077
#, python-format
msgid "Volume Group name %s is already in use. Not saving changes."
msgstr ""
"A kötetcsoport %s neve már használatban van. Változtatások nem kerülnek "
"mentésre."

#: pyanaconda/ui/gui/spokes/custom.py:2168
#, python-format
msgid ""
"This Software RAID array is missing %d of %d member partitions. You can "
"remove it or select a different device."
msgstr ""
"Ez a szoftveres RAID kötet hiányol a %d / %d rész partíciót. Eltávolíthatja, "
"vagy választhat egy másik eszközt."

#: pyanaconda/ui/gui/spokes/custom.py:2174
#, python-format
msgid ""
"This LVM Volume Group is missing %d of %d physical volumes. You can remove "
"it or select a different device."
msgstr ""
"Ez a szoftveres LVM kötet hiányol a %d / %d rész partíciót. Eltávolíthatja, "
"vagy választhat egy másik eszközt."

#: pyanaconda/ui/gui/spokes/custom.py:2247
msgid "No disks selected."
msgstr "Nincsenek lemezek kiválasztva."

#: pyanaconda/ui/gui/spokes/custom.py:2253
msgid "Not enough free space on selected disks."
msgstr "Nincs elég szabad hely a kiválasztott lemezeken."

#: pyanaconda/ui/gui/spokes/custom.py:2259
msgid "Automatic partitioning failed. Click for details."
msgstr "Automata particionálás sikertelen. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:2499
msgid "Failed to unlock encrypted block device. Click for details"
msgstr ""
"A titkosított blokk eszköz feloldása sikertelen. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/custom.py:2522
#, python-format
msgid ""
"You have chosen to manually set up the filesystems for your new "
"%(productName)s installation. Before you begin, you might want to take a "
"minute to learn the lay of the land. Quite a bit has changed.\n"
"\n"
"The most important change is that creation of new filesystems has been "
"streamlined. You no longer have to build complex devices like LVM logical "
"volumes in stages (physical volume, then volume group, then logical volume) "
"-- now you just create a logical volume and we'll handle the legwork of "
"setting up the physical volumes and volume group to contain it. We'll also "
"handle adjusting the volume group as you add, remove, and resize logical "
"volumes so you don't have to worry about the mundane details.\n"
"\n"
"\n"
"Screen Layout\n"
"\n"
"The left-hand side of the screen shows the OS installations we were able to "
"find on this computer. The new %(productName)s installation is at the top of "
"the list. You can click on the names of the installations to see what "
"filesystems they contain.\n"
"\n"
"Below the various installations and mountpoints on the left-hand side there "
"are buttons to add a new filesystem, remove the selected filesystem, or "
"configure the selected filesystem.\n"
"\n"
"The right-hand side of the screen is where you can customize the currently-"
"selected mountpoint.\n"
"\n"
"On the bottom-left you will see a summary of the disks you have chosen to "
"use for the installation. You can click on the blue text to see more "
"detailed information about your selected disks.\n"
"\n"
"\n"
"How to create a new filesystem on a new device\n"
"\n"
"1. Click on the + button.\n"
"2. Enter the mountpoint and size. (Hint: Hover the mouse pointer over either "
"of the text entry areas for help.)\n"
"3. Select the new mountpoint under \"New %(productName)s Installation\" on "
"the left-hand side of the screen and customize it to suit your needs.\n"
"\n"
"\n"
"How to reformat a device/filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem from the left-hand side of the screen.\n"
"2. Click on the \"Customize\" expander in the mountpoint customization area "
"on the right-hand side of the screen.\n"
"3. Activate the \"Reformat\" checkbutton, select a filesystem type and, if "
"applicable, enter a mountpoint above in the \"Mountpoint\" text entry area.\n"
"4. Click on \"Apply changes\"\n"
"\n"
"\n"
"How to set a mountpoint for a filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem from the left-hand side of the screen.\n"
"2. Enter a mountpoint in the \"Mountpoint\" text entry area in the "
"mountpoint customization area.\n"
"3. Click on \"Apply changes\"\n"
"\n"
"\n"
"How to remove a filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem you wish to remove on the left-hand side of the "
"screen.\n"
"2. Click the - button.\n"
"\n"
"Hint: Removing a device that already exists on your disk from the \"New "
"%(productName)s Installation\" does not remove it from the disk. It only "
"resets that device to its original state. To remove a device that already "
"exists on your disk, you must select it from under any of the other detected "
"installations (or \"Unknown\") and hit the - button.\n"
"\n"
"\n"
"Tips and hints\n"
"\n"
"You can enter sizes for new filesystems that are greater than the total "
"available free space. The installer will come as close as possible to the "
"size you request.\n"
"\n"
"By default, new devices use any/all of your selected disks.\n"
"\n"
"You can change which disks a new device may be allocated from by clicking "
"the configure button (the one with a tools graphic) while that device is "
"selected.\n"
"\n"
"When adding a new mountpoint by clicking the + button, leave the size entry "
"blank to make the new device use all available free space.\n"
"\n"
"When you remove the last device from a container device like an LVM volume "
"group, we will automatically remove that container device to make room for "
"new devices.\n"
"\n"
"When the last partition is removed from a disk, that disk may be "
"reinitialized with a new partition table if we think there is a more "
"appropriate type for that disk.\n"
msgstr ""
"Úgy döntött, hogy manuálisan állítja be a fájlrendszert az új "
"%(productName)s telepítéséhez. Mielőtt elkezdené, érdemes egy percet, hogy "
"tanulmányozza a felületet. Ez eléggé megváltozott a korábbiakhoz képest.\n"
"\n"
" A legfontosabb változás az, hogy az új fájlrendszer létrehozása "
"modernizálásra került. Többé nem kell kézzel felépíteni bonyolult eszközöket "
"lépésenként, mint a LVM logikai köteteket (fizikai méret, majd kötet "
"csoport, majd a logikai kötet) -- most csak hozzon létre egy logikai kötetet "
"és mi kezeljük a további beállításokhoz igényelt utánjárást,  ideértve a "
"fizikai kötetméreteket és a kötetcsoportot - ami tartalmazza majd azt. "
"Kezelni fogjuk a kötetcsoport kiigazítását, ahogy hozzáadja, az "
"eltávolítását és átméretezését a logikai köteteknek is, így nem kell "
"bajlódnia a különféle részletekkel.\n"
"\n"
"\n"
"Felület elrendezés\n"
"\n"
"A bal oldali a képernyőn a különféle operációs rendszer  telepítéseket "
"tudjuk megtalálni ezen a számítógépen. Az új %(productName)s telepítést a "
"lista tetején találja. Kattintson a telepítés nevére, hogy lássa milyen "
"fájlrendszert tartalmaznak azok.\n"
"\n"
"A különböző telepítések és csatlakoztatási pontok alatt a bal oldalon "
"gombokat talál új fájlrendszer hozzáadásához, eltávolításához,  vagy "
"beállításához.\n"
"\n"
"A jobb oldalon a képernyőn, az hely az, ahol testre szabhatja az aktuálisan "
"kiválasztott csatolási pontokat.\n"
"\n"
"A bal alsó részben látni fog mindig egy összefoglalót a kiválasztott "
"lemezekről - amikről úgy döntött, hogy használni fog a telepítéshez. Ha "
"további részletek is érdeklik a lemezeket illetően, akkor kattintson a kék "
"szövegre további részletes információhoz.\n"
"\n"
"\n"
"Hogyan hozzunk létre egy új fájlrendszert egy új eszközön\n"
"\n"
"1. Kattintson a + gombra.\n"
"2. Adja meg a csatolási pontot és a méretét. (Tipp: Vigye az egérmutatót "
"bármelyik szövegbeviteli területre segítségért.)\n"
"3. Válassza ki az új csatlakoztatási pont alatt az \"Új %(productName)s "
"telepítés\", majd a bal oldalon szabja testre, hogy megfeleljen az "
"igényeinek.\n"
"\n"
"\n"
"Hogyan formázhat eszközt / fájlrendszert, amely már létezik a lemezen\n"
"\n"
"1. Válassza ki a fájlrendszert a képernyő bal oldalán.\n"
"2. Kattintson a \"Testreszabás\" kibontható menün a csatolási pont "
"beállítási területen a képernyő jobb oldalán.\n"
"3. Aktiválja az \"Újraformázás\" jelölőmezőt, válassza ki a fájlrendszer "
"típusát és adott esetben, adjon meg egy csatolási pontot a \"Csatolási pont"
"\" beviteli mezőben.\n"
"4. Kattintson a \"Módosítások alkalmazása\" gombra\n"
"\n"
"\n"
"Hogyan kell beállítani egy csatolási pontot a fájlrendszerhez, amely már "
"létezik a lemezen\n"
"\n"
"1. Válassza ki a fájlrendszert a képernyő bal oldalán.\n"
"2. Írja be a csatlakoztatási pontot a \"Csatolási pont\" szövegbeviteli "
"terület a csatolási pont testreszabási területen.\n"
"3. Kattintson a \"Módosítások alkalmazása\" gombra \n"
"\n"
"\n"
"Hogyan kell eltávolítani a fájlrendszert, amely már létezik a lemezen\n"
"\n"
"1. Válassza ki az eltávolítani kívánt fájlrendszert a képernyő bal "
"oldalán. \n"
"2. Kattintson a - gombra.\n"
"\n"
"Tipp: Eszköz eltávolítása, amely már létezik a lemezen az \"Új "
"%(productName)s telepítés\"-ben nem távolítja el a lemezről. Csak "
"visszaállítja az eszközt az eredeti állapotába. Ha el szeretne távolítani "
"egy eszközt, amely már létezik a lemezen, akkor ki kell választania bármely "
"egyéb felismert telepítések  (vagy \"Ismeretlen\") közül, és nyomja meg a - "
"gombot.\n"
"\n"
"Tippek és tanácsok\n"
"\n"
"Megadhat  az új fájlrendszerekhez méreteiben olyan értéket, amely nagyobb, "
"mint a teljes rendelkezésre álló szabad hely. A telepítő kívánthoz a lehető "
"legközelebbi méretet igyekszik majd felajánlani. \n"
"\n"
"Alapértelmezés szerint az új eszközök felhasználhatnak bármely / minden "
"kiválasztott lemezt.\n"
"\n"
"Megadhatja mely lemez kerüljön felosztásra, akkor ha a Beállítás gombra "
"kattint (Az egyik az egy grafikus eszköz), addig míg az eszköz ki van "
"választva.\n"
"\n"
"Ha  egy új csatolási pontot ad meg, kattintson a + gombra, majd hagyja a "
"méret bejegyzést üresen, hogy az új eszköz felhasználhassa az összes "
"rendelkezésre álló szabad helyet.\n"
"\n"
"Ha eltávolítja az utolsó eszközt egy olyan konténer eszközből, mint egy LVM "
"kötet-csoport, akkor automatikusan eltávolítjuk a konténer eszközt, hogy "
"legyen helye az új eszközök számára. \n"
"\n"
"Amikor az utolsó partíciót is eltávolítjuk a lemezről, előfordulhat, hogy a "
"lemez alapállapotba állításakor új partíciós tábla kerül beállításra, ha úgy "
"érezzük, ott megfelelőbb típus elérhető az adott lemez számára. \n"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:56
msgid "Note: pool servers may not be available all the time"
msgstr "Megjegyzés: távoli pool kiszolgálók nem minden esetben elérhetőek"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:296
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:31
msgid "DATE & TIME"
msgstr "DÁTUM ÉS IDŐ"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:381
msgid "Invalid timezone"
msgstr "Rossz időzóna"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:813
msgid "You need to set up networking first if you want to use NTP"
msgstr ""
"Elsőként a hálózatot kell beállítania ha az NTP szolgáltatást kívánja "
"használni."

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:817
msgid "You have no working NTP server configured"
msgstr "Nincs működő NTP kiszolgálója beállítva"

#: pyanaconda/ui/gui/spokes/keyboard.py:40
#, python-format
msgid "%s to switch layouts."
msgstr "Kiosztás váltásához :%s"

#: pyanaconda/ui/gui/spokes/keyboard.py:261
msgid "KEYBOARD"
msgstr "BILLENTYŰZET"

#: pyanaconda/ui/gui/spokes/keyboard.py:318
msgid "Testing layouts configuration not available."
msgstr "Teszt kiosztás összeállítása nem elérhető."

#: pyanaconda/ui/gui/spokes/keyboard.py:372
msgid "Layout switching not configured."
msgstr "Kiosztás váltási funkció nincs beállítva."

#: pyanaconda/ui/gui/spokes/network.py:92
msgid "Status unknown (missing)"
msgstr "Állapot ismeretlen (hiányzik)"

#: pyanaconda/ui/gui/spokes/network.py:96
msgid "Status unknown"
msgstr "Állapot ismeretlen"

#: pyanaconda/ui/gui/spokes/network.py:98
msgid "Unmanaged"
msgstr "Nincs beállítva"

#: pyanaconda/ui/gui/spokes/network.py:101
msgid "Firmware missing"
msgstr "Firmware hiányzik"

#: pyanaconda/ui/gui/spokes/network.py:104
msgid "Cable unplugged"
msgstr "Kábel kihúzva"

#: pyanaconda/ui/gui/spokes/network.py:106
msgid "Unavailable"
msgstr "Elérhetetlen"

#: pyanaconda/ui/gui/spokes/network.py:108
msgid "Disconnected"
msgstr "Leválasztva"

#: pyanaconda/ui/gui/spokes/network.py:113
msgid "Connecting"
msgstr "Csatlakozás"

#: pyanaconda/ui/gui/spokes/network.py:115
msgid "Authentication required"
msgstr "Azonosítás szükséges"

#: pyanaconda/ui/gui/spokes/network.py:117
msgid "Connected"
msgstr "Csatlakozás"

#: pyanaconda/ui/gui/spokes/network.py:119
msgid "Disconnecting"
msgstr "Leválasztás"

#: pyanaconda/ui/gui/spokes/network.py:121
msgid "Connection failed"
msgstr "Csatlakozás sikertelen"

#: pyanaconda/ui/gui/spokes/network.py:574
msgid "unplugged"
msgstr "kihúzva"

#: pyanaconda/ui/gui/spokes/network.py:587
msgid "Ethernet"
msgstr "Vezetékes"

#: pyanaconda/ui/gui/spokes/network.py:589
msgid "Wireless"
msgstr "Vezeték nélküli"

#: pyanaconda/ui/gui/spokes/network.py:683
#: pyanaconda/ui/gui/spokes/network.glade:349
#: pyanaconda/ui/gui/spokes/network.glade:702
msgid "IPv4 Address"
msgstr "IPv4 cím"

#: pyanaconda/ui/gui/spokes/network.py:684
#: pyanaconda/ui/gui/spokes/network.glade:363
#: pyanaconda/ui/gui/spokes/network.glade:716
#: pyanaconda/ui/gui/spokes/network.glade:1335
msgid "IPv6 Address"
msgstr "IPv6 cím"

#: pyanaconda/ui/gui/spokes/network.py:686
#: pyanaconda/ui/gui/spokes/network.py:688
#: pyanaconda/ui/gui/spokes/network.glade:1321
msgid "IP Address"
msgstr "IP cím"

#: pyanaconda/ui/gui/spokes/network.py:753
#, python-format
msgid "%d Mb/s"
msgstr "%d Mb/s"

#: pyanaconda/ui/gui/spokes/network.py:930
msgid "WEP"
msgstr "WEP"

#: pyanaconda/ui/gui/spokes/network.py:933
msgid "WPA"
msgstr "WPA"

#: pyanaconda/ui/gui/spokes/network.py:936
msgid "WPA2"
msgstr "WPA2"

#: pyanaconda/ui/gui/spokes/network.py:940
msgid "Enterprise"
msgstr "Enterprise"

#: pyanaconda/ui/gui/spokes/network.py:945 widgets/src/SpokeSelector.c:54
msgid "None"
msgstr "Nincs"

#: pyanaconda/ui/gui/spokes/network.py:967
#: pyanaconda/ui/gui/spokes/network.glade:37
#: pyanaconda/ui/gui/spokes/network.glade:109
msgid "NETWORK CONFIGURATION"
msgstr "HÁLÓZATI BEÁLLÍTÁSOK"

#: pyanaconda/ui/gui/spokes/network.py:1005
msgid "Connecting..."
msgstr "Csatlakozás..."

#: pyanaconda/ui/gui/spokes/network.py:1007
msgid "Disconnecting..."
msgstr "Leválasztás..."

#: pyanaconda/ui/gui/spokes/network.py:1014
#, python-format
msgid "Wireless connected to %s"
msgstr "Vezeték nélküli eszköz csatlakozott ide: %s"

#: pyanaconda/ui/gui/spokes/network.py:1017
#, python-format
msgid "Wired (%s) connected"
msgstr "Vezetékes (%s) kapcsolat csatlakozott"

#: pyanaconda/ui/gui/spokes/network.py:1027
#, python-format
msgid "Connected: %s"
msgstr "Csatlakoztatva ide: %s"

#: pyanaconda/ui/gui/spokes/network.py:1029
msgid "Not connected"
msgstr "Nincs csatlakozva"

#: pyanaconda/ui/gui/spokes/network.py:1032
#: pyanaconda/ui/gui/spokes/network.glade:2085
msgid "No network devices available"
msgstr "Nincs elérhető hálózati eszköz."

#: pyanaconda/ui/gui/spokes/network.py:1072
#: pyanaconda/ui/gui/spokes/network.py:1142
#, python-format
msgid "Hostname is not valid: %s"
msgstr "Kiszolgálónév nem érvényes: %s"

#: pyanaconda/ui/gui/spokes/password.py:48
#: pyanaconda/ui/gui/spokes/password.glade:9
msgid "ROOT PASSWORD"
msgstr "RENDSZERGAZDA JELSZÓ"

#: pyanaconda/ui/gui/spokes/password.py:77
msgid "Error setting root password"
msgstr "Hiba történt a root jelszó beállításakor"

#: pyanaconda/ui/gui/spokes/password.py:79
msgid "Root password is set"
msgstr "Root jelszó beállítva"

#: pyanaconda/ui/gui/spokes/password.py:81
msgid "Root account is disabled"
msgstr "Root felhasználó kikapcsolva"

#: pyanaconda/ui/gui/spokes/password.py:83
msgid "Root password is not set"
msgstr "Root jelszó nincs beállítva"

#: pyanaconda/ui/gui/spokes/password.py:103
msgid "You must provide and confirm a password."
msgstr "Ajda meg jelszavát amit meg kell erősítenie."

#: pyanaconda/ui/gui/spokes/password.py:113
#, python-format
msgid "You have provided a weak password: %s.  Press Done again to use anyway."
msgstr ""
"Gyenge jelszót adott meg: %s. Nyomjon újra elfogadást ha mégis felhasználná."

#: pyanaconda/ui/gui/spokes/software.py:53
#: pyanaconda/ui/gui/spokes/software.glade:31
msgid "SOFTWARE SELECTION"
msgstr "SZOFTVER KIVÁLASZTÁS"

#: pyanaconda/ui/gui/spokes/software.py:107
#: pyanaconda/ui/gui/spokes/source.py:612
msgid "Checking software dependencies..."
msgstr "Szoftverek függőségeinek ellenőrzése..."

#: pyanaconda/ui/gui/spokes/software.py:113
msgid "Error checking software dependencies"
msgstr "Hiba történt a függőségek ellenőrzésekor"

#: pyanaconda/ui/gui/spokes/software.py:150
msgid "Error checking software selection"
msgstr "Hiba a kiválasztott szoftverek ellenőrzésekor"

#: pyanaconda/ui/gui/spokes/software.py:153
msgid "Installation source not set up"
msgstr "Telepítési forrás nincs beállítva"

#: pyanaconda/ui/gui/spokes/software.py:156
msgid "Source changed - please verify"
msgstr "Forrás megváltozott - kérem ellenőrizze"

#: pyanaconda/ui/gui/spokes/software.py:164
msgid "Custom software selected"
msgstr "Egyéni szoftverek kiválasztva"

#: pyanaconda/ui/gui/spokes/software.py:166
#: pyanaconda/ui/gui/spokes/source.py:597
#: pyanaconda/ui/gui/spokes/source.py:630
msgid "Nothing selected"
msgstr "Semmi sincs kijelölve"

#: pyanaconda/ui/gui/spokes/software.py:175
#: pyanaconda/ui/gui/spokes/source.py:50
msgid "Downloading package metadata..."
msgstr "Csomagok metaadatainak letöltése..."

#: pyanaconda/ui/gui/spokes/software.py:181
msgid "Downloading group metadata..."
msgstr "Csoport metaadatainak letöltése..."

#: pyanaconda/ui/gui/spokes/software.py:215
#: pyanaconda/ui/gui/spokes/source.py:589
msgid "No installation source available"
msgstr "Nincs elérhető telepítési forrás"

#: pyanaconda/ui/gui/spokes/software.py:265
msgid "Error checking software dependencies.  Click for details."
msgstr "Hiba történt a függőségek ellenőrzésekor. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/software.py:329
msgid ""
"The following software marked for installation has errors.  This is likely "
"caused by an error with\n"
"your installation source.  You can attempt to remove these packages from "
"your installation.\n"
"change your installation source, or quit the installer."
msgstr ""
"A következő telepítésre jelölt szoftverekben hiba van. Ez általában egy "
"olyan hiba okozza\n"
"ami telepítési forrással függ össze. Ebben az esetben megpróbálhatja "
"eltávolítani ezeket a csomagokat a telepítésből, \n"
"megváltoztathatja a telepítési forrást, vagy kiléphet a telepítőből."

#: pyanaconda/ui/gui/spokes/software.py:333
#: pyanaconda/ui/gui/spokes/storage.glade:613
#: pyanaconda/ui/gui/spokes/source.glade:592
#: pyanaconda/ui/gui/spokes/custom.glade:91
#: pyanaconda/ui/gui/spokes/custom.glade:341
#: pyanaconda/ui/gui/spokes/custom.glade:1956
#: pyanaconda/ui/gui/spokes/custom.glade:2194 pyanaconda/ui/gui/main.glade:20
msgid "_Cancel"
msgstr "_Mégsem"

#: pyanaconda/ui/gui/spokes/software.py:334
msgid "_Remove Packages"
msgstr "_Csomagok eltávolítása"

#: pyanaconda/ui/gui/spokes/software.py:335
msgid "_Modify Software Source"
msgstr "Szoftverforrás _módosítása"

#: pyanaconda/ui/gui/spokes/source.py:49
msgid "Setting up installation source..."
msgstr "Telepítési források beállítása..."

#: pyanaconda/ui/gui/spokes/source.py:51
msgid "Error downloading package metadata..."
msgstr "HIba a csomag metaadatainak letöltésekor..."

#: pyanaconda/ui/gui/spokes/source.py:144
msgid "This media is good to install from."
msgstr "Ez a média alkalmas a telepítésre."

#: pyanaconda/ui/gui/spokes/source.py:146
msgid "This media is not good to install from."
msgstr "Ez a média nem alkalmas a telepítésre."

#: pyanaconda/ui/gui/spokes/source.py:347
msgid "Getting info about requested repository"
msgstr "Információk letöltése a kért tárolóból."

#: pyanaconda/ui/gui/spokes/source.py:370
#: pyanaconda/ui/gui/spokes/source.glade:257
msgid "enter URL of your desired repository"
msgstr "adja meg az URL-t a kívánt tárolóhoz"

#: pyanaconda/ui/gui/spokes/source.py:428
#: pyanaconda/ui/gui/spokes/source.glade:827
msgid "INSTALLATION SOURCE"
msgstr "TELEPÍTÉSI FORRÁS"

#: pyanaconda/ui/gui/spokes/source.py:561
msgid "Failed to set up install source"
msgstr "Telepítési forrás beállítása sikertelen"

#: pyanaconda/ui/gui/spokes/source.py:563
#: pyanaconda/ui/gui/spokes/source.py:577
msgid "Failed to set up install source, check the repo url"
msgstr "Telepítési forrás beállítása sikertelen, ellenőrizze a megadott URL-t"

#: pyanaconda/ui/gui/spokes/source.py:565
msgid "Failed to set up install source, check the repo url and proxy settings"
msgstr ""
"Telepítési forrás beállítása sikertelen, ellenőrizze a megadott tároló URL-"
"t, és proxy beállításait"

#: pyanaconda/ui/gui/spokes/source.py:614
msgid "Not ready"
msgstr "Nem kész"

#: pyanaconda/ui/gui/spokes/source.py:616
#: pyanaconda/ui/gui/spokes/source.py:625
msgid "Error setting up software source"
msgstr "Szoftver forrás beállítása sikertelen"

#: pyanaconda/ui/gui/spokes/source.py:620
#, python-format
msgid "NFS server %s"
msgstr "NFS kiszolgáló %s"

#: pyanaconda/ui/gui/spokes/source.py:622
msgid "CD/DVD drive"
msgstr "CD/DVD meghajtó"

#: pyanaconda/ui/gui/spokes/source.py:628
msgid "Closest mirror"
msgstr "Legközelebbi tükör"

#: pyanaconda/ui/gui/spokes/storage.py:151
#, python-format
msgid ""
"You have plenty of space to install <b>%s</b>, so we can automatically\n"
"configure the rest of the installation for you.\n"
"\n"
"You're all set!"
msgstr ""
"Rengeteg tárhellyel rendelkezik a telepítéshez <b>%s</b>, így automatikusan\n"
"beállíthatjuk a telepítés hátralévő lépéseit.\n"
"\n"
"Minden kész! "

#: pyanaconda/ui/gui/spokes/storage.py:170
#, python-format
msgid ""
"Your current <b>%s</b> software selection requires <b>%s</b> of available "
"space."
msgstr ""
"A jelenlegi <b>%s</b> szoftver összeállítása <b>%s</b> tárhelyet igényel."

#: pyanaconda/ui/gui/spokes/storage.py:243
#, python-format
msgid ""
"%s\n"
"The disks you've selected have the following amounts of free space:"
msgstr ""
"%s\n"
"A kiválasztott lemezeken elérhető összes szabad hely:"

#: pyanaconda/ui/gui/spokes/storage.py:252
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>, but we can help "
"you\n"
"reclaim space by shrinking or removing existing partitions."
msgstr ""
"<b>Nincs elég szabad tárhelye %s</b> telepítéshez, de segíthetünk\n"
"visszanyerni átméretezéssel, vagy a partíciók eltávolításával."

#: pyanaconda/ui/gui/spokes/storage.py:274
#, python-format
msgid ""
"%s\n"
"You don't have enough space available to install <b>%s</b>, even if you used "
"all of the free space\n"
"available on the selected disks."
msgstr ""
"%s\n"
"Nincs elég szabad tárhelye <b>%s</b> telepítéshez, még ha fel is használja "
"az összes szabad tárhelyet\n"
"a kiválasztott lemezeken."

#: pyanaconda/ui/gui/spokes/storage.py:285
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>, even if you used "
"all of the free space\n"
"available on the selected disks.  You could add more disks for additional "
"space,\n"
"modify your software selection to install a smaller version of <b>%s</b>, or "
"quit the installer."
msgstr ""
"<b>Nincs elég szabad tárhelye %s telepítéshez</b>, még ha fel is használja "
"az összes szabad tárhelyet\n"
"a kiválasztott lemezeken. További lemezeket adhat hozzá bővebb tárhely "
"kapacitásért,\n"
"módosíthatja, leválogathatja a szoftvereit, hogy kisebb méretű verziót "
"kapjon <b>%s</b>, vagy kiléphet a telepítőből."

#: pyanaconda/ui/gui/spokes/storage.py:325
#: pyanaconda/ui/gui/spokes/storage.glade:844
msgid "INSTALLATION DESTINATION"
msgstr "TELEPÍTÉSI CÉL"

#: pyanaconda/ui/gui/spokes/storage.py:397
msgid "Saving storage configuration..."
msgstr "Tároló konfiguráció mentése..."

#: pyanaconda/ui/gui/spokes/storage.py:404
msgid "Failed to save storage configuration..."
msgstr "Tároló összeállítás mentése sikertelen..."

#: pyanaconda/ui/gui/spokes/storage.py:496
msgid "Error checking storage configuration.  Click for details."
msgstr ""
"Hiba az tárolók összeállításának vizsgálatakor. Kattintson a részletekért."

#: pyanaconda/ui/gui/spokes/storage.py:575
#, python-format
msgid "%d disk selected; %s capacity; %s free"
msgid_plural "%d disks selected; %s capacity; %s free"
msgstr[0] "%d lemez kiválasztva; %s kapacitással; %s szabad"
msgstr[1] "%d lemez kiválasztva; %s kapacitással; %s szabad"

#: pyanaconda/ui/gui/spokes/storage.py:627
msgid ""
"You have chosen to skip bootloader installation.  Your system may not be "
"bootable."
msgstr ""
"Az választotta, hogy kihagyja a rendszerbetöltő telepítését. A rendszere "
"lehetséges, hogy nem lesz indítható."

#: pyanaconda/ui/gui/spokes/storage.py:767
msgid ""
"The following errors were encountered when checking your storage "
"configuration.  You can modify your storage layout\n"
"or quit the installer."
msgstr ""
"A következő hibák léptek fel a tárolók összeállításának vizsgálatakor. Ebben "
"az esetben módosíthatja a tárolók kiosztását,\n"
"vagy kiléphet a telepítőből."

#: pyanaconda/ui/gui/spokes/storage.py:770
msgid "_Modify Storage Layout"
msgstr "_Módosítsa a tárhely kiosztását"

#: pyanaconda/ui/gui/spokes/welcome.py:310
msgid "LANGUAGE"
msgstr "NYELV"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:130
msgid "DATA"
msgstr "ADATOK"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:135
msgid "SYSTEM"
msgstr "RENDSZER"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:235
#, python-format
msgid "You haven't created any mount points for your %s %s installation yet:"
msgstr "Még nem készített egyetlen csatolási pontot sem a %s %s telepítéséhez:"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:240
msgid "Click here to create them automatically."
msgstr "Kattintson ide az automatikus elkészítésükhez."

#: pyanaconda/ui/gui/spokes/lib/accordion.py:250
msgid "Or, create new mount points below with the '+' icon."
msgstr "Vagy,  készítsen új csatolási pontokat az alábbi '+' ikonnal."

#: pyanaconda/ui/gui/spokes/lib/cart.py:138
#, python-format
msgid ""
"<b>%d disk; %s capacity; %s free space</b> (unpartitioned and in filesystems)"
msgid_plural ""
"<b>%d disks; %s capacity; %s free space</b> (unpartitioned and in "
"filesystems)"
msgstr[0] ""
"<b>%d lemez; %s kapacitás; %s szabad terület</b> (partícionálatlan és a "
"rendszeren belül)"
msgstr[1] ""
"<b>%d lemez; %s kapacitás; %s szabad terület</b> (partícionálatlan és a "
"rendszeren belül)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:190
msgid "_Do not install bootloader"
msgstr "Ne telepítsen rendszerbetöltőt"

#: pyanaconda/ui/gui/spokes/lib/cart.py:192
#: pyanaconda/ui/gui/spokes/lib/cart.glade:190
msgid "_Set as Boot Device"
msgstr "Állít_sa be mint bootolható eszközt"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:38
#, python-format
msgid ""
"Warning: Your current keyboard layout is <b>%s</b>.If you change your "
"keyboard layout, you may not be able to decrypt your disks after install."
msgstr ""
"Figyelem: A jelenlegi billentyűzet kiosztása: <b>%s</b>. Ha megváltoztatja a "
"billentyűzet kiosztását, előfordulhat, hogy nem lesz képes többet feloldani "
"a lemezei titkosítását telepítés után."

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:42
#, python-format
msgid "You have provided a weak passphrase: %s"
msgstr "Gyenge jelszót adott meg: %s"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:43
msgid "Passphrases do not match."
msgstr "Jelszavak nem egyeznek."

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:116
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:165
msgid "Weak"
msgstr "Gyenge"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:119
msgid "Fair"
msgstr "Elégséges"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:122
msgid "Good"
msgstr "Jó"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:125
msgid "Strong"
msgstr "Erős"

#: pyanaconda/ui/gui/spokes/lib/resize.py:46
#: pyanaconda/ui/gui/spokes/lib/resize.glade:216
msgid "Preserve"
msgstr "Megőriz"

#: pyanaconda/ui/gui/spokes/lib/resize.py:47
msgid "Shrink"
msgstr "Összezsugorít"

#: pyanaconda/ui/gui/spokes/lib/resize.py:48
#: pyanaconda/ui/gui/spokes/lib/resize.glade:228
msgid "Delete"
msgstr "Törli"

#: pyanaconda/ui/gui/spokes/lib/resize.py:134
msgid "Whole disks are not editable."
msgstr "Teljes lemezek nem szerkeszthetőek."

#: pyanaconda/ui/gui/spokes/lib/resize.py:151
msgid "This device contains the installation source."
msgstr "Ez az eszköz tartalmazza a telepítési forrást."

#: pyanaconda/ui/gui/spokes/lib/resize.py:158
#, python-format
msgid "%s of %s"
msgstr "%s %s"

#: pyanaconda/ui/gui/spokes/lib/resize.py:175
msgid ""
"You don't have enough free space available for this installation.\n"
"\n"
"You can remove existing filesystems you no longer need to free up space for "
"this installation.  Removing a filesystem will permanently delete all of the "
"data it contains."
msgstr ""
"Nincs elegendő szabad helye ehhez a telepítéshez.\n"
"\n"
"Eltávolíthatja a létező fájlrendszereket, amikre továbbiakban nincs "
"szüksége, hogy felszabadítson szabad helyet ehhez a telepítéshez. A teljes "
"fájlrendszer eltávolításával véglegesen törli az összes adatot amit "
"tartalmaz."

#: pyanaconda/ui/gui/spokes/lib/resize.py:191
#, python-format
msgid "<b>%s disk; %s reclaimable space</b> (in filesystems)"
msgid_plural "<b>%s disks; %s reclaimable space</b> (in filesystems)"
msgstr[0] "<b>%s lemez; %s visszanyerhető tárhely</b> (fájlrendszerben)"
msgstr[1] "<b>%s lemezek; %s visszanyerhető tárhely</b> (fájlrendszerben)"

#: pyanaconda/ui/gui/spokes/lib/resize.py:197
#, python-format
msgid "Total selected space to reclaim: <b>%s</b>"
msgstr "Teljes visszanyerni kívánt tárhely:  <b>%s</b>"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:87
msgid "Region:"
msgstr "Régió:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:120
msgid "City:"
msgstr "Város:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:164
msgid "Network Time"
msgstr "Hálózati idő"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:257
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:289
msgid "00"
msgstr "00"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:273
msgid ":"
msgstr ":"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:401
msgid " "
msgstr " "

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:417
msgid "PM"
msgstr "DU"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:461
msgid "24-hour"
msgstr "24 órás"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:479
msgid "AM/PM"
msgstr "DE/DU"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:646
msgid "Add and mark for usage NTP servers"
msgstr "Adja meg és jelölje ki az NTP kiszolgálók használatához"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:727
msgid "Hostname"
msgstr "Kiszolgálónév"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:742
msgid "Working"
msgstr "Működik"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:750
msgid "Use"
msgstr "Alkalmaz"

#: pyanaconda/ui/gui/spokes/network.glade:78
msgid ""
"We'll need network access to fetch information about your location and to "
"make software\n"
"updates available for you."
msgstr ""
"Szükséges egy hálózati hozzáférés a helyéről, és hogy\n"
"a szoftverfrissítések elérhetőek legyenek számára."

#: pyanaconda/ui/gui/spokes/network.glade:321
#: pyanaconda/ui/gui/spokes/network.glade:674
msgid "Hardware Address"
msgstr "Hardver cím"

#: pyanaconda/ui/gui/spokes/network.glade:335
#: pyanaconda/ui/gui/spokes/network.glade:688
#: pyanaconda/ui/gui/spokes/network.glade:1176
msgid "Speed"
msgstr "Sebessége"

#: pyanaconda/ui/gui/spokes/network.glade:377
msgid "Subnet Mask"
msgstr "Alhálózati maszk"

#: pyanaconda/ui/gui/spokes/network.glade:391
#: pyanaconda/ui/gui/spokes/network.glade:730
#: pyanaconda/ui/gui/spokes/network.glade:1349
msgid "Default Route"
msgstr "Alapértelmezett elérési út"

#: pyanaconda/ui/gui/spokes/network.glade:406
#: pyanaconda/ui/gui/spokes/network.glade:745
#: pyanaconda/ui/gui/spokes/network.glade:1364
msgid "DNS"
msgstr "DNS"

#: pyanaconda/ui/gui/spokes/network.glade:553
msgid "C_onfigure..."
msgstr "Beállítás..."

#: pyanaconda/ui/gui/spokes/network.glade:867
msgid "Security"
msgstr "Biztonság"

#: pyanaconda/ui/gui/spokes/network.glade:881
msgid "_Network Name"
msgstr "Hálózat  _neve"

#: pyanaconda/ui/gui/spokes/network.glade:897
msgid "Network Name"
msgstr "Hálózat neve"

#: pyanaconda/ui/gui/spokes/network.glade:911
msgid "Security Key"
msgstr " Biztonsági kulcs"

#: pyanaconda/ui/gui/spokes/network.glade:1001
msgid "_Use as Hotspot..."
msgstr "Alkalmazás Hotspot-ként..."

#: pyanaconda/ui/gui/spokes/network.glade:1020
msgid "_Stop Hotspot..."
msgstr "Hot_spot leállítása..."

#: pyanaconda/ui/gui/spokes/network.glade:1039
#: pyanaconda/ui/gui/spokes/network.glade:1391
#: pyanaconda/ui/gui/spokes/network.glade:1676
msgid "_Configure..."
msgstr "Beállítás..."

#: pyanaconda/ui/gui/spokes/network.glade:1162
msgid "IMEI"
msgstr "IMEI"

#: pyanaconda/ui/gui/spokes/network.glade:1190
msgid "Provider"
msgstr "Szolgáltató"

#: pyanaconda/ui/gui/spokes/network.glade:1504
msgid "VPN Type"
msgstr "VPN típusa"

#: pyanaconda/ui/gui/spokes/network.glade:1518
msgid "Gateway"
msgstr "Átjáró"

#: pyanaconda/ui/gui/spokes/network.glade:1532
msgid "Group Name"
msgstr "Csoport neve"

#: pyanaconda/ui/gui/spokes/network.glade:1546
msgid "Group Password"
msgstr "Csoport jelszava"

#: pyanaconda/ui/gui/spokes/network.glade:1560
msgid "Username"
msgstr "Felhasználónév"

#: pyanaconda/ui/gui/spokes/network.glade:1803
msgid "_Method"
msgstr "_Metódus"

#: pyanaconda/ui/gui/spokes/network.glade:1831
msgid "_Configuration URL"
msgstr "Beállítási URL"

#: pyanaconda/ui/gui/spokes/network.glade:1861
msgid "_HTTP Proxy"
msgstr "_HTTP Proxy"

#: pyanaconda/ui/gui/spokes/network.glade:1877
msgid "H_TTPS Proxy"
msgstr "H_TTPS Proxy"

#: pyanaconda/ui/gui/spokes/network.glade:1893
msgid "_FTP Proxy"
msgstr "_FTP Proxy"

#: pyanaconda/ui/gui/spokes/network.glade:1909
msgid "_Socks Host"
msgstr "_Socks Host"

#: pyanaconda/ui/gui/spokes/network.glade:2153
msgid "Unlock"
msgstr "Feloldás"

#: pyanaconda/ui/gui/spokes/network.glade:2173
msgid "Air_plane Mode"
msgstr "Re_pülő mód"

#: pyanaconda/ui/gui/spokes/network.glade:2207
msgid "Hostname:"
msgstr "Kiszolgáló neve:"

#: pyanaconda/ui/gui/spokes/software.glade:86
msgid "Choose your environment"
msgstr "Válasszon környezetet"

#: pyanaconda/ui/gui/spokes/software.glade:106
msgid "Choose your add-ons"
msgstr "Válassza ki a kiegészítő modulokat"

#: pyanaconda/ui/gui/spokes/software.glade:143
#: pyanaconda/ui/gui/spokes/software.glade:158
#: pyanaconda/ui/gui/spokes/software.glade:215
#: pyanaconda/ui/gui/spokes/software.glade:230
msgid "column"
msgstr "oszlop"

#: pyanaconda/ui/gui/spokes/software.glade:266
msgid "_Add custom add-on..."
msgstr "Egyéni bővítmény hozzá_adása..."

#: pyanaconda/ui/gui/spokes/storage.glade:26
#: pyanaconda/ui/gui/spokes/storage.glade:221
msgid "Cancel & _add more disks"
msgstr "Mégsem & további lemezek hozzá_adása"

#: pyanaconda/ui/gui/spokes/storage.glade:79
#: pyanaconda/ui/gui/spokes/storage.glade:293
#: pyanaconda/ui/gui/spokes/storage.glade:650
msgid "INSTALLATION OPTIONS"
msgstr "TELEPÍTÉSI OPCIÓK"

#: pyanaconda/ui/gui/spokes/storage.glade:96
#: pyanaconda/ui/gui/spokes/storage.glade:327
#: pyanaconda/ui/gui/spokes/storage.glade:806
msgid "Here we'll describe what your options are."
msgstr "Itt megjelenítjük milyen lehetőségei vannak."

#: pyanaconda/ui/gui/spokes/storage.glade:122
#: pyanaconda/ui/gui/spokes/storage.glade:477
msgid "<b>Partition type:</b>"
msgstr "<b>Partició típusa:</b>"

#: pyanaconda/ui/gui/spokes/storage.glade:155
#: pyanaconda/ui/gui/spokes/storage.glade:510
msgid "Partition scheme configuration"
msgstr "Partíciós séma összeállítása"

#: pyanaconda/ui/gui/spokes/storage.glade:170
msgid "Let me customize the _partitioning of the disks instead."
msgstr "Hagyja hogy egyénire szabjam a lemezek particionálását helyette."

#: pyanaconda/ui/gui/spokes/storage.glade:238
#: pyanaconda/ui/gui/spokes/storage.glade:594
msgid "_Modify software selection"
msgstr "Kijelölt szoftverek _módosítása"

#: pyanaconda/ui/gui/spokes/storage.glade:242
#: pyanaconda/ui/gui/spokes/storage.glade:598
msgid "Please wait... software metadata still loading."
msgstr "Kérem várjon... szoftver metaadatai még töltődnek..."

#: pyanaconda/ui/gui/spokes/storage.glade:257
msgid "Reclaim _space"
msgstr "Tárhely visszanyeré_se"

#: pyanaconda/ui/gui/spokes/storage.glade:310
#: pyanaconda/ui/gui/spokes/storage.glade:666
msgid ""
"Here we'll describe how much space is needed for the current software "
"selection."
msgstr ""
"Itt jelenítjük meg mennyi tárhelyre lesz szüksége a jelenlegi kiválasztott "
"szoftverekhez"

#: pyanaconda/ui/gui/spokes/storage.glade:353
#: pyanaconda/ui/gui/spokes/storage.glade:692
msgid "disk free"
msgstr "üres"

#: pyanaconda/ui/gui/spokes/storage.glade:371
#: pyanaconda/ui/gui/spokes/storage.glade:709
msgid "Free space available for use."
msgstr "szabad hely felhasználható"

#: pyanaconda/ui/gui/spokes/storage.glade:389
#: pyanaconda/ui/gui/spokes/storage.glade:727
msgid "fs free"
msgstr "fs szabad"

#: pyanaconda/ui/gui/spokes/storage.glade:407
#: pyanaconda/ui/gui/spokes/storage.glade:745
msgid "Free space unavailable but reclaimable from existing partitions."
msgstr ""
"Szabad terület ami nem elérhető, de visszanyerhető a meglévő partíciókból."

#: pyanaconda/ui/gui/spokes/storage.glade:425
#: pyanaconda/ui/gui/spokes/storage.glade:763
msgid "disks size"
msgstr "lemez mérete"

#: pyanaconda/ui/gui/spokes/storage.glade:443
#: pyanaconda/ui/gui/spokes/storage.glade:781
msgid "Space in selected disks reclaimable by deleting existing partitions."
msgstr ""
"A tárhely a kiválasztott lemezeken visszanyerhetőek a meglévő partíciók "
"törlésével. "

#: pyanaconda/ui/gui/spokes/storage.glade:525
msgid "I don't need help; let me customize disk _partitioning."
msgstr "Nincs szükségem segítségre, engedje át a lemez _particionálását."

#: pyanaconda/ui/gui/spokes/storage.glade:577
msgid "_Quit installer"
msgstr "Kilépés a telepítőből"

#: pyanaconda/ui/gui/spokes/storage.glade:891
msgid "Local Standard Disks"
msgstr "Helyi szabványos lemezek"

#: pyanaconda/ui/gui/spokes/storage.glade:972
msgid "Full disk summary and options..."
msgstr "Teljes lemezinformáció összegzés és opciók..."

#: pyanaconda/ui/gui/spokes/storage.glade:997
#: pyanaconda/ui/gui/spokes/custom.glade:1900
msgid "summary"
msgstr "összesítés"

#: pyanaconda/ui/gui/spokes/storage.glade:1011
msgid "Encrypt my data. I'll set a passphrase later."
msgstr "Titkosítsa az adatokat. A jelszót később állítom be."

#: pyanaconda/ui/gui/spokes/keyboard.glade:68
msgid "ADD A KEYBOARD LAYOUT"
msgstr "BILLENTYÚZETKIOSZTÁS HOZZÁADÁSA"

#: pyanaconda/ui/gui/spokes/keyboard.glade:85
msgid "You may add a keyboard layout by selecting it below:"
msgstr "Hozzáadhatja a billentyűzet kiosztását az alábbi listából kiválasztva:"

#: pyanaconda/ui/gui/spokes/keyboard.glade:121
msgid "Name"
msgstr "Neve"

#: pyanaconda/ui/gui/spokes/keyboard.glade:182
msgid "KEYBOARD LAYOUT"
msgstr "BILLENTYŰZET KIOSZTÁSA"

#: pyanaconda/ui/gui/spokes/keyboard.glade:223
msgid ""
"Which keyboard layouts would you like to use on this system?  You may move "
"any layout to the top of the list to select it as the default."
msgstr ""
"Melyik billentyűzetkiosztást szeretné használni ebben a rendszerben? "
"Bármelyik kiosztást elmozgathatja a lista elejére, hogy alapértelmezettként "
"kiválaszthassa."

#: pyanaconda/ui/gui/spokes/keyboard.glade:262
msgid ""
"Changes here will only apply to the installed system. Use the desktop's tool "
"to configure the keyboard for the installation process."
msgstr ""
"A változtatások csak a telepített rendszerre lesznek érvényesek. Használja a "
"felület eszközeit a telepítésnél a billentyűzet beállításához."

#: pyanaconda/ui/gui/spokes/keyboard.glade:319
msgid "name"
msgstr "neve"

#: pyanaconda/ui/gui/spokes/keyboard.glade:355
msgid "Add layout"
msgstr "Kiosztás hozzáadása"

#: pyanaconda/ui/gui/spokes/keyboard.glade:370
msgid "Remove layout"
msgstr "Kiosztás eltávolítása"

#: pyanaconda/ui/gui/spokes/keyboard.glade:385
msgid "Move selected layout up"
msgstr "Kiválasztott kiosztás mozgatása felfelé"

#: pyanaconda/ui/gui/spokes/keyboard.glade:400
msgid "Move selected layout down"
msgstr "Kiválasztott kiosztás mozgatása lefelé"

#: pyanaconda/ui/gui/spokes/keyboard.glade:416
msgid "Preview layout"
msgstr "Kiosztás előnézete"

#: pyanaconda/ui/gui/spokes/keyboard.glade:453
msgid "Test the selected layout below:"
msgstr "Tesztelje a kiválasztott kiosztást alább:"

#: pyanaconda/ui/gui/spokes/keyboard.glade:492
msgid "Alt + Shift to switch layouts."
msgstr "Alt + Shift a kiosztások átváltásához."

#: pyanaconda/ui/gui/spokes/keyboard.glade:506
msgid "_Options"
msgstr "_Opciók"

#: pyanaconda/ui/gui/spokes/keyboard.glade:623
msgid "LAYOUT SWITCHING OPTIONS"
msgstr "KIOSZTÁS VÁLTÁSI OPCIÓK"

#: pyanaconda/ui/gui/spokes/keyboard.glade:640
msgid ""
"Which combination(s) would you prefer for switching between keyboard layouts?"
msgstr ""
"Melyik kombináció(kat) részesíti előnyben a billentyűzet kioszás váltásához?"

#: pyanaconda/ui/gui/spokes/keyboard.glade:676
msgid "use"
msgstr "Alkalmaz"

#: pyanaconda/ui/gui/spokes/keyboard.glade:689
msgid "description"
msgstr "Leírás"

#: pyanaconda/ui/gui/spokes/password.glade:52
msgid "Root Password:"
msgstr "Root jelszó:"

#: pyanaconda/ui/gui/spokes/password.glade:67
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:127
msgid "Confirm:"
msgstr "Megerősítés:"

#: pyanaconda/ui/gui/spokes/password.glade:123
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"A root jelszó a rendszer adminisztrálására szolgál. Adja meg a jelszavát a "
"root felhasználóhoz."

#: pyanaconda/ui/gui/spokes/source.glade:35
#: pyanaconda/ui/gui/spokes/source.glade:607
msgid "_Add"
msgstr "_Hozzáadás"

#: pyanaconda/ui/gui/spokes/source.glade:66
msgid "ADD A CUSTOM ADD-ON"
msgstr "EGYÉNI BŐVÍTMÉNY HOZZÁADÁSA"

#: pyanaconda/ui/gui/spokes/source.glade:82
msgid "Where is the yum repository for your add-on?"
msgstr "Hol a yum tároló a bővítő moduljához?"

#: pyanaconda/ui/gui/spokes/source.glade:140
msgid "Repository"
msgstr "Tároló"

#: pyanaconda/ui/gui/spokes/source.glade:189
msgid "Fedora People Repositories"
msgstr "Fedora People tároló"

#: pyanaconda/ui/gui/spokes/source.glade:306
msgid "Standard YUM repository:"
msgstr "Szabványos YUM tároló:"

#: pyanaconda/ui/gui/spokes/source.glade:439 widgets/src/SpokeWindow.c:46
msgid "_Done"
msgstr "Kész"

#: pyanaconda/ui/gui/spokes/source.glade:472
msgid "MEDIA VERIFICATION"
msgstr "MÉDIA ELLENŐRZÉS"

#: pyanaconda/ui/gui/spokes/source.glade:499
msgid "Verifying media, please wait..."
msgstr "Média ellenőrzése, kérem várjon..."

#: pyanaconda/ui/gui/spokes/source.glade:635
msgid "_Enable HTTP Proxy"
msgstr "HTTP Proxy _engedélyezése"

#: pyanaconda/ui/gui/spokes/source.glade:668
msgid "<b>Proxy URL</b>"
msgstr "<b>Proxy URL</b>"

#: pyanaconda/ui/gui/spokes/source.glade:683
msgid "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"
msgstr "<span size=\"small\"><b>Például:</b> squid.mysite.org:3128</span>"

#: pyanaconda/ui/gui/spokes/source.glade:716
msgid "_Use Authentication"
msgstr "Azonosítás használata"

#: pyanaconda/ui/gui/spokes/source.glade:743
msgid "<b>Username</b>"
msgstr "<b>Felhasználói név</b>"

#: pyanaconda/ui/gui/spokes/source.glade:758
msgid "<b>Password</b>"
msgstr "<b>Jelszó</b>"

#: pyanaconda/ui/gui/spokes/source.glade:869
msgid "Which installation source would you like to use?"
msgstr "Melyik telepítési forrást kívánja felhasználni?"

#: pyanaconda/ui/gui/spokes/source.glade:883
msgid "_Auto-detected install media:"
msgstr "_Automatikusan észlelt média:"

#: pyanaconda/ui/gui/spokes/source.glade:938
#: pyanaconda/ui/gui/spokes/source.glade:1031
msgid "_Verify"
msgstr "Ellenőrzés"

#: pyanaconda/ui/gui/spokes/source.glade:961
msgid "_ISO file:"
msgstr "_ISO fájl:"

#: pyanaconda/ui/gui/spokes/source.glade:988
msgid "Device:"
msgstr "Eszköz:"

#: pyanaconda/ui/gui/spokes/source.glade:1016
msgid "_Choose an ISO"
msgstr "Válasszon egy ISO lemezképet"

#: pyanaconda/ui/gui/spokes/source.glade:1054
msgid "On the _network:"
msgstr "Hálozato_n"

#: pyanaconda/ui/gui/spokes/source.glade:1129
msgid "_Proxy setup..."
msgstr "_Proxy beállítása..."

#: pyanaconda/ui/gui/spokes/source.glade:1147
msgid "This URL refers to a _mirror list."
msgstr "Ez az URL hivatkozik a tükrök listájára."

#: pyanaconda/ui/gui/spokes/source.glade:1182
msgid "NFS mount options:"
msgstr "NFS csatolási opciók:"

#: pyanaconda/ui/gui/spokes/source.glade:1195
#: pyanaconda/ui/gui/spokes/source.glade:1196
msgid "This field is optional."
msgstr "Ez a mező opcionális."

#: pyanaconda/ui/gui/spokes/welcome.glade:21
msgid "_Get me out of here!"
msgstr "Tünés innen!"

#: pyanaconda/ui/gui/spokes/welcome.glade:35
msgid "_I accept my fate."
msgstr "Elfogadom a végzetemet."

#: pyanaconda/ui/gui/spokes/welcome.glade:66
msgid "This is unstable, pre-release software."
msgstr "Ez egy instabil, stabil kiadás előtti szoftver."

#: pyanaconda/ui/gui/spokes/welcome.glade:99
msgid ""
"You wake up inside an OS installer in Timbuktu, and it's six months in the "
"future.  But, there are bugs.  Bugs everywhere.  Bugs you must live with.  "
"This OS of the future isn't a stable OS you can rely on.  It's for testing "
"purposes only."
msgstr ""
"Felébred egy OS telepítőjében valahol Timbuktuban, és 6 hónappal később a "
"jövőben. De vannak hibák. Hibák mindenfele. Hibák amikkel együtt kell élnie. "
"Ez a jövő OS amire számíthat. De csak tesztelési céllal. "

#: pyanaconda/ui/gui/spokes/welcome.glade:251
msgid "WELCOME TO %s %s."
msgstr "ÜDVÖZLI A %s %s."

#: pyanaconda/ui/gui/spokes/welcome.glade:269
msgid "What language would you like to use during the installation process?"
msgstr "Melyik nyelvet szeretné használni a telepítés alatt?"

#: pyanaconda/ui/gui/spokes/welcome.glade:319
msgid "nativeName"
msgstr "nativeName"

#: pyanaconda/ui/gui/spokes/welcome.glade:335
msgid "englishName"
msgstr "englishName"

#: pyanaconda/ui/gui/spokes/welcome.glade:389
msgid "Set _keyboard to default layout for selected language."
msgstr ""
"Állítsa be a billentyűzetet az alapértelmezett _kiosztásra a kiválasztott "
"nyelvnél."

#: pyanaconda/ui/gui/spokes/custom.glade:8
#: pyanaconda/ui/gui/spokes/custom.glade:1741
msgid "Help"
msgstr "Súgó"

#: pyanaconda/ui/gui/spokes/custom.glade:106
msgid "_Add mount point"
msgstr "Cs_atolási pont hozzáadása"

#: pyanaconda/ui/gui/spokes/custom.glade:139
msgid "<b>Desired Capacity:</b>"
msgstr "<b>Kívánt kapacitás<b>"

#: pyanaconda/ui/gui/spokes/custom.glade:154
#: pyanaconda/ui/gui/spokes/custom.glade:558
msgid "<b>Mount Point:</b>"
msgstr "<b>Csatolási pont </b>"

#: pyanaconda/ui/gui/spokes/custom.glade:170
msgid "ADD A NEW MOUNT POINT"
msgstr "ÚJ CSATOLÁSI PONT HOZZÁADÁSA"

#: pyanaconda/ui/gui/spokes/custom.glade:188
msgid ""
"More customization options are available\n"
"after creating the mount point below."
msgstr ""
"További finomhangolási opciók elérhetőek\n"
"miután új csatolási pontot adott meg alább."

#: pyanaconda/ui/gui/spokes/custom.glade:206
msgid "eg: \"/\", \"/home\", \"swap\" (minus the quotation marks)"
msgstr "pl: \"/\", \"/home\", \"swap\" (idézőjelek nélkül)"

#: pyanaconda/ui/gui/spokes/custom.glade:239
msgid ""
"That mount point is already in\n"
"use.  Try something else?"
msgstr ""
"Ez a csatolási pont\n"
"már használatban. Megpróbál egy másikat?"

#: pyanaconda/ui/gui/spokes/custom.glade:265
msgid "eg: \"20 GB\", \"500mb\" (minus the quotation marks)"
msgstr "pl: \"20 GB\", \"500mb\" (idézőjelek nélkül)"

#: pyanaconda/ui/gui/spokes/custom.glade:308
msgid "Are you sure you want to delete all of the data on %s?"
msgstr "Biztos benne hogy törli az összes adatot innen: %s?"

#: pyanaconda/ui/gui/spokes/custom.glade:322
msgid "Delete all other filesystems in the %s root as well."
msgstr ""
"Töröljön minden más fájlrendszert is innen: %s , beleértve a root részét is."

#: pyanaconda/ui/gui/spokes/custom.glade:357
msgid "_Delete It"
msgstr "Törlés"

#: pyanaconda/ui/gui/spokes/custom.glade:390
msgid "_Back to destination selection"
msgstr "Vissza a cél kiválasztásához"

#: pyanaconda/ui/gui/spokes/custom.glade:476
msgid ""
"When you create mount points for your %s %s install,\n"
"you'll be able to view their details here."
msgstr ""
"Amikor csatolási pontot készít a %s %s telepítéshez,\n"
"itt megtekintheti a részleteket."

#: pyanaconda/ui/gui/spokes/custom.glade:499
#: pyanaconda/ui/gui/spokes/custom.glade:1362
#: pyanaconda/ui/gui/spokes/custom.glade:1504
#: pyanaconda/ui/gui/spokes/custom.glade:1591
msgid "Selected Device"
msgstr "Kiválasztott eszköz"

#: pyanaconda/ui/gui/spokes/custom.glade:517
#: pyanaconda/ui/gui/spokes/custom.glade:1380
#: pyanaconda/ui/gui/spokes/custom.glade:1522
#: pyanaconda/ui/gui/spokes/custom.glade:1609
msgid "Device description"
msgstr "Eszközinformációk"

#: pyanaconda/ui/gui/spokes/custom.glade:588
msgid "<b>Label:</b>"
msgstr "<b>Címke:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:604
msgid "<b>Desired Capacity (MB):</b>"
msgstr "<b>Kívánt kapacitás (MB):</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:651
#: pyanaconda/ui/gui/spokes/custom.glade:2036
msgid "Name:"
msgstr "Név:"

#: pyanaconda/ui/gui/spokes/custom.glade:712
msgid "<b>Device Type:</b>"
msgstr "<b>Eszköztípus:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:727
msgid "<b>File System:</b>"
msgstr "<b>Fájlrendszer:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:773
msgid "_Encrypt"
msgstr "Titkosítás"

#: pyanaconda/ui/gui/spokes/custom.glade:806
#: pyanaconda/ui/gui/spokes/custom.glade:903
#: pyanaconda/ui/gui/spokes/custom.glade:1144
msgid "Redundancy (mirror)"
msgstr "Redundancia (tükör)"

#: pyanaconda/ui/gui/spokes/custom.glade:825
#: pyanaconda/ui/gui/spokes/custom.glade:868
#: pyanaconda/ui/gui/spokes/custom.glade:922
#: pyanaconda/ui/gui/spokes/custom.glade:965
#: pyanaconda/ui/gui/spokes/custom.glade:1008
#: pyanaconda/ui/gui/spokes/custom.glade:1052
#: pyanaconda/ui/gui/spokes/custom.glade:1084
#: pyanaconda/ui/gui/spokes/custom.glade:1163
#: pyanaconda/ui/gui/spokes/custom.glade:1206
msgid "(-0Gb)"
msgstr "(-0Gb)"

#: pyanaconda/ui/gui/spokes/custom.glade:850
#: pyanaconda/ui/gui/spokes/custom.glade:947
#: pyanaconda/ui/gui/spokes/custom.glade:1188
msgid "Optimized performance (stripe)"
msgstr "Optimalizált teljesítmény (csík)"

#: pyanaconda/ui/gui/spokes/custom.glade:990
msgid "Error detection (parity)"
msgstr "Hiba érzékelés (paritás)"

#: pyanaconda/ui/gui/spokes/custom.glade:1034
msgid "Distributed"
msgstr "Elosztott"

#: pyanaconda/ui/gui/spokes/custom.glade:1065
msgid "Redundant"
msgstr "Redundáns"

#: pyanaconda/ui/gui/spokes/custom.glade:1243
msgid "Reformat"
msgstr "Formázza újra"

#: pyanaconda/ui/gui/spokes/custom.glade:1262
msgid "Volume Group:"
msgstr "Kötetcsoport:"

#: pyanaconda/ui/gui/spokes/custom.glade:1291
msgid "Modify ..."
msgstr "Módosítás..."

#: pyanaconda/ui/gui/spokes/custom.glade:1310
msgid "_Customize..."
msgstr "Testreszabás..."

#: pyanaconda/ui/gui/spokes/custom.glade:1323
msgid "_Apply Changes"
msgstr "Változások _alkalmazása"

#: pyanaconda/ui/gui/spokes/custom.glade:1414
msgid ""
"This device is encrypted and cannot be read without a valid passphrase. You "
"may unlock it below."
msgstr ""
"Ez az eszköz titkosított és nem olvasható addig, míg meg nem ad egy érvényes "
"jelszót. Most megpróbálhatja feloldani alább. "

#: pyanaconda/ui/gui/spokes/custom.glade:1435
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:97
msgid "Passphrase:"
msgstr "Jelszó:"

#: pyanaconda/ui/gui/spokes/custom.glade:1461
msgid "_Unlock"
msgstr "Feloldás"

#: pyanaconda/ui/gui/spokes/custom.glade:1556
msgid ""
"This device cannot be edited directly. You can remove it or select a "
"different device."
msgstr ""
"Az eszköz közvetlenül nem szerkeszthető. Eltávolíthatja, vagy választhat egy "
"másik eszközt."

#: pyanaconda/ui/gui/spokes/custom.glade:1644
msgid ""
"This %s device is missing %d of %d %s. You can remove it or select a "
"different device."
msgstr ""
"Ez az %s eszköz  hiányol a %d / %d %s részt. Eltávolíthatja, vagy választhat "
"egy másik eszközt."

#: pyanaconda/ui/gui/spokes/custom.glade:1690
msgid "Add a new mountpoint."
msgstr "Új csatolási pont hozzáadása"

#: pyanaconda/ui/gui/spokes/custom.glade:1691
msgid "addButton"
msgstr "Hozzáadás"

#: pyanaconda/ui/gui/spokes/custom.glade:1708
msgid "Remove the selected mountpoint(s.)"
msgstr "Távolítsa el a csatolási pontot (pontokat)"

#: pyanaconda/ui/gui/spokes/custom.glade:1709
msgid "removeButton"
msgstr "Eltávolítás"

#: pyanaconda/ui/gui/spokes/custom.glade:1726
msgid "Configure selected mountpoint."
msgstr "Kiválasztott csatolási pontok beállítása"

#: pyanaconda/ui/gui/spokes/custom.glade:1727
msgid "configureButton"
msgstr "Beállítás"

#: pyanaconda/ui/gui/spokes/custom.glade:1742
msgid "Click for help"
msgstr "Kattintson a súgóért"

#: pyanaconda/ui/gui/spokes/custom.glade:1790
msgid "<span size=\"small\" foreground=\"white\">AVAILABLE SPACE</span>"
msgstr "<span size=\"small\" foreground=\"white\">SZABAD TERÜLET</span>"

#: pyanaconda/ui/gui/spokes/custom.glade:1842
msgid "<span size=\"small\" foreground=\"white\">TOTAL SPACE</span>"
msgstr "<span size=\"small\" foreground=\"white\">TELJES TERÜLET</span>"

#: pyanaconda/ui/gui/spokes/custom.glade:1881
msgid "_Finish Partitioning"
msgstr "Partícionálás be_fejezése"

#: pyanaconda/ui/gui/spokes/custom.glade:1971
msgid "_Save"
msgstr "Menté_s"

#: pyanaconda/ui/gui/spokes/custom.glade:2003
msgid "CONFIGURE VOLUME GROUP"
msgstr "KÖTETCSOPORTOK BEÁLLÍTÁSA"

#: pyanaconda/ui/gui/spokes/custom.glade:2018
msgid ""
"Please create a name for your volume group and select at least one disk "
"below."
msgstr ""
"Kérem adjon nevet a kötetcsoportjának és válasszon legalább egy lemezt alább."

#: pyanaconda/ui/gui/spokes/custom.glade:2101
#: pyanaconda/ui/gui/spokes/custom.glade:2302
#: pyanaconda/ui/gui/spokes/lib/cart.glade:138
msgid "Capacity"
msgstr "Kapacitás"

#: pyanaconda/ui/gui/spokes/custom.glade:2114
#: pyanaconda/ui/gui/spokes/custom.glade:2315
#: pyanaconda/ui/gui/spokes/lib/cart.glade:151
msgid "Free"
msgstr "Szabad"

#: pyanaconda/ui/gui/spokes/custom.glade:2127
#: pyanaconda/ui/gui/spokes/custom.glade:2328
msgid "ID"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/custom.glade:2209
msgid "_Select"
msgstr "Kivála_sztás"

#: pyanaconda/ui/gui/spokes/custom.glade:2241
msgid "CONFIGURE MOUNT POINT"
msgstr "CSATOLÁSI PONT BEÁLLÍTÁSA"

#: pyanaconda/ui/gui/spokes/custom.glade:2256
msgid "Select one or more disks this device may reside on."
msgstr ""
"Válasszon ki egy vagy több lemezt az eszközben amire telepíteni szeretne."

#: pyanaconda/ui/gui/spokes/lib/cart.glade:25
#: pyanaconda/ui/gui/spokes/lib/cart.glade:79
msgid "SELECTED DISKS"
msgstr "KIVÁLASZTOTT LEMEZEK"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:43
msgid "_Close"
msgstr "Bezárás"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:111
msgid "Boot"
msgstr "Rendszerindítás"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:125
msgid "Description"
msgstr "Leírás"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:163
msgid "Id"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:207
msgid "_Remove"
msgstr "Eltávolítás"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:235
msgid "Disk summary goes here"
msgstr "Összesített információk a lemezekről"

#: pyanaconda/ui/gui/spokes/lib/detailederror.glade:24
msgid "An unknown error occurred during installation.  Details are below."
msgstr "Ismeretlen hiba történt a telepítés alatt. Részletek alább láthatóak."

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:20
msgid "DISK ENCRYPTION PASSPHRASE"
msgstr "LEMEZ TITKOSÍTÁSI JELSZÓ"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:52
msgid "Save Passphrase"
msgstr "Jelszó mentése"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:77
msgid ""
"You have chosen to encrypt some of your data. You will need to create a "
"passphrase that you will use to access your data when you start your "
"computer."
msgstr ""
"Úgy döntött, hogy titkosítja néhány adatát. Készítenie kell egy jelszót, "
"amit az adatainak elérésére használ majd amikor elindítja a számítógépét."

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:212
msgid "keymap warning label"
msgstr "Billentyűzet figyelmeztetési cimke"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:58
msgid "_Reclaim space"
msgstr "Lemezte_rület visszanyerése"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:92
msgid "RECLAIM DISK SPACE"
msgstr "LEMEZTERÜLET VISSZANYERÉSE"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:109
msgid "Description goes here."
msgstr "Leírás kerül ide."

#: pyanaconda/ui/gui/spokes/lib/resize.glade:151
msgid "Filesystem"
msgstr "Fájlrendszer"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:162
msgid "Reclaimable Space"
msgstr "Visszanyerhető terület"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:184
msgid "Action"
msgstr "Művelet"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:249
msgid "<b>%s disks; %s reclaimable space</b> (in filesystems)"
msgstr "<b>%s disks; %s visszanyerhető tárhely</b> (fájlrendszerekben)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:264
msgid "Total selected space to reclaim:  <b>%s</b>"
msgstr "Teljes visszanyerni kívánt tárhely:  <b>%s</b>"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:279
msgid "Installation requires a total of <b>%s</b> for system data."
msgstr "A telepítés összesen <b>%s</b> igényel a rendszer adatok részére."

#: pyanaconda/ui/gui/main.glade:80
msgid ""
"Are you sure you wish to quit the\n"
"installation process?"
msgstr ""
"Biztos benne, hogy kilép a\n"
"telepítési eljárásból?"

#: pyanaconda/ui/gui/hubs/summary.glade:11
msgid "INSTALLATION SUMMARY"
msgstr "TELEPÍTÉSI ÖSSZEGZÉS"

#: pyanaconda/ui/gui/hubs/summary.glade:95
msgid "_Begin Installation"
msgstr "Telepítés megkezdése"

#: pyanaconda/ui/gui/hubs/progress.glade:9
msgid "CONFIGURATION"
msgstr "KONFIGURÁCIÓ"

#: pyanaconda/ui/gui/hubs/progress.glade:128
msgid ""
"%s is now successfully installed on your system, but some configuration "
"still needs to be done. \n"
"Finish it and then click the Finish configuration button please."
msgstr ""
"%s sikeresen települt a rendszerében, de néhány beállítást és finomhangolást "
"még el kell végeznie.\n"
"Kérem fejezze be és kattintson a Konfiguráció befejezésére."

#: pyanaconda/ui/gui/hubs/progress.glade:140
msgid "_Finish configuration"
msgstr "Konfiguráció be_fejezése"

#: pyanaconda/ui/gui/hubs/progress.glade:181
msgid ""
"%s is now successfully installed on your system and ready\n"
"for you to use!  Go ahead and reboot to start using it!"
msgstr ""
"%s most sikeresen telepítésre került a rendszerére és kész\n"
"arra, hogy használatba vegye. Gyerünk, indítson újra, és élvezze!"

#: pyanaconda/ui/gui/hubs/progress.glade:193
msgid "_Reboot"
msgstr "Újraindítás"

#: widgets/src/BaseWindow.c:85
msgid "DISTRIBUTION INSTALLATION"
msgstr "DISZTRIBÚCIÓ TELEPÍTÉS"

#: widgets/src/BaseWindow.c:86
msgid "SPOKE NAME"
msgstr "MONDOTT NÉV"

#: widgets/src/BaseWindow.c:87
msgid "PRE-RELEASE / TESTING"
msgstr "KIADÁS ELŐTTI  / TESZT VÁLTOZAT"

#: widgets/src/DiskOverview.c:50
msgid "New Device"
msgstr "Új eszköz"

#: widgets/src/DiskOverview.c:52
msgid "0 MB"
msgstr "0 MB"

#: widgets/src/MountpointSelector.c:48
msgid "Root"
msgstr "Root"

#: widgets/src/MountpointSelector.c:49
msgid "0 GB"
msgstr "0 GB"

#: widgets/src/SpokeSelector.c:55
msgid "New Selector"
msgstr "Új választó"

#: data/liveinst/gnome/fedora-welcome:64
msgid "Welcome to Fedora"
msgstr "Üdvözli a Fedora"

#: data/liveinst/gnome/fedora-welcome:93
msgid "Try Fedora"
msgstr "Próbálja ki a Fedora rendszerét"

#: data/liveinst/gnome/fedora-welcome:111
msgid ""
"You are currently running Fedora from live media.\n"
"You can install Fedora now, or choose \"Install to Hard Drive\" in the "
"Activities Overview at any later time."
msgstr ""
"Jelenleg a Fedora rendszere live médiáról fut.\n"
"Telepítheti most, vagy válassza a \"Telepítés a merevlemezre\" ikont a "
"Tevékenységek menüből bármikor a későbbiekben."

#: data/liveinst/gnome/fedora-welcome:129
msgid ""
"You can choose \"Install to Hard Drive\"\n"
"in the Activities Overview at any later time."
msgstr ""
"Választhatja a \"Telepítés a merevlemezre\"\n"
"ikont a Tevékenységek menüből bármikor a későbbiekben."

#: data/liveinst/gnome/fedora-welcome:132
msgid "Close"
msgstr "Bezár"

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install to Hard Drive"
msgstr "Telepítés merevlemezre"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install"
msgstr "Telepítés"

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install the live CD to your hard disk"
msgstr "Live CD telepítése a merevlemezre"

#: liveinst:5
msgid "Starting Install to Hard Drive"
msgstr "Telepítés megkezdése a merevlemezre"
