# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Red Hat, Inc.
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# dcantrel <dcantrell@redhat.com>, 2011.
# Dimitris Glezos <glezos@indifex.com>, 2011.
# Hajime Taira <htaira@redhat.com>, 2010-2012.
# Hirofumi Saito <hi_saito@yk.rim.or.jp>, 2004-2006.
# Hyu_gabaru Ryu_ichi <hyu_gabaru@yahoo.co.jp>, 2007,2009.
# James Hashida <khashida@redhat.com>, 2002-2003.
# Kiyoto Hashida <khashida@redhat.com>, 2007-2010,2012.
# Kiyoto James Hashida <khashida@redhat.com>, 2002-2003,2006-2010.
# Makoto Mizukami <mmk9060@aol.com>, 2008.
# Naoki Shigematsu <sigematu@linuxml.net>, 2004.
#   <noriko@fedoraproject.org>, 2012.
# Noriko Mizumoto <noriko@fedoraproject.org>, 2010.
# Noriko Mizumoto <noriko@redhat.com>, 2003-2004,2006,2008-2009.
# SATO Satoru <ssato@redhat.com>, 2001.
# Tadashi Jokagi <fedora@elf.no-ip.org>, 2004-2005.
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2011-2012.
#   <www.carrotsoft@gmail.com>, 2012.
# Yoshinari Takaoka <mumumu@mx.edit.ne.jp>, 2004.
msgid ""
msgstr ""
"Project-Id-Version: Anaconda\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2015-10-22 15:55-0400\n"
"PO-Revision-Date: 2013-01-04 23:55+0000\n"
"Last-Translator: Brian Lane <bcl@redhat.com>\n"
"Language-Team: Japanese <trans-ja@lists.fedoraproject.org>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: pyanaconda/bootloader.py:226
#, fuzzy
msgid "/boot file system"
msgstr "/boot ファイルシステム"

#: pyanaconda/bootloader.py:383
#, fuzzy, python-format
msgid ""
"RAID sets that contain '%(desc)s' must have one of the following raid "
"levels: %(raid_level)s."
msgstr "'%s' を含む RAID セットは、次の RAID レベルのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:391
#, fuzzy, python-format
msgid ""
"RAID sets that contain '%(desc)s' must have one of the following metadata "
"versions: %(metadata_versions)s."
msgstr ""
"'%s' を含む RAID セットは、次のメタデータのバージョンのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:399
#, fuzzy, python-format
msgid ""
"RAID sets that contain '%(desc)s' must have one of the following device "
"types: %(types)s."
msgstr "'%s' を含む RAID セットは、次のデバイスタイプのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:415
#, fuzzy, python-format
msgid "%(name)s must have one of the following disklabel types: %(types)s."
msgstr "%s は次のディスクラベルのタイプのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:427
#, fuzzy, python-format
msgid "%(desc)s cannot be of type %(type)s."
msgstr "%s は %s タイプにすることはできません。"

#: pyanaconda/bootloader.py:433
#, fuzzy, python-format
msgid "%(desc)s must be mounted on one of %(mountpoints)s."
msgstr "%s を %s の１つにマウントする必要があります。"

#: pyanaconda/bootloader.py:445
#, fuzzy, python-format
msgid "%(desc)s must be between %(min)d and %(max)d MB in size"
msgstr "%s のサイズは %d MB から %d MB の間でなければなりません。"

#: pyanaconda/bootloader.py:451
#, fuzzy, python-format
msgid "%(desc)s must not be smaller than %(min)dMB."
msgstr "%s のサイズは %d MB 以下でなければなりません。"

#: pyanaconda/bootloader.py:460
#, fuzzy, python-format
msgid "%(desc)s must not be larger than %(max)dMB."
msgstr "%s のサイズは %d MB 以上でなければなりません。"

#: pyanaconda/bootloader.py:478
#, fuzzy, python-format
msgid "%(desc)s must be within the first %(max_end)s of the disk."
msgstr "%s はディスクの先頭から %dMB 以内の位置に配置しなければなりません。"

#: pyanaconda/bootloader.py:488
#, python-format
msgid "%s must be on a primary partition."
msgstr "%s はプライマリパーティション上になければなりません。"

#: pyanaconda/bootloader.py:624 pyanaconda/bootloader.py:724
#, python-format
msgid "%s cannot be on an encrypted block device."
msgstr "%s は暗号化ブロックデバイス上に置くことができません。"

#: pyanaconda/bootloader.py:679
#, fuzzy, python-format
msgid "%s cannot be on an iSCSI disk"
msgstr "%s は暗号化ブロックデバイス上に置くことができません。"

#: pyanaconda/bootloader.py:683
#, fuzzy, python-format
msgid "%(desc)s cannot be of type %(type)s"
msgstr "%s は %s タイプにすることはできません。"

#: pyanaconda/bootloader.py:1365
#, python-format
msgid ""
"boot loader stage2 device %(stage2dev)s is on a multi-disk array, but boot "
"loader stage1 device %(stage1dev)s is not. A drive failure in %(stage2dev)s "
"could render the system unbootable."
msgstr ""

#: pyanaconda/bootloader.py:1371
#, python-format
msgid ""
"boot loader stage2 device %(stage2dev)s is on a multi-disk array, but boot "
"loader stage1 device %(stage1dev)s is not part of this array. The stage1 "
"boot loader will only be installed to a single drive."
msgstr ""

#: pyanaconda/bootloader.py:1666
#, fuzzy, python-format
msgid ""
"%(deviceName)s may not have enough space for grub2 to embed core.img when "
"using the %(fsType)s file system on %(deviceType)s"
msgstr ""
"%3s 上の %2s ファイルシステムを使用している場合、 grub2によって組み込まれる "
"core.img 用の領域が %1s には不足している可能性があります。"

#: pyanaconda/constants.py:73
msgid "Start VNC"
msgstr "VNC を起動する"

#: pyanaconda/constants.py:74
msgid "Use text mode"
msgstr "テキストモードを使用する"

#: pyanaconda/constants.py:138
#, fuzzy
msgid "The password is empty."
msgstr "パスワードは設定されています"

#: pyanaconda/constants.py:139
#, fuzzy
msgid "The passwords do not match."
msgstr "パスワードが一致しません！"

#: pyanaconda/constants.py:140
msgid "The passwords you entered were different.  Please try again."
msgstr ""

#: pyanaconda/constants.py:141
#, fuzzy, python-format
msgid "The password you have provided is weak. %s"
msgstr "強度が弱いパスワードを入力しています: %s"

#: pyanaconda/constants.py:142
#, fuzzy, python-format
msgid "The password you have provided is weak: %s."
msgstr "強度が弱いパスワードを入力しています: %s"

#: pyanaconda/constants.py:143
#, fuzzy
msgid "You have provided a weak password. Press Done again to use anyway."
msgstr "脆弱なパスワードです: %s　それでも使用する場合は完了を押します。"

#: pyanaconda/constants.py:144
#, fuzzy, python-format
msgid "You have provided a weak password: %s. Press Done again to use anyway."
msgstr "脆弱なパスワードです: %s　それでも使用する場合は完了を押します。"

#: pyanaconda/constants.py:145
msgid ""
"The password you have provided contains non-ASCII characters. You may not be "
"able to switch between keyboard layouts to login. Press Done to continue."
msgstr ""

#: pyanaconda/constants.py:146
msgid "You will have to press Done twice to confirm it."
msgstr ""

#: pyanaconda/constants.py:148
msgid "Empty"
msgstr ""

#: pyanaconda/constants.py:148 pyanaconda/ui/gui/spokes/lib/passphrase.py:148
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:180
msgid "Weak"
msgstr "脆弱"

#: pyanaconda/constants.py:148 pyanaconda/ui/gui/spokes/lib/passphrase.py:151
msgid "Fair"
msgstr "普通"

#: pyanaconda/constants.py:148 pyanaconda/ui/gui/spokes/lib/passphrase.py:154
msgid "Good"
msgstr "良好"

#: pyanaconda/constants.py:148 pyanaconda/ui/gui/spokes/lib/passphrase.py:157
msgid "Strong"
msgstr "強力"

#: pyanaconda/constants.py:189
msgid "Probing storage..."
msgstr "ストレージを捜索中..."

#: pyanaconda/constants.py:190
msgid "Downloading package metadata..."
msgstr "パッケージのメタデータをダウンロード中..."

#: pyanaconda/constants.py:191
msgid "Downloading group metadata..."
msgstr "グループメタデータをダウンロード中"

#: pyanaconda/errors.py:129
#, fuzzy, python-format
msgid ""
"The following errors occurred with your partitioning:\n"
"\n"
"%(errortxt)s\n"
"\n"
"The installation will now terminate."
msgstr ""
"インストールリポジトリーを設定中に次のエラーが発生しました。\n"
"\n"
"%(e)s\n"
"\n"
"インストール作業を継続できません。"

#: pyanaconda/errors.py:135
#, python-format
msgid "An error occurred while resizing the device %s."
msgstr ""

#: pyanaconda/errors.py:144
#, python-format
msgid ""
"There is a problem with your existing storage configuration: <b>"
"%(errortxt)s</b>\n"
"\n"
"You must resolve this matter before the installation can proceed. There is a "
"shell available for use which you can access by pressing ctrl-alt-f1 and "
"then ctrl-b 2.\n"
"\n"
"Once you have resolved the issue you can retry the storage scan. If you do "
"not fix it you will have to exit the installer."
msgstr ""

#: pyanaconda/errors.py:153
#, fuzzy
msgctxt "GUI|Storage Detailed Error Dialog"
msgid "_Exit Installer"
msgstr "インストーラーを終了する(_E)"

#: pyanaconda/errors.py:154
#, fuzzy
msgctxt "GUI|Storage Detailed Error Dialog"
msgid "_Retry"
msgstr "再試行(_R)"

#: pyanaconda/errors.py:161
msgid ""
"An error has occurred - no valid devices were found on which to create new "
"file systems.  Please check your hardware for the cause of this problem."
msgstr ""

#: pyanaconda/errors.py:170
msgid ""
"There is an entry in your /etc/fstab file that contains an invalid or "
"incorrect file system type:\n"
"\n"
msgstr ""

#: pyanaconda/errors.py:176
#, python-format
msgid ""
"The ISO image %s has a size which is not a multiple of 2048 bytes.  This may "
"mean it was corrupted on transfer to this computer.\n"
"\n"
"It is recommended that you exit and abort your installation, but you can "
"choose to continue if you think this is in error. Would you like to continue "
"using this image?"
msgstr ""

#: pyanaconda/errors.py:190
msgid ""
"The installer has tried to mount the installation image, but cannot find it "
"on the hard drive.\n"
"\n"
"Should I try again to locate the image?"
msgstr ""

#: pyanaconda/errors.py:200
#, python-format
msgid "An error occurred mounting the source device %s. Retry?"
msgstr ""

#: pyanaconda/errors.py:208
#, python-format
msgid ""
"An error occurred unmounting the disc.  Please make sure you're not "
"accessing %s from the shell on tty2 and then click OK to retry."
msgstr ""

#: pyanaconda/errors.py:216
#, python-format
msgid ""
"The group '%s' is required for this installation. This group does not exist. "
"This is a fatal error and installation will be aborted."
msgstr ""

#: pyanaconda/errors.py:222
#, python-format
msgid ""
"You have specified that the group '%s' should be installed.  This group does "
"not exist.  Would you like to ignore this group and continue with "
"installation?"
msgstr ""

#: pyanaconda/errors.py:227
#, python-format
msgid ""
"You have specified that the group '%s' should be excluded from "
"installation.  This group does not exist.  Would you like to ignore this "
"group and continue with installation?"
msgstr ""

#: pyanaconda/errors.py:239
#, python-format
msgid ""
"The package '%s' is required for this installation. This package does not "
"exist. This is a fatal error and installation will be aborted."
msgstr ""

#: pyanaconda/errors.py:246
#, python-format
msgid ""
"You have specified that the package '%s' should be installed.  This package "
"does not exist.  Would you like to ignore this package and continue with "
"installation?"
msgstr ""

#: pyanaconda/errors.py:257
#, python-format
msgid ""
"There was an error running the kickstart script at line %(lineno)s.  This is "
"a fatal error and installation will be aborted.  The details of this error "
"are:\n"
"\n"
"%(details)s"
msgstr ""

#: pyanaconda/errors.py:265
#, fuzzy
msgid ""
"The following error occurred while installing.  This is a fatal error and "
"installation will be aborted."
msgstr ""
"インストールリポジトリーを設定中に次のエラーが発生しました。\n"
"\n"
"%(e)s\n"
"\n"
"インストール作業を継続できません。"

#: pyanaconda/errors.py:273
#, fuzzy
msgid ""
"The following software marked for installation has errors.  This is likely "
"caused by an error with\n"
"your installation source."
msgstr ""
"インストール用にマークしてある以下のソフトウェアにエラーがあります。これはイ"
"ンストールソースが持つエラーが原因であるようです。これらのパッケージをインス"
"トールから除外するか、インストールソースを変えるか、またはインストーラーを終"
"了することができます。"

#: pyanaconda/errors.py:281
#, fuzzy
msgid ""
"The following error occurred while installing the boot loader. The system "
"will not be bootable. Would you like to ignore this and continue with "
"installation?"
msgstr ""
"インストールリポジトリーを設定中に次のエラーが発生しました。\n"
"\n"
"%(e)s\n"
"\n"
"インストール作業を継続できません。"

#: pyanaconda/errors.py:293
#, python-format
msgid "Unable to encrypt password: unsupported algorithm %s"
msgstr ""

#: pyanaconda/errors.py:300
#, fuzzy, python-format
msgid ""
"Installation was stopped due to an error installing the boot loader. The "
"exact error message is:\n"
"\n"
"%s\n"
"\n"
"The installer will now terminate."
msgstr ""
"インストール作業はハードウェアに問題があると思われる症状が発生したため停止さ"
"れました。正確なエラーメッセージは次のとおりです：\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/exception.py:82
#, python-format
msgid ""
"The installation was stopped due to what seems to be a problem with your "
"hardware. The exact error message is:\n"
"\n"
"%s.\n"
"\n"
" The installer will now terminate."
msgstr ""
"インストール作業はハードウェアに問題があると思われる症状が発生したため停止さ"
"れました。正確なエラーメッセージは次のとおりです：\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/exception.py:86
#, fuzzy
msgid "Hardware error occured"
msgstr "ハードウェアエラーが発生しました。"

#: pyanaconda/exception.py:143
#, fuzzy, python-format
msgid ""
"\n"
"The installation was stopped due to incomplete spokes detected while running "
"in non-interactive cmdline mode. Since there cannot be any questions in "
"cmdline mode, edit your kickstart file and retry installation.\n"
"The exact error message is: \n"
"\n"
"%s.\n"
"\n"
"The installer will now terminate."
msgstr ""
"インストール作業はハードウェアに問題があると思われる症状が発生したため停止さ"
"れました。正確なエラーメッセージは次のとおりです：\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/exception.py:151
#, fuzzy, python-format
msgid ""
"\n"
"Running in cmdline mode, no interactive debugging allowed.\n"
"The exact error message is: \n"
"\n"
"%s.\n"
"\n"
"The installer will now terminate."
msgstr ""
"インストール作業はハードウェアに問題があると思われる症状が発生したため停止さ"
"れました。正確なエラーメッセージは次のとおりです：\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/install.py:75
msgid "Configuring installed system"
msgstr "インストール済みのシステムを構成"

#: pyanaconda/install.py:88
msgid "Writing network configuration"
msgstr "ネットワーク構成を書き込み中"

#: pyanaconda/install.py:92
msgid "Creating users"
msgstr "ユーザーを作成中"

#: pyanaconda/install.py:99
#, fuzzy
msgid "Configuring addons"
msgstr "インストール済みのシステムを構成"

#: pyanaconda/install.py:102
msgid "Generating initramfs"
msgstr ""

#: pyanaconda/install.py:113
#, python-format
msgid "Joining realm: %s"
msgstr ""

#: pyanaconda/install.py:116
#, fuzzy
msgid "Running post-installation scripts"
msgstr "インストール前スクリプトを実行中"

#: pyanaconda/install.py:168
#, python-format
msgid "Waiting for %s threads to finish"
msgstr ""

#: pyanaconda/install.py:175
#, fuzzy
msgid "Setting up the installation environment"
msgstr "インストールソースをセットアップ中..."

#: pyanaconda/install.py:199 pyanaconda/kickstart.py:2145
msgid "Running pre-installation scripts"
msgstr "インストール前スクリプトを実行中"

#: pyanaconda/install.py:207
msgid "Discovering realm to join"
msgstr ""

#: pyanaconda/install.py:239
#, fuzzy
msgid "Installing boot loader"
msgstr "ブートローダーをインストール中"

#: pyanaconda/install.py:242 pyanaconda/packaging/livepayload.py:183
#: pyanaconda/packaging/dnfpayload.py:721
#, fuzzy
msgid "Performing post-installation setup tasks"
msgstr "インストール後設定タスクを実行中"

#: pyanaconda/iutil.py:858
msgid "No host url"
msgstr ""

#: pyanaconda/iutil.py:879
msgid "malformed URL, cannot parse it."
msgstr ""

#: pyanaconda/iutil.py:895
msgid "URL has no host component"
msgstr ""

#: pyanaconda/kickstart.py:161
#, python-format
msgid "Escrow certificate %s requires the network."
msgstr "エスクロー証明書 %s にはネットワークが必要です。"

#: pyanaconda/kickstart.py:169
#, fuzzy, python-format
msgid ""
"SSL error while downloading the escrow certificate:\n"
"\n"
"%s"
msgstr ""
"escrow 証明書のダウンロード中に次のエラーに 遭遇しました:\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:172
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"escrow 証明書のダウンロード中に次のエラーに 遭遇しました:\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:283
#, fuzzy, python-format
msgid "%s is missing. Cannot setup authentication."
msgstr "%s が足りません。 ファイアーウォールの設定ができません。"

#: pyanaconda/kickstart.py:308
#, python-format
msgid "autopart fstype of %s is invalid."
msgstr ""

#: pyanaconda/kickstart.py:325
#, python-format
msgid "Settings default fstype to %s failed."
msgstr ""

#: pyanaconda/kickstart.py:356
msgid "GRUB2 does not support installation to a partition."
msgstr ""

#: pyanaconda/kickstart.py:416
#, python-format
msgid "More than one match found for given boot drive \"%s\"."
msgstr ""

#: pyanaconda/kickstart.py:419
#, python-format
msgid "Requested boot drive \"%s\" doesn't exist or cannot be used."
msgstr ""

#: pyanaconda/kickstart.py:461
#, python-format
msgid ""
"Btrfs partition \"%(device)s\" has a format of \"%(format)s\", but should "
"have a format of \"btrfs\"."
msgstr ""

#: pyanaconda/kickstart.py:466
#, python-format
msgid "Tried to use undefined partition \"%s\" in Btrfs volume specification."
msgstr ""

#: pyanaconda/kickstart.py:479
msgid ""
"Btrfs volume defined without any member devices.  Either specify member "
"devices or use --useexisting."
msgstr ""

#: pyanaconda/kickstart.py:488 pyanaconda/kickstart.py:863
#: pyanaconda/kickstart.py:1455
#, python-format
msgid "The mount point \"%s\" is not valid.  It must start with a /."
msgstr ""

#: pyanaconda/kickstart.py:503
#, python-format
msgid "Btrfs volume \"%s\" specified with --useexisting does not exist."
msgstr ""

#: pyanaconda/kickstart.py:590
#, python-format
msgid ""
"Disklabel \"%s\" given in clearpart command is not supported on this "
"platform."
msgstr ""

#: pyanaconda/kickstart.py:602
#, python-format
msgid "Disk \"%s\" given in clearpart command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:615
#, python-format
msgid "Device \"%s\" given in clearpart device list does not exist."
msgstr ""

#: pyanaconda/kickstart.py:642
#, python-format
msgid "NIC \"%s\" given in fcoe command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:693
#, python-format
msgid "%s is missing. Cannot setup firewall."
msgstr "%s が足りません。 ファイアーウォールの設定ができません。"

#: pyanaconda/kickstart.py:742 pyanaconda/kickstart.py:753
#, python-format
msgid "Disk \"%s\" given in ignoredisk command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:766
#, python-format
msgid ""
"Network interface \"%(nic)s\" required by iSCSI \"%(iscsiTarget)s\" target "
"is not up."
msgstr ""

#: pyanaconda/kickstart.py:776
msgid ""
"iscsi --iface must be specified (binding used) either for all targets or for "
"none"
msgstr ""

#: pyanaconda/kickstart.py:869
#, python-format
msgid ""
"No volume group exists with the name \"%s\".  Specify volume groups before "
"logical volumes."
msgstr ""

#: pyanaconda/kickstart.py:876
#, python-format
msgid ""
"No thin pool exists with the name \"%s\". Specify thin pools before thin "
"volumes."
msgstr ""

#: pyanaconda/kickstart.py:884
msgid "logvol --noformat must also use the --name= option."
msgstr ""

#: pyanaconda/kickstart.py:889 pyanaconda/kickstart.py:951
#, python-format
msgid "Logical volume \"%s\" given in logvol command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:900 pyanaconda/kickstart.py:909
#: pyanaconda/kickstart.py:961 pyanaconda/kickstart.py:1235
#: pyanaconda/kickstart.py:1244 pyanaconda/kickstart.py:1327
#, python-format
msgid "Target size \"%(size)s\" for device \"%(device)s\" is invalid."
msgstr ""

#: pyanaconda/kickstart.py:923
#, python-format
msgid ""
"Logical volume name \"%(logvol)s\" is already in use in volume group "
"\"%(volgroup)s\"."
msgstr ""

#: pyanaconda/kickstart.py:928
#, python-format
msgid ""
"Logical volume size \"%(logvolSize)s\" must be larger than the volume group "
"extent size of \"%(extentSize)s\"."
msgstr ""

#: pyanaconda/kickstart.py:940 pyanaconda/kickstart.py:1263
#: pyanaconda/kickstart.py:1508
#, fuzzy, python-format
msgid "The \"%s\" file system type is not supported."
msgstr "このファイルシステムはラベルをサポートしません。"

#: pyanaconda/kickstart.py:1101 pyanaconda/kickstart.py:1105
#, python-format
msgid "The %s kickstart command is not currently supported."
msgstr ""

#: pyanaconda/kickstart.py:1132
#, python-format
msgid "No disk found for specified BIOS disk \"%s\"."
msgstr ""

#: pyanaconda/kickstart.py:1167
#, python-format
msgid "RAID partition \"%s\" is defined multiple times."
msgstr ""

#: pyanaconda/kickstart.py:1178 pyanaconda/kickstart.py:1430
#, python-format
msgid "PV partition \"%s\" is defined multiple times."
msgstr ""

#: pyanaconda/kickstart.py:1189 pyanaconda/kickstart.py:1440
#, python-format
msgid "Btrfs partition \"%s\" is defined multiple times."
msgstr ""

#: pyanaconda/kickstart.py:1212
#, python-format
msgid "The size \"%s\" is invalid."
msgstr ""

#: pyanaconda/kickstart.py:1219
msgid "part --noformat must also use the --onpart option."
msgstr ""

#: pyanaconda/kickstart.py:1224 pyanaconda/kickstart.py:1318
#, python-format
msgid "Partition \"%s\" given in part command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:1278 pyanaconda/kickstart.py:1292
#, python-format
msgid "Disk \"%s\" given in part command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:1281
#, python-format
msgid "Cannot install to unpartitionable device \"%s\"."
msgstr ""

#: pyanaconda/kickstart.py:1288
#, python-format
msgid "Disk \"%s\" in part command is not partitioned."
msgstr ""

#: pyanaconda/kickstart.py:1301
#, python-format
msgid "The maximum size \"%s\" is invalid."
msgstr ""

#: pyanaconda/kickstart.py:1462
msgid "raid --noformat must also use the --device option."
msgstr ""

#: pyanaconda/kickstart.py:1467
#, python-format
msgid "RAID device  \"%s\" given in raid command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:1490
#, python-format
msgid ""
"RAID device \"%(device)s\" has a format of \"%(format)s\", but should have a "
"format of \"mdmember\"."
msgstr ""

#: pyanaconda/kickstart.py:1495
#, python-format
msgid "Tried to use undefined partition \"%s\" in RAID specification."
msgstr ""

#: pyanaconda/kickstart.py:1524
#, python-format
msgid "RAID volume \"%s\" specified with --useexisting does not exist."
msgstr ""

#: pyanaconda/kickstart.py:1533
#, fuzzy, python-format
msgid "The RAID volume name \"%s\" is already in use."
msgstr "指定された名前 %s はすでに存在します。"

#: pyanaconda/kickstart.py:1773
#, python-format
msgid ""
"Physical volume \"%(device)s\" has a format of \"%(format)s\", but should "
"have a format of \"lvmpv\"."
msgstr ""

#: pyanaconda/kickstart.py:1778
#, python-format
msgid "Tried to use undefined partition \"%s\" in Volume Group specification"
msgstr ""

#: pyanaconda/kickstart.py:1784
#, python-format
msgid ""
"Volume group \"%s\" defined without any physical volumes.  Either specify "
"physical volumes or use --useexisting."
msgstr ""

#: pyanaconda/kickstart.py:1794
#, python-format
msgid ""
"Volume group given physical extent size of \"%(extentSize)s\", but must be "
"one of:\n"
"%(validExtentSizes)s."
msgstr ""

#: pyanaconda/kickstart.py:1801
msgid ""
"volgroup --noformat and volgroup --useexisting must also use the --name= "
"option."
msgstr ""

#: pyanaconda/kickstart.py:1806
#, python-format
msgid "Volume group \"%s\" given in volgroup command does not exist."
msgstr ""

#: pyanaconda/kickstart.py:1809
#, fuzzy, python-format
msgid "The volume group name \"%s\" is already in use."
msgstr "ボリュームグループ名 %s はすでに使われています。変更は保存されません。"

#: pyanaconda/kickstart.py:1865
msgid ""
"The upgrade kickstart command is no longer supported. Upgrade functionality "
"is provided through fedup."
msgstr ""

#: pyanaconda/network.py:119
#, fuzzy
msgid "Host name cannot be None or an empty string."
msgstr "ホスト名なし、または空白の文字は設定できません。"

#: pyanaconda/network.py:122
#, fuzzy
msgid "Host name must be 255 or fewer characters in length."
msgstr "ホスト名は 255 文字かそれ以下の長さにする必要があります。"

#: pyanaconda/network.py:125
#, fuzzy
msgid ""
"Host names can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.', "
"parts between periods must contain something and cannot start or end with "
"'-'."
msgstr ""
" ホスト名には半角英数 'a-z'、'A-Z'、'0-9'、および記号 '-'、'.' を使用すること"
"ができます。ただし、ピリオドは文字列の途中に使用しなければいけません。また、"
"ホスト名の先頭と終わりには '-' は使用できません。"

#: pyanaconda/network.py:1375 pyanaconda/ui/gui/spokes/custom.py:564
#: pyanaconda/ui/gui/spokes/network.py:327
#: pyanaconda/ui/gui/spokes/lib/accordion.py:66
msgid "Unknown"
msgstr "不明"

#: pyanaconda/network.py:1379
msgid "Connecting..."
msgstr "接続中..."

#: pyanaconda/network.py:1381
msgid "Disconnecting..."
msgstr "切断中..."

#: pyanaconda/network.py:1401
#, fuzzy, python-format
msgid "Wired (%(interface_name)s) connected"
msgstr "有線 (%s) は接続されています"

#: pyanaconda/network.py:1404
#, fuzzy, python-format
msgid "Wireless connected to %(access_point)s"
msgstr "%s にワイヤレスで接続しています"

#: pyanaconda/network.py:1407
#, python-format
msgid "Bond %(interface_name)s (%(list_of_slaves)s) connected"
msgstr ""

#: pyanaconda/network.py:1411
#, python-format
msgid "Team%(interface_name)s (%(list_of_slaves)s) connected"
msgstr ""

#: pyanaconda/network.py:1415
#, fuzzy, python-format
msgid "Bridge%(interface_name)s (%(list_of_slaves)s) connected"
msgstr "有線 (%s) は接続されています"

#: pyanaconda/network.py:1421
#, python-format
msgid "VLAN %(interface_name)s (%(parent_device)s, ID %(vlanid)s) connected"
msgstr ""

#: pyanaconda/network.py:1438
#, python-format
msgid "Connected: %(list_of_interface_names)s"
msgstr ""

#: pyanaconda/network.py:1441
msgid "Not connected"
msgstr "接続していません"

#: pyanaconda/network.py:1444 pyanaconda/ui/gui/spokes/network.glade:2099
msgid "No network devices available"
msgstr "ネットワークデバイスは利用できません"

#: pyanaconda/product.py:53
#, python-format
msgid "%(productName)s %(productVersion)s INSTALLATION"
msgstr "%(productName)s %(productVersion)s インストール"

#: pyanaconda/product.py:57
#, fuzzy, python-format
msgid "New %(name)s %(version)s Installation"
msgstr "新しい %s %s のインストール"

#: pyanaconda/pwpolicy.py:114
#, python-format
msgid "policy name required for %s"
msgstr ""

#: pyanaconda/pwpolicy.py:123
#, python-format
msgid "A %(command)s with the name %(policyName)s has already been defined."
msgstr ""

#: pyanaconda/rescue.py:68
#, python-format
msgid "Run %s to unmount the system when you are finished."
msgstr ""
"メンテナンスが終わったら、システムをアンマウントするために %s を実行してくだ"
"さい。"

#: pyanaconda/rescue.py:71
#, fuzzy
msgid "When finished, please exit from the shell and your system will reboot."
msgstr "完了したらシェルを終了してください。システムが再起動します。"

#: pyanaconda/rescue.py:79
#, fuzzy
msgid "Unable to find /bin/bash to execute!  Not starting shell."
msgstr "実行するための /bin/sh が見付かりません。シェルを 開始していません。"

#: pyanaconda/rescue.py:121
msgid "Rescue"
msgstr "レスキュー"

#: pyanaconda/rescue.py:133
msgid "Continue"
msgstr "続行"

#: pyanaconda/rescue.py:133
#, fuzzy
msgid "Read-only mount"
msgstr "読み取り専用"

#: pyanaconda/rescue.py:133
#, fuzzy
msgid "Skip to shell"
msgstr "VNC を起動する"

#: pyanaconda/rescue.py:147
msgid "Please make a selection from the above:  "
msgstr ""

#: pyanaconda/rescue.py:152
#, fuzzy, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory : %s.  You can then make any changes required "
"to your system.  Choose '1' to proceed with this step.\n"
"You can choose to mount your file systems read-only instead of read-write by "
"choosing '2'.\n"
"If for some reason this process does not work choose '3' to skip directly to "
"a shell.\n"
"\n"
msgstr ""
"レスキュー環境はここで、ユーザーの Linux インストールを見つけて、それをディレ"
"クトリ %s にマウントする試みをします。その後に、必要な変更をシステムに加える"
"ことができます。このステップを進めたい場合は、「続ける」を選択します。また、"
"「読み込み専用」を選択すると、読み込み/書き込みの代わりに読み込み専用でファイ"
"ルシステムをマウントする選択ができます。\n"
"\n"
"なんらかの理由でこのプロセスが失敗した場合は、「スキップ」を選択すると、この"
"ステップは除外されて直接、コマンドシェルに進みます。\n"

#: pyanaconda/rescue.py:266
#, fuzzy
msgid "Root Selection"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/rescue.py:283
msgid "The following installations were discovered on your system.\n"
msgstr ""

#: pyanaconda/rescue.py:295
msgid ""
"Please make your selection from the above list.\n"
"Press 'c' to continue after you have made your selection.  "
msgstr ""

#: pyanaconda/rescue.py:325
#, fuzzy
msgid "Rescue Mount"
msgstr "レスキューモード"

#: pyanaconda/rescue.py:344
#, fuzzy, python-format
msgid ""
"Your system has been mounted under %(mountpoint)s.\n"
"\n"
"If you would like to make your system the root environment, run the "
"command:\n"
"\n"
"\tchroot %(mountpoint)s\n"
msgstr ""
"システムを %(rootPath)s 下にマウントしています。\n"
"\n"
"シェルを起動するには <enter>キーを押してください。そのシステムを root 環境と"
"して利用するには次のコマンドを実行します:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"

#: pyanaconda/rescue.py:383
#, fuzzy, python-format
msgid "Run %s to unmount the system when you are finished.\n"
msgstr ""
"メンテナンスが終わったら、システムをアンマウントするために %s を実行してくだ"
"さい。"

#: pyanaconda/rescue.py:385
#, fuzzy, python-format
msgid ""
"An error occurred trying to mount some or all of your system.  Some of it "
"may be mounted under %s\n"
"\n"
msgstr ""
"システムのいくつか、あるいはすべてをマウントしようと試みている間にエラーが発"
"生しました。いくつかのパーティションは %s の下にマウントされています。\n"
"\n"
"シェルを起動するには [Enter] を押してください。"

#: pyanaconda/rescue.py:392
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr "Linux パーティションがありません。再起動します。\n"

#: pyanaconda/rescue.py:399
#, fuzzy
msgid "The system will reboot automatically when you exit from the shell.\n"
msgstr "シェルを終了するとシステムは自動的に再起動します。"

#: pyanaconda/rescue.py:403
#, fuzzy, python-format
msgid "You don't have any Linux partitions. %s\n"
msgstr "Linux パーティションがありません。再起動します。\n"

#: pyanaconda/rescue.py:413
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "システムは %s ディレクトリー配下にマウントされます。"

#: pyanaconda/rescue.py:434
msgid "Please press <return> to get a shell. "
msgstr ""

#: pyanaconda/storage_utils.py:50 pyanaconda/storage_utils.py:82
#: pyanaconda/ui/gui/spokes/custom.glade:31
msgid "LVM"
msgstr "LVM"

#: pyanaconda/storage_utils.py:51 pyanaconda/storage_utils.py:83
#: pyanaconda/ui/gui/spokes/custom.glade:39
msgid "LVM Thin Provisioning"
msgstr ""

#: pyanaconda/storage_utils.py:52 pyanaconda/ui/gui/spokes/custom.glade:35
msgid "RAID"
msgstr "RAID"

#: pyanaconda/storage_utils.py:53 pyanaconda/storage_utils.py:80
#: pyanaconda/ui/gui/spokes/custom.glade:23
msgid "Standard Partition"
msgstr "標準パーティション"

#: pyanaconda/storage_utils.py:54 pyanaconda/storage_utils.py:81
#: pyanaconda/ui/gui/spokes/custom.glade:27
msgid "Btrfs"
msgstr ""

#: pyanaconda/storage_utils.py:55
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:719
#: pyanaconda/ui/gui/spokes/lib/resize.glade:152
msgid "Disk"
msgstr "ディスク"

#: pyanaconda/storage_utils.py:66
msgid ""
"The 'swap' area on your computer is used by the operating\n"
"system when running low on memory."
msgstr ""
"ご使用のコンピューターの 'swap' 領域は、メモリー不足の状態になると\n"
"オペレーティングシステムで使用されます。"

#: pyanaconda/storage_utils.py:68
msgid ""
"The 'boot' area on your computer is where files needed\n"
"to start the operating system are stored."
msgstr ""
"ご使用のコンピューターの 'boot' 領域は、オペレーティング\n"
"システムの開始に必要なファイルを収納しています。"

#: pyanaconda/storage_utils.py:70
msgid ""
"The 'root' area on your computer is where core system\n"
"files and applications are stored."
msgstr ""
"ご使用のコンピューターの 'root' 領域は、コアシステムファイルと\n"
"アプリKションを収納しています。"

#: pyanaconda/storage_utils.py:72
msgid ""
"The 'home' area on your computer is where all your personal\n"
"data is stored."
msgstr ""
"ご使用のコンピューターの 'home' 領域は、ユーザーの個人\n"
"データを収納しています。"

#: pyanaconda/storage_utils.py:74
msgid ""
"The BIOS boot partition is required to enable booting\n"
"from GPT-partitioned disks on BIOS hardware."
msgstr ""
"BIOS ハードウェア上で GPT パーティション設定したディスク からの起動を有効にす"
"るには、BIOS のブートパーティションが必要です。"

#: pyanaconda/storage_utils.py:76
#, fuzzy
msgid ""
"The PReP boot partition is required as part of the\n"
"boot loader configuration on some PPC platforms."
msgstr ""
"数種の PPC プラットフォーム上のブートローダー設定の一部 としてPReP ブートパー"
"ティションが必要です。"

#: pyanaconda/storage_utils.py:184
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"root パーティションが 250 MB 以下になっています。通常、 %s のインストールには"
"小さすぎます。"

#: pyanaconda/storage_utils.py:189
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""
"%s のインストールを継続するために必要な root パーティション (/) が定義されて"
"いません。"

#: pyanaconda/storage_utils.py:203
msgid ""
"This platform requires /boot on a dedicated partition or logical volume.  If "
"you do not want a /boot volume, you must place / on a dedicated non-LVM "
"partition."
msgstr ""
"お使いのプラットフォームでは専用のパーティションまたは論理ボリューム上に /"
"boot を配置する必要があります。あなたが /boot ボリュームを作りたくない場合"
"は、非 LVM 上の専用パーティションに / を配置しなければなりません。"

#: pyanaconda/storage_utils.py:213
#, fuzzy, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"%(mount)s パーティションの容量が %(size)s MB以下であり、通常の "
"%(productName)s のインストールでの 推奨容量には不足しています。"

#: pyanaconda/storage_utils.py:225
#, fuzzy, python-format
msgid ""
"Your %(mount)s partition is too small for %(format)s formatting (allowable "
"size is %(minSize)s to %(maxSize)s)"
msgstr ""
"このシステムの %(mount)s パーティションは %(format)s フォーマットには小さすぎ"
"ます。 (指定可能なサイズは %(minSize)d MB から %(maxSize)d MB となっています)"

#: pyanaconda/storage_utils.py:231
#, fuzzy, python-format
msgid ""
"Your %(mount)s partition is too large for %(format)s formatting (allowable "
"size is %(minSize)s to %(maxSize)s)"
msgstr ""
"このシステムの %(mount)s パーティションは %(format)s フォーマットには大きすぎ"
"ます。 (指定可能なサイズは %(minSize)d MB から %(maxSize)d MB となっています)"

#: pyanaconda/storage_utils.py:240
#, fuzzy
msgid "No valid boot loader target device found. See below for details."
msgstr "新規デバイスの追加に失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/storage_utils.py:252
msgid "You have not created a bootable partition."
msgstr "ブート可能なパーティションが作成されていません。"

#: pyanaconda/storage_utils.py:274
#, fuzzy
msgid ""
"Your BIOS-based system needs a special partition to boot from a GPT disk "
"label. To continue, please create a 1MiB 'biosboot' type partition."
msgstr ""
"ご使用の BIOS ベースのシステムは %s の新規ディスクラベル形式 (GPT) で起動する"
"には、特別なパーティションが必要です。継続するには、1MB の  'BIOS ブート' タ"
"イプのパーティションを作成してください。"

#: pyanaconda/storage_utils.py:285
#, fuzzy, python-format
msgid ""
"You have not specified a swap partition.  %(requiredMem)s of memory is "
"required to continue installation without a swap partition, but you only "
"have %(installedMem)s."
msgstr ""
"swap パーティションが未指定です。swap パーティションなしでのインストール作業"
"の継続には %(requiredMem)s のメモリーが必要となっています。しかし、お使いのシ"
"ステムには %(installedMem)s MB しか搭載されていません。"

#: pyanaconda/storage_utils.py:292
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"swap パーティションが未指定です。すべての場合において必ず必要というわけではあ"
"りませんが、ほとんどのインストールにおいて明らかに性能を向上させます。"

#: pyanaconda/storage_utils.py:299
msgid ""
"At least one of your swap devices does not have a UUID, which is common in "
"swap space created using older versions of mkswap. These devices will be "
"referred to by device path in /etc/fstab, which is not ideal since device "
"paths can change under a variety of circumstances. "
msgstr ""
"swap デバイスの少なくとも1つは UUID を持っていなければなりません。これは旧"
"バージョンの mkswap コマンドを使用して作成した swap 領域ではよくあります。こ"
"れらのデバイスは /etc/fstab のデバイスパスによって参照されます。デバイスパス"
"による参照はさまざまな状況により変更されてしまうため理想的な方法ではありませ"
"ん。"

#: pyanaconda/storage_utils.py:310
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""
"このマウントポイントは正しくありません。%s ディレクトリーは / ファイルシステ"
"ム上になければなりません。"

#: pyanaconda/storage_utils.py:315
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "マウントポイント %s は linux ファイルシステム上にある必要があります。"

#: pyanaconda/storage_utils.py:343
#, python-format
msgid ""
"Encryption requested for LUKS device %s but no encryption key specified for "
"this device."
msgstr ""

#: pyanaconda/vnc.py:75
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr "%(productName)s %(productVersion)s のインストール"

#: pyanaconda/vnc.py:139
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr "ホスト %(name)s 上の %(productName)s %(productVersion)s インストール"

#: pyanaconda/vnc.py:158
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "ホスト %s 上の vnc クライアントに接続を試行中..."

#: pyanaconda/vnc.py:172
msgid "Connected!"
msgstr "接続しました!"

#: pyanaconda/vnc.py:175
msgid "Will try to connect again in 15 seconds..."
msgstr "15 秒後に再接続を試みます..."

#: pyanaconda/vnc.py:182
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] "%d 回接続を試みた後に断念します。\n"

#: pyanaconda/vnc.py:190
msgid "Attempting to start vncconfig"
msgstr ""

#: pyanaconda/vnc.py:203
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""
"インストールを開始するには、ご使用の vnc クライアントを %s に手動で接続してく"
"ださい。"

#: pyanaconda/vnc.py:205
#, python-format
msgid ""
"Please manually connect your vnc client to <IP ADDRESS>:%s to begin the "
"install. Switch to the shell (Ctrl-B 2) and run 'ip addr' to find the <IP "
"ADDRESS>."
msgstr ""

#: pyanaconda/vnc.py:210
msgid "Starting VNC..."
msgstr "VNC を起動中..."

#: pyanaconda/vnc.py:247
msgid "The VNC server is now running."
msgstr "VNC サーバーが稼動しています。"

#: pyanaconda/vnc.py:251
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Listen モードの VNC Viewer に接続するよう選択しました。\n"
"これは、パスワードを必要としません。もしパスワードを設定すると、\n"
"VNC Viewew への接続失敗の原因になります。\n"
"\n"

#: pyanaconda/vnc.py:256
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"警告!!! VNC サーバーがパスワードなしで実行されています!\n"
"サーバーの安全性を確保するには、vncpassword=<password>\n"
"ブートオプションを使うことができます。\n"
"\n"

#: pyanaconda/vnc.py:260
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"パスワードを使って VNC を実行するように選択しました。\n"
"\n"

#: pyanaconda/vnc.py:262
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"不明なエラーが発生しました。作業を中断します。\n"

#: pyanaconda/vnc.py:284
#, fuzzy
msgid ""
"VNC password must be six to eight characters long.\n"
"Please enter a new one, or leave blank for no password."
msgstr ""
"入力された VNC パスワードは最低限の 6文字に足りません。\n"
"新しいパスワードを入力して下さい。パスワード不要なら空白にします。"

#: pyanaconda/packaging/__init__.py:1169
#, fuzzy
msgid "Failed to set up installation source"
msgstr "インストールソースの設定に失敗しました"

#: pyanaconda/packaging/__init__.py:1170
#, fuzzy
msgid "Error downloading package metadata"
msgstr "パッケージメタデータをダウンロード中にエラー..."

#: pyanaconda/packaging/__init__.py:1171
msgid "No installation source available"
msgstr "インストールソースは利用できません"

#: pyanaconda/packaging/livepayload.py:107
#: pyanaconda/packaging/livepayload.py:128
msgid "Installing software"
msgstr "ソフトウェアのインストール中…"

#: pyanaconda/packaging/livepayload.py:238
#: pyanaconda/packaging/livepayload.py:247
#, python-format
msgid "Downloading %(url)s (%(pct)d%%)"
msgstr ""

#: pyanaconda/packaging/livepayload.py:393
msgid "Checking image checksum"
msgstr ""

#: pyanaconda/packaging/dnfpayload.py:158
#, python-format
msgid ""
"Downloading %(total_files)s RPMs, %(downloaded)s / %(total_size)s "
"(%(percent)d%%) done."
msgstr ""

#: pyanaconda/packaging/dnfpayload.py:675
msgid "Starting package installation process"
msgstr "パッケージインストールプロセスを開始しています"

#: pyanaconda/packaging/dnfpayload.py:692
#, fuzzy
msgid "Downloading packages"
msgstr "パッケージのメタデータをダウンロード中..."

#: pyanaconda/packaging/dnfpayload.py:704
msgid "Preparing transaction from installation source"
msgstr "インストールソースからのトランザクションを準備中。"

#: pyanaconda/packaging/dnfpayload.py:714
#, fuzzy, python-format
msgid "Installing %s"
msgstr "インストール中"

#: pyanaconda/packaging/rpmostreepayload.py:167
#, python-format
msgid "Starting pull of %(branchName)s from %(source)s"
msgstr ""

#: pyanaconda/packaging/rpmostreepayload.py:183
#, fuzzy, python-format
msgid "Preparing deployment of %s"
msgstr "インストールの準備中"

#: pyanaconda/packaging/rpmostreepayload.py:203
#, python-format
msgid "Deployment starting: %s"
msgstr ""

#: pyanaconda/packaging/rpmostreepayload.py:206
#, python-format
msgid "Deployment complete: %s"
msgstr ""

#: pyanaconda/ui/helpers.py:92 pyanaconda/ui/tui/spokes/storage.py:408
msgid "Checking storage configuration..."
msgstr "ストレージ設定をチェック中..."

#: pyanaconda/ui/categories/__init__.py:48
msgid "DEFAULT TITLE"
msgstr "デフォルトのタイトル"

#: pyanaconda/ui/categories/customization.py:32
#, fuzzy
msgid "CUSTOMIZATION"
msgstr "地域設定"

#: pyanaconda/ui/categories/localization.py:31
msgid "LOCALIZATION"
msgstr "地域設定"

#: pyanaconda/ui/categories/software.py:31
msgid "SOFTWARE"
msgstr "ソフトウェア"

#: pyanaconda/ui/categories/system.py:32
#: pyanaconda/ui/gui/spokes/lib/accordion.py:171
msgid "SYSTEM"
msgstr "システム"

#: pyanaconda/ui/categories/user_settings.py:32
msgid "USER SETTINGS"
msgstr "ユーザーの設定"

#: pyanaconda/ui/lib/space.py:37
#, fuzzy, python-format
msgid ""
"Not enough space in file systems for the current software selection. An "
"additional %s is needed."
msgstr ""
"現在選択しているソフトウェア選択に対してファイルシステムの空き領域が不足して"
"います。追加で %s 必要です。"

#: pyanaconda/ui/lib/entropy.py:59
msgid "The system needs more random data entropy"
msgstr ""

#: pyanaconda/ui/lib/entropy.py:68
msgid "Entropy can be increased by typing randomly on keyboard"
msgstr ""

#: pyanaconda/ui/lib/entropy.py:69
#, python-format
msgid ""
"After %d minutes, the installation will continue regardless of the amount of "
"available entropy"
msgstr ""

#: pyanaconda/ui/lib/entropy.py:93
#, python-format
msgid ""
"Available entropy: %(av_entr)s, Required entropy: %(req_entr)s [%(pct)d %%] "
"(%(rem)d %(min)s remaining)"
msgstr ""

#: pyanaconda/ui/lib/entropy.py:96
#: pyanaconda/ui/gui/spokes/lib/entropy_dialog.py:92
msgid "minute"
msgid_plural "minutes"
msgstr[0] ""

#: pyanaconda/ui/lib/entropy.py:103
#, python-format
msgid ""
"Available entropy: %(av_entr)s, Required entropy: %(req_entr)s [%(pct)d %%]"
msgstr ""

#: pyanaconda/ui/lib/entropy.py:108
msgid "Enough entropy gathered, please stop typing."
msgstr ""

#: pyanaconda/ui/lib/entropy.py:111
#, python-format
msgid "Giving up, time (%d minutes) ran out."
msgstr ""

#: pyanaconda/ui/lib/disks.py:112
#, python-format
msgid ""
"You selected disk %(selected)s, which contains devices that also use "
"unselected disk %(unselected)s. You must select or de-select these disks as "
"a set."
msgid_plural ""
"You selected disk %(selected)s, which contains devices that also use "
"unselected disks %(unselected)s. You must select or de-select these disks as "
"a set."
msgstr[0] ""

#: pyanaconda/ui/tui/hubs/summary.py:39
#, fuzzy
msgid "Installation"
msgstr "インストールハブ"

#: pyanaconda/ui/tui/hubs/summary.py:55
msgid "Starting automated install"
msgstr "自動インストールの開始"

#: pyanaconda/ui/tui/hubs/summary.py:89
msgid "The following mandatory spokes are not completed:"
msgstr ""

#: pyanaconda/ui/tui/hubs/summary.py:102
#, fuzzy, python-format
msgid ""
"  Please make your choice from above ['%(quit)s' to quit | '%(begin)s' to "
"begin installation |\n"
"  '%(refresh)s' to refresh]: "
msgstr "上記の ['q' 終了 | 'c' 継続] から選択して下さい:"

#. TRANSLATORS: 'q' to quit
#: pyanaconda/ui/tui/hubs/summary.py:104 pyanaconda/ui/tui/hubs/__init__.py:137
#: pyanaconda/ui/tui/simpleline/base.py:462
#: pyanaconda/ui/tui/simpleline/base.py:624
#: pyanaconda/ui/tui/spokes/askvnc.py:111
#, fuzzy
msgctxt "TUI|Spoke Navigation"
msgid "q"
msgstr "q"

#. TRANSLATORS: 'b' to begin installation
#: pyanaconda/ui/tui/hubs/summary.py:106 pyanaconda/ui/tui/hubs/summary.py:123
msgctxt "TUI|Spoke Navigation"
msgid "b"
msgstr ""

#. TRANSLATORS: 'r' to refresh
#. TRANSLATORS:'r' to refresh
#. TRANSLATORS: 'r' to refresh
#. TRANSLATORS:'r' to refresh
#: pyanaconda/ui/tui/hubs/summary.py:108 pyanaconda/ui/tui/hubs/__init__.py:141
#: pyanaconda/ui/tui/simpleline/base.py:450
#: pyanaconda/ui/tui/simpleline/base.py:628
msgctxt "TUI|Spoke Navigation"
msgid "r"
msgstr ""

#: pyanaconda/ui/tui/hubs/summary.py:126 pyanaconda/ui/tui/hubs/__init__.py:116
msgid "Please complete all spokes before continuing"
msgstr "すべてのスポークを完了してから継続して下さい。"

#. TRANSLATORS: 'c' to continue
#. TRANSLATORS:'c' to continue
#. TRANSLATORS: 'c' to continue
#. TRANSLATORS:'c' to continue
#. TRANSLATORS: 'c' to continue
#: pyanaconda/ui/tui/hubs/summary.py:137 pyanaconda/ui/tui/hubs/__init__.py:113
#: pyanaconda/ui/tui/hubs/__init__.py:139
#: pyanaconda/ui/tui/simpleline/base.py:456
#: pyanaconda/ui/tui/simpleline/base.py:626
#: pyanaconda/ui/tui/spokes/software.py:193
#, fuzzy
msgctxt "TUI|Spoke Navigation"
msgid "c"
msgstr "c"

#: pyanaconda/ui/tui/hubs/__init__.py:43
msgid "Default HUB title"
msgstr "デフォルトのハブタイトル"

#: pyanaconda/ui/tui/hubs/__init__.py:133
#, fuzzy, python-format
msgid ""
"  Please make your choice from [ '1' to enter the %(spoke_title)s spoke | "
"'%(quit)s' to quit |\n"
"  '%(continue)s' to continue | '%(refresh)s' to refresh]: "
msgstr "上記の ['q' 終了 | 'c' 継続] から選択して下さい:"

#: pyanaconda/ui/tui/tuiobject.py:30 pyanaconda/ui/gui/main.glade:72
msgid "Error"
msgstr "エラー"

#: pyanaconda/ui/tui/tuiobject.py:51
msgid "Press enter to exit."
msgstr "enter を押して終了します。"

#: pyanaconda/ui/tui/tuiobject.py:61 pyanaconda/ui/tui/spokes/password.py:74
#: pyanaconda/ui/gui/spokes/password.glade:86
#: pyanaconda/ui/gui/spokes/user.glade:170
#, fuzzy
msgid "Password"
msgstr "パスワード: "

#: pyanaconda/ui/tui/tuiobject.py:82
#, fuzzy
msgid "Passphrase: "
msgstr "パスフレーズ:"

#: pyanaconda/ui/tui/tuiobject.py:108
msgid "Question"
msgstr "質問"

#: pyanaconda/ui/tui/tuiobject.py:131
#, fuzzy, python-format
msgid "Please respond '%(yes)s' or '%(no)s': "
msgstr "「はい」か「いいえ」で答えて下さい: "

#. TRANSLATORS: 'yes' as positive reply
#: pyanaconda/ui/tui/tuiobject.py:133 pyanaconda/ui/tui/tuiobject.py:140
#, fuzzy
msgctxt "TUI|Spoke Navigation"
msgid "yes"
msgstr "はい"

#. TRANSLATORS: 'no' as negative reply
#: pyanaconda/ui/tui/tuiobject.py:135 pyanaconda/ui/tui/tuiobject.py:146
#, fuzzy
msgctxt "TUI|Spoke Navigation"
msgid "no"
msgstr "いいえ"

#: pyanaconda/ui/tui/simpleline/base.py:87
msgid "Do you really want to quit?"
msgstr "本当に終了しますか？"

#: pyanaconda/ui/tui/simpleline/base.py:571 anaconda:509
msgid "Press ENTER to continue"
msgstr ""

#: pyanaconda/ui/tui/simpleline/base.py:622
#, fuzzy, python-format
msgid ""
"  Please make your choice from above ['%(quit)s' to quit | '%(continue)s' to "
"continue |\n"
"  '%(refresh)s' to refresh]: "
msgstr "上記の ['q' 終了 | 'c' 継続] から選択して下さい:"

#: pyanaconda/ui/tui/spokes/askvnc.py:46
msgid "VNC"
msgstr "VNC"

#: pyanaconda/ui/tui/spokes/askvnc.py:62
#, fuzzy
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"installation or continue with a text mode installation?"
msgstr ""
"ご使用のマシンで X を起動できませんでした。VNC を起動して別のコンピューターか"
"らこのコンピューターに接続しグラフィカルインストールを行ないますか、あるいは"
"テキストモードのインストールで続行しますか?"

#: pyanaconda/ui/tui/spokes/askvnc.py:131
msgid "VNC Password"
msgstr "VNC パスワード"

#: pyanaconda/ui/tui/spokes/askvnc.py:139
#, fuzzy
msgid ""
"Please provide VNC password (must be six to eight characters long).\n"
"You will have to type it twice. Leave blank for no password"
msgstr ""
"VNC パスワードを記入してください。2度記入して下さい。\n"
"パスワード不要なら空白にします。"

#: pyanaconda/ui/tui/spokes/askvnc.py:158
#: pyanaconda/ui/gui/spokes/network.py:1377
msgid "Password: "
msgstr "パスワード: "

#: pyanaconda/ui/tui/spokes/askvnc.py:159
msgid "Password (confirm): "
msgstr "パスワード(確定): "

#: pyanaconda/ui/tui/spokes/askvnc.py:162
msgid "Passwords do not match!"
msgstr "パスワードが一致しません！"

#: pyanaconda/ui/tui/spokes/askvnc.py:165
msgid "The password must be at least six characters long."
msgstr "パスワードは最低 6 文字以上でなければなりません。"

#: pyanaconda/ui/tui/spokes/askvnc.py:169
#, fuzzy
msgid "The password cannot be more than eight characters long."
msgstr "パスワードは最低 6 文字以上でなければなりません。"

#: pyanaconda/ui/tui/spokes/langsupport.py:41
#, fuzzy
msgid "Language settings"
msgstr "タイムゾーンの設定"

#: pyanaconda/ui/tui/spokes/langsupport.py:68
#, fuzzy
msgid "Language is not set."
msgstr "タイムゾーンは設定されていません"

#: pyanaconda/ui/tui/spokes/langsupport.py:78
#, fuzzy
msgid "Available locales"
msgstr "使用できる地域"

#: pyanaconda/ui/tui/spokes/langsupport.py:81
#, fuzzy
msgid "Available languages"
msgstr "使用できる地域"

#. TRANSLATORS: 'b' to go back
#: pyanaconda/ui/tui/spokes/langsupport.py:117
#: pyanaconda/ui/tui/spokes/langsupport.py:127
msgctxt "TUI|Spoke Navigation|Language Support"
msgid "b"
msgstr ""

#: pyanaconda/ui/tui/spokes/langsupport.py:125
#, python-format
msgid ""
"Please select language support to install.\n"
"['%(back)s' to return to language list, '%(continue)s' to continue, "
"'%(quit)s' to quit]: "
msgstr ""

#. TRANSLATORS:'c' to continue
#: pyanaconda/ui/tui/spokes/langsupport.py:129
#, fuzzy
msgctxt "TUI|Spoke Navigation|Language Support"
msgid "c"
msgstr "c"

#. TRANSLATORS:'q' to quit
#: pyanaconda/ui/tui/spokes/langsupport.py:131
#, fuzzy
msgctxt "TUI|Spoke Navigation|Language Support"
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/spokes/network.py:50
#, fuzzy
msgid "Network configuration"
msgstr "ネットワーク構成を書き込み中"

#: pyanaconda/ui/tui/spokes/network.py:111
#, fuzzy, python-format
msgid "Wired (%(interface_name)s) disconnected\n"
msgstr "有線 (%s) は接続されています"

#: pyanaconda/ui/tui/spokes/network.py:116
#, fuzzy, python-format
msgid "Wired (%(interface_name)s) connected\n"
msgstr "有線 (%s) は接続されています"

#: pyanaconda/ui/tui/spokes/network.py:128
#, python-format
msgid " IPv4 Address: %(addr)s Netmask: %(netmask)s Gateway: %(gateway)s\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:130
#, python-format
msgid " DNS: %s\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:137
#, python-format
msgid " IPv6 Address: %(addr)s/%(prefix)d\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:158
#, fuzzy, python-format
msgid "Host Name: %s\n"
msgstr "ホスト名:"

#: pyanaconda/ui/tui/spokes/network.py:170
#, fuzzy
msgid "Set host name"
msgstr "ホスト名"

#: pyanaconda/ui/tui/spokes/network.py:172
#, python-format
msgid "Configure device %s"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:191
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:241
#: pyanaconda/ui/gui/spokes/network.glade:2248
#, fuzzy
msgid "Host Name"
msgstr "ホスト名"

#: pyanaconda/ui/tui/spokes/network.py:209
msgid ""
"Configuration not saved: gateway or netmask missing in static configuration"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:225
msgid "Can't apply configuration, device activation failed."
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:252
#: pyanaconda/ui/gui/spokes/network.py:1538
#: pyanaconda/ui/gui/spokes/network.py:1611
#, fuzzy, python-format
msgid "Host name is not valid: %s"
msgstr "ホスト名は無効です: %s"

#: pyanaconda/ui/tui/spokes/network.py:290
#, fuzzy
msgid "Device configuration"
msgstr "設定完了(_F)"

#: pyanaconda/ui/tui/spokes/network.py:294
#, python-format
msgid "IPv4 address or %s for DHCP"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:296
msgid "IPv4 netmask"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:297
#, fuzzy
msgid "IPv4 gateway"
msgstr "ゲートウェイ"

#: pyanaconda/ui/tui/spokes/network.py:298
#, python-format
msgid ""
"IPv6 address or %(auto)s for automatic, %(dhcp)s for DHCP, %(ignore)s to "
"turn off"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:301
msgid "IPv6 default gateway"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:302
msgid "Nameservers (comma separated)"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:304
msgid "Connect automatically after reboot"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:305
#, fuzzy
msgid "Apply configuration in installer"
msgstr "ファイルシステム設定にタイプがありません。"

#: pyanaconda/ui/tui/spokes/network.py:316
msgid "Bad format of the IP address"
msgstr ""

#: pyanaconda/ui/tui/spokes/network.py:321
#, fuzzy, python-format
msgid "Configuring device %s."
msgstr "インストール済みのシステムを構成"

#: pyanaconda/ui/tui/spokes/password.py:36
#, fuzzy
msgid "Root password"
msgstr "root パスワード:"

#: pyanaconda/ui/tui/spokes/password.py:59
msgid "Password is set."
msgstr "パスワードは設定されています"

#: pyanaconda/ui/tui/spokes/password.py:61
msgid "Root account is disabled."
msgstr "root アカウントは無効になっています"

#: pyanaconda/ui/tui/spokes/password.py:63
msgid "Password is not set."
msgstr "パスワードが設定されていません"

#: pyanaconda/ui/tui/spokes/password.py:68
msgid "Please select new root password. You will have to type it twice."
msgstr "新しい root パスワードを選択して下さい。２度記入する必要があります。"

#: pyanaconda/ui/tui/spokes/storage.py:60
msgid "Use All Space"
msgstr "すべての領域を使用する"

#: pyanaconda/ui/tui/spokes/storage.py:61
msgid "Replace Existing Linux system(s)"
msgstr "既存の Linux システムを入れ替える"

#: pyanaconda/ui/tui/spokes/storage.py:62
msgid "Use Free Space"
msgstr "空き領域を使用する"

#: pyanaconda/ui/tui/spokes/storage.py:74
#, fuzzy
msgid "Installation Destination"
msgstr "インストール先"

#: pyanaconda/ui/tui/spokes/storage.py:130
#: pyanaconda/ui/gui/spokes/storage.py:401
msgid "No disks selected"
msgstr "ディスクが選択されていません"

#: pyanaconda/ui/tui/spokes/storage.py:133
#: pyanaconda/ui/gui/spokes/storage.py:404
msgid "Kickstart insufficient"
msgstr ""

#: pyanaconda/ui/tui/spokes/storage.py:140
#: pyanaconda/ui/gui/spokes/storage.py:413
msgid "Error checking storage configuration"
msgstr "ストレージ設定のチェック中にエラー"

#: pyanaconda/ui/tui/spokes/storage.py:142
#: pyanaconda/ui/gui/spokes/storage.py:415
#, fuzzy
msgid "Warning checking storage configuration"
msgstr "ストレージ設定のチェック中にエラー"

#: pyanaconda/ui/tui/spokes/storage.py:145
#: pyanaconda/ui/gui/spokes/storage.py:417
msgid "Automatic partitioning selected"
msgstr "自動パーティション設定が選択されました"

#: pyanaconda/ui/tui/spokes/storage.py:147
#: pyanaconda/ui/gui/spokes/storage.py:419
msgid "Custom partitioning selected"
msgstr "カスタムパーティション設定が選択されました"

#: pyanaconda/ui/tui/spokes/storage.py:183
#: pyanaconda/ui/gui/spokes/storage.py:674
msgid ""
"No disks detected.  Please shut down the computer, connect at least one "
"disk, and restart to complete installation."
msgstr ""
"ディスク検出がありません。コンピュータをシャットダウンして最低１個のディスク"
"に接続し、再開始するとインストールが完了できます。"

#: pyanaconda/ui/tui/spokes/storage.py:185
#: pyanaconda/ui/gui/spokes/storage.py:676
msgid "No disks selected; please select at least one disk to install to."
msgstr ""
"ディスクが選択されていません。インストール先として少なくともディスクを１つ選"
"択して下さい。"

#: pyanaconda/ui/tui/spokes/storage.py:221
#, fuzzy
msgid "Select all"
msgstr "選択(_S)"

#: pyanaconda/ui/tui/spokes/storage.py:326
msgid ""
"The following unformatted DASDs have been detected on your system. You can "
"choose to format them now with dasdfmt or cancel to leave them unformatted. "
"Unformatted DASDs cannot be used during installation.\n"
"\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/storage.py:328
msgid ""
"Warning: All storage changes made using the installer will be lost when you "
"choose to format.\n"
"\n"
"Proceed to run dasdfmt?\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/storage.py:343
#: pyanaconda/ui/gui/spokes/lib/dasdfmt.py:94
#, python-format
msgid "Formatting /dev/%s. This may take a moment."
msgstr ""

#: pyanaconda/ui/tui/spokes/storage.py:387
msgid "Generating updated storage configuration"
msgstr "更新したストレージ設定を生成中"

#: pyanaconda/ui/tui/spokes/storage.py:392
#: pyanaconda/ui/tui/spokes/storage.py:404
#, python-format
msgid "storage configuration failed: %s"
msgstr "ストレージの設定に失敗しました: %s"

#: pyanaconda/ui/tui/spokes/storage.py:455
msgid "Autopartitioning Options"
msgstr "自動パーティション設定のオプション"

#: pyanaconda/ui/tui/spokes/storage.py:481
#, fuzzy
msgid ""
"Installation requires partitioning of your hard drive. Select what space to "
"use for the install target."
msgstr ""
"インストールにはハードドライブのパーティション設定が必要です。インストール先"
"として使用する領域を選択して下さい。"

#: pyanaconda/ui/tui/spokes/storage.py:520
#, fuzzy
msgid "Partition Scheme Options"
msgstr "パーティションスキーマの設定"

#: pyanaconda/ui/tui/spokes/storage.py:544
#, fuzzy
msgid "Select a partition scheme configuration."
msgstr "パーティションスキーマの設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:35
msgid "Timezone settings"
msgstr "タイムゾーンの設定"

#: pyanaconda/ui/tui/spokes/time_spoke.py:65
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:550
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:556
#, python-format
msgid "%s timezone"
msgstr "%s タイムゾーン"

#: pyanaconda/ui/tui/spokes/time_spoke.py:67
msgid "Timezone is not set."
msgstr "タイムゾーンは設定されていません"

#: pyanaconda/ui/tui/spokes/time_spoke.py:75
#, python-format
msgid "Available timezones in region %s"
msgstr "地域 %s で使用できるタイムゾーン"

#: pyanaconda/ui/tui/spokes/time_spoke.py:78
msgid "Available regions"
msgstr "使用できる地域"

#. TRANSLATORS: 'b' to go back
#: pyanaconda/ui/tui/spokes/time_spoke.py:117
#: pyanaconda/ui/tui/spokes/time_spoke.py:147
msgctxt "TUI|Spoke Navigation|Time Settings"
msgid "b"
msgstr ""

#: pyanaconda/ui/tui/spokes/time_spoke.py:145
#, fuzzy, python-format
msgid ""
"Please select the timezone.\n"
"Use numbers or type names directly ['%(back)s' to region list, '%(quit)s' to "
"quit]: "
msgstr ""
"タイムゾーンを選択して下さい。\n"
"番号かタイプ名を直接選択して下さい\n"
"[b で地域一覧、q で終了]: "

#. TRANSLATORS:'q' to quit
#: pyanaconda/ui/tui/spokes/time_spoke.py:149
#, fuzzy
msgctxt "TUI|Spoke Navigation|Time Settings"
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/spokes/shell_spoke.py:37
msgid "Shell"
msgstr ""

#: pyanaconda/ui/tui/spokes/shell_spoke.py:52
#, fuzzy
msgid "Start shell"
msgstr "VNC を起動する"

#: pyanaconda/ui/tui/spokes/shell_spoke.py:61
msgid "Exit the shell to continue"
msgstr ""

#: pyanaconda/ui/tui/spokes/source.py:59
#, fuzzy
msgid "Installation source"
msgstr "インストールの進捗"

#: pyanaconda/ui/tui/spokes/source.py:62 pyanaconda/ui/tui/spokes/source.py:111
#: pyanaconda/ui/gui/spokes/source.py:587
#: pyanaconda/ui/gui/spokes/source.glade:758
msgid "Closest mirror"
msgstr "最寄りのミラー"

#: pyanaconda/ui/tui/spokes/source.py:103
#: pyanaconda/ui/gui/spokes/source.py:579
#, python-format
msgid "NFS server %s"
msgstr "NFS サーバー %s"

#: pyanaconda/ui/tui/spokes/source.py:105
#: pyanaconda/ui/gui/spokes/source.py:581
msgid "Local media"
msgstr ""

#: pyanaconda/ui/tui/spokes/source.py:108
#: pyanaconda/ui/tui/spokes/source.py:122
#: pyanaconda/ui/gui/spokes/source.py:575
msgid "Error setting up software source"
msgstr "ソフトウェアソースの設定でエラー"

#: pyanaconda/ui/tui/spokes/source.py:113
#: pyanaconda/ui/tui/spokes/software.py:125
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:558
#: pyanaconda/ui/gui/spokes/software.py:307
#: pyanaconda/ui/gui/spokes/software.py:312
#: pyanaconda/ui/gui/spokes/source.py:589
msgid "Nothing selected"
msgstr "何も選択されていません"

#: pyanaconda/ui/tui/spokes/source.py:124
#: pyanaconda/ui/tui/spokes/software.py:113
#, fuzzy
msgid "Processing..."
msgstr "接続中..."

#: pyanaconda/ui/tui/spokes/source.py:140
#, fuzzy
msgid "CD/DVD"
msgstr "CD/DVD ドライブ"

#: pyanaconda/ui/tui/spokes/source.py:140
#, fuzzy
msgid "local ISO file"
msgstr "ISO ファイル(_I):"

#: pyanaconda/ui/tui/spokes/source.py:140
#, fuzzy
msgid "Network"
msgstr "ネットワーク時刻同期"

#: pyanaconda/ui/tui/spokes/source.py:144
#: pyanaconda/ui/gui/spokes/source.py:900
msgid ""
"The installation source is in use by the installer and cannot be changed."
msgstr ""

#: pyanaconda/ui/tui/spokes/source.py:151
#, fuzzy
msgid "Choose an installation source type."
msgstr "インストールソースは利用できません"

#: pyanaconda/ui/tui/spokes/source.py:248
#: pyanaconda/ui/tui/spokes/source.py:286
msgid "Specify Repo Options"
msgstr ""

#: pyanaconda/ui/tui/spokes/source.py:252
msgid "Repo URL"
msgstr ""

#: pyanaconda/ui/tui/spokes/source.py:290
#, fuzzy
msgid "<server>:/<path>"
msgstr "NFS サーバー %s"

#: pyanaconda/ui/tui/spokes/source.py:291
#, fuzzy
msgid "NFS mount options"
msgstr "NFS マウントオプション:"

#: pyanaconda/ui/tui/spokes/source.py:333
#, fuzzy
msgid "Select device containing the ISO file"
msgstr "/boot を含むデバイス"

#: pyanaconda/ui/tui/spokes/source.py:392
msgid "No mountable devices found"
msgstr ""

#: pyanaconda/ui/tui/spokes/source.py:420
#, fuzzy
msgid "Select an ISO to use as install source"
msgstr "インストールソースの設定に失敗しました"

#: pyanaconda/ui/tui/spokes/source.py:449
msgid "No *.iso files found in device root folder"
msgstr ""

#: pyanaconda/ui/tui/spokes/software.py:44
#, fuzzy
msgid "Software selection"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/ui/tui/spokes/software.py:111
#: pyanaconda/ui/gui/spokes/software.py:288
msgid "Error checking software selection"
msgstr "ソフトウェアの選択をチェック中にエラー"

#: pyanaconda/ui/tui/spokes/software.py:115
#: pyanaconda/ui/gui/spokes/software.py:291
msgid "Installation source not set up"
msgstr "インストールソースはセットされていません"

#: pyanaconda/ui/tui/spokes/software.py:117
#: pyanaconda/ui/gui/spokes/software.py:294
msgid "Source changed - please verify"
msgstr "ソースが変更されました - ご確認ください"

#: pyanaconda/ui/tui/spokes/software.py:124
#: pyanaconda/ui/gui/spokes/software.py:301
msgid "Custom software selected"
msgstr "カスタムソフトウェアが選択されています"

#: pyanaconda/ui/tui/spokes/software.py:151
#, fuzzy
msgid "Installation source needs to be set up first."
msgstr "インストールソースはセットされていません"

#: pyanaconda/ui/tui/spokes/software.py:161
#, fuzzy
msgid "Base environment"
msgstr "使用環境を選択します"

#: pyanaconda/ui/tui/spokes/user.py:41
#, fuzzy
msgid "User creation"
msgstr "認証の使用(_U)"

#: pyanaconda/ui/tui/spokes/user.py:74
msgid ""
"You have provided an invalid user name.\n"
"Tip: Keep your user name shorter than 32 characters and do not use spaces.\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/user.py:129 pyanaconda/ui/gui/spokes/user.py:387
msgid "No user will be created"
msgstr ""

#: pyanaconda/ui/tui/spokes/user.py:131
#, fuzzy
msgid "You must set a password"
msgstr "パスワードを入力してから確認を行ってください。"

#: pyanaconda/ui/tui/spokes/user.py:133 pyanaconda/ui/gui/spokes/user.py:389
#, python-format
msgid "Administrator %s will be created"
msgstr ""

#: pyanaconda/ui/tui/spokes/user.py:135 pyanaconda/ui/gui/spokes/user.py:391
#, python-format
msgid "User %s will be created"
msgstr ""

#: pyanaconda/ui/tui/spokes/user.py:141
#, fuzzy, python-format
msgid "Invalid user name: %s.\n"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/tui/spokes/warnings_spoke.py:40
#, fuzzy
msgid "Warnings"
msgstr "警告"

#: pyanaconda/ui/tui/spokes/warnings_spoke.py:48
#: pyanaconda/ui/gui/spokes/welcome.glade:517
msgid ""
"This hardware (or a combination thereof) is not supported by Red Hat.  For "
"more information on supported hardware, please refer to http://www.redhat."
"com/hardware."
msgstr ""

#: pyanaconda/ui/tui/spokes/progress.py:41
#, fuzzy
msgid "Progress"
msgstr "進行中"

#: pyanaconda/ui/tui/spokes/progress.py:143
msgid "\tInstallation complete.  Press return to quit"
msgstr "» インストールは完了しました。改行ボタンを押して終了します"

#: pyanaconda/ui/tui/spokes/__init__.py:52
msgid "Default spoke title"
msgstr "デフォルトのスポークタイトル"

#: pyanaconda/ui/tui/spokes/__init__.py:64
msgid "testing status..."
msgstr "状態をテスト中..."

#: pyanaconda/ui/tui/spokes/__init__.py:117
#, fuzzy
msgid "New value"
msgstr "新しいデバイス"

#: pyanaconda/ui/tui/spokes/__init__.py:144
#, python-format
msgid "%s: "
msgstr ""

#: pyanaconda/ui/tui/spokes/__init__.py:145
#, fuzzy, python-format
msgid "%s (confirm): "
msgstr "パスワード(確定): "

#: pyanaconda/ui/tui/spokes/__init__.py:148
msgid ""
"You must enter your root password and confirm it by typing it a second time "
"to continue."
msgstr ""

#: pyanaconda/ui/tui/spokes/__init__.py:170
msgid ""
"\n"
"Would you like to use it anyway?"
msgstr ""
"\n"
"とにかくこれを使用しますか?"

#: pyanaconda/ui/tui/spokes/__init__.py:187
msgid ""
"You have provided a password containing non-ASCII characters.\n"
"You may not be able to switch between keyboard layouts to login.\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/__init__.py:193
#, python-format
msgid "Enter new value for '%s' and press enter\n"
msgstr ""

#: pyanaconda/ui/tui/spokes/__init__.py:204
#, fuzzy
msgid "You have provided an invalid value\n"
msgstr "脆弱なパスフレーズを記入しています: %s"

#: pyanaconda/ui/tui/spokes/__init__.py:317
#, fuzzy
msgid "Password set."
msgstr "パスワードは設定されています"

#: pyanaconda/ui/gui/__init__.py:443 widgets/src/BaseWindow.c:115
#, fuzzy
msgid "Help!"
msgstr "ヘルプ"

#: pyanaconda/ui/gui/__init__.py:887
#: pyanaconda/ui/gui/spokes/lib/detailederror.py:59
#, fuzzy
msgctxt "GUI|Detailed Error Dialog"
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/__init__.py:903
#, fuzzy
msgctxt "GUI|Yes No Dialog"
msgid "_No"
msgstr "いいえ(_N)"

#: pyanaconda/ui/gui/__init__.py:904
#, fuzzy
msgctxt "GUI|Yes No Dialog"
msgid "_Yes"
msgstr "はい(_Y)"

#: pyanaconda/ui/gui/hubs/__init__.py:241
msgid ""
"Please complete items marked with this icon before continuing to the next "
"step."
msgstr "このアイコンが付いた項目を完了してから、次のステップへと続けて下さい。"

#: pyanaconda/ui/gui/hubs/progress.py:119
msgid "Complete!"
msgstr "完了しました!"

#: pyanaconda/ui/gui/hubs/progress.py:219
#, fuzzy, python-format
msgid ""
"%s is now successfully installed on your system and ready for you to use!  "
"When you are ready, reboot your system to start using it!"
msgstr ""
"%s は、ここでご使用のシステムに正常にインストールされ、\n"
"使用準備ができました。次に進むために再起動して使用を開始して下さい！"

#: pyanaconda/ui/gui/hubs/progress.py:222
#, fuzzy
msgctxt "GUI|Progress"
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/hubs/progress.py:230
#, fuzzy, python-format
msgid ""
"%s is now successfully installed, but some configuration still needs to be "
"done.\n"
"Finish it and then click the Finish configuration button please."
msgstr ""
"%s は今ご使用のシステムに正常にインストールされましたが、まだいくつかの設定が"
"必要です。\n"
"それを終了してから「設定の完了」ボタンをクリックして下さい。"

#: pyanaconda/ui/gui/hubs/progress.py:235
#, fuzzy, python-format
msgid ""
"%s is now successfully installed and ready for you to use!\n"
"Go ahead and reboot to start using it!"
msgstr ""
"%s は、ここでご使用のシステムに正常にインストールされ、\n"
"使用準備ができました。次に進むために再起動して使用を開始して下さい！"

#: pyanaconda/ui/gui/spokes/custom.py:113
#, fuzzy, python-format
msgid "Create a new %(container_type)s ..."
msgstr "新規ボリュームグループを作成中 ..."

#: pyanaconda/ui/gui/spokes/custom.py:114
#, python-format
msgid "Create or select %(container_type)s"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.py:116
#, fuzzy
msgid "Device reconfiguration failed. <a href=\"\">Click for details.</a>"
msgstr "デバイスの設定が失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:118
#, fuzzy
msgid ""
"Storage configuration reset due to unrecoverable error. <a href=\"\">Click "
"for details.</a>"
msgstr ""
"復元不可能なエラーによりストレージ設定がリセットされました。詳細にはクリック"
"して下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:153
#: pyanaconda/ui/gui/spokes/custom.glade:99
msgid "MANUAL PARTITIONING"
msgstr "手作業のパーティション設定"

#: pyanaconda/ui/gui/spokes/custom.py:380
#, fuzzy, python-format
msgctxt "GUI|Custom Partitioning"
msgid "%d _storage device selected"
msgid_plural "%d _storage devices selected"
msgstr[0] "%d 個のストレージデバイスが選択されています"

#: pyanaconda/ui/gui/spokes/custom.py:514
#, fuzzy, python-format
msgid ""
"When you create mount points for your %(name)s %(version)s installation, "
"you'll be able to view their details here."
msgstr ""
"%s %s インストール用のマウントポイントを作成する際に、\n"
"ここでその詳細を表示できます。"

#: pyanaconda/ui/gui/spokes/custom.py:674
#, fuzzy, python-format
msgid ""
"/boot/efi must be on a device of type %(oneFsType)s or %(anotherFsType)s"
msgstr "/boot/efi は タイプ %s のデバイス上でなければなりません"

#: pyanaconda/ui/gui/spokes/custom.py:678
#, fuzzy, python-format
msgid "%(fs)s must be on a device of type %(type)s"
msgstr "%s はタイプ %s のデバイス上でなければなりません"

#: pyanaconda/ui/gui/spokes/custom.py:681
#: pyanaconda/ui/gui/spokes/custom.py:683
#, python-format
msgid "%s cannot be encrypted"
msgstr "%s は暗号化できません"

#: pyanaconda/ui/gui/spokes/custom.py:685
#, fuzzy
msgid "You must create a new file system on the root device."
msgstr "新しいファイルシステムは root デバイス上に作成する必要があります。"

#: pyanaconda/ui/gui/spokes/custom.py:690
#, fuzzy, python-format
msgid "Device does not support RAID level selection %s."
msgstr "タイプ %s のデバイスには有効な RAID レベルを選択する必要があります。"

#: pyanaconda/ui/gui/spokes/custom.py:803
#, fuzzy
msgid "Device resize request failed. <a href=\"\">Click for details.</a>"
msgstr "デバイスのサイズ変更要求は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:876
#, fuzzy
msgid "Device reformat request failed. <a href=\"\">Click for details.</a>"
msgstr ""
"デバイスの再フォーマット要求は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:1247
#: pyanaconda/ui/gui/spokes/custom.py:2140
#, fuzzy, python-format
msgid "Invalid device name: %s"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/custom.py:1253
#, python-format
msgid "Specified name %s already in use."
msgstr "指定された名前 %s はすでに存在します。"

#: pyanaconda/ui/gui/spokes/custom.py:1460
#, fuzzy
msgid "No disks assigned"
msgstr "ディスクが選択されていません"

#: pyanaconda/ui/gui/spokes/custom.py:1466
#, python-format
msgctxt "GUI|Custom Partitioning|Devices"
msgid " and %d other"
msgid_plural " and %d others"
msgstr[0] ""

#: pyanaconda/ui/gui/spokes/custom.py:1524
#, fuzzy
msgid "The container is encrypted."
msgstr "%s は暗号化できません"

#: pyanaconda/ui/gui/spokes/custom.py:1560
msgid ""
"The space available to this mount point can be changed by modifying the "
"volume below."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.py:1562
msgid "This file system may not be resized."
msgstr "このファイルシステムはサイズ変更できません。"

#: pyanaconda/ui/gui/spokes/custom.py:1616
#, fuzzy
msgid ""
"Error checking storage configuration.  <a href=\"\">Click for details</a> or "
"press Done again to continue."
msgstr "ストレージ設定のチェックでエラー発生。クリックして詳細を見ます。"

#: pyanaconda/ui/gui/spokes/custom.py:1618
#, fuzzy
msgid ""
"Warning checking storage configuration.  <a href=\"\">Click for details</a> "
"or press Done again to continue."
msgstr "ストレージ設定のチェックでエラー発生。クリックして詳細を見ます。"

#: pyanaconda/ui/gui/spokes/custom.py:1724
#, fuzzy, python-format
msgid "Added new %(type)s to existing container %(name)s."
msgstr "新しい %s をすでに存在するコンテナー %s へ追加しました。"

#: pyanaconda/ui/gui/spokes/custom.py:1735
#, fuzzy
msgid "Failed to add new device. <a href=\"\">Click for details.</a>"
msgstr "新規デバイスの追加に失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:1740
msgid "Invalid partition size set. Use a valid integer."
msgstr ""
"無効なパーティション容量が設定されました。有効な範囲の整数を使用してくださ"
"い。"

#: pyanaconda/ui/gui/spokes/custom.py:1847
#, fuzzy
msgid "Device removal request failed. <a href=\"\">Click for details.</a>"
msgstr "デバイスの除去要求は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:2077
#, python-format
msgid "Volume Group name %s is already in use. Not saving changes."
msgstr "ボリュームグループ名 %s はすでに使われています。変更は保存されません。"

#: pyanaconda/ui/gui/spokes/custom.py:2107
#, fuzzy, python-format
msgid "(%s free)"
msgstr "fs free"

#: pyanaconda/ui/gui/spokes/custom.py:2272
#, fuzzy, python-format
msgid ""
"This Software RAID array is missing %(missingMembers)d of %(totalMembers)d "
"member partitions. You can remove it or select a different device."
msgstr ""
"ソフトウェアRAIDアレイの %d / %d のメンバーパーティションが見つかりません。削"
"除するか他のデバイスを選択してください。"

#: pyanaconda/ui/gui/spokes/custom.py:2278
#, fuzzy, python-format
msgid ""
"This LVM Volume Group is missing %(missingPVs)d of %(totalPVs)d physical "
"volumes. You can remove it or select a different device."
msgstr ""
"LVM ボリュームグループの %d / %d の物理ボリュームが見つかりません。削除するか"
"他のデバイスを選択してください。"

#: pyanaconda/ui/gui/spokes/custom.py:2361
msgid "No disks selected."
msgstr "ディスクが選択されていません。"

#: pyanaconda/ui/gui/spokes/custom.py:2366
msgid "Not enough free space on selected disks."
msgstr "選択したディスクには十分な空き領域がありません。"

#: pyanaconda/ui/gui/spokes/custom.py:2371
#: pyanaconda/ui/gui/spokes/custom.py:2396
#, fuzzy
msgid "Automatic partitioning failed. <a href=\"\">Click for details.</a>"
msgstr "自動パーティション設定は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:2626
msgid ""
"Continuing with this action will reset all your partitioning selections to "
"their current on-disk state."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.py:2634
#, fuzzy
msgctxt "GUI|Custom Partitioning|Reset Dialog"
msgid "_Reset selections"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/ui/gui/spokes/custom.py:2635
#, fuzzy
msgctxt "GUI|Custom Partitioning|Reset Dialog"
msgid "_Preserve current selections"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/ui/gui/spokes/custom.py:2710
#, fuzzy
msgid ""
"Failed to unlock encrypted block device. <a href=\"\">Click for details.</a>"
msgstr ""
"暗号化されたブロックデバイスのアンロックに失敗しました。詳細にはクリックして"
"下さい。"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:418
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_TIME & DATE"
msgstr "日付と時刻"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:541
msgid "Restoring hardware time..."
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:552
msgid "Invalid timezone"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:728
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:742
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:928
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:751
msgid "PM"
msgstr "PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:730
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:739
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:927
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:930
msgid "AM"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:1078
msgid "You need to set up networking first if you want to use NTP"
msgstr "NTP を使用する場合は、ネットワークを最初に設定する必要があります。"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:1082
msgid "You have no working NTP server configured"
msgstr "稼働できる NTP サーバーの設定がありません。"

#: pyanaconda/ui/gui/spokes/filter.py:489
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_INSTALLATION DESTINATION"
msgstr "インストール先"

#: pyanaconda/ui/gui/spokes/filter.py:590
#, fuzzy, python-format
msgctxt "GUI|Installation Destination|Filter"
msgid "%d _storage device selected"
msgid_plural "%d _storage devices selected"
msgstr[0] "%d 個のストレージデバイスが選択されています"

#: pyanaconda/ui/gui/spokes/keyboard.py:52
#, python-format
msgid "%s to switch layouts."
msgstr "%s レイアウトの切り替え"

#: pyanaconda/ui/gui/spokes/keyboard.py:276
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_KEYBOARD"
msgstr "キーボード"

#: pyanaconda/ui/gui/spokes/keyboard.py:363
msgid "Testing layouts configuration not available."
msgstr "レイアウト設定のテストは出来ません。"

#: pyanaconda/ui/gui/spokes/keyboard.py:371
#, fuzzy
msgid "Getting list of layouts..."
msgstr "状態をテスト中..."

#: pyanaconda/ui/gui/spokes/keyboard.py:426
msgid "Layout switching not configured."
msgstr "レイアウトの切り替えは設定されていません。"

#: pyanaconda/ui/gui/spokes/langsupport.py:63
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_LANGUAGE SUPPORT"
msgstr "言語"

#: pyanaconda/ui/gui/spokes/network.py:96
msgid "Status unknown (missing)"
msgstr "状態は不明です (情報欠如)"

#: pyanaconda/ui/gui/spokes/network.py:99
msgid "Status unknown"
msgstr "状態は不明です"

#: pyanaconda/ui/gui/spokes/network.py:101
msgid "Unmanaged"
msgstr "管理されていません"

#: pyanaconda/ui/gui/spokes/network.py:104
#: pyanaconda/ui/gui/spokes/network.py:108
msgid "Unavailable"
msgstr "利用できません"

#: pyanaconda/ui/gui/spokes/network.py:106
msgid "Firmware missing"
msgstr "ファームウェアがありません"

#: pyanaconda/ui/gui/spokes/network.py:112
msgid "Cable unplugged"
msgstr "ケーブルが外れています"

#: pyanaconda/ui/gui/spokes/network.py:114
msgid "Disconnected"
msgstr "切断されています"

#: pyanaconda/ui/gui/spokes/network.py:119
msgid "Connecting"
msgstr "接続しています"

#: pyanaconda/ui/gui/spokes/network.py:121
msgid "Authentication required"
msgstr "認証が必要です"

#: pyanaconda/ui/gui/spokes/network.py:123
msgid "Connected"
msgstr "接続済みです"

#: pyanaconda/ui/gui/spokes/network.py:125
msgid "Disconnecting"
msgstr "切断しています"

#: pyanaconda/ui/gui/spokes/network.py:127
msgid "Connection failed"
msgstr "接続に失敗しました"

#: pyanaconda/ui/gui/spokes/network.py:328
msgid "Ethernet"
msgstr "イーサネット"

#: pyanaconda/ui/gui/spokes/network.py:329
msgid "Wireless"
msgstr "ワイヤーレス"

#: pyanaconda/ui/gui/spokes/network.py:330
#: pyanaconda/ui/gui/spokes/network.glade:15
msgid "Bond"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.py:331
#: pyanaconda/ui/gui/spokes/network.glade:27
msgid "VLAN"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.py:332
#: pyanaconda/ui/gui/spokes/network.glade:23
msgid "Team"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.py:333
#: pyanaconda/ui/gui/spokes/network.glade:19
msgid "Bridge"
msgstr ""

#. TRANSLATORS: ethernet cable is unplugged
#: pyanaconda/ui/gui/spokes/network.py:781
msgid "unplugged"
msgstr "外れています"

#: pyanaconda/ui/gui/spokes/network.py:871
#: pyanaconda/ui/gui/spokes/network.glade:542
#: pyanaconda/ui/gui/spokes/network.glade:843
msgid "IPv4 Address"
msgstr "IPv4 アドレス"

#: pyanaconda/ui/gui/spokes/network.py:872
#: pyanaconda/ui/gui/spokes/network.glade:518
#: pyanaconda/ui/gui/spokes/network.glade:855
#: pyanaconda/ui/gui/spokes/network.glade:1422
msgid "IPv6 Address"
msgstr "IPv6 アドレス"

#: pyanaconda/ui/gui/spokes/network.py:874
#: pyanaconda/ui/gui/spokes/network.py:876
#: pyanaconda/ui/gui/spokes/network.glade:1410
msgid "IP Address"
msgstr "IP アドレス"

#: pyanaconda/ui/gui/spokes/network.py:966
#, python-format
msgid "%d Mb/s"
msgstr "%d Mb/s"

#: pyanaconda/ui/gui/spokes/network.py:1192
msgid "WEP"
msgstr "WEP"

#: pyanaconda/ui/gui/spokes/network.py:1195
msgid "WPA"
msgstr "WPA"

#: pyanaconda/ui/gui/spokes/network.py:1198
msgid "WPA2"
msgstr "WPA2"

#: pyanaconda/ui/gui/spokes/network.py:1202
msgid "Enterprise"
msgstr "企業"

#: pyanaconda/ui/gui/spokes/network.py:1207 widgets/src/SpokeSelector.c:59
#: pyanaconda/ui/gui/spokes/filter.glade:145
#: pyanaconda/ui/gui/spokes/filter.glade:560
#: pyanaconda/ui/gui/spokes/filter.glade:894
#: pyanaconda/ui/gui/spokes/filter.glade:1214
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:535
msgid "None"
msgstr "なし"

#: pyanaconda/ui/gui/spokes/network.py:1339
#: pyanaconda/ui/gui/spokes/network.glade:2450
#, fuzzy
msgid "Authentication required by wireless network"
msgstr "認証が必要です"

#: pyanaconda/ui/gui/spokes/network.py:1340
#, python-format
msgid ""
"Passwords or encryption keys are required to access\n"
"the wireless network '%(network_id)s'."
msgstr ""

#: pyanaconda/ui/gui/spokes/network.py:1354
#, fuzzy
msgctxt "GUI|Network|Secrets Dialog"
msgid "_Password:"
msgstr "パスワード: "

#: pyanaconda/ui/gui/spokes/network.py:1362
msgctxt "GUI|Network|Secrets Dialog"
msgid "_Key:"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.py:1372
#, fuzzy
msgid "User name: "
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/network.py:1383
msgid "Identity: "
msgstr ""

#: pyanaconda/ui/gui/spokes/network.py:1388
#, fuzzy
msgid "Private key password: "
msgstr "パスワード: "

#: pyanaconda/ui/gui/spokes/network.py:1448
msgctxt "GUI|Spoke"
msgid "_NETWORK & HOST NAME"
msgstr ""

#: pyanaconda/ui/gui/spokes/password.py:56
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_ROOT PASSWORD"
msgstr "root パスワード"

#: pyanaconda/ui/gui/spokes/password.py:99
#: pyanaconda/ui/gui/spokes/password.py:100
#, fuzzy
msgid "The password is set."
msgstr "パスワードは設定されています"

#: pyanaconda/ui/gui/spokes/password.py:127
msgid "Root password is set"
msgstr "root パスワードは設定されています"

#: pyanaconda/ui/gui/spokes/password.py:129
msgid "Root account is disabled"
msgstr "root アカウントは無効になっています"

#: pyanaconda/ui/gui/spokes/password.py:131
msgid "Root password is not set"
msgstr "root パスワードが設定されていません"

#: pyanaconda/ui/gui/spokes/software.py:60
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_SOFTWARE SELECTION"
msgstr "ソフトウェアの選択"

#: pyanaconda/ui/gui/spokes/software.py:214
#: pyanaconda/ui/gui/spokes/source.py:569
msgid "Checking software dependencies..."
msgstr "ソフトウェアの依存関係をチェック中..."

#: pyanaconda/ui/gui/spokes/software.py:219
msgid "Error checking software dependencies"
msgstr "ソフトウェアの依存関係をチェック中にエラー"

#: pyanaconda/ui/gui/spokes/software.py:304
msgid "Invalid environment specified in kickstart"
msgstr ""

#: pyanaconda/ui/gui/spokes/software.py:317
#, fuzzy
msgid "Selected environment is not valid"
msgstr "ホスト名は無効です: %s"

#: pyanaconda/ui/gui/spokes/software.py:472
#, fuzzy
msgid ""
"Error checking software dependencies.  <a href=\"\">Click for details.</a>"
msgstr "ソフトウェアの依存関係のチェック中にエラー。クリックして詳細をみます。"

#: pyanaconda/ui/gui/spokes/software.py:579
#, fuzzy
msgid ""
"The software marked for installation has the following errors.  This is "
"likely caused by an error with your installation source.  You can quit the "
"installer, change your software source, or change your software selections."
msgstr ""
"インストール用にマークしてある以下のソフトウェアにエラーがあります。これはイ"
"ンストールソースが持つエラーが原因であるようです。これらのパッケージをインス"
"トールから除外するか、インストールソースを変えるか、またはインストーラーを終"
"了することができます。"

#: pyanaconda/ui/gui/spokes/software.py:584
#, fuzzy
msgctxt "GUI|Software Selection|Error Dialog"
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/spokes/software.py:585
#, fuzzy
msgctxt "GUI|Software Selection|Error Dialog"
msgid "_Modify Software Source"
msgstr "ソフトウェア提供元を修正(_M)"

#: pyanaconda/ui/gui/spokes/software.py:586
#, fuzzy
msgctxt "GUI|Software Selection|Error Dialog"
msgid "Modify _Selections"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/ui/gui/spokes/source.py:61
msgid "Setting up installation source..."
msgstr "インストールソースをセットアップ中..."

#: pyanaconda/ui/gui/spokes/source.py:81
msgid " <a href=\"\">Click for details.</a>"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:92
msgid "Invalid proxy URL"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:97
#, python-format
msgid "Invalid proxy protocol: %s"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:103
msgid "Extra characters in proxy URL"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:107
#, fuzzy
msgid "Proxy authentication data duplicated"
msgstr "認証が必要です"

#: pyanaconda/ui/gui/spokes/source.py:261
msgid "This media is good to install from."
msgstr "このメディアは以下からのインストールに適切です。"

#: pyanaconda/ui/gui/spokes/source.py:263
msgid "This media is not good to install from."
msgstr "このメディアは以下からのインストールに不適切です。"

#: pyanaconda/ui/gui/spokes/source.py:390
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_INSTALLATION SOURCE"
msgstr "インストールソース"

#: pyanaconda/ui/gui/spokes/source.py:510
#, fuzzy
msgid "Failed to set up installation source; check the repo url"
msgstr ""
"インストールソースの設定に失敗しました。レポジトリの url を確認して下さい"

#: pyanaconda/ui/gui/spokes/source.py:573
#, fuzzy
msgid "Error setting up base repository"
msgstr "リポジトリーの設定中にエラー"

#: pyanaconda/ui/gui/spokes/source.py:584
#, fuzzy
msgid "Error setting up ISO file"
msgstr "ソフトウェアソースの設定でエラー"

#: pyanaconda/ui/gui/spokes/source.py:717
#, fuzzy
msgid "Failed to set up installation source; check the repo url."
msgstr ""
"インストールソースの設定に失敗しました。レポジトリの url を確認して下さい"

#: pyanaconda/ui/gui/spokes/source.py:719
#, fuzzy
msgid ""
"Failed to set up installation source; check the repo url and proxy settings."
msgstr ""
"インストールソースの設定に失敗しました。レポジトリの url とプロキシの設定を確"
"認して下さい"

#: pyanaconda/ui/gui/spokes/source.py:751
#, fuzzy, python-format
msgid "Device: %s"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/source.py:752
#, python-format
msgid "Label: %s"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:912
msgid "You need to configure the network to use a network installation source."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:983
#, python-format
msgid "Repository %s has empty url"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:985
msgid "URL is empty"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:990
#, python-format
msgid "Repository %s has invalid url"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:992
msgid "Invalid URL"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:999
#, python-format
msgid "Repository %s does not match selected protocol"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:1001
msgid "Protocol in URL does not match selected protocol"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:1005
#, python-format
msgid "Repository %s has empty NFS server"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:1007
#, fuzzy
msgid "NFS server is empty"
msgstr "NFS サーバー %s"

#: pyanaconda/ui/gui/spokes/source.py:1015
#, fuzzy, python-format
msgid "Repository %s has invalid host name"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/source.py:1017
#, fuzzy
msgid "Invalid host name"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/source.py:1021
#, python-format
msgid "Repository %s required remote directory"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:1023
msgid "Remote directory is required"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:1044
msgid "Duplicate repository names."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.py:1052
#, fuzzy
msgid "Empty repository name"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/source.py:1055
#, fuzzy
msgid "Invalid repository name"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/source.py:1061
msgid "Repository name conflicts with internal repository name."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:123
msgid "Please wait... software metadata still loading."
msgstr "少々お待ち下さい... ソフトウェアのメタデータがまだロード中です。"

#: pyanaconda/ui/gui/spokes/storage.py:126
#, fuzzy, python-format
msgid ""
"Your current <b>%(product)s</b> software selection requires <b>%(total)s</b> "
"of available space, including <b>%(software)s</b> for software and <b>"
"%(swap)s</b> for swap space."
msgstr ""
"現在の <b>%s</b> のソフトウェア選択には、利用可能な領域の <b>%s</b> が必要で"
"す。"

#: pyanaconda/ui/gui/spokes/storage.py:135
#, python-format
msgid ""
"Your current <a href=\"\" title=\"%(tooltip)s\"><b>%(product)s</b> software "
"selection</a> requires <b>%(total)s</b> of available space, including <b>"
"%(software)s</b> for software and <b>%(swap)s</b> for swap space."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:185
#, fuzzy, python-format
msgid "%s The disks you've selected have the following amounts of free space:"
msgstr ""
"%s\n"
"選択したディスクには、以下の容量の空き領域があります:"

#: pyanaconda/ui/gui/spokes/storage.py:195
#, fuzzy, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>.  You can shrink "
"or remove existing partitions via our guided reclaim space tool, or you can "
"adjust your partitions on your own in the custom partitioning interface."
msgstr ""
"<b>%s をインストールするには利用可能領域が足りませんが、</b>既存パーティショ"
"ンを縮小したり、削除したりして領域を取り戻すことができます。"

#: pyanaconda/ui/gui/spokes/storage.py:219
#, fuzzy, python-format
msgid ""
"  You don't have enough space available to install <b>%(product)s</b>, even "
"if you used all of the free space available on the selected disks."
msgstr ""
"%s\n"
"選択したディスクで利用できるすべての空き領域を使用しても、<b>%s</b> のインス"
"トールには十分な領域がありません。"

#: pyanaconda/ui/gui/spokes/storage.py:231
#, fuzzy, python-format
msgid ""
"<b>You don't have enough space available to install %(productName)s</b>, "
"even if you used all of the free space available on the selected disks.  You "
"could add more disks for additional space, modify your software selection to "
"install a smaller version of <b>%(productName)s</b>, or quit the installer."
msgstr ""
"選択したディスクで利用できるすべての空き領域を使用しても、<b>%s のインストー"
"ルには十分な領域がありません。</b> 更なる領域の為に他のディスクを追加するか、"
"小さいバージョンの <b>%s</b> をインストールするためにソフトウェア選択を修正す"
"るか、またはインストーラーを終了することができます。"

#: pyanaconda/ui/gui/spokes/storage.py:256
#, fuzzy
msgctxt "GUI|Spoke"
msgid "INSTALLATION _DESTINATION"
msgstr "インストール先"

#: pyanaconda/ui/gui/spokes/storage.py:345
msgid "Saving storage configuration..."
msgstr "ストレージ設定を保存しています..."

#: pyanaconda/ui/gui/spokes/storage.py:348
msgid "Passphrase for autopart encryption not specified."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:357
#: pyanaconda/ui/gui/spokes/storage.py:369
msgid "Failed to save storage configuration..."
msgstr "ストレージ設定の保存に失敗しました..."

#: pyanaconda/ui/gui/spokes/storage.py:406
#: pyanaconda/ui/gui/spokes/storage.py:707
#, fuzzy
msgid "Formatting DASDs"
msgstr "DASD デバイスをフォーマット中..."

#: pyanaconda/ui/gui/spokes/storage.py:556
#, fuzzy
msgid ""
"Error checking storage configuration.  <a href=\"\">Click for details.</a>"
msgstr "ストレージ設定のチェックでエラー発生。クリックして詳細を見ます。"

#: pyanaconda/ui/gui/spokes/storage.py:558
#, fuzzy
msgid ""
"Warning checking storage configuration.  <a href=\"\">Click for details.</a>"
msgstr "ストレージ設定のチェックでエラー発生。クリックして詳細を見ます。"

#: pyanaconda/ui/gui/spokes/storage.py:599
#, python-format
msgid ""
"FCP device %(hba_id)s\n"
"WWPN %(wwpn)s\n"
"LUN %(lun)s"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:609
#, fuzzy, python-format
msgid "%s free"
msgstr "fs free"

#: pyanaconda/ui/gui/spokes/storage.py:656
#, fuzzy, python-format
msgid "%(count)d disk selected; %(capacity)s capacity; %(free)s free"
msgid_plural "%(count)d disks selected; %(capacity)s capacity; %(free)s free"
msgstr[0] "選択されたディスク数 %d; 容量 %s; 空き領域 %s"

#: pyanaconda/ui/gui/spokes/storage.py:740
#, fuzzy
msgid ""
"You have chosen to skip boot loader installation.  Your system may not be "
"bootable."
msgstr ""
"ブートローダーのインストールを省略するよう選択しています。 システムが起動不可"
"になる可能性があります。"

#: pyanaconda/ui/gui/spokes/storage.py:913
msgid "There was a problem with your disk selection. Click here for details."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:1006
msgid "You'll be able to make space available during custom partitioning."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:1022
#, fuzzy
msgid ""
"The following errors were encountered when checking your disk selection. You "
"can modify your selection or quit the installer."
msgstr ""
"ストレージ設定をチェック中に以下のエラーに遭遇しました。ストレージレイアウト"
"を変更するか、またはインストーラーを終了することが出来ます。"

#: pyanaconda/ui/gui/spokes/storage.py:1027
#: pyanaconda/ui/gui/spokes/storage.py:1048
#, fuzzy
msgctxt "GUI|Storage|Error Dialog"
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/spokes/storage.py:1028
#, fuzzy
msgctxt "GUI|Storage|Error Dialog"
msgid "_Modify Disk Selection"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/ui/gui/spokes/storage.py:1043
#, fuzzy
msgid ""
"The following errors were encountered when checking your storage "
"configuration.  You can modify your storage layout or quit the installer."
msgstr ""
"ストレージ設定をチェック中に以下のエラーに遭遇しました。ストレージレイアウト"
"を変更するか、またはインストーラーを終了することが出来ます。"

#: pyanaconda/ui/gui/spokes/storage.py:1049
#, fuzzy
msgctxt "GUI|Storage|Error Dialog"
msgid "_Modify Storage Layout"
msgstr "ストレージの構成変更(_M)"

#: pyanaconda/ui/gui/spokes/storage.py:1063
#, fuzzy
msgid ""
"The following warnings were encountered when checking your storage "
"configuration.  These are not fatal, but you may wish to make changes to "
"your storage layout."
msgstr ""
"ストレージ設定をチェック中に以下のエラーに遭遇しました。ストレージレイアウト"
"を変更するか、またはインストーラーを終了することが出来ます。"

#: pyanaconda/ui/gui/spokes/storage.py:1068
#, fuzzy
msgctxt "GUI|Storage|Warning Dialog"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/user.py:65
#, python-format
msgid "Invalid group name: %s"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.py:242
#, fuzzy
msgctxt "GUI|Spoke"
msgid "_USER CREATION"
msgstr "ユーザーの設定"

#: pyanaconda/ui/gui/spokes/user.py:334
#, fuzzy
msgid "Invalid user name"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/user.py:336
msgid "Full name cannot contain colon characters"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.py:348 pyanaconda/ui/gui/spokes/user.py:349
msgid "The password was set by kickstart."
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.py:262
#, fuzzy, python-format
msgid "WELCOME TO %(name)s %(version)s."
msgstr "%s %s へようこそ。"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.py:282
#, python-format
msgid ""
"The following nodes were discovered using the iSCSI initiator <b>"
"%(initiatorName)s</b> using the target IP address <b>%(targetAddress)s</b>.  "
"Please select which nodes you wish to log into:"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/accordion.py:162
msgid "DATA"
msgstr "データ"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:288
#, fuzzy, python-format
msgid ""
"You haven't created any mount points for your %(product)s %(version)s "
"installation yet.  You can:"
msgstr "%s %s インストール用のマウントポイントをまだ選択していません:"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:298
#, fuzzy
msgctxt "GUI|Custom Partitioning|Autopart Page"
msgid "_Click here to create them automatically."
msgstr "ここをクリックすると自動的に作成します。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:323
#, fuzzy
msgid "Create new mount points by clicking the '+' button."
msgstr "あるいは、'+' アイコンで以下に新規のマウントポイントを作成します。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:331
msgid ""
"Or, assign new mount points to existing partitions after selecting them "
"below."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/accordion.py:336
msgctxt "GUI|Custom Partitioning|Autopart Page"
msgid "_New mount points will use the following partitioning scheme:"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/cart.py:134
#, fuzzy, python-format
msgid ""
"<b>%(count)d disk; %(size)s capacity; %(free)s free space</b> (unpartitioned "
"and in file systems)"
msgid_plural ""
"<b>%(count)d disks; %(size)s capacity; %(free)s free space</b> "
"(unpartitioned and in file systems)"
msgstr[0] ""
"<b>ディスク数 %d; 容量%s ; 空き領域 %s</b> (パーティション未設定でファイルシ"
"ステム内)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:193
#, fuzzy
msgctxt "GUI|Selected Disks Dialog"
msgid "_Do not install boot loader"
msgstr "ブートローダーをインストールしない(_D)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:196
#: pyanaconda/ui/gui/spokes/lib/cart.glade:183
#, fuzzy
msgctxt "GUI|Selected Disks Dialog"
msgid "_Set as Boot Device"
msgstr "起動デバイスとして設定(_S)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:63
#, fuzzy, python-format
msgid ""
"The RAID level you have selected (%(level)s) requires more disks (%(min)d) "
"than you currently have selected (%(count)d)."
msgstr ""
"選択した RAID レベルには現在選択している領域より大きな領域が必要になります。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:67
#, python-format
msgid "CONFIGURE %(container_type)s"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:68
#, fuzzy, python-format
msgid ""
"Please create a name for this %(container_type)s and select at least one "
"disk below."
msgstr ""
"ボリュームグループ名を決めて作成し、以下から少なくても1つのディスクを選択して"
"ください。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:73
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:74
#, fuzzy
msgid "Volume Group"
msgstr "ボリュームグループ:"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:73
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:74
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Volume Group:"
msgstr "ボリュームグループ:"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:75
#, fuzzy
msgid "Volume"
msgstr "列"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:75
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Volume:"
msgstr "列"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:135
#, fuzzy
msgid "Cannot relabel already existing file system."
msgstr "マウントポイント %s は linux ファイルシステム上にある必要があります。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:140
#, fuzzy
msgid "Cannot set label on file system."
msgstr "マウントポイント %s は linux ファイルシステム上にある必要があります。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:142
#, fuzzy
msgid "Unacceptable label format for file system."
msgstr "マウントポイント %s は linux ファイルシステム上にある必要があります。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:152
msgid "That mount point is already in use. Try something else?"
msgstr "そのマウントポイントはすでに使用中です。他を試しますか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:154
#, fuzzy
msgid "Please enter a valid mount point."
msgstr "有効なマウントポイントを記入して下さい"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:156
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:168
msgid "That mount point is invalid. Try something else?"
msgstr "そのマウントポイントは無効です。他を試しますか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:309
msgid "container"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:309
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "container"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:387
#, fuzzy, python-format
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "Delete _all other file systems in the %s root as well."
msgstr "%s root にある他のファイルシステムもすべて削除されます。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:390
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "(This includes those shared with other installed operating systems.)"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:402
#, python-format
msgid "Are you sure you want to delete all of the data on %s?"
msgstr "%s にある全データを本当に削除してもよいですか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:404
#, fuzzy, python-format
msgid ""
"Are you sure you want to delete all of the data on %s, including snapshots "
"and/or subvolumes?"
msgstr "%s にある全データを本当に削除してもよいですか?"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.py:704
#, fuzzy
msgid "Invalid container name"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/lib/detailederror.py:49
#, fuzzy
msgctxt "GUI|Detailed Error Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:38
#, python-format
msgid "You have provided a weak passphrase: %s"
msgstr "脆弱なパスフレーズを記入しています: %s"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:39
msgid "Passphrases do not match."
msgstr "パスフレーズが一致しません。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:187
msgid "Passphrase contains non-ASCII characters"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/resize.py:57
msgid "Preserve"
msgstr "保存"

#: pyanaconda/ui/gui/spokes/lib/resize.py:58
msgid "Shrink"
msgstr "縮小"

#: pyanaconda/ui/gui/spokes/lib/resize.py:59
msgid "Delete"
msgstr "削除"

#: pyanaconda/ui/gui/spokes/lib/resize.py:118
msgid "This device contains the installation source."
msgstr "インストールソースが含まれているデバイス"

#: pyanaconda/ui/gui/spokes/lib/resize.py:164
#, fuzzy, python-format
msgid "%(freeSize)s of %(devSize)s"
msgstr "%(device)s 上に %(type)s を作成"

#: pyanaconda/ui/gui/spokes/lib/resize.py:171
#, fuzzy
msgid "Not resizeable"
msgstr "準備できていません"

#: pyanaconda/ui/gui/spokes/lib/resize.py:195
#, fuzzy
msgid "Free space"
msgstr "空き領域を使用する"

#: pyanaconda/ui/gui/spokes/lib/resize.py:217
#, fuzzy
msgid ""
"You can remove existing file systems you no longer need to free up space for "
"this installation.  Removing a file system will permanently delete all of "
"the data it contains."
msgstr ""
"このインストールに十分な空き領域がありません。\n"
"\n"
"必要の無い既存ファイルシステムを削除してこのインストール用に空き領域を得るこ"
"とができます。　\n"
"ファイルシステムを削除するとそこに収納してあるすべてのデータを永久に喪失しま"
"す。"

#: pyanaconda/ui/gui/spokes/lib/resize.py:223
msgid ""
"There is also free space available in pre-existing file systems.  While it's "
"risky and we recommend you back up your data first, you can recover that "
"free disk space and make it available for this installation below."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/resize.py:233
#, fuzzy, python-format
msgid "<b>%(count)s disk; %(size)s reclaimable space</b> (in file systems)"
msgid_plural ""
"<b>%(count)s disks; %(size)s reclaimable space</b> (in file systems)"
msgstr[0] "<b>%s 個のディスク; %s つの獲得可能領域</b> (ファイルシステム内) "

#: pyanaconda/ui/gui/spokes/lib/resize.py:240
#, python-format
msgid "Total selected space to reclaim: <b>%s</b>"
msgstr "選択した獲得する領域合計: <b>%s</b>"

#: pyanaconda/ui/gui/spokes/lib/resize.py:455
#: pyanaconda/ui/gui/spokes/lib/resize.py:460
#: pyanaconda/ui/gui/spokes/lib/resize.glade:269
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "Delete _all"
msgstr "削除"

#: pyanaconda/ui/gui/spokes/lib/resize.py:457
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "Preserve _all"
msgstr "保存"

#: pyanaconda/ui/gui/spokes/lib/summary.py:54
#, python-format
msgid "%(description)s (%(deviceName)s)"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/summary.py:58
#, python-format
msgid "%(deviceName)s on %(container)s"
msgstr ""

#: widgets/src/BaseWindow.c:111
msgid "DISTRIBUTION INSTALLATION"
msgstr "ディストリビューションのインストール"

#: widgets/src/BaseWindow.c:112
msgid "SPOKE NAME"
msgstr "スポーク名"

#: widgets/src/BaseWindow.c:113
msgid "PRE-RELEASE / TESTING"
msgstr "プレリリース / テスト中"

#: widgets/src/DiskOverview.c:56
msgid "New Device"
msgstr "新しいデバイス"

#: widgets/src/DiskOverview.c:58 widgets/src/DiskOverview.c:59
msgid "0 MB"
msgstr "0 MB"

#: widgets/src/MountpointSelector.c:55
msgid "0 GB"
msgstr "0 GB"

#: widgets/src/SpokeSelector.c:60
msgid "New Selector"
msgstr "新しいセレクター"

#: widgets/src/SpokeWindow.c:48
#, fuzzy
msgctxt "GUI|Spoke Navigation"
msgid "_Done"
msgstr "完了(_D)"

#: widgets/src/StandaloneWindow.c:54
#, fuzzy
msgctxt "GUI|Standalone Navigation"
msgid "_Quit"
msgstr "終了する (_Q)"

#: widgets/src/StandaloneWindow.c:55
#, fuzzy
msgctxt "GUI|Standalone Navigation"
msgid "_Continue"
msgstr "続行(_C)"

#: widgets/src/LayoutIndicator.c:34
#, c-format
msgid "Current layout: '%s'. Click to switch to the next layout."
msgstr ""

#: widgets/src/LayoutIndicator.c:35
#, c-format
msgid "Current layout: '%s'. Add more layouts to enable switching."
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:36
#, fuzzy
msgctxt "GUI|Advanced User"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advanced_user.glade:50
#, fuzzy
msgctxt "GUI|Advanced User"
msgid "_Save Changes"
msgstr "変更を適用(_A)"

#: pyanaconda/ui/gui/spokes/advanced_user.glade:82
#, fuzzy
msgid "ADVANCED USER CONFIGURATION"
msgstr "ネットワーク設定"

#: pyanaconda/ui/gui/spokes/advanced_user.glade:105
msgctxt "GUI|Advanced User"
msgid "Home _directory:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:140
msgid "User and Group IDs"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:160
msgctxt "GUI|Advanced User"
msgid "Specify a _user ID manually:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:177
msgctxt "GUI|Advanced User"
msgid "Specify a _group ID manually:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:237
#, fuzzy
msgid "Group Membership"
msgstr "グループ名"

#: pyanaconda/ui/gui/spokes/advanced_user.glade:265
msgctxt "GUI|Advanced User"
msgid "_Add user to the following groups:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:298
msgid "Example:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:315
msgid "wheel, my-team (1245), project-x (29935)"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:348
msgid "Tip:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advanced_user.glade:367
msgid ""
"You may input a comma-separated list of group names and group IDs here. "
"Groups that do not already exist will be created; specify their GID in "
"parentheses. "
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:110
#, fuzzy
msgctxt "GUI|Date and Time|NTP"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:124
#, fuzzy
msgctxt "GUI|Date and Time|NTP"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:149
msgid "Add and mark for usage NTP servers"
msgstr "NTP サーバーの使用法を追加してマークする"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:171
#, fuzzy
msgid "New NTP Server"
msgstr "Web サーバー"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:190
msgid "Add NTP Server"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:210
#, fuzzy
msgid "This URL refers to a pool of NTP servers"
msgstr "この URL はミラーリストを参照します。"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:256
msgid "Pool"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:269
msgid "Working"
msgstr "稼働中"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:277
msgid "Use"
msgstr "使用"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:305
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:519
#, fuzzy
msgid "Configure NTP"
msgstr "設定する(_C)..."

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:326
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:934
#, fuzzy
msgid "TIME & DATE"
msgstr "日付と時刻"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:376
#, fuzzy
msgctxt "GUI|Date and Time"
msgid "_Region:"
msgstr "地域:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:406
#, fuzzy
msgid "Region"
msgstr "地域:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:423
#, fuzzy
msgctxt "GUI|Date and Time"
msgid "_City:"
msgstr "都市:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:453
#, fuzzy
msgid "City"
msgstr "都市:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:481
#, fuzzy
msgctxt "GUI|Date and Time"
msgid "_Network Time"
msgstr "ネットワーク名(_N)"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:499
#, fuzzy
msgid "Use Network Time"
msgstr "ネットワーク名"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:586
msgid "Hours"
msgstr ""

#. TRANSLATORS: This is the separator between hours and minutes, like in HH:MM
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:599
#, fuzzy
msgctxt "GUI|Date and Time"
msgid ":"
msgstr ":"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:619
msgid "Minutes"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:637
msgid "Hour Up"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:655
msgid "Hour Down"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:673
msgid "Minutes Up"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:691
msgid "Minutes Down"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:735
#, fuzzy
msgid "AM/PM Up"
msgstr "AM/PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:771
#, fuzzy
msgid "AM/PM Down"
msgstr "AM/PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:822
#, fuzzy
msgctxt "GUI|Date and Time"
msgid "24-_hour"
msgstr "24 時間"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:840
#, fuzzy
msgctxt "GUI|Date and Time"
msgid "_AM/PM"
msgstr "AM/PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:899
msgid "Set Date & Time"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:60
#: pyanaconda/ui/gui/spokes/storage.glade:444
#: pyanaconda/ui/gui/spokes/storage.glade:1024
msgid "INSTALLATION DESTINATION"
msgstr "インストール先"

#: pyanaconda/ui/gui/spokes/filter.glade:129
msgctxt "GUI|Installation Destination|Filter|Search"
msgid "Search _By:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:146
msgid "Port / Target / LUN #"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:147
msgid "Target WWID"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:186
msgctxt "GUI|Installation Destination|Filter|Search|Port Target LUN"
msgid "_Port:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:212
msgctxt "GUI|Installation Destination|Filter|Search|Port Target LUN"
msgid "_Target:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:241
msgctxt "GUI|Installation Destination|Filter|Search|Port Target LUN"
msgid "_LUN:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:283
msgctxt "GUI|Installation Destination|Filter|Search|WWID"
msgid "_WWID:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:333
msgctxt "GUI|Installation Destination|Filter|Search"
msgid "Search Res_ults:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:380
#: pyanaconda/ui/gui/spokes/filter.glade:1438
#: pyanaconda/ui/gui/spokes/keyboard.glade:519
#: pyanaconda/ui/gui/spokes/source.glade:988
#: pyanaconda/ui/gui/spokes/lib/cart.glade:133
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:235
#: pyanaconda/ui/gui/spokes/lib/resize.glade:163
msgid "Name"
msgstr "名前"

#: pyanaconda/ui/gui/spokes/filter.glade:394
#: pyanaconda/ui/gui/spokes/filter.glade:563
#: pyanaconda/ui/gui/spokes/filter.glade:766
msgid "WWID"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:408
#: pyanaconda/ui/gui/spokes/filter.glade:780
#: pyanaconda/ui/gui/spokes/filter.glade:1114
#: pyanaconda/ui/gui/spokes/filter.glade:1466
#: pyanaconda/ui/gui/spokes/lib/cart.glade:145
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:248
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:732
msgid "Capacity"
msgstr "容量"

#: pyanaconda/ui/gui/spokes/filter.glade:422
#: pyanaconda/ui/gui/spokes/filter.glade:562
#: pyanaconda/ui/gui/spokes/filter.glade:808
#: pyanaconda/ui/gui/spokes/filter.glade:896
#: pyanaconda/ui/gui/spokes/filter.glade:1142
#, fuzzy
msgid "Interconnect"
msgstr "接続していません"

#: pyanaconda/ui/gui/spokes/filter.glade:436
msgid "Model"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:450
#: pyanaconda/ui/gui/spokes/filter.glade:1217
#: pyanaconda/ui/gui/spokes/filter.glade:1494
msgid "LUN"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:464
#: pyanaconda/ui/gui/spokes/filter.glade:1508
msgid "Port"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:478
msgid "Target"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:492
#: pyanaconda/ui/gui/spokes/filter.glade:561
#: pyanaconda/ui/gui/spokes/filter.glade:794
#: pyanaconda/ui/gui/spokes/filter.glade:895
#: pyanaconda/ui/gui/spokes/filter.glade:1128
msgid "Vendor"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:519
msgctxt "GUI|Installation Destination|Filter"
msgid "Searc_h"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:544
msgctxt "GUI|Installation Destination|Filter|Multipath"
msgid "Filter _By:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:601
msgctxt "GUI|Installation Destination|Filter|Multipath|Vendor"
msgid "Show Only _Devices From:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:642
msgctxt "GUI|Installation Destination|Filter|Multipath|Interconnect"
msgid "Show Only _Devices With:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:683
msgctxt "GUI|Installation Destination|Filter|Multipath|WWID"
msgid "Show Only _Devices Containing:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:822
msgid "Paths"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:852
msgctxt "GUI|Installation Destination|Filter"
msgid "_Multipath Devices"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:878
msgctxt "GUI|Installation Destination|Filter|Other"
msgid "Filter _By:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:897
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:758
msgid "ID"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/filter.glade:935
msgctxt "GUI|Installation Destination|Filter|Other|Vendor"
msgid "Show Only _Devices From:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:976
msgctxt "GUI|Installation Destination|Filter|Other|Interconnect"
msgid "Show Only _Devices With:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1017
msgctxt "GUI|Installation Destination|Filter|Other|ID"
msgid "Show Only _Devices Containing:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1100
msgid "Identifier"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1172
#, fuzzy
msgctxt "GUI|Installation Destination|Filter"
msgid "_Other SAN Devices"
msgstr "選択したデバイス"

#: pyanaconda/ui/gui/spokes/filter.glade:1198
msgctxt "GUI|Installation Destination|Filter|zSeries"
msgid "Filter B_y:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1215
#: pyanaconda/ui/gui/spokes/filter.glade:1424
msgid "CCW"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1216
#: pyanaconda/ui/gui/spokes/filter.glade:1480
msgid "WWPN"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1254
msgctxt "GUI|Installation Destination|Filter|zSeries|CCW"
msgid "_CCW:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1297
msgctxt "GUI|Installation Destination|Filter|zSeries|WWPN"
msgid "_WWPN:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1341
msgctxt "GUI|Installation Destination|Filter|zSeries|LUN"
msgid "_LUN:"
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1452
#: pyanaconda/ui/gui/spokes/lib/summary.glade:155
#, fuzzy
msgid "Type"
msgstr "VPN タイプ"

#: pyanaconda/ui/gui/spokes/filter.glade:1538
#, fuzzy
msgctxt "GUI|Installation Destination|Filter"
msgid "_zSeries Devices"
msgstr "選択したデバイス"

#: pyanaconda/ui/gui/spokes/filter.glade:1561
msgctxt "GUI|Installation Destination|Filter"
msgid "_Add zFCP LUN..."
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1576
msgctxt "GUI|Installation Destination|Filter"
msgid "Add EC_KD DASD..."
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1591
msgctxt "GUI|Installation Destination|Filter"
msgid "Add _iSCSI Target..."
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1606
msgctxt "GUI|Installation Destination|Filter"
msgid "Add FCo_E SAN..."
msgstr ""

#: pyanaconda/ui/gui/spokes/filter.glade:1621
msgctxt "GUI|Installation Destination|Filter"
msgid "Refresh _List"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:35
#, fuzzy
msgid "Add device"
msgstr "RAID デバイス"

#: pyanaconda/ui/gui/spokes/network.glade:49
#, fuzzy
msgctxt "GUI|Network|Add Device Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/network.glade:63
#, fuzzy
msgctxt "GUI|Network|Add Device Dialog"
msgid "_Add"
msgstr "追加(_A)"

#: pyanaconda/ui/gui/spokes/network.glade:92
msgctxt "GUI|Network|Add Device Dialog"
msgid "_Select the type of device you wish to add"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:167
#: pyanaconda/ui/gui/spokes/network.glade:2285
msgid "NETWORK & HOST NAME"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:206
msgid ""
"Please use the live desktop environment's tools for customizing your network "
"configuration.  You can set the host name here."
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:420
msgid "Slaves"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:444
#: pyanaconda/ui/gui/spokes/network.glade:880
#: pyanaconda/ui/gui/spokes/network.glade:1447
msgid "DNS"
msgstr "DNS"

#: pyanaconda/ui/gui/spokes/network.glade:470
#: pyanaconda/ui/gui/spokes/network.glade:867
#: pyanaconda/ui/gui/spokes/network.glade:1434
msgid "Default Route"
msgstr "デフォルトルート"

#: pyanaconda/ui/gui/spokes/network.glade:494
msgid "Subnet Mask"
msgstr "サブネットマスク"

#: pyanaconda/ui/gui/spokes/network.glade:566
#: pyanaconda/ui/gui/spokes/network.glade:831
#: pyanaconda/ui/gui/spokes/network.glade:1278
msgid "Speed"
msgstr "速度"

#: pyanaconda/ui/gui/spokes/network.glade:590
#: pyanaconda/ui/gui/spokes/network.glade:819
msgid "Hardware Address"
msgstr "ハードウェアアドレス"

#: pyanaconda/ui/gui/spokes/network.glade:614
msgid "Parent"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:626
msgid "VLAN ID"
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:701
#, fuzzy
msgctxt "GUI|Network|Wired"
msgid "_Configure..."
msgstr "設定する(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade:705
msgid "To apply the configuration immediately turn the device off and on."
msgstr ""

#: pyanaconda/ui/gui/spokes/network.glade:992
msgid "Security"
msgstr "セキュリティ"

#: pyanaconda/ui/gui/spokes/network.glade:1004
#, fuzzy
msgctxt "GUI|Network|Wireless"
msgid "_Network Name"
msgstr "ネットワーク名(_N)"

#: pyanaconda/ui/gui/spokes/network.glade:1018
msgid "Network Name"
msgstr "ネットワーク名"

#: pyanaconda/ui/gui/spokes/network.glade:1030
msgid "Security Key"
msgstr "セキュリティキー"

#: pyanaconda/ui/gui/spokes/network.glade:1113
#, fuzzy
msgctxt "GUI|Network|Wireless"
msgid "_Use as Hotspot..."
msgstr "ホットスポットとして使用する(_U)..."

#: pyanaconda/ui/gui/spokes/network.glade:1130
#, fuzzy
msgctxt "GUI|Network|Wireless"
msgid "_Stop Hotspot..."
msgstr "ホットスポットを停止する(_S)..."

#: pyanaconda/ui/gui/spokes/network.glade:1147
#, fuzzy
msgctxt "GUI|Network|Wireless"
msgid "_Configure..."
msgstr "設定する(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade:1266
msgid "IMEI"
msgstr "IMEI"

#: pyanaconda/ui/gui/spokes/network.glade:1290
msgid "Provider"
msgstr "プロバイダー"

#: pyanaconda/ui/gui/spokes/network.glade:1472
#, fuzzy
msgctxt "GUI|Network|Mobile Broadband"
msgid "_Configure..."
msgstr "設定する(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade:1583
msgid "VPN Type"
msgstr "VPN タイプ"

#: pyanaconda/ui/gui/spokes/network.glade:1595
msgid "Gateway"
msgstr "ゲートウェイ"

#: pyanaconda/ui/gui/spokes/network.glade:1607
msgid "Group Name"
msgstr "グループ名"

#: pyanaconda/ui/gui/spokes/network.glade:1619
msgid "Group Password"
msgstr "グループパスワード"

#: pyanaconda/ui/gui/spokes/network.glade:1631
#: pyanaconda/ui/gui/spokes/user.glade:116
#, fuzzy
msgid "User Name"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/network.glade:1738
#, fuzzy
msgctxt "GUI|Network|VPN"
msgid "_Configure..."
msgstr "設定する(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade:1861
#, fuzzy
msgctxt "GUI|Network|Proxy"
msgid "_Method"
msgstr "メソッド(_M)"

#: pyanaconda/ui/gui/spokes/network.glade:1886
#, fuzzy
msgctxt "GUI|Network|Proxy"
msgid "_Configuration URL"
msgstr "設定の URL(_C)"

#: pyanaconda/ui/gui/spokes/network.glade:1911
#, fuzzy
msgctxt "GUI|Network|Proxy"
msgid "HTTP _Proxy"
msgstr "HTTP プロキシ(_H)"

#: pyanaconda/ui/gui/spokes/network.glade:1925
#, fuzzy
msgctxt "GUI|Network|Proxy"
msgid "H_TTPS Proxy"
msgstr "HTTPS プロキシ(_T)"

#: pyanaconda/ui/gui/spokes/network.glade:1939
#, fuzzy
msgctxt "GUI|Network|Proxy"
msgid "_FTP Proxy"
msgstr "FTP プロキシ(_F)"

#: pyanaconda/ui/gui/spokes/network.glade:1953
#, fuzzy
msgctxt "GUI|Network|Proxy"
msgid "_Socks Host"
msgstr "Socks ホスト(_S)"

#: pyanaconda/ui/gui/spokes/network.glade:2142
#, fuzzy
msgid "Network Config Box"
msgstr "ネットワーク構成を書き込み中"

#: pyanaconda/ui/gui/spokes/network.glade:2158
#, fuzzy
msgctxt "GUI|Network"
msgid "Unloc_k"
msgstr "ロックを解除する"

#: pyanaconda/ui/gui/spokes/network.glade:2191
#, fuzzy
msgctxt "GUI|Network"
msgid "_Airplane Mode"
msgstr "航空機内モード(_P)"

#: pyanaconda/ui/gui/spokes/network.glade:2211
#, fuzzy
msgid "More Network Config Box"
msgstr "ネットワーク構成を書き込み中"

#: pyanaconda/ui/gui/spokes/network.glade:2231
#, fuzzy
msgctxt "GUI|Network"
msgid "_Host Name:"
msgstr "ホスト名:"

#: pyanaconda/ui/gui/spokes/network.glade:2291
msgid "NETWORK CONFIGURATION"
msgstr "ネットワーク設定"

#: pyanaconda/ui/gui/spokes/network.glade:2336
msgid ""
"We'll need network access to fetch information about your location and to "
"make software\n"
"updates available for you."
msgstr ""
"ユーザーの位置情報の取得およびソフトウェア更新を取得可能にするためネットワー"
"クアクセスが必要です。"

#: pyanaconda/ui/gui/spokes/network.glade:2366
#, fuzzy
msgid "Authentication"
msgstr "認証の使用(_U)"

#: pyanaconda/ui/gui/spokes/network.glade:2380
#, fuzzy
msgctxt "GUI|Network|Authentication Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/network.glade:2395
#, fuzzy
msgctxt "GUI|Network|Authentication Dialog"
msgid "C_onnect"
msgstr "接続済みです"

#: pyanaconda/ui/gui/spokes/network.glade:2469
msgid ""
"Passwords or encryption keys are required to access\n"
"the wireless network"
msgstr ""

#: pyanaconda/ui/gui/spokes/software.glade:10
msgid "SOFTWARE SELECTION"
msgstr "ソフトウェアの選択"

#: pyanaconda/ui/gui/spokes/software.glade:66
#, fuzzy
msgid "Base Environment"
msgstr "使用環境を選択します"

#: pyanaconda/ui/gui/spokes/software.glade:84
msgid "Add-Ons for Selected Environment"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:27
#, fuzzy
msgctxt "GUI|Storage|Need Space Dialog"
msgid "_Cancel & add more disks"
msgstr "取り消して、もっとディスクを追加(_A)"

#: pyanaconda/ui/gui/spokes/storage.glade:43
#, fuzzy
msgctxt "GUI|Storage|Need Space Dialog"
msgid "_Reclaim space"
msgstr "領域を確保する(_R)"

#: pyanaconda/ui/gui/spokes/storage.glade:78
#: pyanaconda/ui/gui/spokes/storage.glade:293
msgid "INSTALLATION OPTIONS"
msgstr "インストールオプション"

#: pyanaconda/ui/gui/spokes/storage.glade:95
#: pyanaconda/ui/gui/spokes/storage.glade:309
msgid ""
"Here we'll describe how much space is needed for the current software "
"selection."
msgstr "ここで、現在のソフトウェア選択に必要となる領域を説明します。"

#: pyanaconda/ui/gui/spokes/storage.glade:121
#: pyanaconda/ui/gui/spokes/storage.glade:335
msgid "disk free"
msgstr "disk free"

#: pyanaconda/ui/gui/spokes/storage.glade:137
#: pyanaconda/ui/gui/spokes/storage.glade:350
msgid "Free space available for use."
msgstr "使用できる空き領域"

#: pyanaconda/ui/gui/spokes/storage.glade:153
#: pyanaconda/ui/gui/spokes/storage.glade:366
msgid "fs free"
msgstr "fs free"

#: pyanaconda/ui/gui/spokes/storage.glade:169
#: pyanaconda/ui/gui/spokes/storage.glade:382
msgid "Free space unavailable but reclaimable from existing partitions."
msgstr ""
"現在利用できないものの、既存のパーティションから取り戻すことができる空き領域"

#: pyanaconda/ui/gui/spokes/storage.glade:192
#: pyanaconda/ui/gui/spokes/storage.glade:405
msgid "Here we'll describe what your options are."
msgstr "ここで、ユーザーのオプションを説明します。"

#: pyanaconda/ui/gui/spokes/storage.glade:219
#, fuzzy
msgid "Need Space"
msgstr "空き領域を使用する"

#: pyanaconda/ui/gui/spokes/storage.glade:242
#, fuzzy
msgctxt "GUI|Storage|No Space Dialog"
msgid "_Quit installer"
msgstr "インストーラーを終了(_Q)"

#: pyanaconda/ui/gui/spokes/storage.glade:258
#, fuzzy
msgctxt "GUI|Storage|No Space Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/storage.glade:432
msgid "No Space"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:507
#, fuzzy
msgid "Device Selection"
msgstr "デバイスの説明"

#: pyanaconda/ui/gui/spokes/storage.glade:526
msgid ""
"Select the device(s) you'd like to install to.  They will be left untouched "
"until you click on the main menu's \"Begin Installation\" button."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:544
msgid "Local Standard Disks"
msgstr "ローカルの標準ディスク"

#: pyanaconda/ui/gui/spokes/storage.glade:608
#: pyanaconda/ui/gui/spokes/storage.glade:748
msgid "Disks left unselected here will not be touched."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:627
msgid "Specialized & Network Disks"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:697
msgctxt "GUI|Storage"
msgid "_Add a disk..."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:714
msgid "Add Specialized Disk"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:767
msgid "Other Storage Options"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:793
#, fuzzy
msgid "Partitioning"
msgstr "パーティション設定の終了(_F)"

#: pyanaconda/ui/gui/spokes/storage.glade:810
#, fuzzy
msgid "Encryption"
msgstr "暗号化する(_E)"

#: pyanaconda/ui/gui/spokes/storage.glade:823
#, fuzzy
msgctxt "GUI|Storage"
msgid "A_utomatically configure partitioning."
msgstr "自動パーティション設定が選択されました"

#: pyanaconda/ui/gui/spokes/storage.glade:839
#, fuzzy
msgctxt "GUI|Storage"
msgid "_I will configure partitioning."
msgstr "パーティション設定の終了(_F)"

#: pyanaconda/ui/gui/spokes/storage.glade:871
#, fuzzy
msgctxt "GUI|Storage"
msgid "_Encrypt my data."
msgstr "暗号化する(_E)"

#: pyanaconda/ui/gui/spokes/storage.glade:886
#, fuzzy
msgid "You'll set a passphrase next."
msgstr "データを暗号化する。パスフレーズは後で設定。"

#: pyanaconda/ui/gui/spokes/storage.glade:907
msgctxt "GUI|Storage"
msgid "I would like to _make additional space available."
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.glade:923
#, fuzzy
msgid "Storage Options"
msgstr "自動パーティション設定のオプション"

#: pyanaconda/ui/gui/spokes/storage.glade:955
msgid "summary"
msgstr "要約"

#: pyanaconda/ui/gui/spokes/storage.glade:988
#, fuzzy
msgctxt "GUI|Storage"
msgid "_Full disk summary and boot loader..."
msgstr "完全なディスク要約とオプション... "

#: pyanaconda/ui/gui/spokes/keyboard.glade:15
#: pyanaconda/ui/gui/spokes/keyboard.glade:388
msgid "KEYBOARD LAYOUT"
msgstr "キーボードのレイアウト"

#: pyanaconda/ui/gui/spokes/keyboard.glade:56
msgid ""
"Which keyboard layouts would you like to use on this system?  You may move "
"any layout to the top of the list to select it as the default."
msgstr ""
"このシステムで使用するキーボードのレイアウトを選択してください。 いずれのレイ"
"アウトでも一覧の先頭に移動させデフォルトとして選択することができます。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:96
msgid ""
"Changes here will only apply to the installed system. Use the desktop's tool "
"to configure the keyboard for the installation process."
msgstr ""
"ここでの変更は、インストールされた後のシステムに対して適用されます。インス"
"トールプロセスのためにキーボードレイアウトを設定するには、デスクトップのツー"
"ルを使用してください。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:153
msgid "name"
msgstr "名前"

#: pyanaconda/ui/gui/spokes/keyboard.glade:167
#, fuzzy
msgid "Selected Layouts"
msgstr "選択したレイアウトを上に移動"

#: pyanaconda/ui/gui/spokes/keyboard.glade:190
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "_Add layout"
msgstr "レイアウトの追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade:205
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "_Remove layout"
msgstr "レイアウトの削除"

#: pyanaconda/ui/gui/spokes/keyboard.glade:220
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "Move selected layout _up"
msgstr "選択したレイアウトを上に移動"

#: pyanaconda/ui/gui/spokes/keyboard.glade:235
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "Move selected layout _down"
msgstr "選択したレイアウトを下に移動"

#: pyanaconda/ui/gui/spokes/keyboard.glade:251
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "_Preview layout"
msgstr "レイアウトのプレビュー"

#: pyanaconda/ui/gui/spokes/keyboard.glade:291
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "_Test the layout configuration below:"
msgstr "レイアウト設定のテストは出来ません。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:331
msgid "Alt + Shift to switch layouts."
msgstr "Alt + Shift を使ってレイアウトを切り替えます"

#: pyanaconda/ui/gui/spokes/keyboard.glade:346
#, fuzzy
msgctxt "GUI|Keyboard Layout"
msgid "_Options"
msgstr "オプション(_O)"

#: pyanaconda/ui/gui/spokes/keyboard.glade:421
#, fuzzy
msgctxt "GUI|Keyboard Layout|Add Layout"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/keyboard.glade:435
#, fuzzy
msgctxt "GUI|Keyboard Layout|Add Layout"
msgid "_Add"
msgstr "追加(_A)"

#: pyanaconda/ui/gui/spokes/keyboard.glade:467
msgid "ADD A KEYBOARD LAYOUT"
msgstr "キーボードレイアウトを追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade:483
msgid "You may add a keyboard layout by selecting it below:"
msgstr "以下の表で選択してキーボードレイアウトを追加することができます"

#: pyanaconda/ui/gui/spokes/keyboard.glade:532
#, fuzzy
msgid "Available Layouts"
msgstr "使用できる地域"

#: pyanaconda/ui/gui/spokes/keyboard.glade:573
#, fuzzy
msgid "Add Layout"
msgstr "レイアウトの追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade:605
#, fuzzy
msgctxt "GUI|Keyboard Layout|Switching Options"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/keyboard.glade:619
#, fuzzy
msgctxt "GUI|Keyboard Layout|Switching Options"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/keyboard.glade:651
msgid "LAYOUT SWITCHING OPTIONS"
msgstr "レイアウト切り替えのオプション"

#: pyanaconda/ui/gui/spokes/keyboard.glade:668
msgid ""
"Which combination(s) would you prefer for switching between keyboard layouts?"
msgstr "切り替えを行うキーボードレイアウトの組み合わせを選択してください。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:704
msgid "use"
msgstr "使用"

#: pyanaconda/ui/gui/spokes/keyboard.glade:717
msgid "description"
msgstr "詳細"

#: pyanaconda/ui/gui/spokes/keyboard.glade:751
#, fuzzy
msgid "Layout Options"
msgstr "NFS マウントオプション:"

#: pyanaconda/ui/gui/spokes/langsupport.glade:33
#, fuzzy
msgid "LANGUAGE SUPPORT"
msgstr "言語"

#: pyanaconda/ui/gui/spokes/langsupport.glade:79
msgid "Select additional language support to be installed:"
msgstr ""

#: pyanaconda/ui/gui/spokes/langsupport.glade:138
#: pyanaconda/ui/gui/spokes/langsupport.glade:241
#: pyanaconda/ui/gui/spokes/welcome.glade:273
#: pyanaconda/ui/gui/spokes/welcome.glade:372
msgid "nativeName"
msgstr "nativeName"

#: pyanaconda/ui/gui/spokes/langsupport.glade:155
#: pyanaconda/ui/gui/spokes/welcome.glade:290
msgid "englishName"
msgstr "englishName"

#: pyanaconda/ui/gui/spokes/langsupport.glade:173
#: pyanaconda/ui/gui/spokes/welcome.glade:308
#, fuzzy
msgid "selected"
msgstr "何も選択されていません"

#: pyanaconda/ui/gui/spokes/langsupport.glade:193
#: pyanaconda/ui/gui/spokes/welcome.glade:336
msgid "Type here to search."
msgstr ""

#: pyanaconda/ui/gui/spokes/langsupport.glade:227
msgid "checked"
msgstr ""

#: pyanaconda/ui/gui/spokes/password.glade:8
#: pyanaconda/ui/gui/spokes/password.glade:195
msgid "ROOT PASSWORD"
msgstr "root パスワード"

#: pyanaconda/ui/gui/spokes/password.glade:53
#, fuzzy
msgctxt "GUI|Password"
msgid "_Root Password:"
msgstr "root パスワード:"

#: pyanaconda/ui/gui/spokes/password.glade:67
#, fuzzy
msgctxt "GUI|Password"
msgid "_Confirm:"
msgstr "確認:"

#: pyanaconda/ui/gui/spokes/password.glade:104
#: pyanaconda/ui/gui/spokes/user.glade:187
#, fuzzy
msgid "Confirm Password"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/password.glade:139
#: pyanaconda/ui/gui/spokes/user.glade:251
#, fuzzy
msgid "empty password"
msgstr "root パスワードを設定する"

#: pyanaconda/ui/gui/spokes/password.glade:160
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"システムの管理には root アカウントを使用します。 root ユーザーのパスワードを"
"入力してください。"

#: pyanaconda/ui/gui/spokes/source.glade:29
#, fuzzy
msgctxt "GUI|Software Source|ISO Chooser Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/source.glade:43
msgctxt "GUI|Software Source|ISO Chooser Dialog"
msgid "_Open"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:95
#, fuzzy
msgctxt "GUI|Software Source|Media Check Dialog"
msgid "_Done"
msgstr "完了(_D)"

#: pyanaconda/ui/gui/spokes/source.glade:128
msgid "MEDIA VERIFICATION"
msgstr "メディアの確認"

#: pyanaconda/ui/gui/spokes/source.glade:155
msgid "Verifying media, please wait..."
msgstr "メディアを確認しています。お待ち下さい..."

#: pyanaconda/ui/gui/spokes/source.glade:224
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/source.glade:238
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/source.glade:267
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Enable HTTP Proxy"
msgstr "HTTP プロキシを有効にする(_E)"

#: pyanaconda/ui/gui/spokes/source.glade:299
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Proxy Host:"
msgstr "<b>プロキシの URL</b>"

#: pyanaconda/ui/gui/spokes/source.glade:316
msgid "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"
msgstr "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"

#: pyanaconda/ui/gui/spokes/source.glade:349
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "_Use Authentication"
msgstr "認証の使用(_U)"

#: pyanaconda/ui/gui/spokes/source.glade:375
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "User _name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/source.glade:392
#, fuzzy
msgctxt "GUI|Software Source|Proxy Dialog"
msgid "Pass_word:"
msgstr "パスワード: "

#: pyanaconda/ui/gui/spokes/source.glade:474
msgid "INSTALLATION SOURCE"
msgstr "インストールソース"

#: pyanaconda/ui/gui/spokes/source.glade:531
msgid "Which installation source would you like to use?"
msgstr "使用するインストールソースを選択してください。"

#: pyanaconda/ui/gui/spokes/source.glade:545
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_Auto-detected installation media:"
msgstr "自動検出したインストールメディア(_A):"

#: pyanaconda/ui/gui/spokes/source.glade:571
msgid "Device:"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/source.glade:583
#, fuzzy
msgid "Label:"
msgstr "<b>ラベル:</b>"

#: pyanaconda/ui/gui/spokes/source.glade:593
#: pyanaconda/ui/gui/spokes/source.glade:693
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_Verify"
msgstr "確認する(_V)"

#: pyanaconda/ui/gui/spokes/source.glade:617
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_ISO file:"
msgstr "ISO ファイル(_I):"

#: pyanaconda/ui/gui/spokes/source.glade:645
#, fuzzy
msgctxt "GUI|Software Source"
msgid "D_evice:"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/source.glade:676
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_Choose an ISO"
msgstr "ISO を1つ選択(_C)"

#: pyanaconda/ui/gui/spokes/source.glade:717
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_On the network:"
msgstr "ネットワーク上(_N):"

#: pyanaconda/ui/gui/spokes/source.glade:781
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_Proxy setup..."
msgstr "プロキシの設定(_P)..."

#: pyanaconda/ui/gui/spokes/source.glade:796
#, fuzzy
msgctxt "GUI|Software Source"
msgid "This URL refers to a _mirror list."
msgstr "この URL はミラーリストを参照します。"

#: pyanaconda/ui/gui/spokes/source.glade:834
#, fuzzy
msgctxt "GUI|Software Source"
msgid "N_FS mount options:"
msgstr "NFS マウントオプション:"

#: pyanaconda/ui/gui/spokes/source.glade:849
#: pyanaconda/ui/gui/spokes/source.glade:850
msgid "This field is optional."
msgstr "このフィールドはオプションです。"

#: pyanaconda/ui/gui/spokes/source.glade:883
msgid "Updates"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:910
msgctxt "GUI|Software Source"
msgid ""
"Don't install the latest available software _updates. Install the default "
"versions provided by the installation source above."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:934
#, fuzzy
msgid "Additional repositories"
msgstr "Fedora Peopleのレポジトリ"

#: pyanaconda/ui/gui/spokes/source.glade:975
msgid "Enabled"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1020
#: pyanaconda/ui/gui/spokes/source.glade:1021
#, fuzzy
msgid "Add a new repository."
msgstr "新しいマウントポイントを追加します。"

#: pyanaconda/ui/gui/spokes/source.glade:1022
msgctxt "GUI|Software Source"
msgid "A_dd"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1039
#: pyanaconda/ui/gui/spokes/source.glade:1040
#, fuzzy
msgid "Remove the selected repository."
msgstr "選択したマウントポイントを削除します。"

#: pyanaconda/ui/gui/spokes/source.glade:1041
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_Remove"
msgstr "削除(_R)"

#: pyanaconda/ui/gui/spokes/source.glade:1058
#: pyanaconda/ui/gui/spokes/source.glade:1059
msgid "Revert to the previous list of repositories."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1060
msgctxt "GUI|Software Source"
msgid "Rese_t"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1090
#: pyanaconda/ui/gui/spokes/source.glade:1091
msgid "URL for the repository, without protocol."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1103
#: pyanaconda/ui/gui/spokes/source.glade:1104
msgid "URL of proxy in the form of protocol://host:[port]"
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1116
#: pyanaconda/ui/gui/spokes/source.glade:1117
#, fuzzy
msgid "Optional proxy user name."
msgstr "操作上のエラー"

#: pyanaconda/ui/gui/spokes/source.glade:1129
#, fuzzy
msgid "Optional proxy password."
msgstr "root パスワードを設定する"

#: pyanaconda/ui/gui/spokes/source.glade:1141
#, fuzzy
msgctxt "GUI|Software Source"
msgid "This URL refers to a mirror _list."
msgstr "この URL はミラーリストを参照します。"

#: pyanaconda/ui/gui/spokes/source.glade:1160
#, fuzzy
msgctxt "GUI|Software Source"
msgid "_Name:"
msgstr "名前:"

#: pyanaconda/ui/gui/spokes/source.glade:1177
#: pyanaconda/ui/gui/spokes/source.glade:1178
msgid "Protocol for the repository URL."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1197
#, fuzzy
msgctxt "GUI|Software Source"
msgid "Pro_xy URL:"
msgstr "<b>プロキシの URL</b>"

#: pyanaconda/ui/gui/spokes/source.glade:1214
#, fuzzy
msgctxt "GUI|Software Source"
msgid "U_ser name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/source.glade:1231
#, fuzzy
msgctxt "GUI|Software Source"
msgid "Pass_word:"
msgstr "パスワード: "

#: pyanaconda/ui/gui/spokes/source.glade:1248
#: pyanaconda/ui/gui/spokes/source.glade:1249
msgid "Name of the repository."
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.glade:23
#, fuzzy
msgctxt "GUI|Welcome|Beta Warn Dialog"
msgid "_Get me out of here!"
msgstr "ここから脱出したい! (_G)"

#: pyanaconda/ui/gui/spokes/welcome.glade:37
#, fuzzy
msgctxt "GUI|Welcome|Beta Warn Dialog"
msgid "_I accept my fate."
msgstr "運命を受け入れます(_I)"

#: pyanaconda/ui/gui/spokes/welcome.glade:68
msgid "This is unstable, pre-release software."
msgstr "これは不安定なプレリリースのソフトウェアです。"

#: pyanaconda/ui/gui/spokes/welcome.glade:97
msgid ""
"You wake up inside an OS installer in Timbuktu, and it's six months in the "
"future.  But, there are bugs.  Bugs everywhere.  Bugs you must live with.  "
"This OS of the future isn't a stable OS you can rely on.  It's for testing "
"purposes only."
msgstr ""
"Timbuktu の OS インストーラー内で目覚めました。そして 6 か月だけ未来です。し"
"かし、バグがあります。バグだらけです。共存すべきバグです。未来のこの OS は信"
"頼できるほど安定していません。これはテスト目的のみのものです。"

#: pyanaconda/ui/gui/spokes/welcome.glade:126
msgid "Beta Warn"
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.glade:225
msgid "What language would you like to use during the installation process?"
msgstr "インストール時に使用する言語を選択してください。"

#: pyanaconda/ui/gui/spokes/welcome.glade:316
msgid "Languages"
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.glade:388
msgid "Locales"
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.glade:422
msgid "WELCOME"
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.glade:443
#, fuzzy
msgctxt "GUI|Welcome|Unsupported Hardware Dialog"
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/spokes/welcome.glade:457
#, fuzzy
msgctxt "GUI|Welcome|Unsupported Hardware Dialog"
msgid "_Continue"
msgstr "続行(_C)"

#: pyanaconda/ui/gui/spokes/welcome.glade:488
msgid "Unsupported Hardware Detected"
msgstr ""

#: pyanaconda/ui/gui/spokes/welcome.glade:546
msgid "Unsupported Hardware"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.glade:10
#: pyanaconda/ui/gui/spokes/user.glade:346
msgid "CREATE USER"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.glade:62
msgctxt "GUI|User"
msgid "_Full name"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.glade:80
#, fuzzy
msgctxt "GUI|User"
msgid "_User name"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/user.glade:100
#, fuzzy
msgid "Full Name"
msgstr "グループ名"

#: pyanaconda/ui/gui/spokes/user.glade:131
#, fuzzy
msgctxt "GUI|User"
msgid "_Password"
msgstr "パスワード: "

#: pyanaconda/ui/gui/spokes/user.glade:149
#, fuzzy
msgctxt "GUI|User"
msgid "_Confirm password"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/user.glade:201
msgid ""
"<b>Tip:</b> Keep your user name shorter than 32 characters and do not use "
"spaces."
msgstr ""

#: pyanaconda/ui/gui/spokes/user.glade:211
msgctxt "GUI|User"
msgid "_Require a password to use this account"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.glade:270
msgctxt "GUI|User"
msgid "_Make this user administrator"
msgstr ""

#: pyanaconda/ui/gui/spokes/user.glade:289
msgctxt "GUI|User"
msgid "_Advanced..."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:68
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:543
#, fuzzy
msgid "RAID0"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.glade:72
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:547
#, fuzzy
msgid "RAID1"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.glade:76
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:551
#, fuzzy
msgid "RAID4"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.glade:80
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:555
#, fuzzy
msgid "RAID5"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.glade:84
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:559
#, fuzzy
msgid "RAID6"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.glade:88
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:563
#, fuzzy
msgid "RAID10"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.glade:187
#, fuzzy
msgid "Add a new mount point."
msgstr "新しいマウントポイントを追加します。"

#: pyanaconda/ui/gui/spokes/custom.glade:188
#, fuzzy
msgctxt "GUI|Custom Partitioning"
msgid "Add"
msgstr "追加(_A)"

#: pyanaconda/ui/gui/spokes/custom.glade:203
#, fuzzy
msgid "Remove the selected mount point(s)."
msgstr "選択したマウントポイントを削除します。"

#: pyanaconda/ui/gui/spokes/custom.glade:204
#, fuzzy
msgctxt "GUI|Custom Partitioning"
msgid "Remove"
msgstr "削除(_R)"

#: pyanaconda/ui/gui/spokes/custom.glade:219
#, fuzzy
msgid "Reload storage configuration from disk."
msgstr "ストレージの設定に失敗しました: %s"

#: pyanaconda/ui/gui/spokes/custom.glade:220
msgctxt "GUI|Custom Partitioning"
msgid "Refresh"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:285
#: pyanaconda/ui/gui/spokes/custom.glade:1025
#: pyanaconda/ui/gui/spokes/custom.glade:1170
#: pyanaconda/ui/gui/spokes/custom.glade:1257
msgid "Selected Device"
msgstr "選択したデバイス"

#: pyanaconda/ui/gui/spokes/custom.glade:303
#: pyanaconda/ui/gui/spokes/custom.glade:1043
#: pyanaconda/ui/gui/spokes/custom.glade:1188
#: pyanaconda/ui/gui/spokes/custom.glade:1275
msgid "Device description"
msgstr "デバイスの説明"

#: pyanaconda/ui/gui/spokes/custom.glade:364
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "Mount _Point:"
msgstr "<b>マウントポイント:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:411
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Desired Capacity:"
msgstr "<b>要望する容量:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:461
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Label:"
msgstr "<b>ラベル:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:508
#, fuzzy
msgid "Device(s):"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/custom.glade:537
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Modify..."
msgstr "変更 ..."

#: pyanaconda/ui/gui/spokes/custom.glade:569
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Name:"
msgstr "名前:"

#: pyanaconda/ui/gui/spokes/custom.glade:624
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "Device _Type:"
msgstr "<b>デバイスタイプ:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:668
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "_Encrypt"
msgstr "暗号化する(_E)"

#: pyanaconda/ui/gui/spokes/custom.glade:709
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "File S_ystem:"
msgstr "ファイルシステム"

#: pyanaconda/ui/gui/spokes/custom.glade:753
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "Ref_ormat"
msgstr "再フォーマット"

#: pyanaconda/ui/gui/spokes/custom.glade:807
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "_Volume Group:"
msgstr "ボリュームグループ:"

#: pyanaconda/ui/gui/spokes/custom.glade:860
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "_Modify..."
msgstr "変更 ..."

#: pyanaconda/ui/gui/spokes/custom.glade:892
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure"
msgid "RA_ID Level:"
msgstr "RAID デバイス"

#: pyanaconda/ui/gui/spokes/custom.glade:957
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure|Devices"
msgid "_Update Settings"
msgstr "タイムゾーンの設定"

#: pyanaconda/ui/gui/spokes/custom.glade:980
msgid ""
"Note:  The settings you make on this screen will not be applied until you "
"click on the main menu's 'Begin Installation' button."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:1077
msgid ""
"This device is encrypted and cannot be read without a valid passphrase. You "
"may unlock it below."
msgstr ""
"このデバイスは暗号化されているため有効なパスフレーズがないと読み込めません。"
"以下でアンロックできます。"

#: pyanaconda/ui/gui/spokes/custom.glade:1098
#, fuzzy
msgctxt "GUI|Custom Partitioning|Encrypted"
msgid "_Passphrase:"
msgstr "パスフレーズ:"

#: pyanaconda/ui/gui/spokes/custom.glade:1127
#, fuzzy
msgctxt "GUI|Custom Partitioning|Encrypted"
msgid "_Unlock"
msgstr "アンロック(_U)"

#: pyanaconda/ui/gui/spokes/custom.glade:1222
msgid ""
"This device cannot be edited directly. You can remove it or select a "
"different device."
msgstr ""
"このデバイスの直接編集はできません。 デバイスを削除するか別のデバイスを選択し"
"ます。"

#: pyanaconda/ui/gui/spokes/custom.glade:1370
msgid "AVAILABLE SPACE"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:1423
msgid "TOTAL SPACE"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:1463
msgctxt "GUI|Custom Partitioning"
msgid "_Reset All"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:23
#, fuzzy
msgctxt "GUI|Advanced Storage|FCoE"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:56
msgid ""
"Please select the network interface which is connected to your FCoE switch."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:70
msgctxt "GUI|Advanced Storage|FCoE"
msgid "_NIC:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:92
msgctxt "GUI|Advanced Storage|FCoE"
msgid "Use _DCB"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:108
msgctxt "GUI|Advanced Storage|FCoE"
msgid "Use auto _VLAN"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:144
msgctxt "GUI|Advanced Storage|FCoE"
msgid "_Add FCoE Disk(s)"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:187
msgid "Error adding FCoE SAN."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/fcoe.glade:215
msgid ""
"The following error occurred while attempting to add an FCoE SAN.  Please "
"check your configuration and try again"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:40
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:54
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:85
msgid "ADD iSCSI STORAGE TARGET"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:114
msgid ""
"To use iSCSI disks, you must provide the address of your iSCSI target and "
"the iSCSI initiator name you've configured for your host."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:142
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Target IP Address:"
msgstr "IP アドレス"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:170
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "iSCSI _Initiator Name:"
msgstr "iSCSI イニシエーター名を入力しなければなりません"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:187
#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:760
msgid "No credentials (discovery authentication disabled)"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:188
#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:761
msgid "CHAP pair"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:189
#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:762
msgid "CHAP pair and a reverse pair"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:203
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Discovery Authentication Type:"
msgstr "認証の使用(_U)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:218
#, fuzzy
msgid ""
"<span size=\"small\"><b>Example:</b> iqn.2012-09.com.example:diskarrays-sn-"
"a8675309</span>"
msgstr "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:263
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure|CHAP"
msgid "CHAP _User name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:277
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure|CHAP"
msgid "CHAP _Password:"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:389
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "CHAP _User name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:403
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "CHAP _Password:"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:417
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "Reverse CHAP User _name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:431
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Reverse CHAP"
msgid "Reverse CHAP Pass_word:"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:465
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Start"
msgid "_Start Discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:502
msgid "Discovering iSCSI targets.  This may take a moment..."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:541
msgid "Discovery login rejected."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:556
msgid ""
"The following error occurred discovering iSCSI targets.  Please double check "
"your authorization information and try again."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:579
msgctxt "GUI|Advanced Storage|iSCSI|Configure|Retry"
msgid "_Retry Discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:619
msgctxt "GUI|Advanced Storage|iSCSI|Configure"
msgid "_Bind targets to network interfaces This may take a moment..."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:695
#, fuzzy
msgid "Node Name"
msgstr "ネットワーク名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:706
msgid "Interface"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:717
msgid "Portal"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:745
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login"
msgid "_Node Login Authentication Type:"
msgstr "認証の使用(_U)"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:763
msgid "Use the credentials from discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:797
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login|CHAP"
msgid "CHAP _User name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:811
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login|CHAP"
msgid "CHAP _Password:"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:923
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "CHAP _User name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:937
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "CHAP _Password:"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:951
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "_Reverse CHAP User name:"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:965
#, fuzzy
msgctxt "GUI|Advanced Storage|iSCSI|Login|Reverse CHAP"
msgid "Reverse CHAP Pass_word:"
msgstr "VNC パスワード"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:1014
msgctxt "GUI|Advanced Storage|iSCSI|Login|Login"
msgid "_Log In"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:1069
#, fuzzy
msgid "Node login failed."
msgstr "接続に失敗しました"

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:1084
msgid ""
"The following error occurred logging into the selected iSCSI node.  Please "
"double check your authorization information and try again"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/iscsi.glade:1107
msgctxt "GUI|Advanced Storage|iSCSI|Login|Retry"
msgid "Retry _Log In"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:22
#, fuzzy
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:36
#, fuzzy
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:67
msgid "ADD DASD STORAGE TARGET"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:90
msgid "To use DASD disks, you must provide the device number."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:117
#, fuzzy
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Device number:"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:136
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Start Discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:173
msgid "Discovering DASD devices.  This may take a moment..."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:212
#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:253
msgid "Device discovery failed."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:227
msgid ""
"The following error occurred discovering DASD devices.  Please double check "
"your configuration information and try again."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/dasd.glade:250
msgctxt "GUI|Advanced Storage|DASD|Configure"
msgid "_Retry Discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:82
msgid "ADD zFCP STORAGE TARGET"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:105
msgid ""
"To use zFCP disks, you must provide the device number, WWPN, and LUN "
"configured for the device."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:132
#, fuzzy
msgctxt "GUI|Advanced Storage|zFCP|Device Number"
msgid "_Device number:"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:159
msgid "WWPN:"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:177
msgctxt "GUI|Advanced Storage|zFCP|Start Discovery"
msgid "_Start Discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:214
msgid "Discovering zFCP devices.  This may take a moment..."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:268
msgid ""
"The following error occurred discovering zFCP devices.  Please double check "
"your configuration information and try again."
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:291
msgctxt "GUI|Advanced Storage|zFCP|Retry Discovery"
msgid "_Retry Discovery"
msgstr ""

#: pyanaconda/ui/gui/spokes/advstorage/zfcp.glade:333
msgid "LUN:"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/cart.glade:26
#: pyanaconda/ui/gui/spokes/lib/cart.glade:78
msgid "SELECTED DISKS"
msgstr "選択したディスク"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:43
#, fuzzy
msgctxt "GUI|Selected Disks Dialog"
msgid "_Close"
msgstr "閉じる(_C)"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:106
msgid "Boot"
msgstr "起動"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:120
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:222
msgid "Description"
msgstr "説明"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:158
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:261
#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:745
msgid "Free"
msgstr "空き"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:199
#, fuzzy
msgctxt "GUI|Selected Disks Dialog"
msgid "_Remove"
msgstr "削除(_R)"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:226
msgid "Disk summary goes here"
msgstr "ディスクの要約はここへ"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:21
#, fuzzy
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:37
#, fuzzy
msgctxt "GUI|Custom Partitioning|Confirm Delete Dialog"
msgid "_Delete It"
msgstr "それを削除します(_D)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:129
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:144
#, fuzzy
msgctxt "GUI|Custom Partitioning|Configure Dialog"
msgid "_Select"
msgstr "選択(_S)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:175
msgid "CONFIGURE MOUNT POINT"
msgstr "マウントポイントの設定"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:191
msgid "Select one or more disks this device may reside on."
msgstr "このデバイスを存在させるディスクをひとつまたは複数選択してください。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:321
#, fuzzy
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:336
#, fuzzy
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "_Add mount point"
msgstr "マウントポイントの追加(_A)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:370
#, fuzzy
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "_Desired Capacity:"
msgstr "<b>要望する容量:</b>"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:387
#, fuzzy
msgctxt "GUI|Custom Partitioning|Add Dialog"
msgid "Mount _Point:"
msgstr "<b>マウントポイント:</b>"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:405
msgid "ADD A NEW MOUNT POINT"
msgstr "新規のマウントポイントの追加"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:423
msgid ""
"More customization options are available\n"
"after creating the mount point below."
msgstr ""
"以下にマウントポイントを作成した後に、他のカスタム化オプションが利用できるよ"
"うになります。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:458
msgid ""
"That mount point is already in\n"
"use.  Try something else?"
msgstr ""
"そのマウントポイントはすでに使用中です。\n"
"　他を試しますか？"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:482
msgid "eg: \"20 GB\", \"500mb\" (minus the quotation marks)"
msgstr "例: \"20 GB\"、 \"500mb\" (引用符は除く)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:539
msgid "Single"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:587
#, fuzzy
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:601
#, fuzzy
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "_Save"
msgstr "保存(_S)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:633
#, fuzzy
msgid "CONFIGURE CONTAINER"
msgstr "マウントポイントの設定"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:649
#, fuzzy
msgid ""
"Please create a name for this container and select at least one disk below."
msgstr ""
"ボリュームグループ名を決めて作成し、以下から少なくても1つのディスクを選択して"
"ください。"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:667
#, fuzzy
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "_Name:"
msgstr "名前:"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:786
#, fuzzy
msgid "RAID Level:"
msgstr "RAID デバイス"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:815
#, fuzzy
msgid "Encrypt"
msgstr "暗号化する(_E)"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:856
#, fuzzy
msgid "Please enter a valid name."
msgstr "有効なマウントポイントを記入して下さい"

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:886
msgctxt "GUI|Custom Partitioning|Container Dialog"
msgid "Si_ze policy:"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:901
msgid "Automatic"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:902
msgid "As large as possible"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/custom_storage_helpers.glade:903
msgid "Fixed"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:8
msgid "UNFORMATTED DASDS"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:23
#, fuzzy
msgctxt "GUI|DAD Format Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:37
#, fuzzy
msgctxt "GUI|DAD Format Dialog"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:70
msgid ""
"The following unformatted DASDs have been detected on your system. You can "
"choose to format them now with dasdfmt or cancel to leave them unformatted. "
"Unformatted DASDs cannot be used during installation."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:86
#, fuzzy
msgid "Unformatted DASDs Detected"
msgstr "DASD デバイスをフォーマット中..."

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:136
msgid ""
"<b>Warning</b>: All storage changes made using the installer will be lost "
"when you choose to format."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:160
msgctxt "GUI|DAD Format Dialog"
msgid "_Format with dasdfmt"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:207
msgid ""
"You may <a href=\"\">go back to the main menu</a> to complete other\n"
"installation options while formatting completes."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/dasdfmt.glade:247
msgid "Disk formatting complete."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/detailederror.glade:25
msgid "An unknown error occurred during installation.  Details are below."
msgstr "インストール中に不明なエラーが発生しました。詳細は以下にあります。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:23
#, fuzzy
msgctxt "GUI|Passphrase Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:38
#, fuzzy
msgctxt "GUI|Passphrase Dialog"
msgid "_Save Passphrase"
msgstr "パスフレーズの保存"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:65
msgid "DISK ENCRYPTION PASSPHRASE"
msgstr "ディスク暗号化用パスフレーズ"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:81
msgid ""
"You have chosen to encrypt some of your data. You will need to create a "
"passphrase that you will use to access your data when you start your "
"computer."
msgstr ""
"データの一部を暗号化する選択をしました。コンピュータの開始時にデータへのアク"
"セスに使用するパスフレーズを作成する必要があります。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:102
#, fuzzy
msgctxt "GUI|Passphrase Dialog"
msgid "_Passphrase:"
msgstr "パスフレーズ:"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:132
#, fuzzy
msgctxt "GUI|Passphrase Dialog"
msgid "Con_firm:"
msgstr "確認:"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:273
#, fuzzy
msgid ""
"Warning: You won't be able to switch between keyboard layouts (from the "
"default one) when you decrypt your disks after install."
msgstr ""
"警告: 現在のキーボートレイアウトは <b>%s</b> です。キーボードのレイアウトを変"
"更すると、インストールの後にディスクの復号が出来ないかもしれません。"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:8
#: pyanaconda/ui/gui/spokes/lib/refresh.glade:71
#, fuzzy
msgid "RESCAN DISKS"
msgstr "ディスク領域の獲得"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:25
#, fuzzy
msgctxt "GUI|Refresh Dialog|Rescan"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:39
#, fuzzy
msgctxt "GUI|Refresh Dialog|Rescan"
msgid "_OK"
msgstr "OK"

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:87
msgid ""
"You can remove or insert additional disks at this time and press 'Rescan "
"Disks' below for the changes to take effect."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:118
msgid ""
"<b>Warning:</b> All storage changes made using the installer will be lost "
"when you press 'Rescan Disks'."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:143
msgctxt "GUI|Refresh Dialog|Rescan"
msgid "_Rescan Disks"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:176
#: pyanaconda/ui/gui/spokes/lib/refresh.glade:212
msgid "Scanning disks.  This may take a moment..."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:223
msgid ""
"You may <a href=\"\">go back to the main menu</a> to complete other\n"
"installation options while this scan completes."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:254
msgid "Disk rescan complete."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/refresh.glade:269
msgid ""
"Pressing 'OK' below will take you to the disk selection screen where you "
"will need to re-select your disks."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/resize.glade:55
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:70
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "_Reclaim space"
msgstr "領域を確保する(_R)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:104
msgid "RECLAIM DISK SPACE"
msgstr "ディスク領域の獲得"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:121
msgid "Description goes here."
msgstr "説明"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:174
#, fuzzy
msgid "File System"
msgstr "ファイルシステム"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:185
msgid "Reclaimable Space"
msgstr "獲得可能な領域"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:196
#: pyanaconda/ui/gui/spokes/lib/summary.glade:144
msgid "Action"
msgstr "アクション"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:221
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "_Preserve"
msgstr "保存"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:237
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "_Delete"
msgstr "削除"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:253
#, fuzzy
msgctxt "GUI|Reclaim Dialog"
msgid "_Shrink"
msgstr "縮小"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:367
#, fuzzy
msgid "Reclaim"
msgstr "領域を取り戻す(_S)"

#: pyanaconda/ui/gui/spokes/lib/summary.glade:25
#: pyanaconda/ui/gui/spokes/lib/summary.glade:89
msgid "SUMMARY OF CHANGES"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/summary.glade:42
#, fuzzy
msgctxt "GUI|Summary Dialog"
msgid "_Cancel & Return to Custom Partitioning"
msgstr "カスタムパーティション設定が選択されました"

#: pyanaconda/ui/gui/spokes/lib/summary.glade:57
#, fuzzy
msgctxt "GUI|Summary Dialog"
msgid "_Accept Changes"
msgstr "変更を適用(_A)"

#: pyanaconda/ui/gui/spokes/lib/summary.glade:105
msgid ""
"Your customizations will result in the following changes taking effect after "
"you return to the main menu and begin installation:"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/summary.glade:133
msgid "Order"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/summary.glade:166
#, fuzzy
msgid "Device"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/lib/summary.glade:177
#, fuzzy
msgid "Mount point"
msgstr "マウントポイントの追加(_A)"

#: pyanaconda/ui/gui/spokes/lib/entropy_dialog.glade:35
msgid ""
"The system needs better quality of random data, you can improve it by typing "
"randomly on keyboard and moving your mouse. The installation will continue "
"automatically regardless of random data quality when time runs out."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/entropy_dialog.glade:53
msgid "Random data quality:"
msgstr ""

#: pyanaconda/ui/gui/main.glade:24
#, fuzzy
msgctxt "GUI|Error Dialog"
msgid "_Exit Installer"
msgstr "インストーラーを終了する(_E)"

#: pyanaconda/ui/gui/main.glade:94
#, fuzzy
msgctxt "GUI|Main"
msgid "_No"
msgstr "いいえ(_N)"

#: pyanaconda/ui/gui/main.glade:108
#, fuzzy
msgctxt "GUI|Main"
msgid "_Yes"
msgstr "はい(_Y)"

#: pyanaconda/ui/gui/main.glade:151
msgid ""
"Are you sure you wish to quit the\n"
"installation process?"
msgstr ""
"インストールプロセスを本当に\n"
"終了したいですか？"

#: pyanaconda/ui/gui/main.glade:175
#, fuzzy
msgid "Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/hubs/summary.glade:8
#: pyanaconda/ui/gui/hubs/summary.glade:145
msgid "INSTALLATION SUMMARY"
msgstr "インストール概要"

#: pyanaconda/ui/gui/hubs/summary.glade:81
#, fuzzy
msgctxt "GUI|Summary"
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/hubs/summary.glade:97
#, fuzzy
msgctxt "GUI|Summary"
msgid "_Begin Installation"
msgstr "インストールの開始(_B)"

#: pyanaconda/ui/gui/hubs/summary.glade:128
msgid "We won't touch your disks until you click 'Begin Installation'."
msgstr ""

#: pyanaconda/ui/gui/hubs/progress.glade:8
#: pyanaconda/ui/gui/hubs/progress.glade:260
msgid "CONFIGURATION"
msgstr "設定"

#: pyanaconda/ui/gui/hubs/progress.glade:88
msgid "Preparing to install"
msgstr "インストールの準備中"

#: pyanaconda/ui/gui/hubs/progress.glade:146
#, fuzzy
msgctxt "GUI|Progress"
msgid "_Finish configuration"
msgstr "設定完了(_F)"

#: pyanaconda/ui/gui/hubs/progress.glade:200
#, fuzzy
msgctxt "GUI|Progress"
msgid "_Reboot"
msgstr "再起動(_R)"

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install to Hard Drive"
msgstr "ハードディスクにインストール"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install"
msgstr "インストール"

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install the live CD to your hard disk"
msgstr "ライブ ディスク をハードディスクにインストール"

#: /home/sbueno/scm/anaconda/data/liveinst/console.apps/liveinst:5
msgid "Starting Install to Hard Drive"
msgstr "ハードディスクへのインストールを開始します"

#: data/liveinst/gnome/fedora-welcome.desktop.in.h:1
#: data/liveinst/gnome/fedora-welcome:65
msgid "Welcome to Fedora"
msgstr "Fedora へようこそ"

#: anaconda:461
#, fuzzy, python-format
msgid ""
"%(product_name)s requires %(needed_ram)s MB of memory to install, but you "
"only have %(total_ram)s MB on this machine.\n"
msgstr ""
"インストールするために %s は、最低 %s MB のメモリーを必要とします。お使いのシ"
"ステムには %s MB しか搭載されていません。\n"

#: anaconda:463
#, fuzzy, python-format
msgid ""
"The %(product_name)s graphical installer requires %(needed_ram)s MB of "
"memory, but you only have %(total_ram)s MB\n"
"."
msgstr ""
"%s のグラフィカルインストーラーは、最低 %s MB のメモリーを必要とします。お使"
"いのシステムには %s MB のメモリーしか搭載されていません。"

#: anaconda:466
msgid ""
"\n"
"Press <return> to reboot your system.\n"
msgstr ""

#: anaconda:468
msgid "Not enough RAM"
msgstr "メモリーが足りません。"

#: anaconda:469
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""
"次のとおり実行してテキストモードインストーラーを試して下さい:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
"なお、この操作は root でのターミナルから実行します。"

#: anaconda:472
msgid " Starting text mode."
msgstr " テキストモードを開始しています。"

#: anaconda:508
msgid "The installation cannot continue and the system will be rebooted"
msgstr ""

#: anaconda:632
msgid "DISPLAY variable not set. Starting text mode."
msgstr "DISPLAY 変数がセットされていません。テキストモードで起動します。"

#: anaconda:640
msgid "Graphical installation is not available. Starting text mode."
msgstr "グラフィカルインストールは使用できません。テキストモードを起動します。"

#: anaconda:648
#, fuzzy
msgid ""
"Text mode provides a limited set of installation options. It does not offer "
"custom partitioning for full control over the disk layout. Would you like to "
"use VNC mode instead?"
msgstr ""
"テキストモードによるインストールは限定的なインストールオプションしか提供され"
"ず、パーティション設定やパッケージ選択の指定が行えません。代わりに VNC モード"
"を使用しますか？"

#: anaconda:744
#, python-format
msgid "Please ssh install@%s to begin the install."
msgstr "ssh install@%s を実行して、インストールを始めて下さい。"

#: anaconda:746
msgid "Please ssh install@<host> to continue installation."
msgstr "ssh install@<host> を実行して、インストールを継続して下さい。"

#: anaconda:940
msgid "Unable to create PID file"
msgstr ""

#: anaconda:941
#, python-format
msgid ""
"Anaconda is unable to create %s because the file already exists. Anaconda is "
"already running, or a previous instance of anaconda has crashed."
msgstr ""

#: data/liveinst/gnome/fedora-welcome:94
msgid "Try Fedora"
msgstr "Fedora を試す"

#: data/liveinst/gnome/fedora-welcome:110
msgid ""
"You are currently running Fedora from live media.\n"
"You can install Fedora now, or choose \"Install to Hard Drive\" in the "
"Activities Overview at any later time."
msgstr ""
"現在、ライブメディアから Fedora を稼働しています。\n"
"今、Fedora をインストールできます。または後でアクティビティオーバービューで"
"「ハードドライブにインストールする」を選択することもできます。"

#: data/liveinst/gnome/fedora-welcome:128
msgid ""
"You can choose \"Install to Hard Drive\"\n"
"in the Activities Overview at any later time."
msgstr ""
"後にでも「アクティビティオーバービュー」内で 「ハードドライブにインストール」"
"を選択することができます。"

#: data/liveinst/gnome/fedora-welcome:131
msgid "Close"
msgstr "閉じる"

#~ msgid "OK"
#~ msgstr "OK"

#, fuzzy
#~ msgid "Cancel"
#~ msgstr "取り消し(_C)"

#, fuzzy
#~ msgid "Yes"
#~ msgstr "はい(_Y)"

#, fuzzy
#~ msgid "No"
#~ msgstr "いいえ(_N)"

#~ msgid "Skip"
#~ msgstr "スキップする"

#~ msgid "System to Rescue"
#~ msgstr "レスキュー対象システム"

#~ msgid "Which device holds the root partition of your installation?"
#~ msgstr "どのデバイスにインストールの root パーティションを置きますか？"

#~ msgid "Exit"
#~ msgstr "終了"

#~ msgid " The system will reboot automatically when you exit from the shell."
#~ msgstr " シェルを終了するとシステムは自動的に再起動します。"

#~ msgid "You don't have any Linux partitions. Press return to get a shell.%s"
#~ msgstr ""
#~ "Linux パーティションがありません。<enter>キーを押すとシェルを起動しま"
#~ "す。%s"

#, fuzzy
#~ msgid "Passphrase"
#~ msgstr "パスフレーズ:"

#~ msgid "Installing"
#~ msgstr "インストール中"

#, fuzzy
#~ msgid "Fatal Error"
#~ msgstr "エラー"

#~ msgid ""
#~ "Your system had dirty file systems which you chose not to mount.  Press "
#~ "return to get a shell from which you can fsck and mount your partitions. "
#~ "%s"
#~ msgstr ""
#~ "システムに損傷のあるファイルシステムがありマウントしないことを選択していま"
#~ "す。<enter> を押すとシェルが起動され、ファイルシステムの検証(fsck)や パー"
#~ "ティションのマウント(mount)を行うことができます。 %s"

#~ msgid "BTRFS"
#~ msgstr "Btrfs"

#~ msgid "_Fedora"
#~ msgstr "Fedora(_F)"

#~ msgid "Red Hat Enterprise Linux"
#~ msgstr "Red Hat Enterprise Linux"

#, fuzzy
#~ msgid "Failed to set up installation source. Check the source address."
#~ msgstr ""
#~ "インストールソースの設定に失敗しました。レポジトリの url を確認して下さい"

#, fuzzy
#~ msgid ""
#~ "You have provided a weak password: %s\n"
#~ "Would you like to use it anyway?"
#~ msgstr "脆弱なパスワードです: %s　それでも使用する場合は完了を押します。"

#, fuzzy
#~ msgid ""
#~ "You have provided a weak password.\n"
#~ "Would you like to use it anyway?"
#~ msgstr "脆弱なパスワードです: %s　それでも使用する場合は完了を押します。"

#, fuzzy
#~ msgctxt "GUI|Spoke"
#~ msgid "DATE & _TIME"
#~ msgstr "日付と時刻"

#, fuzzy
#~ msgctxt "GUI|Installation Destination|Filter|zSeries"
#~ msgid "_Label"
#~ msgstr "<b>ラベル:</b>"

#, fuzzy
#~ msgctxt "GUI|Installation Destination|Filter|zSeries"
#~ msgid "_Go"
#~ msgstr "いいえ(_N)"

#, fuzzy
#~ msgctxt "GUI|Network|Wired"
#~ msgid "C_onfigure..."
#~ msgstr "設定する(_O) ..."

#, fuzzy
#~ msgctxt "GUI|Software Source|Proxy Dialog"
#~ msgid "_Ok"
#~ msgstr "OK"

#, fuzzy
#~ msgctxt "GUI|Software Source|Proxy Dialog"
#~ msgid "Pass_word"
#~ msgstr "パスワード: "

#~ msgid "Filesystem"
#~ msgstr "ファイルシステム"

#, fuzzy
#~ msgid "Device Name"
#~ msgstr "デバイス:"

#~ msgid ""
#~ "Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or "
#~ "'0-9'"
#~ msgstr ""
#~ "ホスト名は 「a-z」 または 「A-Z」または 「0-9」 の範囲の有効な文字で開始し"
#~ "なければ なりません。"

#~ msgid "You need more space on the following file systems:\n"
#~ msgstr "以下のファイルシステムは容量を増やす必要があります。\n"

#~ msgid "Can't have a question in command line mode!"
#~ msgstr "コマンドラインモードでは質問は置けません!"

#, fuzzy
#~ msgid "That name is invalid. Try something else?"
#~ msgstr "そのマウントポイントは無効です。他を試しますか?"

#, fuzzy
#~ msgid "_NETWORK CONFIGURATION"
#~ msgstr "ネットワーク設定"

#~ msgid "Error downloading package metadata..."
#~ msgstr "パッケージメタデータをダウンロード中にエラー..."

#, fuzzy
#~ msgid "Nothing here yet."
#~ msgstr "何も選択されていません"

#, fuzzy
#~ msgid "Firmware _RAID"
#~ msgstr "ファームウェアがありません"

#, fuzzy
#~ msgid "<b>Authentication required by wireless network</b>"
#~ msgstr "認証が必要です"

#~ msgid "column"
#~ msgstr "列"

#, fuzzy
#~ msgid "<b>Partition scheme:</b>"
#~ msgstr "<b>パーティションタイプ:</b>"

#, fuzzy
#~ msgid "<b>_Proxy URL</b>"
#~ msgstr "<b>プロキシの URL</b>"

#, fuzzy
#~ msgid "<b>User_name</b>"
#~ msgstr "<b>ユーザー名</b>"

#, fuzzy
#~ msgid "<b>Pass_word</b>"
#~ msgstr "<b>パスワード</b>"

#, fuzzy
#~ msgid "Invalid repository name. Try something else?"
#~ msgstr "そのマウントポイントは無効です。他を試しますか?"

#, fuzzy
#~ msgid "<b>_Label:</b>"
#~ msgstr "<b>ラベル:</b>"

#, fuzzy
#~ msgid "<b>File _System:</b>"
#~ msgstr "<b>ファイルシステム:</b>"

#, fuzzy
#~ msgid "R_AID Level:"
#~ msgstr "RAID デバイス"

#~ msgid "Configure selected mountpoint."
#~ msgstr "選択したマウントポイントの設定を行います。"

#, fuzzy
#~ msgid "Click for help."
#~ msgstr "ヘルプをクリックします"

#~ msgid "<span size=\"small\" foreground=\"white\">AVAILABLE SPACE</span>"
#~ msgstr "<span size=\"small\" foreground=\"white\">利用可能な領域</span>"

#~ msgid "<span size=\"small\" foreground=\"white\">TOTAL SPACE</span>"
#~ msgstr "<span size=\"small\" foreground=\"white\">合計領域</span>"

#~ msgid "Completed"
#~ msgstr "完了"

#~ msgid ""
#~ "(%s)\n"
#~ "Command line mode requires all choices to be specified in a kickstart "
#~ "configuration file."
#~ msgstr ""
#~ "(%s)\n"
#~ "コマンドラインモードではすべての選択肢がキックスタート設定ファイルで指定さ"
#~ "れている必要があります。"

#~ msgid ""
#~ "The following error was found while parsing the kickstart configuration "
#~ "file:\n"
#~ "\n"
#~ "%s"
#~ msgstr ""
#~ "キックスタート設定ファイルの解析中に次のエラーが見つかりました。\n"
#~ "\n"
#~ "%s"

#~ msgid ""
#~ "(%s)\n"
#~ "%s"
#~ msgstr ""
#~ "(%s)\n"
#~ "%s"

#~ msgid "In interactive step can't continue. (%s)"
#~ msgstr "対話ステップを続行できません。(%s)"

#~ msgid ""
#~ "An unhandled exception has occurred.  This is most likely a bug.  Please "
#~ "save a copy of the detailed exception and file a bug report"
#~ msgstr ""
#~ "未処理の例外が発生しました。バグの可能性が考えられます。すべてのメッセージ"
#~ "をコピーし、バグとして報告してください。"

#~ msgid " with the provider of this software."
#~ msgstr "このソフトウェアの提供者と共に"

#~ msgid " against anaconda at %s"
#~ msgstr "anaconda の %s に対して"

#~ msgid "Running post install scripts"
#~ msgstr "インストールの後処理スクリプトを実行中"

#~ msgid "Install on System"
#~ msgstr "システム上にインストール"

#~ msgid "Exit installer"
#~ msgstr "インストーラーを終了する"

#~ msgid "_Exit installer"
#~ msgstr "インストーラーを終了する(_E)"

#~ msgid ""
#~ "After shutdown, please perform a manual IPL from %s to continue "
#~ "installation."
#~ msgstr ""
#~ "シャットダウンの後に、%s から手動で IPL を実行してインストールを継続してく"
#~ "ださい"

#~ msgid "IP address is missing."
#~ msgstr "IP アドレスがありません。"

#~ msgid ""
#~ "IPv4 addresses must contain four numbers between 0 and 255, separated by "
#~ "periods."
#~ msgstr ""
#~ "IPv4 アドレスは、ピリオドで区切られた 0 から 255 までの 4 つの数字を含まな"
#~ "ければなりません。"

#~ msgid "'%s' is not a valid IPv6 address."
#~ msgstr "%s は有効な IPv6 アドレスではありません。"

#~ msgid "'%s' is an invalid IP address."
#~ msgstr "'%s' は、有効な IP アドレスではありません。"

#~ msgid "bootloader device"
#~ msgstr "ブートローダーデバイス"

#~ msgid "First sector of boot partition"
#~ msgstr "ブートパーティションの最初のセクタ"

#~ msgid "Master Boot Record"
#~ msgstr "Master Boot Record"

#~ msgid "EFI System Partition"
#~ msgstr "EFI システムパーティション"

#~ msgid "Apple EFI Boot Partition"
#~ msgstr "Apple EFI Boot パーティション"

#~ msgid "PReP Boot Partition"
#~ msgstr "PReP ブートパーティション"

#~ msgid "Apple Bootstrap Partition"
#~ msgstr "Apple ブートストラップパーティション"

#~ msgid "DASD"
#~ msgstr "DASD"

#~ msgid "zFCP"
#~ msgstr "zFCP"

#~ msgid "U-Boot Partition"
#~ msgstr "U-Boot パーティション"

#~ msgid "%s MB"
#~ msgstr "%s MB"

#~ msgid "%s KB"
#~ msgstr "%s KB"

#~ msgid "%s Byte"
#~ msgid_plural "%s Bytes"
#~ msgstr[0] "%s バイト"

#~ msgid "<b>Upgrading %(pkgStr)s</b> (%(size)s)\n"
#~ msgstr "<b>%(pkgStr)s をアップグレード中</b> (%(size)s)\n"

#~ msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
#~ msgstr "<b>%(pkgStr)s のインストール</b> (%(size)s)\n"

#~ msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
#~ msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
#~ msgstr[0] "完了したパッケージ: %(numpkgs)d 個中 %(donepkgs)d 個が完了"

#~ msgid "<b>Cleaning up %s</b>"
#~ msgstr "<b>%s をクリーンナップ中</b>"

#~ msgid "cpio"
#~ msgstr "cpio"

#~ msgid "unpack"
#~ msgstr "展開"

#~ msgid "script"
#~ msgstr "スクリプト"

#~ msgid "Error Installing Package"
#~ msgstr "パッケージのインストールでエラー"

#~ msgid ""
#~ "A %s error occurred when installing the %s package.  This could indicate "
#~ "errors when reading the installation media.  Installation cannot continue."
#~ msgstr ""
#~ "%s エラーが %s パッケージのインストール中に発生しました。インストールメ"
#~ "ディアの読み込み中に問題が発生した可能性があります。インストール作業を続行"
#~ "できません。"

#~ msgid "Wrong Disc"
#~ msgstr "不適切なディスクです"

#~ msgid "That's not the correct %s disc."
#~ msgstr "正しい %s ディスクではありません。"

#~ msgid "Repository %r is missing name in configuration, using id"
#~ msgstr "リポジトリー %r は設定内で名前がありません。id を使用します。"

#~ msgid "No Network Available"
#~ msgstr "ネットワークは使用できません。"

#~ msgid ""
#~ "Some of your software repositories require networking, but there was an "
#~ "error enabling the network on your system."
#~ msgstr ""
#~ "ソフトウェアリポジトリーの一部はネットワークを必要とします。しかし、使用中"
#~ "のシステムでネットワークの有効化にエラーが発生しました。"

#~ msgid "Re_boot"
#~ msgstr "再起動(_B)"

#~ msgid "_Eject"
#~ msgstr "ディスクを取り出す(_E)"

#~ msgid ""
#~ "The file %s cannot be opened.  This is due to a missing file, a corrupt "
#~ "package or corrupt media.  Please verify your installation source.\n"
#~ "\n"
#~ "If you exit, your system will be left in an inconsistent state that will "
#~ "likely require reinstallation.\n"
#~ "\n"
#~ msgstr ""
#~ "ファイル %s を開けません。ファイルが見つからないか、パッケージやメディアが"
#~ "破損している可能性があります。インストール元を検証してください。\n"
#~ "\n"
#~ "終了するとシステムは矛盾した状態となり、再インストールを必要とする可能性が"
#~ "高くなります。\n"
#~ "\n"

#~ msgid "Retrying"
#~ msgstr "再試行中"

#~ msgid "Retrying download."
#~ msgstr "ダウンロードの再試行中。"

#~ msgid ""
#~ "There was an error running your transaction for the following reason: %s\n"
#~ msgstr ""
#~ "トランザクションの実行中に次のような理由でエラーが発生しました。%s\n"

#~ msgid "_Back"
#~ msgstr "戻る(_B)"

#~ msgid ""
#~ "There was an error running your transaction for the following reason: "
#~ "%s.\n"
#~ msgstr "トランザクションを実行中に次のエラーが発生しました: %s\n"

#~ msgid "Error Running Transaction"
#~ msgstr "トランザクション実行中にエラーが発生しました。"

#~ msgid "file conflicts"
#~ msgstr "ファイル競合"

#~ msgid "older package(s)"
#~ msgstr "旧パッケージ"

#~ msgid "insufficient disk space"
#~ msgstr "ディスク容量の不足"

#~ msgid "insufficient disk inodes"
#~ msgstr "ディスク inode の不足"

#~ msgid "package conflicts"
#~ msgstr "パッケージ競合"

#~ msgid "package already installed"
#~ msgstr "パッケージはすでにインストールされています"

#~ msgid "required package"
#~ msgstr "必要なパッケージ"

#~ msgid "package for incorrect arch"
#~ msgstr "不適切なアーキテクチャ用のパッケージ"

#~ msgid "package for incorrect os"
#~ msgstr "不適切な OS 用のパッケージ"

#~ msgid ""
#~ "There were file conflicts when checking the packages to be installed:\n"
#~ "%s\n"
#~ msgstr ""
#~ "インストールするパッケージに、競合するファイルがみつかりました:\n"
#~ "%s\n"

#~ msgid ""
#~ "There was an error running your transaction for the following reason(s): "
#~ "%s.\n"
#~ msgstr ""
#~ "トランザクションの実行中に次のような理由でエラーが発生しました: %s\n"

#~ msgid ""
#~ "Unable to read group information from repositories.  This is a problem "
#~ "with the generation of your install tree."
#~ msgstr ""
#~ "リポジトリーからグループ情報を読み取ることはできません。これは、インストー"
#~ "ルツリーの生成の問題です。"

#~ msgid "Edit"
#~ msgstr "編集"

#~ msgid ""
#~ "Unable to read package metadata. This may be due to a missing repodata "
#~ "directory.  Please ensure that your install tree has been correctly "
#~ "generated.\n"
#~ "\n"
#~ "%s"
#~ msgstr ""
#~ "パッケージのメタデータを読めません。repodata ディレクトリーが見つからない"
#~ "のが原因かもしれません。インストールツリーが正しく構築されているか確認して"
#~ "ください。\n"
#~ "\n"
#~ "%s"

#~ msgid ""
#~ "Some of the packages you have selected for install are missing "
#~ "dependencies.  You can exit the installation, go back and change your "
#~ "package selections, or continue installing these packages without their "
#~ "dependencies.  If you continue, these packages may not work correctly due "
#~ "to missing components."
#~ msgstr ""
#~ "インストールするために選択したパッケージの一部は依存関係が欠如していま"
#~ "す。 インストールを終了してパッケージ選択に戻るか、または依存関係のない"
#~ "パッケージの インストールを継続してください。継続する場合、欠如したコン"
#~ "ポーネントのために これらのパッケージは正常に機能しない可能性があります。"

#~ msgid ""
#~ "Your selected packages require %d MB of free space for installation, but "
#~ "you do not have enough available.  You can change your selections or exit "
#~ "the installer."
#~ msgstr ""
#~ "選択したパッケージはインストールに %d MB の空き領域を必要としますが、充分"
#~ "な空きがありません。選択を変更するか、またはインストーラーを終了してくださ"
#~ "い。"

#~ msgid "Post Upgrade"
#~ msgstr "アップグレード後"

#~ msgid "Performing post-upgrade configuration"
#~ msgstr "アップグレード後の設定を実行中。"

#~ msgid "Post Installation"
#~ msgstr "インストール後"

#~ msgid "Performing post-installation configuration"
#~ msgstr "インストール後の設定を実行中"

#~ msgid "Installation Starting"
#~ msgstr "インストールを開始しています"

#~ msgid "Starting installation process"
#~ msgstr "インストール処理の開始"

#~ msgid "Dependency Check"
#~ msgstr "依存関係チェック"

#~ msgid "Checking dependencies in packages selected for installation"
#~ msgstr "インストール対象パッケージの依存関係をチェック中。"

#~ msgid "Retrieving installation information."
#~ msgstr "インストール情報を読み出し中。"

#~ msgid "Retrieving installation information for %s."
#~ msgstr "%s に関するインストール情報を読み出し中。"

#~ msgid ""
#~ "The default installation of %s includes a set of software applicable for "
#~ "general internet usage. You can optionally select a different set of "
#~ "software now."
#~ msgstr ""
#~ "%s のデフォルトインストールには一般的なネットワーク環境で利用できるソフト"
#~ "ウェアのセットが含まれています。オプションとして異なる組み合わせのソフト"
#~ "ウェアを選択することができます。"

#~ msgid "Graphical Desktop"
#~ msgstr "デスクトップ"

#~ msgid "Software Development"
#~ msgstr "ソフトウェア開発"

#~ msgid "Minimal"
#~ msgstr "最小限"

#~ msgid ""
#~ "The default installation of %s is a minimum install. You can optionally "
#~ "select a different set of software now."
#~ msgstr ""
#~ "%s のデフォルトインストールは最小限インストールです。オプションとして追加"
#~ "のソフトウェアを選択することができます。"

#~ msgid "Upgrading"
#~ msgstr "アップグレード中"

#~ msgid "This partition is holding the data for the hard drive install."
#~ msgstr ""
#~ "このパーティションはハードディスクインストール用のデータを保有しています。"

#~ msgid "You cannot delete a partition of a LDL formatted DASD."
#~ msgstr "DASD 形式でフォーマットされた LDL パーティションは削除できません。"

#~ msgid "This device is part of the RAID device %s."
#~ msgstr "このデバイスは RAID デバイス %s の一部です。"

#~ msgid "This device is part of a RAID device."
#~ msgstr "このデバイスは RAID デバイスの一部です。"

#~ msgid "This device is part of an inconsistent LVM Volume Group."
#~ msgstr "このデバイスは一貫性のない LVM ボリュームグループの一部です。"

#~ msgid "This device is part of the LVM volume group '%s'."
#~ msgstr "このデバイスは LVM ボリュームグループ %s の一部です。"

#~ msgid "This device is part of a LVM volume group."
#~ msgstr "このデバイスは LVM ボリュームグループの一部です。"

#~ msgid ""
#~ "This device is an extended partition which contains logical partitions "
#~ "that cannot be deleted:\n"
#~ "\n"
#~ msgstr ""
#~ "このデバイスは拡張パーティションです。この中の論理パーティションは先に 削"
#~ "除できません:\n"
#~ "\n"

#~ msgid ""
#~ "Installing on a USB device.  This may or may not produce a working system."
#~ msgstr ""
#~ "USB デバイス上にインストールしています。稼動するシステムが作成されることも"
#~ "ありますが、されないこともあります。"

#~ msgid ""
#~ "Installing on a FireWire device.  This may or may not produce a working "
#~ "system."
#~ msgstr ""
#~ "FireWire デバイス上にインストールしています。稼動するシステムが作成される"
#~ "こともありますが、されないこともあります。"

#~ msgid "you have not created a bootloader stage1 target device"
#~ msgstr ""
#~ "対象のデバイスでブートローダーの stage1 を作成することができませんでした。"

#~ msgid "Linux on %s"
#~ msgstr "%s 上の Linux"

#~ msgid "Unknown Linux"
#~ msgstr "未知の Linux"

#~ msgid "%(product)s Linux %(version)s for %(arch)s"
#~ msgstr "%(product)s Linux %(version)s － %(arch)s"

#~ msgid "Preparing %d DASD device for use with Linux..."
#~ msgid_plural "Preparing %d DASD devices for use with Linux..."
#~ msgstr[0] "Linuxで使うために %d 個のDASDのデバイスを準備中..."

#~ msgid "Resizing filesystem on %(device)s"
#~ msgstr "%(device)s のファイルシステムの容量変更中"

#~ msgid "Migrating filesystem on %(device)s"
#~ msgstr "%(device)s のファイルシステムを移行中"

#~ msgid "vginfo failed for %s"
#~ msgstr "%s 用の vginfo に失敗"

#~ msgid "lvs failed for %s"
#~ msgstr "%s 用の lvs に失敗"

#~ msgid "A RAID%(raidLevel)d set requires at least %(minMembers)d member"
#~ msgid_plural ""
#~ "A RAID%(raidLevel)d set requires at least %(minMembers)d members"
#~ msgstr[0] ""
#~ "RAID%(raidLevel)d には少なくても %(minMembers)d 個のディスクが必要です。"

#~ msgid "Back"
#~ msgstr "戻る"

#~ msgid "Confirm"
#~ msgstr "確認"

#~ msgid ""
#~ "Are you sure you want to skip entering a passphrase for device %s?\n"
#~ "\n"
#~ "If you skip this step the device's contents will not be available during "
#~ "installation."
#~ msgstr ""
#~ "本当にデバイス %s のパスフレーズの入力を省略しますか?\n"
#~ "\n"
#~ "このステップをスキップすると、インストール中のデバイス内のコンテンツへのア"
#~ "クセスはできません。"

#~ msgid "FCoE not available"
#~ msgstr "FCoE は使用できません"

#~ msgid "Unknown return code: %d."
#~ msgstr "不明なリターンコードです: %d"

#~ msgid "%(type)s filesystem check failure on %(device)s: "
#~ msgstr "%(device)s 上で %(type)s ファイルシステムのチェックに失敗: "

#~ msgid "Unrecoverable Error"
#~ msgstr "修正不可能なエラー"

#~ msgid "File system errors left uncorrected."
#~ msgstr "ファイルシステムエラーが未修正のままです。"

#~ msgid "Usage or syntax error."
#~ msgstr "ユーザーまたは構文のエラー"

#~ msgid "e2fsck cancelled by user request."
#~ msgstr "ユーザーの指示で e2fsck がキャンセルされました。"

#~ msgid "Shared library error."
#~ msgstr "共有ライブラリのエラー"

#~ msgid ""
#~ "Recoverable errors have been detected or dosfsck has discovered an "
#~ "internal inconsistency."
#~ msgstr ""
#~ "復元可能なエラーが検出されたか、または dosfsck が内部の整合性問題を発見し"
#~ "ました。"

#~ msgid "Usage error."
#~ msgstr "使用法エラー"

#~ msgid "Encrypted"
#~ msgstr "暗号化"

#~ msgid "Unable to change iSCSI initiator name once set"
#~ msgstr "iSCSI イニシエータ名はセットされた後は変更できません"

#~ msgid "iSCSI not available"
#~ msgstr "iSCSI は使用できません"

#~ msgid "No initiator name set"
#~ msgstr "イニシエーター名がありません"

#~ msgid "Logging in to iSCSI node"
#~ msgstr "iSCSI ノードにログイン中"

#~ msgid "Logging in to iSCSI node %s"
#~ msgstr "iSCSI ノード %s にログイン中"

#~ msgid "No iSCSI nodes discovered"
#~ msgstr "iSCSI ノードが見つかりませんでした"

#~ msgid "No new iSCSI nodes discovered"
#~ msgstr "新しい iSCSI ノードは見つかりませんでした。"

#~ msgid "Could not log in to any of the discovered nodes"
#~ msgstr "見つかったノードすべてにログインできませんでした"

#~ msgid "No usable disks selected"
#~ msgstr "使用可能なディスクが未選択"

#~ msgid "Not enough free space on disks for automatic partitioning"
#~ msgstr ""
#~ "自動パーティション構成のために必要なディスクの空き領域が不足しています。"

#~ msgid "unable to allocate aligned partition"
#~ msgstr "アラインされたパーティションを割り当てることができません。"

#~ msgid "can't allocate partitions without platform data"
#~ msgstr ""
#~ "プラットフォームデータなしでパーティションを割り当てることはできません。"

#~ msgid "disk %s inaccessible"
#~ msgstr "ディスク %s はアクセスできません"

#~ msgid ""
#~ "partition is too small for %(format)s formatting (allowable size is "
#~ "%(minSize)d MB to %(maxSize)d MB)"
#~ msgstr ""
#~ "%(format)s でフォーマットするにはパーティションが小さ過ぎます。(割り当てサ"
#~ "イズは %(minSize)d MB から %(maxSize)d MB までが指定可能)"

#~ msgid ""
#~ "partition is too large for %(format)s formatting (allowable size is "
#~ "%(minSize)d MB to %(maxSize)d MB)"
#~ msgstr ""
#~ "%(format)s でフォーマットするにはパーティションが大き過ぎます。(割り当てサ"
#~ "イズは %(minSize)d MB から %(maxSize)d MB までが指定可能)"

#~ msgid "not enough free space on disks"
#~ msgstr "ディスクの空き領域が不足しています"

#~ msgid "not enough free space after creating extended partition"
#~ msgstr ""
#~ "拡張パーティションを作成するためのディスクの空き領域が不足しています。"

#~ msgid "DiskChunk requests must be of type PartitionRequest"
#~ msgstr ""
#~ "DiskChunk リクエストは PartitionRequest のタイプでなければなりません。"

#~ msgid "partitions allocated outside disklabel limits"
#~ msgstr "ディスクラベルの上限を超える割り当てパーティション"

#~ msgid "VGChunk requests must be of type LVRequest"
#~ msgstr "VGChunk リクエストは LVRequest のタイプでなければなりません。"

#~ msgid "not enough space for LVM requests"
#~ msgstr "LVM リクエストのために空き領域が不足しています。"

#~ msgid "You have not specified a device number or the number is invalid"
#~ msgstr "デバイス番号を指定していないか番号が無効です。"

#~ msgid "You have not specified a worldwide port name or the name is invalid."
#~ msgstr "WWPN を指定していないか、そのポート名が無効です。"

#~ msgid "You have not specified a FCP LUN or the number is invalid."
#~ msgstr "FCP FUN を指定していないか、番号が無効です。"

#~ msgid "zFCP device %s not found, not even in device ignore list."
#~ msgstr "zFCP デバイス %s が見つからず、デバイス無視リストにもありません。"

#~ msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
#~ msgstr ""
#~ "zFCP デバイス %(devnum)s を オンライン (%(e)s) にセットできませんでした。"

#~ msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
#~ msgstr ""
#~ "WWPN %(wwpn)s を zFCP デバイス %(devnum)s (%(e)s) に追加できません。"

#~ msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
#~ msgstr "WWPN %(wwpn)s が zFCP デバイス %(devnum)s で見つかりません。"

#~ msgid ""
#~ "Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s "
#~ "(%(e)s)."
#~ msgstr ""
#~ "LUN %(fcplun)s を zFCP デバイス %(devnum)s (%(e)s)上で WWPN %(wwpn)s に追"
#~ "加できません、。"

#~ msgid ""
#~ "LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already "
#~ "configured."
#~ msgstr ""
#~ "LUN %(fcplun)s は、zFCP デバイス %(devnum)s 上の WWPN %(wwpn)s ですでに設"
#~ "定されています。"

#~ msgid ""
#~ "Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on "
#~ "zFCP device %(devnum)s (%(e)s)."
#~ msgstr ""
#~ "zFCP デバイス %(devnum)s (%(e)s) 上の WWPN %(wwpn)s で LUN %(fcplun)s の "
#~ "失敗属性を読みこむことが できませんでした。"

#~ msgid ""
#~ "Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
#~ "again."
#~ msgstr ""
#~ "zFCP デバイス %(devnum)s 上の WWPN %(wwpn)s で失敗した LUN %(fcplun)s が "
#~ "再度削除されました。"

#~ msgid ""
#~ "Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s "
#~ "%(fcplun)s (%(e)s)."
#~ msgstr ""
#~ "zFCP %(devnum)s %(wwpn)s %(fcplun)s (%(e)s) の SCSI デバイスを正しく消すこ"
#~ "とができませんでした。"

#~ msgid ""
#~ "Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device "
#~ "%(devnum)s (%(e)s)."
#~ msgstr ""
#~ "zFCP デバイス %(devnum)s (%(e)s) 上の WWPN %(wwpn)s で LUN %(fcplun)s を削"
#~ "除できませんでした。"

#~ msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
#~ msgstr ""
#~ "zFCP デバイス %(devnum)s (%(e)s) 上で WWPN %(wwpn)s を削除できませんでし"
#~ "た。"

#~ msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
#~ msgstr ""
#~ "zFCP デバイス %(devnum)s をオフライン (%(e)s) に設定できませんでした。"

#~ msgid "Install hub"
#~ msgstr "インストールハブ"

#~ msgid "STORAGE"
#~ msgstr "ストレージ"

#~ msgid ""
#~ "When all items marked with this icon are complete, installation will "
#~ "automatically continue."
#~ msgstr ""
#~ "このアイコンの付いたすべての項目が完了すると、自動的にインストールが継続し"
#~ "ます。"

#~ msgid "Note: pool servers may not be available all the time"
#~ msgstr "注記:  プールサーバーは常時利用可能ではないかも知れません。"

#~ msgid "Connected: %s"
#~ msgstr "接続しています: %s"

#~ msgid "Error setting root password"
#~ msgstr "root パスワードの設定エラーです"

#~ msgid "_Remove Packages"
#~ msgstr "パッケージを削除 (_R)"

#~ msgid "Getting info about requested repository"
#~ msgstr "要求されたレポジトリの情報を取得中…"

#~ msgid "enter URL of your desired repository"
#~ msgstr "ご希望のレポジトリの URL を入力してください"

#~ msgid "Whole disks are not editable."
#~ msgstr "ディスクは編集できません"

#~ msgid "%s of %s"
#~ msgstr "%s のうち %s"

#~ msgid "00"
#~ msgstr "00"

#~ msgid " "
#~ msgstr " "

#~ msgid "Choose your add-ons"
#~ msgstr "使用アドオンを選択します"

#~ msgid "_Add custom add-on..."
#~ msgstr "カスタムアドオンを追加(_A)"

#~ msgid "Let me customize the _partitioning of the disks instead."
#~ msgstr ""
#~ "代わりにディスクのパーティション設定をカスタマイズさせて下さい。(_P)"

#~ msgid "disks size"
#~ msgstr "ディスクのサイズ"

#~ msgid "Space in selected disks reclaimable by deleting existing partitions."
#~ msgstr "既存パーティションの削除により選択したディスク内の獲得できる領域"

#~ msgid "I don't need help; let me customize disk _partitioning."
#~ msgstr ""
#~ "ヘルプは必要ありません。 ディスクのパーティション設定をカスタマイズしま"
#~ "す。"

#~ msgid "Test the selected layout below:"
#~ msgstr "選択したレイアウトでテストしてください:"

#~ msgid "ADD A CUSTOM ADD-ON"
#~ msgstr "カスタムアドオンを追加"

#~ msgid "Where is the yum repository for your add-on?"
#~ msgstr "アドオン用の yum リポジトリを選択してください。"

#~ msgid "Repository"
#~ msgstr "レポジトリ"

#~ msgid "Standard YUM repository:"
#~ msgstr "標準の YUM レポジトリ"

#~ msgid "Set _keyboard to default layout for selected language."
#~ msgstr "選択した言語でデフォルトのキーボードに設定(_K)"

#~ msgid "eg: \"/\", \"/home\", \"swap\" (minus the quotation marks)"
#~ msgstr "例: \"/\"、 \"/home\"、 \"swap\" (引用符は除く)"

#~ msgid "_Back to destination selection"
#~ msgstr "目的地選択に戻る(_B)"

#~ msgid "<b>Desired Capacity (MB):</b>"
#~ msgstr "<b>要望する容量 (MB):</b>"

#~ msgid "Redundancy (mirror)"
#~ msgstr "冗長 (ミラー)"

#~ msgid "(-0Gb)"
#~ msgstr "(-0Gb)"

#~ msgid "Optimized performance (stripe)"
#~ msgstr "最適化したパフォーマンス (ストライプ)"

#~ msgid "Error detection (parity)"
#~ msgstr "エラー検出 (パリティ)"

#~ msgid "Distributed"
#~ msgstr "分散"

#~ msgid "Redundant"
#~ msgstr "冗長"

#~ msgid "_Customize..."
#~ msgstr "カスタマイズする(_C)..."

#~ msgid ""
#~ "This %s device is missing %d of %d %s. You can remove it or select a "
#~ "different device."
#~ msgstr ""
#~ "%s デバイスの %d / %d の %s が見つかりません。削除するか他のデバイスを選択"
#~ "してください。"

#~ msgid "addButton"
#~ msgstr "追加ボタン"

#~ msgid "removeButton"
#~ msgstr "removeButton"

#~ msgid "configureButton"
#~ msgstr "設定ボタン"

#~ msgid "CONFIGURE VOLUME GROUP"
#~ msgstr "構成するボリュームグループ"

#~ msgid "Id"
#~ msgstr "ID"

#~ msgid "keymap warning label"
#~ msgstr "キー対応表警告ラベル"

#~ msgid "<b>%s disks; %s reclaimable space</b> (in filesystems)"
#~ msgstr "<b>%s 個のディスク; %s つの獲得可能領域</b> (ファイルシステム内)"

#~ msgid "Total selected space to reclaim:  <b>%s</b>"
#~ msgstr "選択した取得する領域の合計:　<b>%s</b>"

#~ msgid "Installation requires a total of <b>%s</b> for system data."
#~ msgstr "インストールには、システムデータ用に合計 <b>%s</b> が必要です。"

#~ msgid "Root"
#~ msgstr "Root"
