# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Red Hat, Inc.
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# dcantrel <dcantrell@redhat.com>, 2011.
# Dimitris Glezos <glezos@indifex.com>, 2011.
# Hajime Taira <htaira@redhat.com>, 2010-2012.
# Hirofumi Saito <hi_saito@yk.rim.or.jp>, 2004-2006.
# Hyu_gabaru Ryu_ichi <hyu_gabaru@yahoo.co.jp>, 2007,2009.
# James Hashida <khashida@redhat.com>, 2002-2003.
# Kiyoto Hashida <khashida@redhat.com>, 2007-2010,2012.
# Kiyoto James Hashida <khashida@redhat.com>, 2002-2003,2006-2010.
# Makoto Mizukami <mmk9060@aol.com>, 2008.
# Naoki Shigematsu <sigematu@linuxml.net>, 2004.
#   <noriko@fedoraproject.org>, 2012.
# Noriko Mizumoto <noriko@fedoraproject.org>, 2010.
# Noriko Mizumoto <noriko@redhat.com>, 2003-2004,2006,2008-2009.
# SATO Satoru <ssato@redhat.com>, 2001.
# Tadashi Jokagi <fedora@elf.no-ip.org>, 2004-2005.
# Tomoyuki KATO <tomo@dream.daynight.jp>, 2011-2012.
#   <www.carrotsoft@gmail.com>, 2012.
# Yoshinari Takaoka <mumumu@mx.edit.ne.jp>, 2004.
msgid ""
msgstr ""
"Project-Id-Version: Anaconda\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2013-01-07 16:55-0800\n"
"PO-Revision-Date: 2013-01-04 23:55+0000\n"
"Last-Translator: Brian Lane <bcl@redhat.com>\n"
"Language-Team: Japanese <trans-ja@lists.fedoraproject.org>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=1; plural=0;\n"

#: anaconda:344
#, c-format
msgid ""
"%s requires %s MB of memory to install, but you only have %s MB on this "
"machine.\n"
msgstr ""
"インストールするために %s は、最低 %s MB のメモリーを必要とします。お使いのシ"
"ステムには %s MB しか搭載されていません。\n"

#: anaconda:346
#, c-format
msgid ""
"The %s graphical installer requires %s MB of memory, but you only have %s MB."
msgstr ""
"%s のグラフィカルインストーラーは、最低 %s MB のメモリーを必要とします。お使"
"いのシステムには %s MB のメモリーしか搭載されていません。"

#: anaconda:351
msgid "Not enough RAM"
msgstr "メモリーが足りません。"

#: anaconda:352
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""
"次のとおり実行してテキストモードインストーラーを試して下さい:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
"なお、この操作は root でのターミナルから実行します。"

#: anaconda:355
msgid " Starting text mode."
msgstr " テキストモードを開始しています。"

#: anaconda:382 pyanaconda/rescue.py:268 pyanaconda/rescue.py:301
#: pyanaconda/rescue.py:314 pyanaconda/rescue.py:382 pyanaconda/rescue.py:398
#: pyanaconda/rescue.py:409
msgid "OK"
msgstr "OK"

#: anaconda:484
msgid ""
"Text mode provides a limited set of installation options. It does not allow "
"you to specify your own partitioning layout or package selections. Would you "
"like to use VNC mode instead?"
msgstr ""
"テキストモードによるインストールは限定的なインストールオプションしか提供され"
"ず、パーティション設定やパッケージ選択の指定が行えません。代わりに VNC モード"
"を使用しますか？"

#: anaconda:508
msgid "DISPLAY variable not set. Starting text mode."
msgstr "DISPLAY 変数がセットされていません。テキストモードで起動します。"

#: anaconda:516
msgid "Graphical installation is not available. Starting text mode."
msgstr "グラフィカルインストールは使用できません。テキストモードを起動します。"

#: anaconda:627
#, c-format
msgid "Please ssh install@%s to begin the install."
msgstr "ssh install@%s を実行して、インストールを始めて下さい。"

#: anaconda:629
msgid "Please ssh install@<host> to continue installation."
msgstr "ssh install@<host> を実行して、インストールを継続して下さい。"

#: pyanaconda/bootloader.py:239
msgid "/boot filesystem"
msgstr "/boot ファイルシステム"

#: pyanaconda/bootloader.py:388
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following raid levels: %s."
msgstr "'%s' を含む RAID セットは、次の RAID レベルのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:396
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following metadata "
"versions: %s."
msgstr ""
"'%s' を含む RAID セットは、次のメタデータのバージョンのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:404
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following device types: %s."
msgstr "'%s' を含む RAID セットは、次のデバイスタイプのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:420
#, python-format
msgid "%s must have one of the following disklabel types: %s."
msgstr "%s は次のディスクラベルのタイプのいずれかが必要です: %s"

#: pyanaconda/bootloader.py:432
#, python-format
msgid "%s cannot be of type %s."
msgstr "%s は %s タイプにすることはできません。"

#: pyanaconda/bootloader.py:438
#, python-format
msgid "%s must be mounted on one of %s."
msgstr "%s を %s の１つにマウントする必要があります。"

#: pyanaconda/bootloader.py:450
#, python-format
msgid "%s must be between %d and %d MB in size"
msgstr "%s のサイズは %d MB から %d MB の間でなければなりません。"

#: pyanaconda/bootloader.py:455
#, python-format
msgid "%s must not be smaller than %dMB."
msgstr "%s のサイズは %d MB 以下でなければなりません。"

#: pyanaconda/bootloader.py:464
#, python-format
msgid "%s must not be larger than %dMB."
msgstr "%s のサイズは %d MB 以上でなければなりません。"

#: pyanaconda/bootloader.py:482
#, python-format
msgid "%s must be within the first %dMB of the disk."
msgstr "%s はディスクの先頭から %dMB 以内の位置に配置しなければなりません。"

#: pyanaconda/bootloader.py:492
#, python-format
msgid "%s must be on a primary partition."
msgstr "%s はプライマリパーティション上になければなりません。"

#: pyanaconda/bootloader.py:616 pyanaconda/bootloader.py:706
#, python-format
msgid "%s cannot be on an encrypted block device."
msgstr "%s は暗号化ブロックデバイス上に置くことができません。"

#: pyanaconda/bootloader.py:664
#, python-format
msgid "%s cannot be of type %s"
msgstr "%s は %s タイプにすることはできません。"

#: pyanaconda/bootloader.py:1585
#, python-format
msgid ""
"%s may not have enough space for grub2 to embed core.img when using the %s "
"filesystem on %s"
msgstr ""
"%3s 上の %2s ファイルシステムを使用している場合、 grub2によって組み込まれる "
"core.img 用の領域が %1s には不足している可能性があります。"

#: pyanaconda/cmdline.py:66
msgid "Completed"
msgstr "完了"

#: pyanaconda/cmdline.py:74
msgid "In progress"
msgstr "進行中"

#: pyanaconda/cmdline.py:87
#, python-format
msgid ""
"(%s)\n"
"Command line mode requires all choices to be specified in a kickstart "
"configuration file."
msgstr ""
"(%s)\n"
"コマンドラインモードではすべての選択肢がキックスタート設定ファイルで指定され"
"ている必要があります。"

#: pyanaconda/cmdline.py:104
#, python-format
msgid ""
"The following error was found while parsing the kickstart configuration "
"file:\n"
"\n"
"%s"
msgstr ""
"キックスタート設定ファイルの解析中に次のエラーが見つかりました。\n"
"\n"
"%s"

#: pyanaconda/cmdline.py:113
#, python-format
msgid ""
"(%s)\n"
"%s"
msgstr ""
"(%s)\n"
"%s"

#: pyanaconda/cmdline.py:126 pyanaconda/cmdline.py:131
#: pyanaconda/cmdline.py:137 pyanaconda/cmdline.py:142
#: pyanaconda/ui/tui/hubs/summary.py:58
msgid "Can't have a question in command line mode!"
msgstr "コマンドラインモードでは質問は置けません!"

#: pyanaconda/cmdline.py:161
#, python-format
msgid "In interactive step can't continue. (%s)"
msgstr "対話ステップを続行できません。(%s)"

#: pyanaconda/constants.py:57
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""
"未処理の例外が発生しました。バグの可能性が考えられます。すべてのメッセージを"
"コピーし、バグとして報告してください。"

#: pyanaconda/constants.py:63
msgid " with the provider of this software."
msgstr "このソフトウェアの提供者と共に"

#: pyanaconda/constants.py:67
#, python-format
msgid " against anaconda at %s"
msgstr "anaconda の %s に対して"

#: pyanaconda/constants.py:95
msgid "Start VNC"
msgstr "VNC を起動する"

#: pyanaconda/constants.py:96
msgid "Use text mode"
msgstr "テキストモードを使用する"

#: pyanaconda/install.py:59
msgid "Configuring installed system"
msgstr "インストール済みのシステムを構成"

#: pyanaconda/install.py:71
msgid "Writing network configuration"
msgstr "ネットワーク構成を書き込み中"

#: pyanaconda/install.py:75
msgid "Creating users"
msgstr "ユーザーを作成中"

#: pyanaconda/install.py:82
msgid "Running post install scripts"
msgstr "インストールの後処理スクリプトを実行中"

#: pyanaconda/install.py:130 pyanaconda/packaging/livepayload.py:133
#: pyanaconda/packaging/yumpayload.py:1631
msgid "Performing post-install setup tasks"
msgstr "インストール後設定タスクを実行中"

#: pyanaconda/install.py:134
msgid "Installing bootloader"
msgstr "ブートローダーをインストール中"

#: pyanaconda/installclass.py:68
msgid "Install on System"
msgstr "システム上にインストール"

#: pyanaconda/installinterfacebase.py:51
msgid "Error Setting Up Repository"
msgstr "リポジトリーの設定中にエラー"

#: pyanaconda/installinterfacebase.py:52
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Installation can not continue."
msgstr ""
"インストールリポジトリーを設定中に次のエラーが発生しました。\n"
"\n"
"%(e)s\n"
"\n"
"インストール作業を継続できません。"

#: pyanaconda/installinterfacebase.py:58
msgid "Exit installer"
msgstr "インストーラーを終了する"

#: pyanaconda/installinterfacebase.py:62
#, python-format
msgid ""
"The installation was stopped due to what seems to be a problem with your "
"hardware. The exact error message is:\n"
"\n"
"%s.\n"
"\n"
" The installer will now terminate."
msgstr ""
"インストール作業はハードウェアに問題があると思われる症状が発生したため停止さ"
"れました。正確なエラーメッセージは次のとおりです：\n"
"\n"
"%s\n"
"\n"
" インストーラーを終了します。"

#: pyanaconda/installinterfacebase.py:65
msgid "Hardware Error Encountered"
msgstr "ハードウェアエラーが発生しました。"

#: pyanaconda/installinterfacebase.py:69 pyanaconda/yuminstall.py:263
#: pyanaconda/yuminstall.py:409 pyanaconda/yuminstall.py:835
#: pyanaconda/yuminstall.py:1013 pyanaconda/yuminstall.py:1018
#: pyanaconda/yuminstall.py:1055 pyanaconda/yuminstall.py:1107
#: pyanaconda/yuminstall.py:1113 pyanaconda/yuminstall.py:1269
#: pyanaconda/yuminstall.py:1284 pyanaconda/yuminstall.py:1339
#: pyanaconda/yuminstall.py:1534 pyanaconda/yuminstall.py:1567
#: pyanaconda/yuminstall.py:1590
msgid "_Exit installer"
msgstr "インストーラーを終了する(_E)"

#: pyanaconda/iutil.py:898
msgid "the device containing /boot"
msgstr "/boot を含むデバイス"

#: pyanaconda/iutil.py:900
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from %s to continue installation."
msgstr ""
"シャットダウンの後に、%s から手動で IPL を実行してインストールを継続してくだ"
"さい"

#: pyanaconda/kickstart.py:155
#, python-format
msgid "Escrow certificate %s requires the network."
msgstr "エスクロー証明書 %s にはネットワークが必要です。"

#: pyanaconda/kickstart.py:163
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"escrow 証明書のダウンロード中に次のエラーに 遭遇しました:\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:482
#, python-format
msgid "%s is missing. Cannot setup firewall."
msgstr "%s が足りません。 ファイアーウォールの設定ができません。"

#: pyanaconda/kickstart.py:1466
msgid "Running pre-installation scripts"
msgstr "インストール前スクリプトを実行中"

#: pyanaconda/network.py:94
msgid "Hostname cannot be None or an empty string."
msgstr "ホスト名なし、または空白の文字は設定できません。"

#: pyanaconda/network.py:97
msgid "Hostname must be 255 or fewer characters in length."
msgstr "ホスト名は 255 文字かそれ以下の長さにする必要があります。"

#: pyanaconda/network.py:103
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or "
"'0-9'"
msgstr ""
"ホスト名は 「a-z」 または 「A-Z」または 「0-9」 の範囲の有効な文字で開始しな"
"ければ なりません。"

#: pyanaconda/network.py:111
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.', "
"parts between periods must contain something and cannot start or end with "
"'-'."
msgstr ""
" ホスト名には半角英数 'a-z'、'A-Z'、'0-9'、および記号 '-'、'.' を使用すること"
"ができます。ただし、ピリオドは文字列の途中に使用しなければいけません。また、"
"ホスト名の先頭と終わりには '-' は使用できません。"

#: pyanaconda/network.py:168
msgid "IP address is missing."
msgstr "IP アドレスがありません。"

#: pyanaconda/network.py:172
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""
"IPv4 アドレスは、ピリオドで区切られた 0 から 255 までの 4 つの数字を含まなけ"
"ればなりません。"

#: pyanaconda/network.py:175
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr "%s は有効な IPv6 アドレスではありません。"

#: pyanaconda/network.py:177
#, python-format
msgid "'%s' is an invalid IP address."
msgstr "'%s' は、有効な IP アドレスではありません。"

#: pyanaconda/platform.py:58
msgid "bootloader device"
msgstr "ブートローダーデバイス"

#: pyanaconda/platform.py:59
msgid "RAID Device"
msgstr "RAID デバイス"

#: pyanaconda/platform.py:60
msgid "First sector of boot partition"
msgstr "ブートパーティションの最初のセクタ"

#: pyanaconda/platform.py:158 pyanaconda/platform.py:341
msgid "Master Boot Record"
msgstr "Master Boot Record"

#: pyanaconda/platform.py:194
msgid "EFI System Partition"
msgstr "EFI システムパーティション"

#: pyanaconda/platform.py:223
msgid "Apple EFI Boot Partition"
msgstr "Apple EFI Boot パーティション"

#: pyanaconda/platform.py:248
msgid "PReP Boot Partition"
msgstr "PReP ブートパーティション"

#: pyanaconda/platform.py:271
msgid "Apple Bootstrap Partition"
msgstr "Apple ブートストラップパーティション"

#: pyanaconda/platform.py:300
msgid "DASD"
msgstr "DASD"

#: pyanaconda/platform.py:301
msgid "zFCP"
msgstr "zFCP"

#: pyanaconda/platform.py:366
msgid "U-Boot Partition"
msgstr "U-Boot パーティション"

#: pyanaconda/product.py:54
#, python-format
msgid "%(productName)s %(productVersion)s INSTALLATION"
msgstr "%(productName)s %(productVersion)s インストール"

#: pyanaconda/rescue.py:171 pyanaconda/rescue.py:290 pyanaconda/rescue.py:375
#, python-format
msgid "Run %s to unmount the system when you are finished."
msgstr ""
"メンテナンスが終わったら、システムをアンマウントするために %s を実行してくだ"
"さい。"

#: pyanaconda/rescue.py:174
msgid "When finished please exit from the shell and your system will reboot."
msgstr "完了したらシェルを終了してください。システムが再起動します。"

#: pyanaconda/rescue.py:188
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr "実行するための /bin/sh が見付かりません。シェルを 開始していません。"

#: pyanaconda/rescue.py:224 pyanaconda/rescue.py:297 pyanaconda/rescue.py:307
#: pyanaconda/rescue.py:378 pyanaconda/rescue.py:409
msgid "Rescue"
msgstr "レスキュー"

#: pyanaconda/rescue.py:225
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.  \n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""
"レスキュー環境はここで、ユーザーの Linux インストールを見つけて、それをディレ"
"クトリ %s にマウントする試みをします。その後に、必要な変更をシステムに加える"
"ことができます。このステップを進めたい場合は、「続ける」を選択します。また、"
"「読み込み専用」を選択すると、読み込み/書き込みの代わりに読み込み専用でファイ"
"ルシステムをマウントする選択ができます。\n"
"\n"
"なんらかの理由でこのプロセスが失敗した場合は、「スキップ」を選択すると、この"
"ステップは除外されて直接、コマンドシェルに進みます。\n"

#: pyanaconda/rescue.py:235 pyanaconda/storage/devicetree.py:96
msgid "Continue"
msgstr "続行"

#: pyanaconda/rescue.py:235 pyanaconda/rescue.py:241
msgid "Read-Only"
msgstr "読み取り専用"

#: pyanaconda/rescue.py:235 pyanaconda/rescue.py:237
msgid "Skip"
msgstr "スキップする"

#: pyanaconda/rescue.py:265
msgid "System to Rescue"
msgstr "レスキュー対象システム"

#: pyanaconda/rescue.py:266
msgid "Which device holds the root partition of your installation?"
msgstr "どのデバイスにインストールの root パーティションを置きますか？"

#: pyanaconda/rescue.py:268 pyanaconda/rescue.py:272
msgid "Exit"
msgstr "終了"

#: pyanaconda/rescue.py:287 pyanaconda/rescue.py:372
msgid "The system will reboot automatically when you exit from the shell."
msgstr "シェルを終了するとシステムは自動的に再起動します。"

#: pyanaconda/rescue.py:298
#, python-format
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions. %s"
msgstr ""
"システムに損傷のあるファイルシステムがありマウントしないことを選択していま"
"す。<enter> を押すとシェルが起動され、ファイルシステムの検証(fsck)や パーティ"
"ションのマウント(mount)を行うことができます。 %s"

#: pyanaconda/rescue.py:308
#, python-format
msgid ""
"Your system has been mounted under %(rootPath)s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"
msgstr ""
"システムを %(rootPath)s 下にマウントしています。\n"
"\n"
"シェルを起動するには <enter>キーを押してください。そのシステムを root 環境と"
"して利用するには次のコマンドを実行します:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"

#: pyanaconda/rescue.py:379
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell."
msgstr ""
"システムのいくつか、あるいはすべてをマウントしようと試みている間にエラーが発"
"生しました。いくつかのパーティションは %s の下にマウントされています。\n"
"\n"
"シェルを起動するには [Enter] を押してください。"

#: pyanaconda/rescue.py:387
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr "Linux パーティションがありません。再起動します。\n"

#: pyanaconda/rescue.py:391
msgid " The system will reboot automatically when you exit from the shell."
msgstr " シェルを終了するとシステムは自動的に再起動します。"

#: pyanaconda/rescue.py:395
msgid "Rescue Mode"
msgstr "レスキューモード"

#: pyanaconda/rescue.py:396
#, python-format
msgid "You don't have any Linux partitions. Press return to get a shell.%s"
msgstr ""
"Linux パーティションがありません。<enter>キーを押すとシェルを起動します。%s"

#: pyanaconda/rescue.py:408
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "システムは %s ディレクトリー配下にマウントされます。"

#: pyanaconda/vnc.py:61
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr "%(productName)s %(productVersion)s のインストール"

#: pyanaconda/vnc.py:118
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr "ホスト %(name)s 上の %(productName)s %(productVersion)s インストール"

#: pyanaconda/vnc.py:137
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "ホスト %s 上の vnc クライアントに接続を試行中..."

#: pyanaconda/vnc.py:151
msgid "Connected!"
msgstr "接続しました!"

#: pyanaconda/vnc.py:154
msgid "Will try to connect again in 15 seconds..."
msgstr "15 秒後に再接続を試みます..."

#: pyanaconda/vnc.py:160
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] "%d 回接続を試みた後に断念します。\n"

#: pyanaconda/vnc.py:171
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr ""
"インストールを開始するには、ご使用の vnc クライアントを %s に手動で接続してく"
"ださい。"

#: pyanaconda/vnc.py:173
#, python-format
msgid ""
"Please manually connect your vnc client to <IP ADDRESS>:%s to begin the "
"install. Switch to the shell (Ctrl-B 2) and run 'ip addr' to find the <IP "
"ADDRESS>."
msgstr ""

#: pyanaconda/vnc.py:178
msgid "Starting VNC..."
msgstr "VNC を起動中..."

#: pyanaconda/vnc.py:220
msgid "The VNC server is now running."
msgstr "VNC サーバーが稼動しています。"

#: pyanaconda/vnc.py:224
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Listen モードの VNC Viewer に接続するよう選択しました。\n"
"これは、パスワードを必要としません。もしパスワードを設定すると、\n"
"VNC Viewew への接続失敗の原因になります。\n"
"\n"

#: pyanaconda/vnc.py:229
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"警告!!! VNC サーバーがパスワードなしで実行されています!\n"
"サーバーの安全性を確保するには、vncpassword=<password>\n"
"ブートオプションを使うことができます。\n"
"\n"

#: pyanaconda/vnc.py:233
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"パスワードを使って VNC を実行するように選択しました。\n"
"\n"

#: pyanaconda/vnc.py:235
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"不明なエラーが発生しました。作業を中断します。\n"

#: pyanaconda/vnc.py:255
msgid ""
"VNC password provided was not at least 6 characters long.\n"
"Please enter a new one.  Leave blank for no password."
msgstr ""
"入力された VNC パスワードは最低限の 6文字に足りません。\n"
"新しいパスワードを入力して下さい。パスワード不要なら空白にします。"

#: pyanaconda/yuminstall.py:87
#, python-format
msgid "%s MB"
msgstr "%s MB"

#: pyanaconda/yuminstall.py:90
#, python-format
msgid "%s KB"
msgstr "%s KB"

#: pyanaconda/yuminstall.py:92
#, python-format
msgid "%s Byte"
msgid_plural "%s Bytes"
msgstr[0] "%s バイト"

#: pyanaconda/yuminstall.py:134 pyanaconda/ui/gui/hubs/progress.glade:83
msgid "Preparing to install"
msgstr "インストールの準備中"

#: pyanaconda/yuminstall.py:135 pyanaconda/packaging/yumpayload.py:1536
msgid "Preparing transaction from installation source"
msgstr "インストールソースからのトランザクションを準備中。"

#: pyanaconda/yuminstall.py:170
#, python-format
msgid "<b>Upgrading %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>%(pkgStr)s をアップグレード中</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:173
#, python-format
msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>%(pkgStr)s のインストール</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:218
#, python-format
msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgstr[0] "完了したパッケージ: %(numpkgs)d 個中 %(donepkgs)d 個が完了"

#: pyanaconda/yuminstall.py:232
#, python-format
msgid "<b>Cleaning up %s</b>"
msgstr "<b>%s をクリーンナップ中</b>"

#: pyanaconda/yuminstall.py:252
msgid "cpio"
msgstr "cpio"

#: pyanaconda/yuminstall.py:254
msgid "unpack"
msgstr "展開"

#: pyanaconda/yuminstall.py:256
msgid "script"
msgstr "スクリプト"

#: pyanaconda/yuminstall.py:257
msgid "Error Installing Package"
msgstr "パッケージのインストールでエラー"

#: pyanaconda/yuminstall.py:258
#, python-format
msgid ""
"A %s error occurred when installing the %s package.  This could indicate "
"errors when reading the installation media.  Installation cannot continue."
msgstr ""
"%s エラーが %s パッケージのインストール中に発生しました。インストールメディア"
"の読み込み中に問題が発生した可能性があります。インストール作業を続行できませ"
"ん。"

#: pyanaconda/yuminstall.py:406
msgid "Wrong Disc"
msgstr "不適切なディスクです"

#: pyanaconda/yuminstall.py:407
#, python-format
msgid "That's not the correct %s disc."
msgstr "正しい %s ディスクではありません。"

#: pyanaconda/yuminstall.py:564
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr "リポジトリー %r は設定内で名前がありません。id を使用します。"

#: pyanaconda/yuminstall.py:830 pyanaconda/yuminstall.py:1264
msgid "No Network Available"
msgstr "ネットワークは使用できません。"

#: pyanaconda/yuminstall.py:831 pyanaconda/yuminstall.py:1265
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""
"ソフトウェアリポジトリーの一部はネットワークを必要とします。しかし、使用中の"
"システムでネットワークの有効化にエラーが発生しました。"

#: pyanaconda/yuminstall.py:919 pyanaconda/yuminstall.py:921
msgid "Re_boot"
msgstr "再起動(_B)"

#: pyanaconda/yuminstall.py:919
msgid "_Eject"
msgstr "ディスクを取り出す(_E)"

#: pyanaconda/yuminstall.py:921 pyanaconda/yuminstall.py:1284
#: pyanaconda/yuminstall.py:1339 pyanaconda/yuminstall.py:1567
msgid "_Retry"
msgstr "再試行(_R)"

#: pyanaconda/yuminstall.py:924 pyanaconda/yuminstall.py:1011
#: pyanaconda/yuminstall.py:1016 pyanaconda/yuminstall.py:1289
#: pyanaconda/yuminstall.py:1349 pyanaconda/yuminstall.py:1561
#: pyanaconda/yuminstall.py:1583 pyanaconda/storage/zfcp.py:375
#: pyanaconda/ui/tui/__init__.py:38
msgid "Error"
msgstr "エラー"

#: pyanaconda/yuminstall.py:925
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""
"ファイル %s を開けません。ファイルが見つからないか、パッケージやメディアが破"
"損している可能性があります。インストール元を検証してください。\n"
"\n"
"終了するとシステムは矛盾した状態となり、再インストールを必要とする可能性が高"
"くなります。\n"
"\n"

#: pyanaconda/yuminstall.py:972
msgid "Retrying"
msgstr "再試行中"

#: pyanaconda/yuminstall.py:972
msgid "Retrying download."
msgstr "ダウンロードの再試行中。"

#: pyanaconda/yuminstall.py:1007
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr "トランザクションの実行中に次のような理由でエラーが発生しました。%s\n"

#: pyanaconda/yuminstall.py:1018 pyanaconda/yuminstall.py:1113
#: pyanaconda/yuminstall.py:1536 pyanaconda/yuminstall.py:1590
msgid "_Back"
msgstr "戻る(_B)"

#: pyanaconda/yuminstall.py:1051
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s.\n"
msgstr "トランザクションを実行中に次のエラーが発生しました: %s\n"

#: pyanaconda/yuminstall.py:1053 pyanaconda/yuminstall.py:1105
#: pyanaconda/yuminstall.py:1110
msgid "Error Running Transaction"
msgstr "トランザクション実行中にエラーが発生しました。"

#: pyanaconda/yuminstall.py:1059 pyanaconda/yuminstall.py:1060
msgid "file conflicts"
msgstr "ファイル競合"

#: pyanaconda/yuminstall.py:1061
msgid "older package(s)"
msgstr "旧パッケージ"

#: pyanaconda/yuminstall.py:1062
msgid "insufficient disk space"
msgstr "ディスク容量の不足"

#: pyanaconda/yuminstall.py:1063
msgid "insufficient disk inodes"
msgstr "ディスク inode の不足"

#: pyanaconda/yuminstall.py:1064
msgid "package conflicts"
msgstr "パッケージ競合"

#: pyanaconda/yuminstall.py:1065
msgid "package already installed"
msgstr "パッケージはすでにインストールされています"

#: pyanaconda/yuminstall.py:1066
msgid "required package"
msgstr "必要なパッケージ"

#: pyanaconda/yuminstall.py:1067
msgid "package for incorrect arch"
msgstr "不適切なアーキテクチャ用のパッケージ"

#: pyanaconda/yuminstall.py:1068
msgid "package for incorrect os"
msgstr "不適切な OS 用のパッケージ"

#: pyanaconda/yuminstall.py:1082 pyanaconda/packaging/yumpayload.py:1364
msgid "You need more space on the following file systems:\n"
msgstr "以下のファイルシステムは容量を増やす必要があります。\n"

#: pyanaconda/yuminstall.py:1095
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""
"インストールするパッケージに、競合するファイルがみつかりました:\n"
"%s\n"

#: pyanaconda/yuminstall.py:1098
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): "
"%s.\n"
msgstr "トランザクションの実行中に次のような理由でエラーが発生しました: %s\n"

#: pyanaconda/yuminstall.py:1290
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""
"リポジトリーからグループ情報を読み取ることはできません。これは、インストール"
"ツリーの生成の問題です。"

#: pyanaconda/yuminstall.py:1339
msgid "Edit"
msgstr "編集"

#: pyanaconda/yuminstall.py:1344 pyanaconda/yuminstall.py:1534
#: pyanaconda/ui/gui/spokes/storage.glade:43
#: pyanaconda/ui/gui/spokes/storage.glade:952
#: widgets/src/StandaloneWindow.c:53
msgid "_Continue"
msgstr "続行(_C)"

#: pyanaconda/yuminstall.py:1350 pyanaconda/yuminstall.py:1562
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""
"パッケージのメタデータを読めません。repodata ディレクトリーが見つからないのが"
"原因かもしれません。インストールツリーが正しく構築されているか確認してくださ"
"い。\n"
"\n"
"%s"

#: pyanaconda/yuminstall.py:1538
msgid "Warning"
msgstr "警告"

#: pyanaconda/yuminstall.py:1539
msgid ""
"Some of the packages you have selected for install are missing "
"dependencies.  You can exit the installation, go back and change your "
"package selections, or continue installing these packages without their "
"dependencies.  If you continue, these packages may not work correctly due to "
"missing components."
msgstr ""
"インストールするために選択したパッケージの一部は依存関係が欠如しています。 イ"
"ンストールを終了してパッケージ選択に戻るか、または依存関係のないパッケージの "
"インストールを継続してください。継続する場合、欠如したコンポーネントのために "
"これらのパッケージは正常に機能しない可能性があります。"

#: pyanaconda/yuminstall.py:1584
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""
"選択したパッケージはインストールに %d MB の空き領域を必要としますが、充分な空"
"きがありません。選択を変更するか、またはインストーラーを終了してください。"

#: pyanaconda/yuminstall.py:1669
msgid "Post Upgrade"
msgstr "アップグレード後"

#: pyanaconda/yuminstall.py:1670
msgid "Performing post-upgrade configuration"
msgstr "アップグレード後の設定を実行中。"

#: pyanaconda/yuminstall.py:1672
msgid "Post Installation"
msgstr "インストール後"

#: pyanaconda/yuminstall.py:1673
msgid "Performing post-installation configuration"
msgstr "インストール後の設定を実行中"

#: pyanaconda/yuminstall.py:1832
msgid "Installation Starting"
msgstr "インストールを開始しています"

#: pyanaconda/yuminstall.py:1833
msgid "Starting installation process"
msgstr "インストール処理の開始"

#: pyanaconda/yuminstall.py:1871
msgid "Dependency Check"
msgstr "依存関係チェック"

#: pyanaconda/yuminstall.py:1872
msgid "Checking dependencies in packages selected for installation"
msgstr "インストール対象パッケージの依存関係をチェック中。"

#: pyanaconda/yuminstall.py:1928 pyanaconda/yuminstall.py:1944
msgid "Retrieving installation information."
msgstr "インストール情報を読み出し中。"

#: pyanaconda/yuminstall.py:1930 pyanaconda/yuminstall.py:1946
#, python-format
msgid "Retrieving installation information for %s."
msgstr "%s に関するインストール情報を読み出し中。"

#: pyanaconda/yuminstall.py:1931 pyanaconda/yuminstall.py:1947
msgid "Installation Progress"
msgstr "インストールの進捗"

#: pyanaconda/installclasses/fedora.py:35
msgid "_Fedora"
msgstr "Fedora(_F)"

#: pyanaconda/installclasses/fedora.py:36
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. You can optionally select a different set of "
"software now."
msgstr ""
"%s のデフォルトインストールには一般的なネットワーク環境で利用できるソフトウェ"
"アのセットが含まれています。オプションとして異なる組み合わせのソフトウェアを"
"選択することができます。"

#: pyanaconda/installclasses/fedora.py:45
msgid "Graphical Desktop"
msgstr "デスクトップ"

#: pyanaconda/installclasses/fedora.py:50
msgid "Software Development"
msgstr "ソフトウェア開発"

#: pyanaconda/installclasses/fedora.py:56
msgid "Web Server"
msgstr "Web サーバー"

#: pyanaconda/installclasses/fedora.py:60 pyanaconda/installclasses/rhel.py:39
msgid "Minimal"
msgstr "最小限"

#: pyanaconda/installclasses/rhel.py:28
msgid "Red Hat Enterprise Linux"
msgstr "Red Hat Enterprise Linux"

#: pyanaconda/installclasses/rhel.py:29
#, python-format
msgid ""
"The default installation of %s is a minimum install. You can optionally "
"select a different set of software now."
msgstr ""
"%s のデフォルトインストールは最小限インストールです。オプションとして追加のソ"
"フトウェアを選択することができます。"

#: pyanaconda/packaging/livepayload.py:72
#: pyanaconda/packaging/livepayload.py:90
msgid "Installing software"
msgstr "ソフトウェアのインストール中…"

#: pyanaconda/packaging/yumpayload.py:1300
msgid "Starting package installation process"
msgstr "パッケージインストールプロセスを開始しています"

#: pyanaconda/packaging/yumpayload.py:1556
msgid "Upgrading"
msgstr "アップグレード中"

#: pyanaconda/packaging/yumpayload.py:1558
msgid "Installing"
msgstr "インストール中"

#: pyanaconda/storage/__init__.py:974
msgid "This partition is holding the data for the hard drive install."
msgstr ""
"このパーティションはハードディスクインストール用のデータを保有しています。"

#: pyanaconda/storage/__init__.py:979
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "DASD 形式でフォーマットされた LDL パーティションは削除できません。"

#: pyanaconda/storage/__init__.py:985
#, python-format
msgid "This device is part of the RAID device %s."
msgstr "このデバイスは RAID デバイス %s の一部です。"

#: pyanaconda/storage/__init__.py:988
msgid "This device is part of a RAID device."
msgstr "このデバイスは RAID デバイスの一部です。"

#: pyanaconda/storage/__init__.py:991
msgid "This device is part of an inconsistent LVM Volume Group."
msgstr "このデバイスは一貫性のない LVM ボリュームグループの一部です。"

#: pyanaconda/storage/__init__.py:996
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "このデバイスは LVM ボリュームグループ %s の一部です。"

#: pyanaconda/storage/__init__.py:999
msgid "This device is part of a LVM volume group."
msgstr "このデバイスは LVM ボリュームグループの一部です。"

#: pyanaconda/storage/__init__.py:1015
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""
"このデバイスは拡張パーティションです。この中の論理パーティションは先に 削除で"
"きません:\n"
"\n"

#: pyanaconda/storage/__init__.py:1262 pyanaconda/ui/gui/spokes/custom.py:1006
msgid "You must create a new filesystem on the root device."
msgstr "新しいファイルシステムは root デバイス上に作成する必要があります。"

#: pyanaconda/storage/__init__.py:1450
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""
"%s のインストールを継続するために必要な root パーティション (/) が定義されて"
"いません。"

#: pyanaconda/storage/__init__.py:1455
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"root パーティションが 250 MB 以下になっています。通常、 %s のインストールには"
"小さすぎます。"

#: pyanaconda/storage/__init__.py:1469
msgid ""
"This platform requires /boot on a dedicated partition or logical volume.  If "
"you do not want a /boot volume, you must place / on a dedicated non-LVM "
"partition."
msgstr ""
"お使いのプラットフォームでは専用のパーティションまたは論理ボリューム上に /"
"boot を配置する必要があります。あなたが /boot ボリュームを作りたくない場合"
"は、非 LVM 上の専用パーティションに / を配置しなければなりません。"

#: pyanaconda/storage/__init__.py:1478
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"%(mount)s パーティションの容量が %(size)s MB以下であり、通常の "
"%(productName)s のインストールでの 推奨容量には不足しています。"

#: pyanaconda/storage/__init__.py:1488
#, python-format
msgid ""
"Your %(mount)s partition is too small for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"このシステムの %(mount)s パーティションは %(format)s フォーマットには小さすぎ"
"ます。 (指定可能なサイズは %(minSize)d MB から %(maxSize)d MB となっています)"

#: pyanaconda/storage/__init__.py:1493
#, python-format
msgid ""
"Your %(mount)s partition is too large for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"このシステムの %(mount)s パーティションは %(format)s フォーマットには大きすぎ"
"ます。 (指定可能なサイズは %(minSize)d MB から %(maxSize)d MB となっています)"

#: pyanaconda/storage/__init__.py:1520
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""
"USB デバイス上にインストールしています。稼動するシステムが作成されることもあ"
"りますが、されないこともあります。"

#: pyanaconda/storage/__init__.py:1523
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""
"FireWire デバイス上にインストールしています。稼動するシステムが作成されること"
"もありますが、されないこともあります。"

#: pyanaconda/storage/__init__.py:1529
msgid "you have not created a bootloader stage1 target device"
msgstr ""
"対象のデバイスでブートローダーの stage1 を作成することができませんでした。"

#: pyanaconda/storage/__init__.py:1538
msgid "You have not created a bootable partition."
msgstr "ブート可能なパーティションが作成されていません。"

#: pyanaconda/storage/__init__.py:1559
#, python-format
msgid ""
"Your BIOS-based system needs a special partition to boot with %s's new disk "
"label format (GPT). To continue, please create a 1MB 'BIOS Boot' type "
"partition."
msgstr ""
"ご使用の BIOS ベースのシステムは %s の新規ディスクラベル形式 (GPT) で起動する"
"には、特別なパーティションが必要です。継続するには、1MB の  'BIOS ブート' タ"
"イプのパーティションを作成してください。"

#: pyanaconda/storage/__init__.py:1572
#, python-format
msgid ""
"You have not specified a swap partition.  %(requiredMem)s MB of memory is "
"required to continue installation without a swap partition, but you only "
"have %(installedMem)s MB."
msgstr ""
"swap パーティションが未指定です。swap パーティションなしでのインストール作業"
"の継続には %(requiredMem)s のメモリーが必要となっています。しかし、お使いのシ"
"ステムには %(installedMem)s MB しか搭載されていません。"

#: pyanaconda/storage/__init__.py:1578
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"swap パーティションが未指定です。すべての場合において必ず必要というわけではあ"
"りませんが、ほとんどのインストールにおいて明らかに性能を向上させます。"

#: pyanaconda/storage/__init__.py:1584
msgid ""
"At least one of your swap devices does not have a UUID, which is common in "
"swap space created using older versions of mkswap. These devices will be "
"referred to by device path in /etc/fstab, which is not ideal since device "
"paths can change under a variety of circumstances. "
msgstr ""
"swap デバイスの少なくとも1つは UUID を持っていなければなりません。これは旧"
"バージョンの mkswap コマンドを使用して作成した swap 領域ではよくあります。こ"
"れらのデバイスは /etc/fstab のデバイスパスによって参照されます。デバイスパス"
"による参照はさまざまな状況により変更されてしまうため理想的な方法ではありませ"
"ん。"

#: pyanaconda/storage/__init__.py:1594
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""
"このマウントポイントは正しくありません。%s ディレクトリーは / ファイルシステ"
"ム上になければなりません。"

#: pyanaconda/storage/__init__.py:1598
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "マウントポイント %s は linux ファイルシステム上にある必要があります。"

#: pyanaconda/storage/__init__.py:3199
#, python-format
msgid "Linux on %s"
msgstr "%s 上の Linux"

#: pyanaconda/storage/__init__.py:3204
msgid "Unknown Linux"
msgstr "未知の Linux"

#: pyanaconda/storage/__init__.py:3206
#, python-format
msgid "%(product)s Linux %(version)s for %(arch)s"
msgstr "%(product)s Linux %(version)s － %(arch)s"

#: pyanaconda/storage/dasd.py:159
msgid "Formatting DASD Device"
msgid_plural "Formatting DASD Devices"
msgstr[0] "DASD デバイスをフォーマット中..."

#: pyanaconda/storage/dasd.py:160
#, python-format
msgid "Preparing %d DASD device for use with Linux..."
msgid_plural "Preparing %d DASD devices for use with Linux..."
msgstr[0] "Linuxで使うために %d 個のDASDのデバイスを準備中..."

#: pyanaconda/storage/deviceaction.py:419
#, python-format
msgid "Creating %(type)s on %(device)s"
msgstr "%(device)s 上に %(type)s を作成"

#: pyanaconda/storage/deviceaction.py:559
#, python-format
msgid "Resizing filesystem on %(device)s"
msgstr "%(device)s のファイルシステムの容量変更中"

#: pyanaconda/storage/deviceaction.py:608
#, python-format
msgid "Migrating filesystem on %(device)s"
msgstr "%(device)s のファイルシステムを移行中"

#: pyanaconda/storage/devicelibs/lvm.py:310
#, python-format
msgid "vginfo failed for %s"
msgstr "%s 用の vginfo に失敗"

#: pyanaconda/storage/devicelibs/lvm.py:339
#, python-format
msgid "lvs failed for %s"
msgstr "%s 用の lvs に失敗"

#: pyanaconda/storage/devices.py:2672
#, python-format
msgid "A RAID%(raidLevel)d set requires at least %(minMembers)d member"
msgid_plural "A RAID%(raidLevel)d set requires at least %(minMembers)d members"
msgstr[0] ""
"RAID%(raidLevel)d には少なくても %(minMembers)d 個のディスクが必要です。"

#: pyanaconda/storage/devicetree.py:96
msgid "Back"
msgstr "戻る"

#: pyanaconda/storage/devicetree.py:105
msgid "Confirm"
msgstr "確認"

#: pyanaconda/storage/devicetree.py:106
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""
"本当にデバイス %s のパスフレーズの入力を省略しますか?\n"
"\n"
"このステップをスキップすると、インストール中のデバイス内のコンテンツへのアク"
"セスはできません。"

#: pyanaconda/storage/fcoe.py:110
msgid "FCoE not available"
msgstr "FCoE は使用できません"

#: pyanaconda/storage/formats/fs.py:104
msgid "filesystem configuration missing a type"
msgstr "ファイルシステム設定にタイプがありません。"

#: pyanaconda/storage/formats/fs.py:483
#, python-format
msgid "Unknown return code: %d."
msgstr "不明なリターンコードです: %d"

#: pyanaconda/storage/formats/fs.py:504
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr "%(device)s 上で %(type)s ファイルシステムのチェックに失敗: "

#: pyanaconda/storage/formats/fs.py:511
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair.  Before restarting installation, "
"reboot to rescue mode or another system that allows you to repair the "
"filesystem interactively.  Restart installation after you have corrected the "
"problems on the filesystem."
msgstr ""

#: pyanaconda/storage/formats/fs.py:519
msgid "Unrecoverable Error"
msgstr "修正不可能なエラー"

#: pyanaconda/storage/formats/fs.py:883
msgid "File system errors left uncorrected."
msgstr "ファイルシステムエラーが未修正のままです。"

#: pyanaconda/storage/formats/fs.py:884
msgid "Operational error."
msgstr "操作上のエラー"

#: pyanaconda/storage/formats/fs.py:885
msgid "Usage or syntax error."
msgstr "ユーザーまたは構文のエラー"

#: pyanaconda/storage/formats/fs.py:886
msgid "e2fsck cancelled by user request."
msgstr "ユーザーの指示で e2fsck がキャンセルされました。"

#: pyanaconda/storage/formats/fs.py:887
msgid "Shared library error."
msgstr "共有ライブラリのエラー"

#: pyanaconda/storage/formats/fs.py:1062
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""
"復元可能なエラーが検出されたか、または dosfsck が内部の整合性問題を発見しまし"
"た。"

#: pyanaconda/storage/formats/fs.py:1064
msgid "Usage error."
msgstr "使用法エラー"

#: pyanaconda/storage/formats/luks.py:48
msgid "Encrypted"
msgstr "暗号化"

#: pyanaconda/storage/iscsi.py:123
msgid "Unable to change iSCSI initiator name once set"
msgstr "iSCSI イニシエータ名はセットされた後は変更できません"

#: pyanaconda/storage/iscsi.py:125
msgid "Must provide an iSCSI initiator name"
msgstr "iSCSI イニシエーター名を入力しなければなりません"

#: pyanaconda/storage/iscsi.py:293
msgid "iSCSI not available"
msgstr "iSCSI は使用できません"

#: pyanaconda/storage/iscsi.py:295
msgid "No initiator name set"
msgstr "イニシエーター名がありません"

#: pyanaconda/storage/iscsi.py:334
msgid "Logging in to iSCSI node"
msgstr "iSCSI ノードにログイン中"

#: pyanaconda/storage/iscsi.py:335
#, python-format
msgid "Logging in to iSCSI node %s"
msgstr "iSCSI ノード %s にログイン中"

#: pyanaconda/storage/iscsi.py:369
msgid "No iSCSI nodes discovered"
msgstr "iSCSI ノードが見つかりませんでした"

#: pyanaconda/storage/iscsi.py:391
msgid "No new iSCSI nodes discovered"
msgstr "新しい iSCSI ノードは見つかりませんでした。"

#: pyanaconda/storage/iscsi.py:394
msgid "Could not log in to any of the discovered nodes"
msgstr "見つかったノードすべてにログインできませんでした"

#: pyanaconda/storage/partitioning.py:291
msgid "No usable disks selected"
msgstr "使用可能なディスクが未選択"

#: pyanaconda/storage/partitioning.py:299
msgid "Not enough free space on disks for automatic partitioning"
msgstr ""
"自動パーティション構成のために必要なディスクの空き領域が不足しています。"

#: pyanaconda/storage/partitioning.py:629
msgid "unable to allocate aligned partition"
msgstr "アラインされたパーティションを割り当てることができません。"

#: pyanaconda/storage/partitioning.py:637
msgid "requested size exceeds maximum allowed"
msgstr ""

#: pyanaconda/storage/partitioning.py:728
msgid "can't allocate partitions without platform data"
msgstr ""
"プラットフォームデータなしでパーティションを割り当てることはできません。"

#: pyanaconda/storage/partitioning.py:739
#, python-format
msgid "disk %s inaccessible"
msgstr "ディスク %s はアクセスできません"

#: pyanaconda/storage/partitioning.py:793
#, python-format
msgid ""
"partition is too small for %(format)s formatting (allowable size is "
"%(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"%(format)s でフォーマットするにはパーティションが小さ過ぎます。(割り当てサイ"
"ズは %(minSize)d MB から %(maxSize)d MB までが指定可能)"

#: pyanaconda/storage/partitioning.py:798
#, python-format
msgid ""
"partition is too large for %(format)s formatting (allowable size is "
"%(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"%(format)s でフォーマットするにはパーティションが大き過ぎます。(割り当てサイ"
"ズは %(minSize)d MB から %(maxSize)d MB までが指定可能)"

#: pyanaconda/storage/partitioning.py:1039
msgid "not enough free space on disks"
msgstr "ディスクの空き領域が不足しています"

#: pyanaconda/storage/partitioning.py:1060
msgid "not enough free space after creating extended partition"
msgstr "拡張パーティションを作成するためのディスクの空き領域が不足しています。"

#: pyanaconda/storage/partitioning.py:1232
msgid "cannot reclaim more than request has grown"
msgstr ""

#: pyanaconda/storage/partitioning.py:1412
msgid "DiskChunk requests must be of type PartitionRequest"
msgstr "DiskChunk リクエストは PartitionRequest のタイプでなければなりません。"

#: pyanaconda/storage/partitioning.py:1425
msgid "partitions allocated outside disklabel limits"
msgstr "ディスクラベルの上限を超える割り当てパーティション"

#: pyanaconda/storage/partitioning.py:1505
msgid "VGChunk requests must be of type LVRequest"
msgstr "VGChunk リクエストは LVRequest のタイプでなければなりません。"

#: pyanaconda/storage/partitioning.py:1934
msgid "not enough space for LVM requests"
msgstr "LVM リクエストのために空き領域が不足しています。"

#: pyanaconda/storage/zfcp.py:51
msgid "You have not specified a device number or the number is invalid"
msgstr "デバイス番号を指定していないか番号が無効です。"

#: pyanaconda/storage/zfcp.py:53
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr "WWPN を指定していないか、そのポート名が無効です。"

#: pyanaconda/storage/zfcp.py:55
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr "FCP FUN を指定していないか、番号が無効です。"

#: pyanaconda/storage/zfcp.py:133
#, python-format
msgid "zFCP device %s not found, not even in device ignore list."
msgstr "zFCP デバイス %s が見つからず、デバイス無視リストにもありません。"

#: pyanaconda/storage/zfcp.py:143
#, python-format
msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s を オンライン (%(e)s) にセットできませんでした。"

#: pyanaconda/storage/zfcp.py:154
#, python-format
msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
msgstr "WWPN %(wwpn)s を zFCP デバイス %(devnum)s (%(e)s) に追加できません。"

#: pyanaconda/storage/zfcp.py:161
#, python-format
msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
msgstr "WWPN %(wwpn)s が zFCP デバイス %(devnum)s で見つかりません。"

#: pyanaconda/storage/zfcp.py:176
#, python-format
msgid ""
"Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"LUN %(fcplun)s を zFCP デバイス %(devnum)s (%(e)s)上で WWPN %(wwpn)s に追加で"
"きません、。"

#: pyanaconda/storage/zfcp.py:182
#, python-format
msgid ""
"LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already configured."
msgstr ""
"LUN %(fcplun)s は、zFCP デバイス %(devnum)s 上の WWPN %(wwpn)s ですでに設定さ"
"れています。"

#: pyanaconda/storage/zfcp.py:194
#, python-format
msgid ""
"Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on zFCP "
"device %(devnum)s (%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s (%(e)s) 上の WWPN %(wwpn)s で LUN %(fcplun)s の 失敗"
"属性を読みこむことが できませんでした。"

#: pyanaconda/storage/zfcp.py:203
#, python-format
msgid ""
"Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
"again."
msgstr ""
"zFCP デバイス %(devnum)s 上の WWPN %(wwpn)s で失敗した LUN %(fcplun)s が 再度"
"削除されました。"

#: pyanaconda/storage/zfcp.py:260
#, python-format
msgid ""
"Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s "
"%(fcplun)s (%(e)s)."
msgstr ""
"zFCP %(devnum)s %(wwpn)s %(fcplun)s (%(e)s) の SCSI デバイスを正しく消すこと"
"ができませんでした。"

#: pyanaconda/storage/zfcp.py:269
#, python-format
msgid ""
"Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s (%(e)s) 上の WWPN %(wwpn)s で LUN %(fcplun)s を削除"
"できませんでした。"

#: pyanaconda/storage/zfcp.py:287
#, python-format
msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
msgstr ""
"zFCP デバイス %(devnum)s (%(e)s) 上で WWPN %(wwpn)s を削除できませんでした。"

#: pyanaconda/storage/zfcp.py:313
#, python-format
msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
msgstr "zFCP デバイス %(devnum)s をオフライン (%(e)s) に設定できませんでした。"

#: pyanaconda/ui/lib/space.py:33
#, python-format
msgid ""
"Not enough space in filesystems for the current software selection. An "
"additional %s is needed."
msgstr ""
"現在選択しているソフトウェア選択に対してファイルシステムの空き領域が不足して"
"います。追加で %s 必要です。"

#: pyanaconda/ui/tui/hubs/progress.py:37
msgid "Installation Hub"
msgstr "インストールハブ"

#: pyanaconda/ui/tui/hubs/progress.py:117
msgid "\tInstallation complete.  Press return to quit"
msgstr "» インストールは完了しました。改行ボタンを押して終了します"

#: pyanaconda/ui/tui/hubs/summary.py:32
msgid "Install hub"
msgstr "インストールハブ"

#: pyanaconda/ui/tui/hubs/summary.py:38
msgid "Starting automated install"
msgstr "自動インストールの開始"

#: pyanaconda/ui/tui/hubs/__init__.py:43
msgid "Default HUB title"
msgstr "デフォルトのハブタイトル"

#: pyanaconda/ui/tui/hubs/__init__.py:104
#: pyanaconda/ui/tui/simpleline/base.py:301
msgid "c"
msgstr "c"

#: pyanaconda/ui/tui/hubs/__init__.py:107
msgid "Please complete all spokes before continuing"
msgstr "すべてのスポークを完了してから継続して下さい。"

#: pyanaconda/ui/tui/simpleline/base.py:306
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/simpleline/base.py:308
msgid "Do you really want to quit?"
msgstr "本当に終了しますか？"

#: pyanaconda/ui/tui/simpleline/base.py:407
msgid "  Please make your choice from above ['q' to quit | 'c' to continue]: "
msgstr "上記の ['q' 終了 | 'c' 継続] から選択して下さい:"

#: pyanaconda/ui/tui/spokes/askvnc.py:32
msgid "VNC"
msgstr "VNC"

#: pyanaconda/ui/tui/spokes/askvnc.py:43
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""
"ご使用のマシンで X を起動できませんでした。VNC を起動して別のコンピューターか"
"らこのコンピューターに接続しグラフィカルインストールを行ないますか、あるいは"
"テキストモードのインストールで続行しますか?"

#: pyanaconda/ui/tui/spokes/askvnc.py:95
msgid "VNC Password"
msgstr "VNC パスワード"

#: pyanaconda/ui/tui/spokes/askvnc.py:104
msgid ""
"Please provide VNC password. You will have to type it twice. \n"
"Leave blank for no password"
msgstr ""
"VNC パスワードを記入してください。2度記入して下さい。\n"
"パスワード不要なら空白にします。"

#: pyanaconda/ui/tui/spokes/askvnc.py:123
#: pyanaconda/ui/tui/spokes/password.py:64
msgid "Password: "
msgstr "パスワード: "

#: pyanaconda/ui/tui/spokes/askvnc.py:124
#: pyanaconda/ui/tui/spokes/password.py:65
msgid "Password (confirm): "
msgstr "パスワード(確定): "

#: pyanaconda/ui/tui/spokes/askvnc.py:127
msgid "Passwords do not match!"
msgstr "パスワードが一致しません！"

#: pyanaconda/ui/tui/spokes/askvnc.py:130
msgid "The password must be at least six characters long."
msgstr "パスワードは最低 6 文字以上でなければなりません。"

#: pyanaconda/ui/tui/spokes/password.py:35
msgid "Set root password"
msgstr "root パスワードを設定する"

#: pyanaconda/ui/tui/spokes/password.py:49
msgid "Password is set."
msgstr "パスワードは設定されています"

#: pyanaconda/ui/tui/spokes/password.py:51
msgid "Root account is disabled."
msgstr "root アカウントは無効になっています"

#: pyanaconda/ui/tui/spokes/password.py:53
msgid "Password is not set."
msgstr "パスワードが設定されていません"

#: pyanaconda/ui/tui/spokes/password.py:58
msgid "Please select new root password. You will have to type it twice."
msgstr "新しい root パスワードを選択して下さい。２度記入する必要があります。"

#: pyanaconda/ui/tui/spokes/password.py:76
#, python-format
msgid "You have provided a weak password: %s. "
msgstr "強度が弱いパスワードを入力しています: %s"

#: pyanaconda/ui/tui/spokes/password.py:77
msgid ""
"\n"
"Would you like to use it anyway?"
msgstr ""
"\n"
"とにかくこれを使用しますか?"

#: pyanaconda/ui/tui/spokes/storage.py:47
msgid "Use All Space"
msgstr "すべての領域を使用する"

#: pyanaconda/ui/tui/spokes/storage.py:48
msgid "Replace Existing Linux system(s)"
msgstr "既存の Linux システムを入れ替える"

#: pyanaconda/ui/tui/spokes/storage.py:49
msgid "Use Free Space"
msgstr "空き領域を使用する"

#: pyanaconda/ui/tui/spokes/storage.py:92
msgid "Install Destination"
msgstr "インストール先"

#: pyanaconda/ui/tui/spokes/storage.py:120
#: pyanaconda/ui/gui/spokes/storage.py:439
msgid "No disks selected"
msgstr "ディスクが選択されていません"

#: pyanaconda/ui/tui/spokes/storage.py:127
#: pyanaconda/ui/gui/spokes/storage.py:446
msgid "Error checking storage configuration"
msgstr "ストレージ設定のチェック中にエラー"

#: pyanaconda/ui/tui/spokes/storage.py:130
#: pyanaconda/ui/gui/spokes/storage.py:448
msgid "Automatic partitioning selected"
msgstr "自動パーティション設定が選択されました"

#: pyanaconda/ui/tui/spokes/storage.py:132
#: pyanaconda/ui/gui/spokes/storage.py:450
msgid "Custom partitioning selected"
msgstr "カスタムパーティション設定が選択されました"

#: pyanaconda/ui/tui/spokes/storage.py:168
#: pyanaconda/ui/gui/spokes/storage.py:582
msgid ""
"No disks detected.  Please shut down the computer, connect at least one "
"disk, and restart to complete installation."
msgstr ""
"ディスク検出がありません。コンピュータをシャットダウンして最低１個のディスク"
"に接続し、再開始するとインストールが完了できます。"

#: pyanaconda/ui/tui/spokes/storage.py:170
#: pyanaconda/ui/gui/spokes/storage.py:584
msgid "No disks selected; please select at least one disk to install to."
msgstr ""
"ディスクが選択されていません。インストール先として少なくともディスクを１つ選"
"択して下さい。"

#: pyanaconda/ui/tui/spokes/storage.py:185
#: pyanaconda/ui/gui/spokes/source.py:671
#: pyanaconda/ui/gui/spokes/storage.py:514
msgid "Probing storage..."
msgstr "ストレージを捜索中..."

#: pyanaconda/ui/tui/spokes/storage.py:263
msgid "Generating updated storage configuration"
msgstr "更新したストレージ設定を生成中"

#: pyanaconda/ui/tui/spokes/storage.py:268
#, python-format
msgid "storage configuration failed: %s"
msgstr "ストレージの設定に失敗しました: %s"

#: pyanaconda/ui/tui/spokes/storage.py:277
#: pyanaconda/ui/gui/spokes/storage.py:307
msgid "Checking storage configuration..."
msgstr "ストレージ設定をチェック中..."

#: pyanaconda/ui/tui/spokes/storage.py:311
msgid "Autopartitioning Options"
msgstr "自動パーティション設定のオプション"

#: pyanaconda/ui/tui/spokes/storage.py:342
msgid ""
"Installation requires partitioning of your hard drive.  Select what space to "
"use for the install target."
msgstr ""
"インストールにはハードドライブのパーティション設定が必要です。インストール先"
"として使用する領域を選択して下さい。"

#: pyanaconda/ui/tui/spokes/time.py:30
msgid "Timezone settings"
msgstr "タイムゾーンの設定"

#: pyanaconda/ui/tui/spokes/time.py:53 pyanaconda/ui/tui/spokes/time.py:55
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:379
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:384
#, python-format
msgid "%s timezone"
msgstr "%s タイムゾーン"

#: pyanaconda/ui/tui/spokes/time.py:57
msgid "Timezone is not set."
msgstr "タイムゾーンは設定されていません"

#: pyanaconda/ui/tui/spokes/time.py:65
#, python-format
msgid "Available timezones in region %s"
msgstr "地域 %s で使用できるタイムゾーン"

#: pyanaconda/ui/tui/spokes/time.py:68
msgid "Available regions"
msgstr "使用できる地域"

#: pyanaconda/ui/tui/spokes/time.py:131
msgid ""
"Please select the timezone.\n"
"Use numbers or type names directly [b to region list, q to quit]: "
msgstr ""
"タイムゾーンを選択して下さい。\n"
"番号かタイプ名を直接選択して下さい\n"
"[b で地域一覧、q で終了]: "

#: pyanaconda/ui/tui/spokes/__init__.py:44
msgid "Default spoke title"
msgstr "デフォルトのスポークタイトル"

#: pyanaconda/ui/tui/spokes/__init__.py:54
msgid "testing status..."
msgstr "状態をテスト中..."

#: pyanaconda/ui/tui/__init__.py:58
msgid "Press enter to exit."
msgstr "enter を押して終了します。"

#: pyanaconda/ui/tui/__init__.py:67
msgid "Question"
msgstr "質問"

#: pyanaconda/ui/tui/__init__.py:90
msgid "Please respond 'yes' or 'no': "
msgstr "「はい」か「いいえ」で答えて下さい: "

#: pyanaconda/ui/tui/__init__.py:93
msgid "yes"
msgstr "はい"

#: pyanaconda/ui/tui/__init__.py:98
msgid "no"
msgstr "いいえ"

#: pyanaconda/ui/gui/__init__.py:144
msgid "_Exit Installer"
msgstr "インストーラーを終了する(_E)"

#: pyanaconda/ui/gui/__init__.py:153 pyanaconda/ui/gui/spokes/software.py:333
#: pyanaconda/ui/gui/spokes/storage.py:770 pyanaconda/ui/gui/main.glade:36
#: pyanaconda/ui/gui/hubs/summary.glade:77 widgets/src/StandaloneWindow.c:52
msgid "_Quit"
msgstr "終了する (_Q)"

#: pyanaconda/ui/gui/__init__.py:169
msgid "_No"
msgstr "いいえ(_N)"

#: pyanaconda/ui/gui/__init__.py:169
msgid "_Yes"
msgstr "はい(_Y)"

#: pyanaconda/ui/gui/categories/__init__.py:44
msgid "DEFAULT TITLE"
msgstr "デフォルトのタイトル"

#: pyanaconda/ui/gui/categories/localization.py:31
msgid "LOCALIZATION"
msgstr "地域設定"

#: pyanaconda/ui/gui/categories/software.py:31
msgid "SOFTWARE"
msgstr "ソフトウェア"

#: pyanaconda/ui/gui/categories/storage.py:32
msgid "STORAGE"
msgstr "ストレージ"

#: pyanaconda/ui/gui/categories/user_settings.py:32
msgid "USER SETTINGS"
msgstr "ユーザーの設定"

#: pyanaconda/ui/gui/hubs/__init__.py:226
msgid ""
"When all items marked with this icon are complete, installation will "
"automatically continue."
msgstr ""
"このアイコンの付いたすべての項目が完了すると、自動的にインストールが継続しま"
"す。"

#: pyanaconda/ui/gui/hubs/__init__.py:228
msgid ""
"Please complete items marked with this icon before continuing to the next "
"step."
msgstr "このアイコンが付いた項目を完了してから、次のステップへと続けて下さい。"

#: pyanaconda/ui/gui/hubs/progress.py:254
msgid "Complete!"
msgstr "完了しました!"

#: pyanaconda/ui/gui/spokes/custom.py:99
#, python-format
msgid "New %s %s Installation"
msgstr "新しい %s %s のインストール"

#: pyanaconda/ui/gui/spokes/custom.py:100
msgid "Create a new volume group ..."
msgstr "新規ボリュームグループを作成中 ..."

#: pyanaconda/ui/gui/spokes/custom.py:101
msgid ""
"Storage configuration reset due to unrecoverable error. Click for details."
msgstr ""
"復元不可能なエラーによりストレージ設定がリセットされました。詳細にはクリック"
"して下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:103
msgid "Device reconfiguration failed. Click for details."
msgstr "デバイスの設定が失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:106
msgid "Please enter a valid mountpoint."
msgstr "有効なマウントポイントを記入して下さい"

#: pyanaconda/ui/gui/spokes/custom.py:107
msgid "That mount point is invalid. Try something else?"
msgstr "そのマウントポイントは無効です。他を試しますか?"

#: pyanaconda/ui/gui/spokes/custom.py:108
msgid "That mount point is already in use. Try something else?"
msgstr "そのマウントポイントはすでに使用中です。他を試しますか?"

#: pyanaconda/ui/gui/spokes/custom.py:120
msgid "LVM"
msgstr "LVM"

#: pyanaconda/ui/gui/spokes/custom.py:121
msgid "RAID"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.py:122
msgid "Standard Partition"
msgstr "標準パーティション"

#: pyanaconda/ui/gui/spokes/custom.py:123
msgid "BTRFS"
msgstr "Btrfs"

#: pyanaconda/ui/gui/spokes/custom.py:124
#: pyanaconda/ui/gui/spokes/custom.glade:2088
#: pyanaconda/ui/gui/spokes/custom.glade:2289
#: pyanaconda/ui/gui/spokes/lib/resize.glade:140
msgid "Disk"
msgstr "ディスク"

#: pyanaconda/ui/gui/spokes/custom.py:439
#: pyanaconda/ui/gui/spokes/custom.glade:389
msgid "MANUAL PARTITIONING"
msgstr "手作業のパーティション設定"

#: pyanaconda/ui/gui/spokes/custom.py:636
#, python-format
msgid "%d storage device selected"
msgid_plural "%d storage devices selected"
msgstr[0] "%d 個のストレージデバイスが選択されています"

#: pyanaconda/ui/gui/spokes/custom.py:789
#: pyanaconda/ui/gui/spokes/network.py:585
#: pyanaconda/ui/gui/spokes/network.py:1001
msgid "Unknown"
msgstr "不明"

#: pyanaconda/ui/gui/spokes/custom.py:818
msgid ""
"The 'swap' area on your computer is used by the operating\n"
"system when running low on memory."
msgstr ""
"ご使用のコンピューターの 'swap' 領域は、メモリー不足の状態になると\n"
"オペレーティングシステムで使用されます。"

#: pyanaconda/ui/gui/spokes/custom.py:821
msgid ""
"The 'boot' area on your computer is where files needed\n"
"to start the operating system are stored."
msgstr ""
"ご使用のコンピューターの 'boot' 領域は、オペレーティング\n"
"システムの開始に必要なファイルを収納しています。"

#: pyanaconda/ui/gui/spokes/custom.py:824
msgid ""
"The 'root' area on your computer is where core system\n"
"files and applications are stored."
msgstr ""
"ご使用のコンピューターの 'root' 領域は、コアシステムファイルと\n"
"アプリKションを収納しています。"

#: pyanaconda/ui/gui/spokes/custom.py:827
msgid ""
"The 'home' area on your computer is where all your personal\n"
"data is stored."
msgstr ""
"ご使用のコンピューターの 'home' 領域は、ユーザーの個人\n"
"データを収納しています。"

#: pyanaconda/ui/gui/spokes/custom.py:830
msgid ""
"The BIOS boot partition is required to enable booting\n"
"from GPT-partitioned disks on BIOS hardware."
msgstr ""
"BIOS ハードウェア上で GPT パーティション設定したディスク からの起動を有効にす"
"るには、BIOS のブートパーティションが必要です。"

#: pyanaconda/ui/gui/spokes/custom.py:833
msgid ""
"The PReP boot partition is required as part of the\n"
"bootloader configuration on some PPC platforms."
msgstr ""
"数種の PPC プラットフォーム上のブートローダー設定の一部 としてPReP ブートパー"
"ティションが必要です。"

#: pyanaconda/ui/gui/spokes/custom.py:995
#, python-format
msgid "/boot/efi must be on a device of type %s"
msgstr "/boot/efi は タイプ %s のデバイス上でなければなりません"

#: pyanaconda/ui/gui/spokes/custom.py:999
#, python-format
msgid "%s must be on a device of type %s"
msgstr "%s はタイプ %s のデバイス上でなければなりません"

#: pyanaconda/ui/gui/spokes/custom.py:1002
#: pyanaconda/ui/gui/spokes/custom.py:1004
#, python-format
msgid "%s cannot be encrypted"
msgstr "%s は暗号化できません"

#: pyanaconda/ui/gui/spokes/custom.py:1008
#, python-format
msgid "Devices of type %s require a valid RAID level selection."
msgstr "タイプ %s のデバイスには有効な RAID レベルを選択する必要があります。"

#: pyanaconda/ui/gui/spokes/custom.py:1014
msgid ""
"The RAID level you have selected requires more disks than you currently have "
"selected."
msgstr ""
"選択した RAID レベルには現在選択している領域より大きな領域が必要になります。"

#: pyanaconda/ui/gui/spokes/custom.py:1173
msgid "Device resize request failed. Click for details."
msgstr "デバイスのサイズ変更要求は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:1227
#, python-format
msgid "Specified name %s already in use."
msgstr "指定された名前 %s はすでに存在します。"

#: pyanaconda/ui/gui/spokes/custom.py:1294
msgid "Device reformat request failed. Click for details."
msgstr ""
"デバイスの再フォーマット要求は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:1558
msgid "This file system does not support labels."
msgstr "このファイルシステムはラベルをサポートしません。"

#: pyanaconda/ui/gui/spokes/custom.py:1576
msgid "This file system may not be resized."
msgstr "このファイルシステムはサイズ変更できません。"

#: pyanaconda/ui/gui/spokes/custom.py:1848
#, python-format
msgid "Added new %s to existing container %s."
msgstr "新しい %s をすでに存在するコンテナー %s へ追加しました。"

#: pyanaconda/ui/gui/spokes/custom.py:1856
msgid "Failed to add new device. Click for details."
msgstr "新規デバイスの追加に失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:1862
msgid "Invalid partition size set. Use a valid integer."
msgstr ""
"無効なパーティション容量が設定されました。有効な範囲の整数を使用してくださ"
"い。"

#: pyanaconda/ui/gui/spokes/custom.py:1882
msgid "Device removal request failed. Click for details."
msgstr "デバイスの除去要求は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:2077
#, python-format
msgid "Volume Group name %s is already in use. Not saving changes."
msgstr "ボリュームグループ名 %s はすでに使われています。変更は保存されません。"

#: pyanaconda/ui/gui/spokes/custom.py:2168
#, python-format
msgid ""
"This Software RAID array is missing %d of %d member partitions. You can "
"remove it or select a different device."
msgstr ""
"ソフトウェアRAIDアレイの %d / %d のメンバーパーティションが見つかりません。削"
"除するか他のデバイスを選択してください。"

#: pyanaconda/ui/gui/spokes/custom.py:2174
#, python-format
msgid ""
"This LVM Volume Group is missing %d of %d physical volumes. You can remove "
"it or select a different device."
msgstr ""
"LVM ボリュームグループの %d / %d の物理ボリュームが見つかりません。削除するか"
"他のデバイスを選択してください。"

#: pyanaconda/ui/gui/spokes/custom.py:2247
msgid "No disks selected."
msgstr "ディスクが選択されていません。"

#: pyanaconda/ui/gui/spokes/custom.py:2253
msgid "Not enough free space on selected disks."
msgstr "選択したディスクには十分な空き領域がありません。"

#: pyanaconda/ui/gui/spokes/custom.py:2259
msgid "Automatic partitioning failed. Click for details."
msgstr "自動パーティション設定は失敗しました。詳細にはクリックして下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:2499
msgid "Failed to unlock encrypted block device. Click for details"
msgstr ""
"暗号化されたブロックデバイスのアンロックに失敗しました。詳細にはクリックして"
"下さい。"

#: pyanaconda/ui/gui/spokes/custom.py:2522
#, python-format
msgid ""
"You have chosen to manually set up the filesystems for your new "
"%(productName)s installation. Before you begin, you might want to take a "
"minute to learn the lay of the land. Quite a bit has changed.\n"
"\n"
"The most important change is that creation of new filesystems has been "
"streamlined. You no longer have to build complex devices like LVM logical "
"volumes in stages (physical volume, then volume group, then logical volume) "
"-- now you just create a logical volume and we'll handle the legwork of "
"setting up the physical volumes and volume group to contain it. We'll also "
"handle adjusting the volume group as you add, remove, and resize logical "
"volumes so you don't have to worry about the mundane details.\n"
"\n"
"\n"
"Screen Layout\n"
"\n"
"The left-hand side of the screen shows the OS installations we were able to "
"find on this computer. The new %(productName)s installation is at the top of "
"the list. You can click on the names of the installations to see what "
"filesystems they contain.\n"
"\n"
"Below the various installations and mountpoints on the left-hand side there "
"are buttons to add a new filesystem, remove the selected filesystem, or "
"configure the selected filesystem.\n"
"\n"
"The right-hand side of the screen is where you can customize the currently-"
"selected mountpoint.\n"
"\n"
"On the bottom-left you will see a summary of the disks you have chosen to "
"use for the installation. You can click on the blue text to see more "
"detailed information about your selected disks.\n"
"\n"
"\n"
"How to create a new filesystem on a new device\n"
"\n"
"1. Click on the + button.\n"
"2. Enter the mountpoint and size. (Hint: Hover the mouse pointer over either "
"of the text entry areas for help.)\n"
"3. Select the new mountpoint under \"New %(productName)s Installation\" on "
"the left-hand side of the screen and customize it to suit your needs.\n"
"\n"
"\n"
"How to reformat a device/filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem from the left-hand side of the screen.\n"
"2. Click on the \"Customize\" expander in the mountpoint customization area "
"on the right-hand side of the screen.\n"
"3. Activate the \"Reformat\" checkbutton, select a filesystem type and, if "
"applicable, enter a mountpoint above in the \"Mountpoint\" text entry area.\n"
"4. Click on \"Apply changes\"\n"
"\n"
"\n"
"How to set a mountpoint for a filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem from the left-hand side of the screen.\n"
"2. Enter a mountpoint in the \"Mountpoint\" text entry area in the "
"mountpoint customization area.\n"
"3. Click on \"Apply changes\"\n"
"\n"
"\n"
"How to remove a filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem you wish to remove on the left-hand side of the "
"screen.\n"
"2. Click the - button.\n"
"\n"
"Hint: Removing a device that already exists on your disk from the \"New "
"%(productName)s Installation\" does not remove it from the disk. It only "
"resets that device to its original state. To remove a device that already "
"exists on your disk, you must select it from under any of the other detected "
"installations (or \"Unknown\") and hit the - button.\n"
"\n"
"\n"
"Tips and hints\n"
"\n"
"You can enter sizes for new filesystems that are greater than the total "
"available free space. The installer will come as close as possible to the "
"size you request.\n"
"\n"
"By default, new devices use any/all of your selected disks.\n"
"\n"
"You can change which disks a new device may be allocated from by clicking "
"the configure button (the one with a tools graphic) while that device is "
"selected.\n"
"\n"
"When adding a new mountpoint by clicking the + button, leave the size entry "
"blank to make the new device use all available free space.\n"
"\n"
"When you remove the last device from a container device like an LVM volume "
"group, we will automatically remove that container device to make room for "
"new devices.\n"
"\n"
"When the last partition is removed from a disk, that disk may be "
"reinitialized with a new partition table if we think there is a more "
"appropriate type for that disk.\n"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:56
msgid "Note: pool servers may not be available all the time"
msgstr "注記:  プールサーバーは常時利用可能ではないかも知れません。"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:296
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:31
msgid "DATE & TIME"
msgstr "日付と時刻"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:381
msgid "Invalid timezone"
msgstr "無効なタイムゾーン"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:813
msgid "You need to set up networking first if you want to use NTP"
msgstr "NTP を使用する場合は、ネットワークを最初に設定する必要があります。"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:817
msgid "You have no working NTP server configured"
msgstr "稼働できる NTP サーバーの設定がありません。"

#: pyanaconda/ui/gui/spokes/keyboard.py:40
#, python-format
msgid "%s to switch layouts."
msgstr "%s レイアウトの切り替え"

#: pyanaconda/ui/gui/spokes/keyboard.py:261
msgid "KEYBOARD"
msgstr "キーボード"

#: pyanaconda/ui/gui/spokes/keyboard.py:318
msgid "Testing layouts configuration not available."
msgstr "レイアウト設定のテストは出来ません。"

#: pyanaconda/ui/gui/spokes/keyboard.py:372
msgid "Layout switching not configured."
msgstr "レイアウトの切り替えは設定されていません。"

#: pyanaconda/ui/gui/spokes/network.py:92
msgid "Status unknown (missing)"
msgstr "状態は不明です (情報欠如)"

#: pyanaconda/ui/gui/spokes/network.py:96
msgid "Status unknown"
msgstr "状態は不明です"

#: pyanaconda/ui/gui/spokes/network.py:98
msgid "Unmanaged"
msgstr "管理されていません"

#: pyanaconda/ui/gui/spokes/network.py:101
msgid "Firmware missing"
msgstr "ファームウェアがありません"

#: pyanaconda/ui/gui/spokes/network.py:104
msgid "Cable unplugged"
msgstr "ケーブルが外れています"

#: pyanaconda/ui/gui/spokes/network.py:106
msgid "Unavailable"
msgstr "利用できません"

#: pyanaconda/ui/gui/spokes/network.py:108
msgid "Disconnected"
msgstr "切断されています"

#: pyanaconda/ui/gui/spokes/network.py:113
msgid "Connecting"
msgstr "接続しています"

#: pyanaconda/ui/gui/spokes/network.py:115
msgid "Authentication required"
msgstr "認証が必要です"

#: pyanaconda/ui/gui/spokes/network.py:117
msgid "Connected"
msgstr "接続済みです"

#: pyanaconda/ui/gui/spokes/network.py:119
msgid "Disconnecting"
msgstr "切断しています"

#: pyanaconda/ui/gui/spokes/network.py:121
msgid "Connection failed"
msgstr "接続に失敗しました"

#: pyanaconda/ui/gui/spokes/network.py:574
msgid "unplugged"
msgstr "外れています"

#: pyanaconda/ui/gui/spokes/network.py:587
msgid "Ethernet"
msgstr "イーサネット"

#: pyanaconda/ui/gui/spokes/network.py:589
msgid "Wireless"
msgstr "ワイヤーレス"

#: pyanaconda/ui/gui/spokes/network.py:683
#: pyanaconda/ui/gui/spokes/network.glade:349
#: pyanaconda/ui/gui/spokes/network.glade:702
msgid "IPv4 Address"
msgstr "IPv4 アドレス"

#: pyanaconda/ui/gui/spokes/network.py:684
#: pyanaconda/ui/gui/spokes/network.glade:363
#: pyanaconda/ui/gui/spokes/network.glade:716
#: pyanaconda/ui/gui/spokes/network.glade:1335
msgid "IPv6 Address"
msgstr "IPv6 アドレス"

#: pyanaconda/ui/gui/spokes/network.py:686
#: pyanaconda/ui/gui/spokes/network.py:688
#: pyanaconda/ui/gui/spokes/network.glade:1321
msgid "IP Address"
msgstr "IP アドレス"

#: pyanaconda/ui/gui/spokes/network.py:753
#, python-format
msgid "%d Mb/s"
msgstr "%d Mb/s"

#: pyanaconda/ui/gui/spokes/network.py:930
msgid "WEP"
msgstr "WEP"

#: pyanaconda/ui/gui/spokes/network.py:933
msgid "WPA"
msgstr "WPA"

#: pyanaconda/ui/gui/spokes/network.py:936
msgid "WPA2"
msgstr "WPA2"

#: pyanaconda/ui/gui/spokes/network.py:940
msgid "Enterprise"
msgstr "企業"

#: pyanaconda/ui/gui/spokes/network.py:945 widgets/src/SpokeSelector.c:54
msgid "None"
msgstr "なし"

#: pyanaconda/ui/gui/spokes/network.py:967
#: pyanaconda/ui/gui/spokes/network.glade:37
#: pyanaconda/ui/gui/spokes/network.glade:109
msgid "NETWORK CONFIGURATION"
msgstr "ネットワーク設定"

#: pyanaconda/ui/gui/spokes/network.py:1005
msgid "Connecting..."
msgstr "接続中..."

#: pyanaconda/ui/gui/spokes/network.py:1007
msgid "Disconnecting..."
msgstr "切断中..."

#: pyanaconda/ui/gui/spokes/network.py:1014
#, python-format
msgid "Wireless connected to %s"
msgstr "%s にワイヤレスで接続しています"

#: pyanaconda/ui/gui/spokes/network.py:1017
#, python-format
msgid "Wired (%s) connected"
msgstr "有線 (%s) は接続されています"

#: pyanaconda/ui/gui/spokes/network.py:1027
#, python-format
msgid "Connected: %s"
msgstr "接続しています: %s"

#: pyanaconda/ui/gui/spokes/network.py:1029
msgid "Not connected"
msgstr "接続していません"

#: pyanaconda/ui/gui/spokes/network.py:1032
#: pyanaconda/ui/gui/spokes/network.glade:2085
msgid "No network devices available"
msgstr "ネットワークデバイスは利用できません"

#: pyanaconda/ui/gui/spokes/network.py:1072
#: pyanaconda/ui/gui/spokes/network.py:1142
#, python-format
msgid "Hostname is not valid: %s"
msgstr "ホスト名は無効です: %s"

#: pyanaconda/ui/gui/spokes/password.py:48
#: pyanaconda/ui/gui/spokes/password.glade:9
msgid "ROOT PASSWORD"
msgstr "root パスワード"

#: pyanaconda/ui/gui/spokes/password.py:77
msgid "Error setting root password"
msgstr "root パスワードの設定エラーです"

#: pyanaconda/ui/gui/spokes/password.py:79
msgid "Root password is set"
msgstr "root パスワードは設定されています"

#: pyanaconda/ui/gui/spokes/password.py:81
msgid "Root account is disabled"
msgstr "root アカウントは無効になっています"

#: pyanaconda/ui/gui/spokes/password.py:83
msgid "Root password is not set"
msgstr "root パスワードが設定されていません"

#: pyanaconda/ui/gui/spokes/password.py:103
msgid "You must provide and confirm a password."
msgstr "パスワードを入力してから確認を行ってください。"

#: pyanaconda/ui/gui/spokes/password.py:113
#, python-format
msgid "You have provided a weak password: %s.  Press Done again to use anyway."
msgstr "脆弱なパスワードです: %s　それでも使用する場合は完了を押します。"

#: pyanaconda/ui/gui/spokes/software.py:53
#: pyanaconda/ui/gui/spokes/software.glade:31
msgid "SOFTWARE SELECTION"
msgstr "ソフトウェアの選択"

#: pyanaconda/ui/gui/spokes/software.py:107
#: pyanaconda/ui/gui/spokes/source.py:612
msgid "Checking software dependencies..."
msgstr "ソフトウェアの依存関係をチェック中..."

#: pyanaconda/ui/gui/spokes/software.py:113
msgid "Error checking software dependencies"
msgstr "ソフトウェアの依存関係をチェック中にエラー"

#: pyanaconda/ui/gui/spokes/software.py:150
msgid "Error checking software selection"
msgstr "ソフトウェアの選択をチェック中にエラー"

#: pyanaconda/ui/gui/spokes/software.py:153
msgid "Installation source not set up"
msgstr "インストールソースはセットされていません"

#: pyanaconda/ui/gui/spokes/software.py:156
msgid "Source changed - please verify"
msgstr "ソースが変更されました - ご確認ください"

#: pyanaconda/ui/gui/spokes/software.py:164
msgid "Custom software selected"
msgstr "カスタムソフトウェアが選択されています"

#: pyanaconda/ui/gui/spokes/software.py:166
#: pyanaconda/ui/gui/spokes/source.py:597
#: pyanaconda/ui/gui/spokes/source.py:630
msgid "Nothing selected"
msgstr "何も選択されていません"

#: pyanaconda/ui/gui/spokes/software.py:175
#: pyanaconda/ui/gui/spokes/source.py:50
msgid "Downloading package metadata..."
msgstr "パッケージのメタデータをダウンロード中..."

#: pyanaconda/ui/gui/spokes/software.py:181
msgid "Downloading group metadata..."
msgstr "グループメタデータをダウンロード中"

#: pyanaconda/ui/gui/spokes/software.py:215
#: pyanaconda/ui/gui/spokes/source.py:589
msgid "No installation source available"
msgstr "インストールソースは利用できません"

#: pyanaconda/ui/gui/spokes/software.py:265
msgid "Error checking software dependencies.  Click for details."
msgstr "ソフトウェアの依存関係のチェック中にエラー。クリックして詳細をみます。"

#: pyanaconda/ui/gui/spokes/software.py:329
msgid ""
"The following software marked for installation has errors.  This is likely "
"caused by an error with\n"
"your installation source.  You can attempt to remove these packages from "
"your installation.\n"
"change your installation source, or quit the installer."
msgstr ""
"インストール用にマークしてある以下のソフトウェアにエラーがあります。これはイ"
"ンストールソースが持つエラーが原因であるようです。これらのパッケージをインス"
"トールから除外するか、インストールソースを変えるか、またはインストーラーを終"
"了することができます。"

#: pyanaconda/ui/gui/spokes/software.py:333
#: pyanaconda/ui/gui/spokes/storage.glade:613
#: pyanaconda/ui/gui/spokes/source.glade:592
#: pyanaconda/ui/gui/spokes/custom.glade:91
#: pyanaconda/ui/gui/spokes/custom.glade:341
#: pyanaconda/ui/gui/spokes/custom.glade:1956
#: pyanaconda/ui/gui/spokes/custom.glade:2194 pyanaconda/ui/gui/main.glade:20
msgid "_Cancel"
msgstr "取り消し(_C)"

#: pyanaconda/ui/gui/spokes/software.py:334
msgid "_Remove Packages"
msgstr "パッケージを削除 (_R)"

#: pyanaconda/ui/gui/spokes/software.py:335
msgid "_Modify Software Source"
msgstr "ソフトウェア提供元を修正(_M)"

#: pyanaconda/ui/gui/spokes/source.py:49
msgid "Setting up installation source..."
msgstr "インストールソースをセットアップ中..."

#: pyanaconda/ui/gui/spokes/source.py:51
msgid "Error downloading package metadata..."
msgstr "パッケージメタデータをダウンロード中にエラー..."

#: pyanaconda/ui/gui/spokes/source.py:144
msgid "This media is good to install from."
msgstr "このメディアは以下からのインストールに適切です。"

#: pyanaconda/ui/gui/spokes/source.py:146
msgid "This media is not good to install from."
msgstr "このメディアは以下からのインストールに不適切です。"

#: pyanaconda/ui/gui/spokes/source.py:347
msgid "Getting info about requested repository"
msgstr "要求されたレポジトリの情報を取得中…"

#: pyanaconda/ui/gui/spokes/source.py:370
#: pyanaconda/ui/gui/spokes/source.glade:257
msgid "enter URL of your desired repository"
msgstr "ご希望のレポジトリの URL を入力してください"

#: pyanaconda/ui/gui/spokes/source.py:428
#: pyanaconda/ui/gui/spokes/source.glade:827
msgid "INSTALLATION SOURCE"
msgstr "インストールソース"

#: pyanaconda/ui/gui/spokes/source.py:561
msgid "Failed to set up install source"
msgstr "インストールソースの設定に失敗しました"

#: pyanaconda/ui/gui/spokes/source.py:563
#: pyanaconda/ui/gui/spokes/source.py:577
msgid "Failed to set up install source, check the repo url"
msgstr ""
"インストールソースの設定に失敗しました。レポジトリの url を確認して下さい"

#: pyanaconda/ui/gui/spokes/source.py:565
msgid "Failed to set up install source, check the repo url and proxy settings"
msgstr ""
"インストールソースの設定に失敗しました。レポジトリの url とプロキシの設定を確"
"認して下さい"

#: pyanaconda/ui/gui/spokes/source.py:614
msgid "Not ready"
msgstr "準備できていません"

#: pyanaconda/ui/gui/spokes/source.py:616
#: pyanaconda/ui/gui/spokes/source.py:625
msgid "Error setting up software source"
msgstr "ソフトウェアソースの設定でエラー"

#: pyanaconda/ui/gui/spokes/source.py:620
#, python-format
msgid "NFS server %s"
msgstr "NFS サーバー %s"

#: pyanaconda/ui/gui/spokes/source.py:622
msgid "CD/DVD drive"
msgstr "CD/DVD ドライブ"

#: pyanaconda/ui/gui/spokes/source.py:628
msgid "Closest mirror"
msgstr "最寄りのミラー"

#: pyanaconda/ui/gui/spokes/storage.py:151
#, python-format
msgid ""
"You have plenty of space to install <b>%s</b>, so we can automatically\n"
"configure the rest of the installation for you.\n"
"\n"
"You're all set!"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:170
#, python-format
msgid ""
"Your current <b>%s</b> software selection requires <b>%s</b> of available "
"space."
msgstr ""
"現在の <b>%s</b> のソフトウェア選択には、利用可能な領域の <b>%s</b> が必要で"
"す。"

#: pyanaconda/ui/gui/spokes/storage.py:243
#, python-format
msgid ""
"%s\n"
"The disks you've selected have the following amounts of free space:"
msgstr ""
"%s\n"
"選択したディスクには、以下の容量の空き領域があります:"

#: pyanaconda/ui/gui/spokes/storage.py:252
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>, but we can help "
"you\n"
"reclaim space by shrinking or removing existing partitions."
msgstr ""
"<b>%s をインストールするには利用可能領域が足りませんが、</b>既存パーティショ"
"ンを縮小したり、削除したりして領域を取り戻すことができます。"

#: pyanaconda/ui/gui/spokes/storage.py:274
#, python-format
msgid ""
"%s\n"
"You don't have enough space available to install <b>%s</b>, even if you used "
"all of the free space\n"
"available on the selected disks."
msgstr ""
"%s\n"
"選択したディスクで利用できるすべての空き領域を使用しても、<b>%s</b> のインス"
"トールには十分な領域がありません。"

#: pyanaconda/ui/gui/spokes/storage.py:285
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>, even if you used "
"all of the free space\n"
"available on the selected disks.  You could add more disks for additional "
"space,\n"
"modify your software selection to install a smaller version of <b>%s</b>, or "
"quit the installer."
msgstr ""
"選択したディスクで利用できるすべての空き領域を使用しても、<b>%s のインストー"
"ルには十分な領域がありません。</b> 更なる領域の為に他のディスクを追加するか、"
"小さいバージョンの <b>%s</b> をインストールするためにソフトウェア選択を修正す"
"るか、またはインストーラーを終了することができます。"

#: pyanaconda/ui/gui/spokes/storage.py:325
#: pyanaconda/ui/gui/spokes/storage.glade:844
msgid "INSTALLATION DESTINATION"
msgstr "インストール先"

#: pyanaconda/ui/gui/spokes/storage.py:397
msgid "Saving storage configuration..."
msgstr "ストレージ設定を保存しています..."

#: pyanaconda/ui/gui/spokes/storage.py:404
msgid "Failed to save storage configuration..."
msgstr "ストレージ設定の保存に失敗しました..."

#: pyanaconda/ui/gui/spokes/storage.py:496
msgid "Error checking storage configuration.  Click for details."
msgstr "ストレージ設定のチェックでエラー発生。クリックして詳細を見ます。"

#: pyanaconda/ui/gui/spokes/storage.py:575
#, python-format
msgid "%d disk selected; %s capacity; %s free"
msgid_plural "%d disks selected; %s capacity; %s free"
msgstr[0] "選択されたディスク数 %d; 容量 %s; 空き領域 %s"

#: pyanaconda/ui/gui/spokes/storage.py:627
msgid ""
"You have chosen to skip bootloader installation.  Your system may not be "
"bootable."
msgstr ""
"ブートローダーのインストールを省略するよう選択しています。 システムが起動不可"
"になる可能性があります。"

#: pyanaconda/ui/gui/spokes/storage.py:767
msgid ""
"The following errors were encountered when checking your storage "
"configuration.  You can modify your storage layout\n"
"or quit the installer."
msgstr ""
"ストレージ設定をチェック中に以下のエラーに遭遇しました。ストレージレイアウト"
"を変更するか、またはインストーラーを終了することが出来ます。"

#: pyanaconda/ui/gui/spokes/storage.py:770
msgid "_Modify Storage Layout"
msgstr "ストレージの構成変更(_M)"

#: pyanaconda/ui/gui/spokes/welcome.py:310
msgid "LANGUAGE"
msgstr "言語"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:130
msgid "DATA"
msgstr "データ"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:135
msgid "SYSTEM"
msgstr "システム"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:235
#, python-format
msgid "You haven't created any mount points for your %s %s installation yet:"
msgstr "%s %s インストール用のマウントポイントをまだ選択していません:"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:240
msgid "Click here to create them automatically."
msgstr "ここをクリックすると自動的に作成します。"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:250
msgid "Or, create new mount points below with the '+' icon."
msgstr "あるいは、'+' アイコンで以下に新規のマウントポイントを作成します。"

#: pyanaconda/ui/gui/spokes/lib/cart.py:138
#, python-format
msgid ""
"<b>%d disk; %s capacity; %s free space</b> (unpartitioned and in filesystems)"
msgid_plural ""
"<b>%d disks; %s capacity; %s free space</b> (unpartitioned and in "
"filesystems)"
msgstr[0] ""
"<b>ディスク数 %d; 容量%s ; 空き領域 %s</b> (パーティション未設定でファイルシ"
"ステム内)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:190
msgid "_Do not install bootloader"
msgstr "ブートローダーをインストールしない(_D)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:192
#: pyanaconda/ui/gui/spokes/lib/cart.glade:190
msgid "_Set as Boot Device"
msgstr "起動デバイスとして設定(_S)"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:38
#, python-format
msgid ""
"Warning: Your current keyboard layout is <b>%s</b>.If you change your "
"keyboard layout, you may not be able to decrypt your disks after install."
msgstr ""
"警告: 現在のキーボートレイアウトは <b>%s</b> です。キーボードのレイアウトを変"
"更すると、インストールの後にディスクの復号が出来ないかもしれません。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:42
#, python-format
msgid "You have provided a weak passphrase: %s"
msgstr "脆弱なパスフレーズを記入しています: %s"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:43
msgid "Passphrases do not match."
msgstr "パスフレーズが一致しません。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:116
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:165
msgid "Weak"
msgstr "脆弱"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:119
msgid "Fair"
msgstr "普通"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:122
msgid "Good"
msgstr "良好"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:125
msgid "Strong"
msgstr "強力"

#: pyanaconda/ui/gui/spokes/lib/resize.py:46
#: pyanaconda/ui/gui/spokes/lib/resize.glade:216
msgid "Preserve"
msgstr "保存"

#: pyanaconda/ui/gui/spokes/lib/resize.py:47
msgid "Shrink"
msgstr "縮小"

#: pyanaconda/ui/gui/spokes/lib/resize.py:48
#: pyanaconda/ui/gui/spokes/lib/resize.glade:228
msgid "Delete"
msgstr "削除"

#: pyanaconda/ui/gui/spokes/lib/resize.py:134
msgid "Whole disks are not editable."
msgstr "ディスクは編集できません"

#: pyanaconda/ui/gui/spokes/lib/resize.py:151
msgid "This device contains the installation source."
msgstr "インストールソースが含まれているデバイス"

#: pyanaconda/ui/gui/spokes/lib/resize.py:158
#, python-format
msgid "%s of %s"
msgstr "%s のうち %s"

#: pyanaconda/ui/gui/spokes/lib/resize.py:175
msgid ""
"You don't have enough free space available for this installation.\n"
"\n"
"You can remove existing filesystems you no longer need to free up space for "
"this installation.  Removing a filesystem will permanently delete all of the "
"data it contains."
msgstr ""
"このインストールに十分な空き領域がありません。\n"
"\n"
"必要の無い既存ファイルシステムを削除してこのインストール用に空き領域を得るこ"
"とができます。　\n"
"ファイルシステムを削除するとそこに収納してあるすべてのデータを永久に喪失しま"
"す。"

#: pyanaconda/ui/gui/spokes/lib/resize.py:191
#, python-format
msgid "<b>%s disk; %s reclaimable space</b> (in filesystems)"
msgid_plural "<b>%s disks; %s reclaimable space</b> (in filesystems)"
msgstr[0] "<b>%s 個のディスク; %s つの獲得可能領域</b> (ファイルシステム内) "

#: pyanaconda/ui/gui/spokes/lib/resize.py:197
#, python-format
msgid "Total selected space to reclaim: <b>%s</b>"
msgstr "選択した獲得する領域合計: <b>%s</b>"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:87
msgid "Region:"
msgstr "地域:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:120
msgid "City:"
msgstr "都市:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:164
msgid "Network Time"
msgstr "ネットワーク時刻同期"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:257
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:289
msgid "00"
msgstr "00"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:273
msgid ":"
msgstr ":"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:401
msgid " "
msgstr " "

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:417
msgid "PM"
msgstr "PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:461
msgid "24-hour"
msgstr "24 時間"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:479
msgid "AM/PM"
msgstr "AM/PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:646
msgid "Add and mark for usage NTP servers"
msgstr "NTP サーバーの使用法を追加してマークする"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:727
msgid "Hostname"
msgstr "ホスト名"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:742
msgid "Working"
msgstr "稼働中"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:750
msgid "Use"
msgstr "使用"

#: pyanaconda/ui/gui/spokes/network.glade:78
msgid ""
"We'll need network access to fetch information about your location and to "
"make software\n"
"updates available for you."
msgstr ""
"ユーザーの位置情報の取得およびソフトウェア更新を取得可能にするためネットワー"
"クアクセスが必要です。"

#: pyanaconda/ui/gui/spokes/network.glade:321
#: pyanaconda/ui/gui/spokes/network.glade:674
msgid "Hardware Address"
msgstr "ハードウェアアドレス"

#: pyanaconda/ui/gui/spokes/network.glade:335
#: pyanaconda/ui/gui/spokes/network.glade:688
#: pyanaconda/ui/gui/spokes/network.glade:1176
msgid "Speed"
msgstr "速度"

#: pyanaconda/ui/gui/spokes/network.glade:377
msgid "Subnet Mask"
msgstr "サブネットマスク"

#: pyanaconda/ui/gui/spokes/network.glade:391
#: pyanaconda/ui/gui/spokes/network.glade:730
#: pyanaconda/ui/gui/spokes/network.glade:1349
msgid "Default Route"
msgstr "デフォルトルート"

#: pyanaconda/ui/gui/spokes/network.glade:406
#: pyanaconda/ui/gui/spokes/network.glade:745
#: pyanaconda/ui/gui/spokes/network.glade:1364
msgid "DNS"
msgstr "DNS"

#: pyanaconda/ui/gui/spokes/network.glade:553
msgid "C_onfigure..."
msgstr "設定する(_O) ..."

#: pyanaconda/ui/gui/spokes/network.glade:867
msgid "Security"
msgstr "セキュリティ"

#: pyanaconda/ui/gui/spokes/network.glade:881
msgid "_Network Name"
msgstr "ネットワーク名(_N)"

#: pyanaconda/ui/gui/spokes/network.glade:897
msgid "Network Name"
msgstr "ネットワーク名"

#: pyanaconda/ui/gui/spokes/network.glade:911
msgid "Security Key"
msgstr "セキュリティキー"

#: pyanaconda/ui/gui/spokes/network.glade:1001
msgid "_Use as Hotspot..."
msgstr "ホットスポットとして使用する(_U)..."

#: pyanaconda/ui/gui/spokes/network.glade:1020
msgid "_Stop Hotspot..."
msgstr "ホットスポットを停止する(_S)..."

#: pyanaconda/ui/gui/spokes/network.glade:1039
#: pyanaconda/ui/gui/spokes/network.glade:1391
#: pyanaconda/ui/gui/spokes/network.glade:1676
msgid "_Configure..."
msgstr "設定する(_C)..."

#: pyanaconda/ui/gui/spokes/network.glade:1162
msgid "IMEI"
msgstr "IMEI"

#: pyanaconda/ui/gui/spokes/network.glade:1190
msgid "Provider"
msgstr "プロバイダー"

#: pyanaconda/ui/gui/spokes/network.glade:1504
msgid "VPN Type"
msgstr "VPN タイプ"

#: pyanaconda/ui/gui/spokes/network.glade:1518
msgid "Gateway"
msgstr "ゲートウェイ"

#: pyanaconda/ui/gui/spokes/network.glade:1532
msgid "Group Name"
msgstr "グループ名"

#: pyanaconda/ui/gui/spokes/network.glade:1546
msgid "Group Password"
msgstr "グループパスワード"

#: pyanaconda/ui/gui/spokes/network.glade:1560
msgid "Username"
msgstr "ユーザー名"

#: pyanaconda/ui/gui/spokes/network.glade:1803
msgid "_Method"
msgstr "メソッド(_M)"

#: pyanaconda/ui/gui/spokes/network.glade:1831
msgid "_Configuration URL"
msgstr "設定の URL(_C)"

#: pyanaconda/ui/gui/spokes/network.glade:1861
msgid "_HTTP Proxy"
msgstr "HTTP プロキシ(_H)"

#: pyanaconda/ui/gui/spokes/network.glade:1877
msgid "H_TTPS Proxy"
msgstr "HTTPS プロキシ(_T)"

#: pyanaconda/ui/gui/spokes/network.glade:1893
msgid "_FTP Proxy"
msgstr "FTP プロキシ(_F)"

#: pyanaconda/ui/gui/spokes/network.glade:1909
msgid "_Socks Host"
msgstr "Socks ホスト(_S)"

#: pyanaconda/ui/gui/spokes/network.glade:2153
msgid "Unlock"
msgstr "ロックを解除する"

#: pyanaconda/ui/gui/spokes/network.glade:2173
msgid "Air_plane Mode"
msgstr "航空機内モード(_P)"

#: pyanaconda/ui/gui/spokes/network.glade:2207
msgid "Hostname:"
msgstr "ホスト名:"

#: pyanaconda/ui/gui/spokes/software.glade:86
msgid "Choose your environment"
msgstr "使用環境を選択します"

#: pyanaconda/ui/gui/spokes/software.glade:106
msgid "Choose your add-ons"
msgstr "使用アドオンを選択します"

#: pyanaconda/ui/gui/spokes/software.glade:143
#: pyanaconda/ui/gui/spokes/software.glade:158
#: pyanaconda/ui/gui/spokes/software.glade:215
#: pyanaconda/ui/gui/spokes/software.glade:230
msgid "column"
msgstr "列"

#: pyanaconda/ui/gui/spokes/software.glade:266
msgid "_Add custom add-on..."
msgstr "カスタムアドオンを追加(_A)"

#: pyanaconda/ui/gui/spokes/storage.glade:26
#: pyanaconda/ui/gui/spokes/storage.glade:221
msgid "Cancel & _add more disks"
msgstr "取り消して、もっとディスクを追加(_A)"

#: pyanaconda/ui/gui/spokes/storage.glade:79
#: pyanaconda/ui/gui/spokes/storage.glade:293
#: pyanaconda/ui/gui/spokes/storage.glade:650
msgid "INSTALLATION OPTIONS"
msgstr "インストールオプション"

#: pyanaconda/ui/gui/spokes/storage.glade:96
#: pyanaconda/ui/gui/spokes/storage.glade:327
#: pyanaconda/ui/gui/spokes/storage.glade:806
msgid "Here we'll describe what your options are."
msgstr "ここで、ユーザーのオプションを説明します。"

#: pyanaconda/ui/gui/spokes/storage.glade:122
#: pyanaconda/ui/gui/spokes/storage.glade:477
msgid "<b>Partition type:</b>"
msgstr "<b>パーティションタイプ:</b>"

#: pyanaconda/ui/gui/spokes/storage.glade:155
#: pyanaconda/ui/gui/spokes/storage.glade:510
msgid "Partition scheme configuration"
msgstr "パーティションスキーマの設定"

#: pyanaconda/ui/gui/spokes/storage.glade:170
msgid "Let me customize the _partitioning of the disks instead."
msgstr "代わりにディスクのパーティション設定をカスタマイズさせて下さい。(_P)"

#: pyanaconda/ui/gui/spokes/storage.glade:238
#: pyanaconda/ui/gui/spokes/storage.glade:594
msgid "_Modify software selection"
msgstr "ソフトウェアの選択を修正(_M)"

#: pyanaconda/ui/gui/spokes/storage.glade:242
#: pyanaconda/ui/gui/spokes/storage.glade:598
msgid "Please wait... software metadata still loading."
msgstr "少々お待ち下さい... ソフトウェアのメタデータがまだロード中です。"

#: pyanaconda/ui/gui/spokes/storage.glade:257
msgid "Reclaim _space"
msgstr "領域を取り戻す(_S)"

#: pyanaconda/ui/gui/spokes/storage.glade:310
#: pyanaconda/ui/gui/spokes/storage.glade:666
msgid ""
"Here we'll describe how much space is needed for the current software "
"selection."
msgstr "ここで、現在のソフトウェア選択に必要となる領域を説明します。"

#: pyanaconda/ui/gui/spokes/storage.glade:353
#: pyanaconda/ui/gui/spokes/storage.glade:692
msgid "disk free"
msgstr "disk free"

#: pyanaconda/ui/gui/spokes/storage.glade:371
#: pyanaconda/ui/gui/spokes/storage.glade:709
msgid "Free space available for use."
msgstr "使用できる空き領域"

#: pyanaconda/ui/gui/spokes/storage.glade:389
#: pyanaconda/ui/gui/spokes/storage.glade:727
msgid "fs free"
msgstr "fs free"

#: pyanaconda/ui/gui/spokes/storage.glade:407
#: pyanaconda/ui/gui/spokes/storage.glade:745
msgid "Free space unavailable but reclaimable from existing partitions."
msgstr ""
"現在利用できないものの、既存のパーティションから取り戻すことができる空き領域"

#: pyanaconda/ui/gui/spokes/storage.glade:425
#: pyanaconda/ui/gui/spokes/storage.glade:763
msgid "disks size"
msgstr "ディスクのサイズ"

#: pyanaconda/ui/gui/spokes/storage.glade:443
#: pyanaconda/ui/gui/spokes/storage.glade:781
msgid "Space in selected disks reclaimable by deleting existing partitions."
msgstr "既存パーティションの削除により選択したディスク内の獲得できる領域"

#: pyanaconda/ui/gui/spokes/storage.glade:525
msgid "I don't need help; let me customize disk _partitioning."
msgstr ""
"ヘルプは必要ありません。 ディスクのパーティション設定をカスタマイズします。"

#: pyanaconda/ui/gui/spokes/storage.glade:577
msgid "_Quit installer"
msgstr "インストーラーを終了(_Q)"

#: pyanaconda/ui/gui/spokes/storage.glade:891
msgid "Local Standard Disks"
msgstr "ローカルの標準ディスク"

#: pyanaconda/ui/gui/spokes/storage.glade:972
msgid "Full disk summary and options..."
msgstr "完全なディスク要約とオプション... "

#: pyanaconda/ui/gui/spokes/storage.glade:997
#: pyanaconda/ui/gui/spokes/custom.glade:1900
msgid "summary"
msgstr "要約"

#: pyanaconda/ui/gui/spokes/storage.glade:1011
msgid "Encrypt my data. I'll set a passphrase later."
msgstr "データを暗号化する。パスフレーズは後で設定。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:68
msgid "ADD A KEYBOARD LAYOUT"
msgstr "キーボードレイアウトを追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade:85
msgid "You may add a keyboard layout by selecting it below:"
msgstr "以下の表で選択してキーボードレイアウトを追加することができます"

#: pyanaconda/ui/gui/spokes/keyboard.glade:121
msgid "Name"
msgstr "名前"

#: pyanaconda/ui/gui/spokes/keyboard.glade:182
msgid "KEYBOARD LAYOUT"
msgstr "キーボードのレイアウト"

#: pyanaconda/ui/gui/spokes/keyboard.glade:223
msgid ""
"Which keyboard layouts would you like to use on this system?  You may move "
"any layout to the top of the list to select it as the default."
msgstr ""
"このシステムで使用するキーボードのレイアウトを選択してください。 いずれのレイ"
"アウトでも一覧の先頭に移動させデフォルトとして選択することができます。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:262
msgid ""
"Changes here will only apply to the installed system. Use the desktop's tool "
"to configure the keyboard for the installation process."
msgstr ""
"ここでの変更は、インストールされた後のシステムに対して適用されます。インス"
"トールプロセスのためにキーボードレイアウトを設定するには、デスクトップのツー"
"ルを使用してください。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:319
msgid "name"
msgstr "名前"

#: pyanaconda/ui/gui/spokes/keyboard.glade:355
msgid "Add layout"
msgstr "レイアウトの追加"

#: pyanaconda/ui/gui/spokes/keyboard.glade:370
msgid "Remove layout"
msgstr "レイアウトの削除"

#: pyanaconda/ui/gui/spokes/keyboard.glade:385
msgid "Move selected layout up"
msgstr "選択したレイアウトを上に移動"

#: pyanaconda/ui/gui/spokes/keyboard.glade:400
msgid "Move selected layout down"
msgstr "選択したレイアウトを下に移動"

#: pyanaconda/ui/gui/spokes/keyboard.glade:416
msgid "Preview layout"
msgstr "レイアウトのプレビュー"

#: pyanaconda/ui/gui/spokes/keyboard.glade:453
msgid "Test the selected layout below:"
msgstr "選択したレイアウトでテストしてください:"

#: pyanaconda/ui/gui/spokes/keyboard.glade:492
msgid "Alt + Shift to switch layouts."
msgstr "Alt + Shift を使ってレイアウトを切り替えます"

#: pyanaconda/ui/gui/spokes/keyboard.glade:506
msgid "_Options"
msgstr "オプション(_O)"

#: pyanaconda/ui/gui/spokes/keyboard.glade:623
msgid "LAYOUT SWITCHING OPTIONS"
msgstr "レイアウト切り替えのオプション"

#: pyanaconda/ui/gui/spokes/keyboard.glade:640
msgid ""
"Which combination(s) would you prefer for switching between keyboard layouts?"
msgstr "切り替えを行うキーボードレイアウトの組み合わせを選択してください。"

#: pyanaconda/ui/gui/spokes/keyboard.glade:676
msgid "use"
msgstr "使用"

#: pyanaconda/ui/gui/spokes/keyboard.glade:689
msgid "description"
msgstr "詳細"

#: pyanaconda/ui/gui/spokes/password.glade:52
msgid "Root Password:"
msgstr "root パスワード:"

#: pyanaconda/ui/gui/spokes/password.glade:67
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:127
msgid "Confirm:"
msgstr "確認:"

#: pyanaconda/ui/gui/spokes/password.glade:123
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"システムの管理には root アカウントを使用します。 root ユーザーのパスワードを"
"入力してください。"

#: pyanaconda/ui/gui/spokes/source.glade:35
#: pyanaconda/ui/gui/spokes/source.glade:607
msgid "_Add"
msgstr "追加(_A)"

#: pyanaconda/ui/gui/spokes/source.glade:66
msgid "ADD A CUSTOM ADD-ON"
msgstr "カスタムアドオンを追加"

#: pyanaconda/ui/gui/spokes/source.glade:82
msgid "Where is the yum repository for your add-on?"
msgstr "アドオン用の yum リポジトリを選択してください。"

#: pyanaconda/ui/gui/spokes/source.glade:140
msgid "Repository"
msgstr "レポジトリ"

#: pyanaconda/ui/gui/spokes/source.glade:189
msgid "Fedora People Repositories"
msgstr "Fedora Peopleのレポジトリ"

#: pyanaconda/ui/gui/spokes/source.glade:306
msgid "Standard YUM repository:"
msgstr "標準の YUM レポジトリ"

#: pyanaconda/ui/gui/spokes/source.glade:439 widgets/src/SpokeWindow.c:46
msgid "_Done"
msgstr "完了(_D)"

#: pyanaconda/ui/gui/spokes/source.glade:472
msgid "MEDIA VERIFICATION"
msgstr "メディアの確認"

#: pyanaconda/ui/gui/spokes/source.glade:499
msgid "Verifying media, please wait..."
msgstr "メディアを確認しています。お待ち下さい..."

#: pyanaconda/ui/gui/spokes/source.glade:635
msgid "_Enable HTTP Proxy"
msgstr "HTTP プロキシを有効にする(_E)"

#: pyanaconda/ui/gui/spokes/source.glade:668
msgid "<b>Proxy URL</b>"
msgstr "<b>プロキシの URL</b>"

#: pyanaconda/ui/gui/spokes/source.glade:683
msgid "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"
msgstr "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"

#: pyanaconda/ui/gui/spokes/source.glade:716
msgid "_Use Authentication"
msgstr "認証の使用(_U)"

#: pyanaconda/ui/gui/spokes/source.glade:743
msgid "<b>Username</b>"
msgstr "<b>ユーザー名</b>"

#: pyanaconda/ui/gui/spokes/source.glade:758
msgid "<b>Password</b>"
msgstr "<b>パスワード</b>"

#: pyanaconda/ui/gui/spokes/source.glade:869
msgid "Which installation source would you like to use?"
msgstr "使用するインストールソースを選択してください。"

#: pyanaconda/ui/gui/spokes/source.glade:883
msgid "_Auto-detected install media:"
msgstr "自動検出したインストールメディア(_A):"

#: pyanaconda/ui/gui/spokes/source.glade:938
#: pyanaconda/ui/gui/spokes/source.glade:1031
msgid "_Verify"
msgstr "確認する(_V)"

#: pyanaconda/ui/gui/spokes/source.glade:961
msgid "_ISO file:"
msgstr "ISO ファイル(_I):"

#: pyanaconda/ui/gui/spokes/source.glade:988
msgid "Device:"
msgstr "デバイス:"

#: pyanaconda/ui/gui/spokes/source.glade:1016
msgid "_Choose an ISO"
msgstr "ISO を1つ選択(_C)"

#: pyanaconda/ui/gui/spokes/source.glade:1054
msgid "On the _network:"
msgstr "ネットワーク上(_N):"

#: pyanaconda/ui/gui/spokes/source.glade:1129
msgid "_Proxy setup..."
msgstr "プロキシの設定(_P)..."

#: pyanaconda/ui/gui/spokes/source.glade:1147
msgid "This URL refers to a _mirror list."
msgstr "この URL はミラーリストを参照します。"

#: pyanaconda/ui/gui/spokes/source.glade:1182
msgid "NFS mount options:"
msgstr "NFS マウントオプション:"

#: pyanaconda/ui/gui/spokes/source.glade:1195
#: pyanaconda/ui/gui/spokes/source.glade:1196
msgid "This field is optional."
msgstr "このフィールドはオプションです。"

#: pyanaconda/ui/gui/spokes/welcome.glade:21
msgid "_Get me out of here!"
msgstr "ここから脱出したい! (_G)"

#: pyanaconda/ui/gui/spokes/welcome.glade:35
msgid "_I accept my fate."
msgstr "運命を受け入れます(_I)"

#: pyanaconda/ui/gui/spokes/welcome.glade:66
msgid "This is unstable, pre-release software."
msgstr "これは不安定なプレリリースのソフトウェアです。"

#: pyanaconda/ui/gui/spokes/welcome.glade:99
msgid ""
"You wake up inside an OS installer in Timbuktu, and it's six months in the "
"future.  But, there are bugs.  Bugs everywhere.  Bugs you must live with.  "
"This OS of the future isn't a stable OS you can rely on.  It's for testing "
"purposes only."
msgstr ""
"Timbuktu の OS インストーラー内で目覚めました。そして 6 か月だけ未来です。し"
"かし、バグがあります。バグだらけです。共存すべきバグです。未来のこの OS は信"
"頼できるほど安定していません。これはテスト目的のみのものです。"

#: pyanaconda/ui/gui/spokes/welcome.glade:251
msgid "WELCOME TO %s %s."
msgstr "%s %s へようこそ。"

#: pyanaconda/ui/gui/spokes/welcome.glade:269
msgid "What language would you like to use during the installation process?"
msgstr "インストール時に使用する言語を選択してください。"

#: pyanaconda/ui/gui/spokes/welcome.glade:319
msgid "nativeName"
msgstr "nativeName"

#: pyanaconda/ui/gui/spokes/welcome.glade:335
msgid "englishName"
msgstr "englishName"

#: pyanaconda/ui/gui/spokes/welcome.glade:389
msgid "Set _keyboard to default layout for selected language."
msgstr "選択した言語でデフォルトのキーボードに設定(_K)"

#: pyanaconda/ui/gui/spokes/custom.glade:8
#: pyanaconda/ui/gui/spokes/custom.glade:1741
msgid "Help"
msgstr "ヘルプ"

#: pyanaconda/ui/gui/spokes/custom.glade:106
msgid "_Add mount point"
msgstr "マウントポイントの追加(_A)"

#: pyanaconda/ui/gui/spokes/custom.glade:139
msgid "<b>Desired Capacity:</b>"
msgstr "<b>要望する容量:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:154
#: pyanaconda/ui/gui/spokes/custom.glade:558
msgid "<b>Mount Point:</b>"
msgstr "<b>マウントポイント:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:170
msgid "ADD A NEW MOUNT POINT"
msgstr "新規のマウントポイントの追加"

#: pyanaconda/ui/gui/spokes/custom.glade:188
msgid ""
"More customization options are available\n"
"after creating the mount point below."
msgstr ""
"以下にマウントポイントを作成した後に、他のカスタム化オプションが利用できるよ"
"うになります。"

#: pyanaconda/ui/gui/spokes/custom.glade:206
msgid "eg: \"/\", \"/home\", \"swap\" (minus the quotation marks)"
msgstr "例: \"/\"、 \"/home\"、 \"swap\" (引用符は除く)"

#: pyanaconda/ui/gui/spokes/custom.glade:239
msgid ""
"That mount point is already in\n"
"use.  Try something else?"
msgstr ""
"そのマウントポイントはすでに使用中です。\n"
"　他を試しますか？"

#: pyanaconda/ui/gui/spokes/custom.glade:265
msgid "eg: \"20 GB\", \"500mb\" (minus the quotation marks)"
msgstr "例: \"20 GB\"、 \"500mb\" (引用符は除く)"

#: pyanaconda/ui/gui/spokes/custom.glade:308
msgid "Are you sure you want to delete all of the data on %s?"
msgstr "%s にある全データを本当に削除してもよいですか?"

#: pyanaconda/ui/gui/spokes/custom.glade:322
msgid "Delete all other filesystems in the %s root as well."
msgstr "%s root にある他のファイルシステムもすべて削除されます。"

#: pyanaconda/ui/gui/spokes/custom.glade:357
msgid "_Delete It"
msgstr "それを削除します(_D)"

#: pyanaconda/ui/gui/spokes/custom.glade:390
msgid "_Back to destination selection"
msgstr "目的地選択に戻る(_B)"

#: pyanaconda/ui/gui/spokes/custom.glade:476
msgid ""
"When you create mount points for your %s %s install,\n"
"you'll be able to view their details here."
msgstr ""
"%s %s インストール用のマウントポイントを作成する際に、\n"
"ここでその詳細を表示できます。"

#: pyanaconda/ui/gui/spokes/custom.glade:499
#: pyanaconda/ui/gui/spokes/custom.glade:1362
#: pyanaconda/ui/gui/spokes/custom.glade:1504
#: pyanaconda/ui/gui/spokes/custom.glade:1591
msgid "Selected Device"
msgstr "選択したデバイス"

#: pyanaconda/ui/gui/spokes/custom.glade:517
#: pyanaconda/ui/gui/spokes/custom.glade:1380
#: pyanaconda/ui/gui/spokes/custom.glade:1522
#: pyanaconda/ui/gui/spokes/custom.glade:1609
msgid "Device description"
msgstr "デバイスの説明"

#: pyanaconda/ui/gui/spokes/custom.glade:588
msgid "<b>Label:</b>"
msgstr "<b>ラベル:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:604
msgid "<b>Desired Capacity (MB):</b>"
msgstr "<b>要望する容量 (MB):</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:651
#: pyanaconda/ui/gui/spokes/custom.glade:2036
msgid "Name:"
msgstr "名前:"

#: pyanaconda/ui/gui/spokes/custom.glade:712
msgid "<b>Device Type:</b>"
msgstr "<b>デバイスタイプ:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:727
msgid "<b>File System:</b>"
msgstr "<b>ファイルシステム:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:773
msgid "_Encrypt"
msgstr "暗号化する(_E)"

#: pyanaconda/ui/gui/spokes/custom.glade:806
#: pyanaconda/ui/gui/spokes/custom.glade:903
#: pyanaconda/ui/gui/spokes/custom.glade:1144
msgid "Redundancy (mirror)"
msgstr "冗長 (ミラー)"

#: pyanaconda/ui/gui/spokes/custom.glade:825
#: pyanaconda/ui/gui/spokes/custom.glade:868
#: pyanaconda/ui/gui/spokes/custom.glade:922
#: pyanaconda/ui/gui/spokes/custom.glade:965
#: pyanaconda/ui/gui/spokes/custom.glade:1008
#: pyanaconda/ui/gui/spokes/custom.glade:1052
#: pyanaconda/ui/gui/spokes/custom.glade:1084
#: pyanaconda/ui/gui/spokes/custom.glade:1163
#: pyanaconda/ui/gui/spokes/custom.glade:1206
msgid "(-0Gb)"
msgstr "(-0Gb)"

#: pyanaconda/ui/gui/spokes/custom.glade:850
#: pyanaconda/ui/gui/spokes/custom.glade:947
#: pyanaconda/ui/gui/spokes/custom.glade:1188
msgid "Optimized performance (stripe)"
msgstr "最適化したパフォーマンス (ストライプ)"

#: pyanaconda/ui/gui/spokes/custom.glade:990
msgid "Error detection (parity)"
msgstr "エラー検出 (パリティ)"

#: pyanaconda/ui/gui/spokes/custom.glade:1034
msgid "Distributed"
msgstr "分散"

#: pyanaconda/ui/gui/spokes/custom.glade:1065
msgid "Redundant"
msgstr "冗長"

#: pyanaconda/ui/gui/spokes/custom.glade:1243
msgid "Reformat"
msgstr "再フォーマット"

#: pyanaconda/ui/gui/spokes/custom.glade:1262
msgid "Volume Group:"
msgstr "ボリュームグループ:"

#: pyanaconda/ui/gui/spokes/custom.glade:1291
msgid "Modify ..."
msgstr "変更 ..."

#: pyanaconda/ui/gui/spokes/custom.glade:1310
msgid "_Customize..."
msgstr "カスタマイズする(_C)..."

#: pyanaconda/ui/gui/spokes/custom.glade:1323
msgid "_Apply Changes"
msgstr "変更を適用(_A)"

#: pyanaconda/ui/gui/spokes/custom.glade:1414
msgid ""
"This device is encrypted and cannot be read without a valid passphrase. You "
"may unlock it below."
msgstr ""
"このデバイスは暗号化されているため有効なパスフレーズがないと読み込めません。"
"以下でアンロックできます。"

#: pyanaconda/ui/gui/spokes/custom.glade:1435
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:97
msgid "Passphrase:"
msgstr "パスフレーズ:"

#: pyanaconda/ui/gui/spokes/custom.glade:1461
msgid "_Unlock"
msgstr "アンロック(_U)"

#: pyanaconda/ui/gui/spokes/custom.glade:1556
msgid ""
"This device cannot be edited directly. You can remove it or select a "
"different device."
msgstr ""
"このデバイスの直接編集はできません。 デバイスを削除するか別のデバイスを選択し"
"ます。"

#: pyanaconda/ui/gui/spokes/custom.glade:1644
msgid ""
"This %s device is missing %d of %d %s. You can remove it or select a "
"different device."
msgstr ""
"%s デバイスの %d / %d の %s が見つかりません。削除するか他のデバイスを選択し"
"てください。"

#: pyanaconda/ui/gui/spokes/custom.glade:1690
msgid "Add a new mountpoint."
msgstr "新しいマウントポイントを追加します。"

#: pyanaconda/ui/gui/spokes/custom.glade:1691
msgid "addButton"
msgstr "追加ボタン"

#: pyanaconda/ui/gui/spokes/custom.glade:1708
msgid "Remove the selected mountpoint(s.)"
msgstr "選択したマウントポイントを削除します。"

#: pyanaconda/ui/gui/spokes/custom.glade:1709
msgid "removeButton"
msgstr "removeButton"

#: pyanaconda/ui/gui/spokes/custom.glade:1726
msgid "Configure selected mountpoint."
msgstr "選択したマウントポイントの設定を行います。"

#: pyanaconda/ui/gui/spokes/custom.glade:1727
msgid "configureButton"
msgstr "設定ボタン"

#: pyanaconda/ui/gui/spokes/custom.glade:1742
msgid "Click for help"
msgstr "ヘルプをクリックします"

#: pyanaconda/ui/gui/spokes/custom.glade:1790
msgid "<span size=\"small\" foreground=\"white\">AVAILABLE SPACE</span>"
msgstr "<span size=\"small\" foreground=\"white\">利用可能な領域</span>"

#: pyanaconda/ui/gui/spokes/custom.glade:1842
msgid "<span size=\"small\" foreground=\"white\">TOTAL SPACE</span>"
msgstr "<span size=\"small\" foreground=\"white\">合計領域</span>"

#: pyanaconda/ui/gui/spokes/custom.glade:1881
msgid "_Finish Partitioning"
msgstr "パーティション設定の終了(_F)"

#: pyanaconda/ui/gui/spokes/custom.glade:1971
msgid "_Save"
msgstr "保存(_S)"

#: pyanaconda/ui/gui/spokes/custom.glade:2003
msgid "CONFIGURE VOLUME GROUP"
msgstr "構成するボリュームグループ"

#: pyanaconda/ui/gui/spokes/custom.glade:2018
msgid ""
"Please create a name for your volume group and select at least one disk "
"below."
msgstr ""
"ボリュームグループ名を決めて作成し、以下から少なくても1つのディスクを選択して"
"ください。"

#: pyanaconda/ui/gui/spokes/custom.glade:2101
#: pyanaconda/ui/gui/spokes/custom.glade:2302
#: pyanaconda/ui/gui/spokes/lib/cart.glade:138
msgid "Capacity"
msgstr "容量"

#: pyanaconda/ui/gui/spokes/custom.glade:2114
#: pyanaconda/ui/gui/spokes/custom.glade:2315
#: pyanaconda/ui/gui/spokes/lib/cart.glade:151
msgid "Free"
msgstr "空き"

#: pyanaconda/ui/gui/spokes/custom.glade:2127
#: pyanaconda/ui/gui/spokes/custom.glade:2328
msgid "ID"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/custom.glade:2209
msgid "_Select"
msgstr "選択(_S)"

#: pyanaconda/ui/gui/spokes/custom.glade:2241
msgid "CONFIGURE MOUNT POINT"
msgstr "マウントポイントの設定"

#: pyanaconda/ui/gui/spokes/custom.glade:2256
msgid "Select one or more disks this device may reside on."
msgstr "このデバイスを存在させるディスクをひとつまたは複数選択してください。"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:25
#: pyanaconda/ui/gui/spokes/lib/cart.glade:79
msgid "SELECTED DISKS"
msgstr "選択したディスク"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:43
msgid "_Close"
msgstr "閉じる(_C)"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:111
msgid "Boot"
msgstr "起動"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:125
msgid "Description"
msgstr "説明"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:163
msgid "Id"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:207
msgid "_Remove"
msgstr "削除(_R)"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:235
msgid "Disk summary goes here"
msgstr "ディスクの要約はここへ"

#: pyanaconda/ui/gui/spokes/lib/detailederror.glade:24
msgid "An unknown error occurred during installation.  Details are below."
msgstr "インストール中に不明なエラーが発生しました。詳細は以下にあります。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:20
msgid "DISK ENCRYPTION PASSPHRASE"
msgstr "ディスク暗号化用パスフレーズ"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:52
msgid "Save Passphrase"
msgstr "パスフレーズの保存"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:77
msgid ""
"You have chosen to encrypt some of your data. You will need to create a "
"passphrase that you will use to access your data when you start your "
"computer."
msgstr ""
"データの一部を暗号化する選択をしました。コンピュータの開始時にデータへのアク"
"セスに使用するパスフレーズを作成する必要があります。"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:212
msgid "keymap warning label"
msgstr "キー対応表警告ラベル"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:58
msgid "_Reclaim space"
msgstr "領域を確保する(_R)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:92
msgid "RECLAIM DISK SPACE"
msgstr "ディスク領域の獲得"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:109
msgid "Description goes here."
msgstr "説明"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:151
msgid "Filesystem"
msgstr "ファイルシステム"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:162
msgid "Reclaimable Space"
msgstr "獲得可能な領域"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:184
msgid "Action"
msgstr "アクション"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:249
msgid "<b>%s disks; %s reclaimable space</b> (in filesystems)"
msgstr "<b>%s 個のディスク; %s つの獲得可能領域</b> (ファイルシステム内)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:264
msgid "Total selected space to reclaim:  <b>%s</b>"
msgstr "選択した取得する領域の合計:　<b>%s</b>"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:279
msgid "Installation requires a total of <b>%s</b> for system data."
msgstr "インストールには、システムデータ用に合計 <b>%s</b> が必要です。"

#: pyanaconda/ui/gui/main.glade:80
msgid ""
"Are you sure you wish to quit the\n"
"installation process?"
msgstr ""
"インストールプロセスを本当に\n"
"終了したいですか？"

#: pyanaconda/ui/gui/hubs/summary.glade:11
msgid "INSTALLATION SUMMARY"
msgstr "インストール概要"

#: pyanaconda/ui/gui/hubs/summary.glade:95
msgid "_Begin Installation"
msgstr "インストールの開始(_B)"

#: pyanaconda/ui/gui/hubs/progress.glade:9
msgid "CONFIGURATION"
msgstr "設定"

#: pyanaconda/ui/gui/hubs/progress.glade:128
msgid ""
"%s is now successfully installed on your system, but some configuration "
"still needs to be done. \n"
"Finish it and then click the Finish configuration button please."
msgstr ""
"%s は今ご使用のシステムに正常にインストールされましたが、まだいくつかの設定が"
"必要です。\n"
"それを終了してから「設定の完了」ボタンをクリックして下さい。"

#: pyanaconda/ui/gui/hubs/progress.glade:140
msgid "_Finish configuration"
msgstr "設定完了(_F)"

#: pyanaconda/ui/gui/hubs/progress.glade:181
msgid ""
"%s is now successfully installed on your system and ready\n"
"for you to use!  Go ahead and reboot to start using it!"
msgstr ""
"%s は、ここでご使用のシステムに正常にインストールされ、\n"
"使用準備ができました。次に進むために再起動して使用を開始して下さい！"

#: pyanaconda/ui/gui/hubs/progress.glade:193
msgid "_Reboot"
msgstr "再起動(_R)"

#: widgets/src/BaseWindow.c:85
msgid "DISTRIBUTION INSTALLATION"
msgstr "ディストリビューションのインストール"

#: widgets/src/BaseWindow.c:86
msgid "SPOKE NAME"
msgstr "スポーク名"

#: widgets/src/BaseWindow.c:87
msgid "PRE-RELEASE / TESTING"
msgstr "プレリリース / テスト中"

#: widgets/src/DiskOverview.c:50
msgid "New Device"
msgstr "新しいデバイス"

#: widgets/src/DiskOverview.c:52
msgid "0 MB"
msgstr "0 MB"

#: widgets/src/MountpointSelector.c:48
msgid "Root"
msgstr "Root"

#: widgets/src/MountpointSelector.c:49
msgid "0 GB"
msgstr "0 GB"

#: widgets/src/SpokeSelector.c:55
msgid "New Selector"
msgstr "新しいセレクター"

#: data/liveinst/gnome/fedora-welcome:64
msgid "Welcome to Fedora"
msgstr "Fedora へようこそ"

#: data/liveinst/gnome/fedora-welcome:93
msgid "Try Fedora"
msgstr "Fedora を試す"

#: data/liveinst/gnome/fedora-welcome:111
msgid ""
"You are currently running Fedora from live media.\n"
"You can install Fedora now, or choose \"Install to Hard Drive\" in the "
"Activities Overview at any later time."
msgstr ""
"現在、ライブメディアから Fedora を稼働しています。\n"
"今、Fedora をインストールできます。または後でアクティビティオーバービューで"
"「ハードドライブにインストールする」を選択することもできます。"

#: data/liveinst/gnome/fedora-welcome:129
msgid ""
"You can choose \"Install to Hard Drive\"\n"
"in the Activities Overview at any later time."
msgstr ""
"後にでも「アクティビティオーバービュー」内で 「ハードドライブにインストール」"
"を選択することができます。"

#: data/liveinst/gnome/fedora-welcome:132
msgid "Close"
msgstr "閉じる"

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install to Hard Drive"
msgstr "ハードディスクにインストール"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install"
msgstr "インストール"

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install the live CD to your hard disk"
msgstr "ライブ ディスク をハードディスクにインストール"

#: liveinst:5
msgid "Starting Install to Hard Drive"
msgstr "ハードディスクへのインストールを開始します"
