# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR Red Hat, Inc.
# This file is distributed under the same license as the PACKAGE package.
#
# Translators:
# Aleksandr Brezhnev <abrezhnev@gmail.com>, 2012.
# Alexander Ivanov <hrafn@hrafn.me>, 2012.
# Alexey Vasyukov <alexey.vasyukov@vdel.com>, 2009.
# Alex Nik <rage.iz.me@gmail.com>, 2012.
# Andrew Martynov <andrewm@inventa.ru>, 2004-2006,2008-2009.
# dcantrel <dcantrell@redhat.com>, 2011.
# Dimitris Glezos <glezos@indifex.com>, 2011.
# Inna Kabanova <ikabanova@russianfedora.ru>, 2012.
#   <iya777@yandex.ru>, 2012.
# Leonid Kanter <leon@asplinux.ru>, 2004,2006.
# Misha Shnurapet <shnurapet@fedoraproject.org>, 2011-2012.
# Nikolay Sivov <bunglehead@gmail.com>, 2007.
# Raspopov Sergey <qwerty3456@mail.ru>, 2009.
# Stanislav Darchinov <darchinov@gmail.com>, 2011.
# Stanislav Hanzhin <hanzhin.stas@gmail.com>, 2012.
#   <ti.yarosh@gmail.com>, 2012.
# Valery Suhomlinov <goodguy@goodguy.spb.ru>, 2004.
# wedge <wedge@xwing>, 2006.
# Yulia <ypoyarko@redhat.com>, 2006,2008,2010.
# Yulia  <yulia.poyarkova@redhat.com>, 2006,2008,2010,2012.
# Yuri Khabarov <madb00blik@gmail.com>, 2011.
# Игорь Горбунов <igor.gorbounov@gmail.com>, 2011-2012.
msgid ""
msgstr ""
"Project-Id-Version: Anaconda\n"
"Report-Msgid-Bugs-To: anaconda-devel-list@redhat.com\n"
"POT-Creation-Date: 2013-01-07 16:55-0800\n"
"PO-Revision-Date: 2013-01-04 23:55+0000\n"
"Last-Translator: Brian Lane <bcl@redhat.com>\n"
"Language-Team: Russian <trans-ru@lists.fedoraproject.org>\n"
"Language: ru\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Plural-Forms: nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n"
"%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);\n"

#: anaconda:344
#, c-format
msgid ""
"%s requires %s MB of memory to install, but you only have %s MB on this "
"machine.\n"
msgstr ""
"%s требует %s МБ памяти для установки, но на этом компьютере доступно %s "
"МБ.\n"

#: anaconda:346
#, c-format
msgid ""
"The %s graphical installer requires %s MB of memory, but you only have %s MB."
msgstr ""
"Для графической установки %s необходимо %s МБ, но у вас есть только %s МБ."

#: anaconda:351
msgid "Not enough RAM"
msgstr "Недостаточно оперативной памяти"

#: anaconda:352
msgid ""
" Try the text mode installer by running:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" from a root terminal."
msgstr ""
" Попробуйте запустить установщик в текстовом режиме, выполнив:\n"
"\n"
"'/usr/bin/liveinst -T'\n"
"\n"
" из терминала пользователя root."

#: anaconda:355
msgid " Starting text mode."
msgstr "Запуск текстового режима."

#: anaconda:382 pyanaconda/rescue.py:268 pyanaconda/rescue.py:301
#: pyanaconda/rescue.py:314 pyanaconda/rescue.py:382 pyanaconda/rescue.py:398
#: pyanaconda/rescue.py:409
msgid "OK"
msgstr "OК"

#: anaconda:484
msgid ""
"Text mode provides a limited set of installation options. It does not allow "
"you to specify your own partitioning layout or package selections. Would you "
"like to use VNC mode instead?"
msgstr ""
"Текстовый режим предоставляет ограниченный выбор параметров установки. Он не "
"позволит вам указать ваш собственный метод разбиения на разделы или "
"выбранные пакеты. Хотите ли вы использовать режим VNC вместо этого?"

#: anaconda:508
msgid "DISPLAY variable not set. Starting text mode."
msgstr "Переменная DISPLAY не определена. Запускается текстовый режим."

#: anaconda:516
msgid "Graphical installation is not available. Starting text mode."
msgstr "Графическая установка невозможна. Запускается текстовый режим."

#: anaconda:627
#, c-format
msgid "Please ssh install@%s to begin the install."
msgstr "Для начала установки выполните ssh install@%s."

#: anaconda:629
msgid "Please ssh install@<host> to continue installation."
msgstr "Для продолжения установки выполните ssh install@<узел>."

#: pyanaconda/bootloader.py:239
msgid "/boot filesystem"
msgstr "файловая система /boot"

#: pyanaconda/bootloader.py:388
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following raid levels: %s."
msgstr ""
"Массивы RAID, в которые входит '%s', должны иметь один из следующих raid-"
"уровней: %s."

#: pyanaconda/bootloader.py:396
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following metadata "
"versions: %s."
msgstr ""
"Массивы RAID, в которые входит '%s', должны иметь метаданные одной из "
"следующих версий: %s."

#: pyanaconda/bootloader.py:404
#, python-format
msgid ""
"RAID sets that contain '%s' must have one of the following device types: %s."
msgstr ""
"Массивы RAID, в которые входит '%s', должны иметь устройства одного из "
"следующих типов: %s."

#: pyanaconda/bootloader.py:420
#, python-format
msgid "%s must have one of the following disklabel types: %s."
msgstr "%s должен иметь один из следующих типов меток диска: %s."

#: pyanaconda/bootloader.py:432
#, python-format
msgid "%s cannot be of type %s."
msgstr "%s не может быть типа %s."

#: pyanaconda/bootloader.py:438
#, python-format
msgid "%s must be mounted on one of %s."
msgstr "%s должен быть смонтирован на одном из %s."

#: pyanaconda/bootloader.py:450
#, python-format
msgid "%s must be between %d and %d MB in size"
msgstr "%s должен быть размером между %d и %d МБ"

#: pyanaconda/bootloader.py:455
#, python-format
msgid "%s must not be smaller than %dMB."
msgstr "%s не должен быть меньше, чем %d МБ."

#: pyanaconda/bootloader.py:464
#, python-format
msgid "%s must not be larger than %dMB."
msgstr "%s не должен быть больше, чем %d МБ."

#: pyanaconda/bootloader.py:482
#, python-format
msgid "%s must be within the first %dMB of the disk."
msgstr "%s должен быть в первых %d МБ диска."

#: pyanaconda/bootloader.py:492
#, python-format
msgid "%s must be on a primary partition."
msgstr "%s должен быть на основном разделе."

#: pyanaconda/bootloader.py:616 pyanaconda/bootloader.py:706
#, python-format
msgid "%s cannot be on an encrypted block device."
msgstr "%s не может быть на зашифрованном блочном устройстве."

#: pyanaconda/bootloader.py:664
#, python-format
msgid "%s cannot be of type %s"
msgstr "%s не может быть типа %s"

#: pyanaconda/bootloader.py:1585
#, python-format
msgid ""
"%s may not have enough space for grub2 to embed core.img when using the %s "
"filesystem on %s"
msgstr ""
"В %s может быть недостаточно места, чтобы grub2 мог встроить  core.img при "
"использовании файловой системы %s на %s"

#: pyanaconda/cmdline.py:66
msgid "Completed"
msgstr "Выполнено"

#: pyanaconda/cmdline.py:74
msgid "In progress"
msgstr "В процессе"

#: pyanaconda/cmdline.py:87
#, python-format
msgid ""
"(%s)\n"
"Command line mode requires all choices to be specified in a kickstart "
"configuration file."
msgstr ""
"(%s)\n"
"При установке в режиме командной строки все ответы на вопросы программы "
"установки должны быть указаны в файле конфигурации кикстарта."

#: pyanaconda/cmdline.py:104
#, python-format
msgid ""
"The following error was found while parsing the kickstart configuration "
"file:\n"
"\n"
"%s"
msgstr ""
"Ошибка при разборе конфигурации кикстарта:\n"
"\n"
"%s"

#: pyanaconda/cmdline.py:113
#, python-format
msgid ""
"(%s)\n"
"%s"
msgstr ""
"(%s)\n"
"%s"

#: pyanaconda/cmdline.py:126 pyanaconda/cmdline.py:131
#: pyanaconda/cmdline.py:137 pyanaconda/cmdline.py:142
#: pyanaconda/ui/tui/hubs/summary.py:58
msgid "Can't have a question in command line mode!"
msgstr "Нельзя задавать вопрос в режиме командной строки!"

#: pyanaconda/cmdline.py:161
#, python-format
msgid "In interactive step can't continue. (%s)"
msgstr "Остановка на интерактивном шаге. (%s)"

#: pyanaconda/constants.py:57
msgid ""
"An unhandled exception has occurred.  This is most likely a bug.  Please "
"save a copy of the detailed exception and file a bug report"
msgstr ""
"Произошло необработанное исключение. Скорее всего, это ошибка. Сохраните "
"текст исключения и создайте отчёт об ошибке"

#: pyanaconda/constants.py:63
msgid " with the provider of this software."
msgstr " производителю этого программного компонента."

#: pyanaconda/constants.py:67
#, python-format
msgid " against anaconda at %s"
msgstr " относительно Anaconda (%s)"

#: pyanaconda/constants.py:95
msgid "Start VNC"
msgstr "Запустить VNC"

#: pyanaconda/constants.py:96
msgid "Use text mode"
msgstr "Использовать текстовый режим"

#: pyanaconda/install.py:59
msgid "Configuring installed system"
msgstr ""

#: pyanaconda/install.py:71
msgid "Writing network configuration"
msgstr ""

#: pyanaconda/install.py:75
msgid "Creating users"
msgstr ""

#: pyanaconda/install.py:82
msgid "Running post install scripts"
msgstr ""

#: pyanaconda/install.py:130 pyanaconda/packaging/livepayload.py:133
#: pyanaconda/packaging/yumpayload.py:1631
msgid "Performing post-install setup tasks"
msgstr "Выполняются пост-установочные задачи"

#: pyanaconda/install.py:134
msgid "Installing bootloader"
msgstr ""

#: pyanaconda/installclass.py:68
msgid "Install on System"
msgstr "Установка в системе"

#: pyanaconda/installinterfacebase.py:51
msgid "Error Setting Up Repository"
msgstr "Ошибка настройки репозитория"

#: pyanaconda/installinterfacebase.py:52
#, python-format
msgid ""
"The following error occurred while setting up the installation repository:\n"
"\n"
"%(e)s\n"
"\n"
"Installation can not continue."
msgstr ""
"Следующая ошибка возникла при настройке репозитория установки:\n"
"\n"
"%(e)s\n"
"\n"
"Продолжение установки невозможно."

#: pyanaconda/installinterfacebase.py:58
msgid "Exit installer"
msgstr "Прервать установку"

#: pyanaconda/installinterfacebase.py:62
#, python-format
msgid ""
"The installation was stopped due to what seems to be a problem with your "
"hardware. The exact error message is:\n"
"\n"
"%s.\n"
"\n"
" The installer will now terminate."
msgstr ""
"Установка остановлена, по-видимому, из-за проблемы с вашим оборудованием. "
"Сообщение об ошибке в точности:\n"
"\n"
"%s.\n"
"\n"
" Теперь установка будет прекращена."

#: pyanaconda/installinterfacebase.py:65
msgid "Hardware Error Encountered"
msgstr "Возникла аппаратная ошибка"

#: pyanaconda/installinterfacebase.py:69 pyanaconda/yuminstall.py:263
#: pyanaconda/yuminstall.py:409 pyanaconda/yuminstall.py:835
#: pyanaconda/yuminstall.py:1013 pyanaconda/yuminstall.py:1018
#: pyanaconda/yuminstall.py:1055 pyanaconda/yuminstall.py:1107
#: pyanaconda/yuminstall.py:1113 pyanaconda/yuminstall.py:1269
#: pyanaconda/yuminstall.py:1284 pyanaconda/yuminstall.py:1339
#: pyanaconda/yuminstall.py:1534 pyanaconda/yuminstall.py:1567
#: pyanaconda/yuminstall.py:1590
msgid "_Exit installer"
msgstr "В_ыход из программы установки"

#: pyanaconda/iutil.py:898
msgid "the device containing /boot"
msgstr "устройство, содержащее /boot"

#: pyanaconda/iutil.py:900
#, python-format
msgid ""
"After shutdown, please perform a manual IPL from %s to continue installation."
msgstr ""
"После выключения системы, пожалуйста, выполните вручную IPL-загрузку с %s, "
"чтобы продолжить установку."

#: pyanaconda/kickstart.py:155
#, python-format
msgid "Escrow certificate %s requires the network."
msgstr "Для escrow-сертификата %s требуется сетевое подключение."

#: pyanaconda/kickstart.py:163
#, python-format
msgid ""
"The following error was encountered while downloading the escrow "
"certificate:\n"
"\n"
"%s"
msgstr ""
"Произошла ошибка при загрузке сертификата escrow:\n"
"\n"
"%s"

#: pyanaconda/kickstart.py:482
#, python-format
msgid "%s is missing. Cannot setup firewall."
msgstr "Нет %s. Настройка сетевого экрана невозможна."

#: pyanaconda/kickstart.py:1466
msgid "Running pre-installation scripts"
msgstr "Выполняются пред-установочные сценарии"

#: pyanaconda/network.py:94
msgid "Hostname cannot be None or an empty string."
msgstr ""

#: pyanaconda/network.py:97
msgid "Hostname must be 255 or fewer characters in length."
msgstr "Имя узла не может содержать более 255 символов."

#: pyanaconda/network.py:103
msgid ""
"Hostname must start with a valid character in the ranges 'a-z', 'A-Z', or "
"'0-9'"
msgstr "Имя узла должно начинаться с символов a-z, A-Z, 0-9."

#: pyanaconda/network.py:111
msgid ""
"Hostnames can only contain the characters 'a-z', 'A-Z', '0-9', '-', or '.', "
"parts between periods must contain something and cannot start or end with "
"'-'."
msgstr ""

#: pyanaconda/network.py:168
msgid "IP address is missing."
msgstr "Не указан IP-адрес."

#: pyanaconda/network.py:172
msgid ""
"IPv4 addresses must contain four numbers between 0 and 255, separated by "
"periods."
msgstr ""
"Адреса в формате IPv4 должны состоять из четырёх чисел в диапазоне от 0 до "
"255, разделённых точками."

#: pyanaconda/network.py:175
#, python-format
msgid "'%s' is not a valid IPv6 address."
msgstr "Недопустимый адрес IPv6: %s"

#: pyanaconda/network.py:177
#, python-format
msgid "'%s' is an invalid IP address."
msgstr "Недопустимый адрес IP: %s"

#: pyanaconda/platform.py:58
msgid "bootloader device"
msgstr "устройство загрузчика"

#: pyanaconda/platform.py:59
msgid "RAID Device"
msgstr "Устройство RAID"

#: pyanaconda/platform.py:60
msgid "First sector of boot partition"
msgstr "Первый сектор загрузочного раздела"

#: pyanaconda/platform.py:158 pyanaconda/platform.py:341
msgid "Master Boot Record"
msgstr "Главная загрузочная запись"

#: pyanaconda/platform.py:194
msgid "EFI System Partition"
msgstr "Системный раздел EFI"

#: pyanaconda/platform.py:223
msgid "Apple EFI Boot Partition"
msgstr "Раздел Apple EFI Boot"

#: pyanaconda/platform.py:248
msgid "PReP Boot Partition"
msgstr "Раздел PReP Boot"

#: pyanaconda/platform.py:271
msgid "Apple Bootstrap Partition"
msgstr "Раздел Apple Bootstrap"

#: pyanaconda/platform.py:300
msgid "DASD"
msgstr "DASD"

#: pyanaconda/platform.py:301
msgid "zFCP"
msgstr "zFCP"

#: pyanaconda/platform.py:366
msgid "U-Boot Partition"
msgstr "Раздел U-Boot"

#: pyanaconda/product.py:54
#, python-format
msgid "%(productName)s %(productVersion)s INSTALLATION"
msgstr ""

#: pyanaconda/rescue.py:171 pyanaconda/rescue.py:290 pyanaconda/rescue.py:375
#, python-format
msgid "Run %s to unmount the system when you are finished."
msgstr "Выполнить %s для размонтирования системы, когда вы закончите."

#: pyanaconda/rescue.py:174
msgid "When finished please exit from the shell and your system will reboot."
msgstr "После завершения выйдите из оболочки, и система будет перезагружена."

#: pyanaconda/rescue.py:188
msgid "Unable to find /bin/sh to execute!  Not starting shell"
msgstr "Не удаётся найти /bin/sh для запуска! Оболочка не будет запущена."

#: pyanaconda/rescue.py:224 pyanaconda/rescue.py:297 pyanaconda/rescue.py:307
#: pyanaconda/rescue.py:378 pyanaconda/rescue.py:409
msgid "Rescue"
msgstr "Восстановить"

#: pyanaconda/rescue.py:225
#, python-format
msgid ""
"The rescue environment will now attempt to find your Linux installation and "
"mount it under the directory %s.  You can then make any changes required to "
"your system.  If you want to proceed with this step choose 'Continue'.  You "
"can also choose to mount your file systems read-only instead of read-write "
"by choosing 'Read-Only'.  \n"
"\n"
"If for some reason this process fails you can choose 'Skip' and this step "
"will be skipped and you will go directly to a command shell.\n"
"\n"
msgstr ""
"Режим восстановления сейчас попытается найти вашу систему Linux и "
"смонтировать ее в каталоге %s.  После этого вы сможете внести в систему "
"требуемые изменения.  Если вы хотите продолжить этот шаг, выберите "
"«Продолжить».  Можно также выбрать вариант монтирования файловых систем в "
"режиме только для чтения, а не записи-чтения, выбрав «Только для чтения».  \n"
"\n"
"Если по какой-либо причине этот процесс не удастся, можно выбрать "
"«Пропустить», и этот шаг будет пропущен, а вы попадете прямо в командную "
"оболочку.\n"
"\n"

#: pyanaconda/rescue.py:235 pyanaconda/storage/devicetree.py:96
msgid "Continue"
msgstr "Продолжить"

#: pyanaconda/rescue.py:235 pyanaconda/rescue.py:241
msgid "Read-Only"
msgstr "Только для чтения"

#: pyanaconda/rescue.py:235 pyanaconda/rescue.py:237
msgid "Skip"
msgstr "Пропустить"

#: pyanaconda/rescue.py:265
msgid "System to Rescue"
msgstr "Система для восстановления"

#: pyanaconda/rescue.py:266
msgid "Which device holds the root partition of your installation?"
msgstr "Укажите устройство, содержащее корневой раздел для установки."

#: pyanaconda/rescue.py:268 pyanaconda/rescue.py:272
msgid "Exit"
msgstr "Выход"

#: pyanaconda/rescue.py:287 pyanaconda/rescue.py:372
msgid "The system will reboot automatically when you exit from the shell."
msgstr "Система будет перезагружена автоматически после выхода из оболочки."

#: pyanaconda/rescue.py:298
#, python-format
msgid ""
"Your system had dirty file systems which you chose not to mount.  Press "
"return to get a shell from which you can fsck and mount your partitions. %s"
msgstr ""
"В системе есть «грязные» файловые системы, которые не были выбраны для "
"монтирования. Нажмите return для входа в оболочку, где можно будет выполнить "
"проверку fsck и смонтировать разделы. %s"

#: pyanaconda/rescue.py:308
#, python-format
msgid ""
"Your system has been mounted under %(rootPath)s.\n"
"\n"
"Press <return> to get a shell. If you would like to make your system the "
"root environment, run the command:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"
msgstr ""
"Система смонтирована в %(rootPath)s.\n"
"\n"
"Нажмите «Enter» для входа в оболочку. Если вы хотите сделать систему "
"корневой средой, выполните команду:\n"
"\n"
"\tchroot %(rootPath)s\n"
"\n"
"%(msg)s"

#: pyanaconda/rescue.py:379
#, python-format
msgid ""
"An error occurred trying to mount some or all of your system. Some of it may "
"be mounted under %s.\n"
"\n"
"Press <return> to get a shell."
msgstr ""
"При попытке монтирования некоторых из файловых систем возникла ошибка. "
"Некоторые из них могут быть монтированы в %s.\n"
"\n"
"Нажмите «Enter» для входа в оболочку."

#: pyanaconda/rescue.py:387
msgid "You don't have any Linux partitions.  Rebooting.\n"
msgstr "В системе нет разделов Linux. Будет выполнена перезагрузка.\n"

#: pyanaconda/rescue.py:391
msgid " The system will reboot automatically when you exit from the shell."
msgstr "Система будет перезагружена автоматически после выхода из оболочки."

#: pyanaconda/rescue.py:395
msgid "Rescue Mode"
msgstr "Режим восстановления"

#: pyanaconda/rescue.py:396
#, python-format
msgid "You don't have any Linux partitions. Press return to get a shell.%s"
msgstr "В системе нет разделов Linux. Нажмите «Enter» для входа в оболочку.%s"

#: pyanaconda/rescue.py:408
#, python-format
msgid "Your system is mounted under the %s directory."
msgstr "Ваша система смонтирована в каталог %s."

#: pyanaconda/vnc.py:61
#, python-format
msgid "%(productName)s %(productVersion)s installation"
msgstr "%(productName)s %(productVersion)s установка"

#: pyanaconda/vnc.py:118
#, python-format
msgid "%(productName)s %(productVersion)s installation on host %(name)s"
msgstr "Установка %(productName)s %(productVersion)s на %(name)s"

#: pyanaconda/vnc.py:137
#, python-format
msgid "Attempting to connect to vnc client on host %s..."
msgstr "Попытка соединения с VNC-клиентом на узле %s..."

#: pyanaconda/vnc.py:151
msgid "Connected!"
msgstr "Подключен!"

#: pyanaconda/vnc.py:154
msgid "Will try to connect again in 15 seconds..."
msgstr ""
"Повторная попытка установить соединение будет предпринята через 15 секунд..."

#: pyanaconda/vnc.py:160
#, python-format
msgid "Giving up attempting to connect after %d try!\n"
msgid_plural "Giving up attempting to connect after %d tries!\n"
msgstr[0] "Установка соединения прекращена после %d попытки.\n"
msgstr[1] "Установка соединения прекращена после %d попыток.\n"
msgstr[2] "Установка соединения прекращена после %d попыток.\n"

#: pyanaconda/vnc.py:171
#, python-format
msgid "Please manually connect your vnc client to %s to begin the install."
msgstr "Для начала установки подключите VNC-клиент к %s вручную."

#: pyanaconda/vnc.py:173
#, python-format
msgid ""
"Please manually connect your vnc client to <IP ADDRESS>:%s to begin the "
"install. Switch to the shell (Ctrl-B 2) and run 'ip addr' to find the <IP "
"ADDRESS>."
msgstr ""

#: pyanaconda/vnc.py:178
msgid "Starting VNC..."
msgstr "Запуск VNC..."

#: pyanaconda/vnc.py:220
msgid "The VNC server is now running."
msgstr "Сервер VNC запущен."

#: pyanaconda/vnc.py:224
msgid ""
"\n"
"\n"
"You chose to connect to a listening vncviewer. \n"
"This does not require a password to be set.  If you \n"
"set a password, it will be used in case the connection \n"
"to the vncviewer is unsuccessful\n"
"\n"
msgstr ""
"\n"
"\n"
"Вы выбрали подключение к прослушивающему VNC-клиенту. \n"
"Этот режим не требует указания пароля. Если вы\n"
"определите пароль, его можно будет использовать для \n"
"подключения к VNC-серверу в том случае, если тому не\n"
"удастся подключиться к прослушивающему VNC-клиенту.\n"
"\n"

#: pyanaconda/vnc.py:229
msgid ""
"\n"
"\n"
"WARNING!!! VNC server running with NO PASSWORD!\n"
"You can use the vncpassword=<password> boot option\n"
"if you would like to secure the server.\n"
"\n"
msgstr ""
"\n"
"\n"
"Внимание! Сервер VNC запущен БЕЗ ПАРОЛЯ!\n"
"Используйте параметр загрузки vncpassword=«пароль»,\n"
"если хотите защитить доступ к серверу.\n"
"\n"

#: pyanaconda/vnc.py:233
msgid ""
"\n"
"\n"
"You chose to execute vnc with a password. \n"
"\n"
msgstr ""
"\n"
"\n"
"Вы выбрали запуск VNC с паролем.\n"
"\n"

#: pyanaconda/vnc.py:235
msgid ""
"\n"
"\n"
"Unknown Error.  Aborting. \n"
"\n"
msgstr ""
"\n"
"\n"
"Неизвестная ошибка. Остановка работы.\n"
"\n"

#: pyanaconda/vnc.py:255
msgid ""
"VNC password provided was not at least 6 characters long.\n"
"Please enter a new one.  Leave blank for no password."
msgstr ""
"Указанный пароль VNC содержит меньше 6 символов.\n"
"Введите новый пароль. Для работы без пароля оставьте поле пустым."

#: pyanaconda/yuminstall.py:87
#, python-format
msgid "%s MB"
msgstr "%s МБ"

#: pyanaconda/yuminstall.py:90
#, python-format
msgid "%s KB"
msgstr "%s КБ"

#: pyanaconda/yuminstall.py:92
#, python-format
msgid "%s Byte"
msgid_plural "%s Bytes"
msgstr[0] "%s байт"
msgstr[1] "%s байта"
msgstr[2] "%s байт"

#: pyanaconda/yuminstall.py:134 pyanaconda/ui/gui/hubs/progress.glade:83
msgid "Preparing to install"
msgstr "Подготовка к установке"

#: pyanaconda/yuminstall.py:135 pyanaconda/packaging/yumpayload.py:1536
msgid "Preparing transaction from installation source"
msgstr "Подготовка транзакции из источника установки"

#: pyanaconda/yuminstall.py:170
#, python-format
msgid "<b>Upgrading %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>Обновление %(pkgStr)s</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:173
#, python-format
msgid "<b>Installing %(pkgStr)s</b> (%(size)s)\n"
msgstr "<b>Установка %(pkgStr)s</b> (%(size)s)\n"

#: pyanaconda/yuminstall.py:218
#, python-format
msgid "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgid_plural "Packages completed: %(donepkgs)d of %(numpkgs)d"
msgstr[0] "Установлено пакетов: %(donepkgs)d из %(numpkgs)d"
msgstr[1] "Установлено пакетов: %(donepkgs)d из %(numpkgs)d"
msgstr[2] "Установлено пакетов: %(donepkgs)d из %(numpkgs)d"

#: pyanaconda/yuminstall.py:232
#, python-format
msgid "<b>Cleaning up %s</b>"
msgstr "<b>Очистка %s</b>"

#: pyanaconda/yuminstall.py:252
msgid "cpio"
msgstr "cpio"

#: pyanaconda/yuminstall.py:254
msgid "unpack"
msgstr "распаковать"

#: pyanaconda/yuminstall.py:256
msgid "script"
msgstr "скрипт"

#: pyanaconda/yuminstall.py:257
msgid "Error Installing Package"
msgstr "Ошибка установки пакета"

#: pyanaconda/yuminstall.py:258
#, python-format
msgid ""
"A %s error occurred when installing the %s package.  This could indicate "
"errors when reading the installation media.  Installation cannot continue."
msgstr ""
"Произошла ошибка %s при установке пакета %s. Возможная причина -- ошибки при "
"чтении установочного носителя. Продолжение установки невозможно."

#: pyanaconda/yuminstall.py:406
msgid "Wrong Disc"
msgstr "Неверный диск"

#: pyanaconda/yuminstall.py:407
#, python-format
msgid "That's not the correct %s disc."
msgstr "Неверный диск %s."

#: pyanaconda/yuminstall.py:564
#, python-format
msgid "Repository %r is missing name in configuration, using id"
msgstr ""
"В конфигурации отсутствует имя репозитория %r. Вместо имени будет "
"использоваться идентификатор."

#: pyanaconda/yuminstall.py:830 pyanaconda/yuminstall.py:1264
msgid "No Network Available"
msgstr "Сеть недоступна"

#: pyanaconda/yuminstall.py:831 pyanaconda/yuminstall.py:1265
msgid ""
"Some of your software repositories require networking, but there was an "
"error enabling the network on your system."
msgstr ""
"Некоторые репозитории требуют наличия подключения к сети, но произошла "
"ошибка при ее настройке."

#: pyanaconda/yuminstall.py:919 pyanaconda/yuminstall.py:921
msgid "Re_boot"
msgstr "_Перезагрузка"

#: pyanaconda/yuminstall.py:919
msgid "_Eject"
msgstr "_Извлечь CD"

#: pyanaconda/yuminstall.py:921 pyanaconda/yuminstall.py:1284
#: pyanaconda/yuminstall.py:1339 pyanaconda/yuminstall.py:1567
msgid "_Retry"
msgstr "_Повторить"

#: pyanaconda/yuminstall.py:924 pyanaconda/yuminstall.py:1011
#: pyanaconda/yuminstall.py:1016 pyanaconda/yuminstall.py:1289
#: pyanaconda/yuminstall.py:1349 pyanaconda/yuminstall.py:1561
#: pyanaconda/yuminstall.py:1583 pyanaconda/storage/zfcp.py:375
#: pyanaconda/ui/tui/__init__.py:38
msgid "Error"
msgstr "Ошибка"

#: pyanaconda/yuminstall.py:925
#, python-format
msgid ""
"The file %s cannot be opened.  This is due to a missing file, a corrupt "
"package or corrupt media.  Please verify your installation source.\n"
"\n"
"If you exit, your system will be left in an inconsistent state that will "
"likely require reinstallation.\n"
"\n"
msgstr ""
"Не удается открыть файл %s. Возможная причина -- отсутствие файла или "
"сбойный пакет/ носитель. Убедитесь, что дерево установки содержит все "
"необходимые пакеты.\n"
"\n"
"При отмене установки система останется в нестабильном состоянии, вероятно, "
"требующем переустановки.\n"
"\n"

#: pyanaconda/yuminstall.py:972
msgid "Retrying"
msgstr "Повторная попытка"

#: pyanaconda/yuminstall.py:972
msgid "Retrying download."
msgstr "Повтор попытки загрузки."

#: pyanaconda/yuminstall.py:1007
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s\n"
msgstr "При выполнении транзакции произошла ошибка по следующей причине: %s\n"

#: pyanaconda/yuminstall.py:1018 pyanaconda/yuminstall.py:1113
#: pyanaconda/yuminstall.py:1536 pyanaconda/yuminstall.py:1590
msgid "_Back"
msgstr "_Назад"

#: pyanaconda/yuminstall.py:1051
#, python-format
msgid ""
"There was an error running your transaction for the following reason: %s.\n"
msgstr "В ходе вашей транзакции произошла ошибка по следующей причине: %s.\n"

#: pyanaconda/yuminstall.py:1053 pyanaconda/yuminstall.py:1105
#: pyanaconda/yuminstall.py:1110
msgid "Error Running Transaction"
msgstr "Ошибка при выполнении транзакции"

#: pyanaconda/yuminstall.py:1059 pyanaconda/yuminstall.py:1060
msgid "file conflicts"
msgstr "конфликты файлов"

#: pyanaconda/yuminstall.py:1061
msgid "older package(s)"
msgstr "старые пакеты"

#: pyanaconda/yuminstall.py:1062
msgid "insufficient disk space"
msgstr "недостаточно места на диске"

#: pyanaconda/yuminstall.py:1063
msgid "insufficient disk inodes"
msgstr "недостаточное кол-во индексных дескрипторов на диске"

#: pyanaconda/yuminstall.py:1064
msgid "package conflicts"
msgstr "конфликты пакетов"

#: pyanaconda/yuminstall.py:1065
msgid "package already installed"
msgstr "пакет уже установлен"

#: pyanaconda/yuminstall.py:1066
msgid "required package"
msgstr "требуется пакет"

#: pyanaconda/yuminstall.py:1067
msgid "package for incorrect arch"
msgstr "пакет для не той архитектуры"

#: pyanaconda/yuminstall.py:1068
msgid "package for incorrect os"
msgstr "пакет для не той операционной системы"

#: pyanaconda/yuminstall.py:1082 pyanaconda/packaging/yumpayload.py:1364
msgid "You need more space on the following file systems:\n"
msgstr "Требуется больше места на следующих файловых системах:\n"

#: pyanaconda/yuminstall.py:1095
#, python-format
msgid ""
"There were file conflicts when checking the packages to be installed:\n"
"%s\n"
msgstr ""
"При проверке пакетов для установки обнаружены конфликты файлов:\n"
"%s\n"

#: pyanaconda/yuminstall.py:1098
#, python-format
msgid ""
"There was an error running your transaction for the following reason(s): "
"%s.\n"
msgstr "При выполнении транзакции произошла ошибка по следующим причинам: %s\n"

#: pyanaconda/yuminstall.py:1290
msgid ""
"Unable to read group information from repositories.  This is a problem with "
"the generation of your install tree."
msgstr ""
"Невозможно прочесть информацию о группах из репозиториев. Это проблема "
"относится к генерированию дерева установки."

#: pyanaconda/yuminstall.py:1339
msgid "Edit"
msgstr "Изменить"

#: pyanaconda/yuminstall.py:1344 pyanaconda/yuminstall.py:1534
#: pyanaconda/ui/gui/spokes/storage.glade:43
#: pyanaconda/ui/gui/spokes/storage.glade:952
#: widgets/src/StandaloneWindow.c:53
msgid "_Continue"
msgstr "П_родолжить"

#: pyanaconda/yuminstall.py:1350 pyanaconda/yuminstall.py:1562
#, python-format
msgid ""
"Unable to read package metadata. This may be due to a missing repodata "
"directory.  Please ensure that your install tree has been correctly "
"generated.\n"
"\n"
"%s"
msgstr ""
"Не удаётся прочитать метаданные пакета. Возможная причина — отсутствие "
"каталога repodata. Убедитесь, что дерево установки сформировано правильно.\n"
"\n"
"%s"

#: pyanaconda/yuminstall.py:1538
msgid "Warning"
msgstr "Внимание"

#: pyanaconda/yuminstall.py:1539
msgid ""
"Some of the packages you have selected for install are missing "
"dependencies.  You can exit the installation, go back and change your "
"package selections, or continue installing these packages without their "
"dependencies.  If you continue, these packages may not work correctly due to "
"missing components."
msgstr ""
"Отсутствуют зависимости для некоторых выбранных для установки пакетов.  "
"Можно выйти из процесса установки, вернуться назад и изменить набор пакетов "
"или продолжить установку этих пакетов без их зависимостей. При продолжении "
"установки выбранные пакеты могут работать неверно из-за отсутствия некоторых "
"компонентов."

#: pyanaconda/yuminstall.py:1584
#, python-format
msgid ""
"Your selected packages require %d MB of free space for installation, but you "
"do not have enough available.  You can change your selections or exit the "
"installer."
msgstr ""
"Выбранные пакеты требуют для установки %d МБ свободного места, а у вас его "
"недостаточно. Вы можете изменить выбор или выйти из программы установки."

#: pyanaconda/yuminstall.py:1669
msgid "Post Upgrade"
msgstr "После обновления"

#: pyanaconda/yuminstall.py:1670
msgid "Performing post-upgrade configuration"
msgstr "Выполняется настройка после обновления"

#: pyanaconda/yuminstall.py:1672
msgid "Post Installation"
msgstr "После установки"

#: pyanaconda/yuminstall.py:1673
msgid "Performing post-installation configuration"
msgstr "Выполняется настройка после установки"

#: pyanaconda/yuminstall.py:1832
msgid "Installation Starting"
msgstr "Запуск установки"

#: pyanaconda/yuminstall.py:1833
msgid "Starting installation process"
msgstr "Запуск процесса установки"

#: pyanaconda/yuminstall.py:1871
msgid "Dependency Check"
msgstr "Проверка зависимостей"

#: pyanaconda/yuminstall.py:1872
msgid "Checking dependencies in packages selected for installation"
msgstr "Проверяются зависимости выбранных для установки пакетов"

#: pyanaconda/yuminstall.py:1928 pyanaconda/yuminstall.py:1944
msgid "Retrieving installation information."
msgstr "Получение установочной информации."

#: pyanaconda/yuminstall.py:1930 pyanaconda/yuminstall.py:1946
#, python-format
msgid "Retrieving installation information for %s."
msgstr "Получение установочной информации для %s."

#: pyanaconda/yuminstall.py:1931 pyanaconda/yuminstall.py:1947
msgid "Installation Progress"
msgstr "Прогресс установки"

#: pyanaconda/installclasses/fedora.py:35
msgid "_Fedora"
msgstr "_Fedora"

#: pyanaconda/installclasses/fedora.py:36
#, python-format
msgid ""
"The default installation of %s includes a set of software applicable for "
"general internet usage. You can optionally select a different set of "
"software now."
msgstr ""
"Стандартная установка %s включает набор программ, подходящих для решения "
"обычных задач работы с Интернетом. Поддержку каких дополнительных задач вы "
"хотели бы включить?"

#: pyanaconda/installclasses/fedora.py:45
msgid "Graphical Desktop"
msgstr "Графический рабочий стол"

#: pyanaconda/installclasses/fedora.py:50
msgid "Software Development"
msgstr "Разработка программного обеспечения"

#: pyanaconda/installclasses/fedora.py:56
msgid "Web Server"
msgstr "Веб-сервер"

#: pyanaconda/installclasses/fedora.py:60 pyanaconda/installclasses/rhel.py:39
msgid "Minimal"
msgstr "Минимальный набор программ"

#: pyanaconda/installclasses/rhel.py:28
msgid "Red Hat Enterprise Linux"
msgstr "Red Hat Enterprise Linux"

#: pyanaconda/installclasses/rhel.py:29
#, python-format
msgid ""
"The default installation of %s is a minimum install. You can optionally "
"select a different set of software now."
msgstr ""
"Стандартная установка %s включает минимальный набор программ. По желанию "
"можно выбрать другой набор программ."

#: pyanaconda/packaging/livepayload.py:72
#: pyanaconda/packaging/livepayload.py:90
msgid "Installing software"
msgstr "Устанавливается программное обеспечение"

#: pyanaconda/packaging/yumpayload.py:1300
msgid "Starting package installation process"
msgstr "Начинается процесс установки пакетов"

#: pyanaconda/packaging/yumpayload.py:1556
msgid "Upgrading"
msgstr "Обновление"

#: pyanaconda/packaging/yumpayload.py:1558
msgid "Installing"
msgstr "Установка"

#: pyanaconda/storage/__init__.py:974
msgid "This partition is holding the data for the hard drive install."
msgstr "Этот раздел содержит данные для установки с жесткого диска."

#: pyanaconda/storage/__init__.py:979
msgid "You cannot delete a partition of a LDL formatted DASD."
msgstr "Невозможно удалить DASD, отформатированный как LDL"

#: pyanaconda/storage/__init__.py:985
#, python-format
msgid "This device is part of the RAID device %s."
msgstr "Это устройство является частью устройства RAID %s."

#: pyanaconda/storage/__init__.py:988
msgid "This device is part of a RAID device."
msgstr "Это устройство является частью устройства RAID."

#: pyanaconda/storage/__init__.py:991
msgid "This device is part of an inconsistent LVM Volume Group."
msgstr "Это устройство является частью рассогласованной группы томов LVM."

#: pyanaconda/storage/__init__.py:996
#, python-format
msgid "This device is part of the LVM volume group '%s'."
msgstr "Это устройство является частью группы томов LVM «%s»."

#: pyanaconda/storage/__init__.py:999
msgid "This device is part of a LVM volume group."
msgstr "Это устройство является частью группы томов LVM."

#: pyanaconda/storage/__init__.py:1015
msgid ""
"This device is an extended partition which contains logical partitions that "
"cannot be deleted:\n"
"\n"
msgstr ""
"Этот раздел является расширенным и содержит логические разделы, которые "
"невозможно удалить:\n"
"\n"

#: pyanaconda/storage/__init__.py:1262 pyanaconda/ui/gui/spokes/custom.py:1006
msgid "You must create a new filesystem on the root device."
msgstr "Вы должны создать новую файловую систему на корневом устройстве."

#: pyanaconda/storage/__init__.py:1450
#, python-format
msgid ""
"You have not defined a root partition (/), which is required for "
"installation of %s to continue."
msgstr ""
"Вы не указали корневой раздел (/), который необходим для продолжения "
"установки %s."

#: pyanaconda/storage/__init__.py:1455
#, python-format
msgid ""
"Your root partition is less than 250 megabytes which is usually too small to "
"install %s."
msgstr ""
"Размер корневого раздела меньше 250 МБ. Как правило, этого недостаточно для "
"установки %s."

#: pyanaconda/storage/__init__.py:1469
msgid ""
"This platform requires /boot on a dedicated partition or logical volume.  If "
"you do not want a /boot volume, you must place / on a dedicated non-LVM "
"partition."
msgstr ""
"Для данной платформы требуется монтировать /boot на выделенном разделе или "
"логическом томе. Если вы не хотите выносить /boot на отдельный том, "
"необходимо разместить / на выделенном не-LVM разделе."

#: pyanaconda/storage/__init__.py:1478
#, python-format
msgid ""
"Your %(mount)s partition is less than %(size)s megabytes which is lower than "
"recommended for a normal %(productName)s install."
msgstr ""
"Размер раздела %(mount)s меньше %(size)s МБ, что меньше рекомендуемого "
"размера для нормальной установки %(productName)s. "

#: pyanaconda/storage/__init__.py:1488
#, python-format
msgid ""
"Your %(mount)s partition is too small for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"Раздел %(mount)s слишком мал для %(format)s форматирования (допустимые "
"размеры: от %(minSize)d МБ до %(maxSize)d МБ)"

#: pyanaconda/storage/__init__.py:1493
#, python-format
msgid ""
"Your %(mount)s partition is too large for %(format)s formatting (allowable "
"size is %(minSize)d MB to %(maxSize)d MB)"
msgstr ""
"Раздел %(mount)s слишком велик для %(format)s форматирования (допустимые "
"размеры: от %(minSize)d МБ до %(maxSize)d МБ)"

#: pyanaconda/storage/__init__.py:1520
msgid ""
"Installing on a USB device.  This may or may not produce a working system."
msgstr ""
"Установка на USB-устройство. Существует вероятность получения нерабочей "
"системы."

#: pyanaconda/storage/__init__.py:1523
msgid ""
"Installing on a FireWire device.  This may or may not produce a working "
"system."
msgstr ""
"Установка на FireWire-устройство. Существует вероятность получения нерабочей "
"системы."

#: pyanaconda/storage/__init__.py:1529
msgid "you have not created a bootloader stage1 target device"
msgstr "вы не установили устройство 1го этапа загрузчика"

#: pyanaconda/storage/__init__.py:1538
msgid "You have not created a bootable partition."
msgstr "Вы не создали загружаемый раздел."

#: pyanaconda/storage/__init__.py:1559
#, python-format
msgid ""
"Your BIOS-based system needs a special partition to boot with %s's new disk "
"label format (GPT). To continue, please create a 1MB 'BIOS Boot' type "
"partition."
msgstr ""
"BIOS в вашей системе требует специальный раздел для загрузки %s с новым "
"форматом меток диска (GPT). Для продолжения создайте раздел типа 'BIOS Boot' "
"размером 1 МБ."

#: pyanaconda/storage/__init__.py:1572
#, python-format
msgid ""
"You have not specified a swap partition.  %(requiredMem)s MB of memory is "
"required to continue installation without a swap partition, but you only "
"have %(installedMem)s MB."
msgstr ""
"Вы не определили swap-раздел.  Для продолжения установки без swap-раздела "
"необходимо %(requiredMem)s МБ памяти, а доступно лишь %(installedMem)s МБ."

#: pyanaconda/storage/__init__.py:1578
msgid ""
"You have not specified a swap partition.  Although not strictly required in "
"all cases, it will significantly improve performance for most installations."
msgstr ""
"Вы не создали раздел подкачки. Хотя это и не всегда является необходимым, в "
"большинстве случаев раздел подкачки может значительно улучшить "
"производительность системы."

#: pyanaconda/storage/__init__.py:1584
msgid ""
"At least one of your swap devices does not have a UUID, which is common in "
"swap space created using older versions of mkswap. These devices will be "
"referred to by device path in /etc/fstab, which is not ideal since device "
"paths can change under a variety of circumstances. "
msgstr ""
"По крайней мере одно из устройств подкачки не имеет UUID, что обычно бывает, "
"если область подкачки создается с использованием старых версий mkswap. К "
"этим устройствам обращение будет по пути к устройству из /etc/fstab, а это "
"не самый лучший способ, так как пути устройств могут меняться при различных "
"обстоятельствах. "

#: pyanaconda/storage/__init__.py:1594
#, python-format
msgid ""
"This mount point is invalid.  The %s directory must be on the / file system."
msgstr ""
"Неверная точка монтирования. Каталог %s должен располагаться в файловой "
"системе /."

#: pyanaconda/storage/__init__.py:1598
#, python-format
msgid "The mount point %s must be on a linux file system."
msgstr "Точка монтирования %s должна располагаться в файловой системе Linux. "

#: pyanaconda/storage/__init__.py:3199
#, python-format
msgid "Linux on %s"
msgstr "Linux на %s"

#: pyanaconda/storage/__init__.py:3204
msgid "Unknown Linux"
msgstr "Неизвестный Linux"

#: pyanaconda/storage/__init__.py:3206
#, python-format
msgid "%(product)s Linux %(version)s for %(arch)s"
msgstr "%(product)s Linux %(version)s для %(arch)s"

#: pyanaconda/storage/dasd.py:159
msgid "Formatting DASD Device"
msgid_plural "Formatting DASD Devices"
msgstr[0] "Форматирование DASD-устройства"
msgstr[1] "Форматирование DASD устройств"
msgstr[2] "Форматирование DASD устройств"

#: pyanaconda/storage/dasd.py:160
#, python-format
msgid "Preparing %d DASD device for use with Linux..."
msgid_plural "Preparing %d DASD devices for use with Linux..."
msgstr[0] "Подготовка %d DASD-устройства для использования с Linux..."
msgstr[1] "Подготовка %d DASD-устройств для использования с Linux..."
msgstr[2] "Подготовка %d DASD-устройств для использования с Linux..."

#: pyanaconda/storage/deviceaction.py:419
#, python-format
msgid "Creating %(type)s on %(device)s"
msgstr "Создание %(type)s на %(device)s"

#: pyanaconda/storage/deviceaction.py:559
#, python-format
msgid "Resizing filesystem on %(device)s"
msgstr "Изменение размера файловой системы на %(device)s"

#: pyanaconda/storage/deviceaction.py:608
#, python-format
msgid "Migrating filesystem on %(device)s"
msgstr "Перенос файловой системы на %(device)s"

#: pyanaconda/storage/devicelibs/lvm.py:310
#, python-format
msgid "vginfo failed for %s"
msgstr "сбой вызова vginfo для %s"

#: pyanaconda/storage/devicelibs/lvm.py:339
#, python-format
msgid "lvs failed for %s"
msgstr "сбой вызова lvs для %s"

#: pyanaconda/storage/devices.py:2672
#, python-format
msgid "A RAID%(raidLevel)d set requires at least %(minMembers)d member"
msgid_plural "A RAID%(raidLevel)d set requires at least %(minMembers)d members"
msgstr[0] "RAID%(raidLevel)d требуется как минимум %(minMembers)d член"
msgstr[1] "RAID%(raidLevel)d требуется как минимум %(minMembers)d членов"
msgstr[2] "RAID%(raidLevel)d требуется как минимум %(minMembers)d членов"

#: pyanaconda/storage/devicetree.py:96
msgid "Back"
msgstr "Назад"

#: pyanaconda/storage/devicetree.py:105
msgid "Confirm"
msgstr "Подтвердить"

#: pyanaconda/storage/devicetree.py:106
#, python-format
msgid ""
"Are you sure you want to skip entering a passphrase for device %s?\n"
"\n"
"If you skip this step the device's contents will not be available during "
"installation."
msgstr ""
"Вы действительно хотите пропустить ввод пароля для устройства %s?\n"
"\n"
"Если вы пропустите этот шаг, содержимое устройства будет недоступно в "
"процессе установки."

#: pyanaconda/storage/fcoe.py:110
msgid "FCoE not available"
msgstr "FCoE недоступен"

#: pyanaconda/storage/formats/fs.py:104
msgid "filesystem configuration missing a type"
msgstr "в описании файловой системы отсутствует поле тип"

#: pyanaconda/storage/formats/fs.py:483
#, python-format
msgid "Unknown return code: %d."
msgstr "Неизвестный код возврата: %d."

#: pyanaconda/storage/formats/fs.py:504
#, python-format
msgid "%(type)s filesystem check failure on %(device)s: "
msgstr "Ошибка проверки файловой системы %(type)s на %(device)s: "

#: pyanaconda/storage/formats/fs.py:511
msgid ""
"Errors like this usually mean there is a problem with the filesystem that "
"will require user interaction to repair.  Before restarting installation, "
"reboot to rescue mode or another system that allows you to repair the "
"filesystem interactively.  Restart installation after you have corrected the "
"problems on the filesystem."
msgstr ""

#: pyanaconda/storage/formats/fs.py:519
msgid "Unrecoverable Error"
msgstr ""

#: pyanaconda/storage/formats/fs.py:883
msgid "File system errors left uncorrected."
msgstr "Ошибки файловой системы остались неисправленными."

#: pyanaconda/storage/formats/fs.py:884
msgid "Operational error."
msgstr "Операционная ошибка."

#: pyanaconda/storage/formats/fs.py:885
msgid "Usage or syntax error."
msgstr "Ошибка использования или синтаксиса."

#: pyanaconda/storage/formats/fs.py:886
msgid "e2fsck cancelled by user request."
msgstr "Отмена e2fsck по требованию пользователя."

#: pyanaconda/storage/formats/fs.py:887
msgid "Shared library error."
msgstr "Ошибка разделяемой библиотеки."

#: pyanaconda/storage/formats/fs.py:1062
msgid ""
"Recoverable errors have been detected or dosfsck has discovered an internal "
"inconsistency."
msgstr ""
"Обнаружены некритические ошибки или dosfsck обнаружила внутреннюю "
"противоречивость."

#: pyanaconda/storage/formats/fs.py:1064
msgid "Usage error."
msgstr "Ошибка использования."

#: pyanaconda/storage/formats/luks.py:48
msgid "Encrypted"
msgstr "Зашифровано"

#: pyanaconda/storage/iscsi.py:123
msgid "Unable to change iSCSI initiator name once set"
msgstr "Невозможно изменить установленное имя iSCSI-инициатора."

#: pyanaconda/storage/iscsi.py:125
msgid "Must provide an iSCSI initiator name"
msgstr "Необходимо указать имя iSCSI-инициатора."

#: pyanaconda/storage/iscsi.py:293
msgid "iSCSI not available"
msgstr "iSCSI недоступен"

#: pyanaconda/storage/iscsi.py:295
msgid "No initiator name set"
msgstr "Не задано имя iSCSI-инициатора"

#: pyanaconda/storage/iscsi.py:334
msgid "Logging in to iSCSI node"
msgstr "Вход на iSCSI-узел"

#: pyanaconda/storage/iscsi.py:335
#, python-format
msgid "Logging in to iSCSI node %s"
msgstr "Вход на iSCSI-узел %s"

#: pyanaconda/storage/iscsi.py:369
msgid "No iSCSI nodes discovered"
msgstr "iSCSI-узлы не обнаружены"

#: pyanaconda/storage/iscsi.py:391
msgid "No new iSCSI nodes discovered"
msgstr "Не обнаружено новых iSCSI-узлов"

#: pyanaconda/storage/iscsi.py:394
msgid "Could not log in to any of the discovered nodes"
msgstr "Не удалось войти ни в один из обнаруженных узлов"

#: pyanaconda/storage/partitioning.py:291
msgid "No usable disks selected"
msgstr ""

#: pyanaconda/storage/partitioning.py:299
msgid "Not enough free space on disks for automatic partitioning"
msgstr ""

#: pyanaconda/storage/partitioning.py:629
msgid "unable to allocate aligned partition"
msgstr ""

#: pyanaconda/storage/partitioning.py:637
msgid "requested size exceeds maximum allowed"
msgstr ""

#: pyanaconda/storage/partitioning.py:728
msgid "can't allocate partitions without platform data"
msgstr ""

#: pyanaconda/storage/partitioning.py:739
#, python-format
msgid "disk %s inaccessible"
msgstr ""

#: pyanaconda/storage/partitioning.py:793
#, python-format
msgid ""
"partition is too small for %(format)s formatting (allowable size is "
"%(minSize)d MB to %(maxSize)d MB)"
msgstr ""

#: pyanaconda/storage/partitioning.py:798
#, python-format
msgid ""
"partition is too large for %(format)s formatting (allowable size is "
"%(minSize)d MB to %(maxSize)d MB)"
msgstr ""

#: pyanaconda/storage/partitioning.py:1039
msgid "not enough free space on disks"
msgstr ""

#: pyanaconda/storage/partitioning.py:1060
msgid "not enough free space after creating extended partition"
msgstr ""

#: pyanaconda/storage/partitioning.py:1232
msgid "cannot reclaim more than request has grown"
msgstr ""

#: pyanaconda/storage/partitioning.py:1412
msgid "DiskChunk requests must be of type PartitionRequest"
msgstr ""

#: pyanaconda/storage/partitioning.py:1425
msgid "partitions allocated outside disklabel limits"
msgstr ""

#: pyanaconda/storage/partitioning.py:1505
msgid "VGChunk requests must be of type LVRequest"
msgstr ""

#: pyanaconda/storage/partitioning.py:1934
msgid "not enough space for LVM requests"
msgstr ""

#: pyanaconda/storage/zfcp.py:51
msgid "You have not specified a device number or the number is invalid"
msgstr "Номер устройства не задан или задан неправильно"

#: pyanaconda/storage/zfcp.py:53
msgid "You have not specified a worldwide port name or the name is invalid."
msgstr "Общее имя порта устройства не задано или задано неправильно."

#: pyanaconda/storage/zfcp.py:55
msgid "You have not specified a FCP LUN or the number is invalid."
msgstr "FCP LUN не задан, или номер указан неправильно."

#: pyanaconda/storage/zfcp.py:133
#, python-format
msgid "zFCP device %s not found, not even in device ignore list."
msgstr ""
"zFCP-устройство %s не найдено. Его нет даже в списке игнорируемых устройств."

#: pyanaconda/storage/zfcp.py:143
#, python-format
msgid "Could not set zFCP device %(devnum)s online (%(e)s)."
msgstr ""
"Не удалось перевести zFCP-устройство %(devnum)s в рабочий режим (%(e)s)."

#: pyanaconda/storage/zfcp.py:154
#, python-format
msgid "Could not add WWPN %(wwpn)s to zFCP device %(devnum)s (%(e)s)."
msgstr ""
"Не удалось добавить WWPN %(wwpn)s к zFCP-устройству %(devnum)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:161
#, python-format
msgid "WWPN %(wwpn)s not found at zFCP device %(devnum)s."
msgstr "WWPN %(wwpn)s не найден на zFCP-устройстве %(devnum)s."

#: pyanaconda/storage/zfcp.py:176
#, python-format
msgid ""
"Could not add LUN %(fcplun)s to WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"Не удалось добавить LUN %(fcplun)s к WWPN %(wwpn)s на zFCP-устройстве "
"%(devnum)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:182
#, python-format
msgid ""
"LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s already configured."
msgstr ""
"LUN %(fcplun)s у WWPN %(wwpn)s на zFCP-устройстве %(devnum)s уже настроен."

#: pyanaconda/storage/zfcp.py:194
#, python-format
msgid ""
"Could not read failed attribute of LUN %(fcplun)s at WWPN %(wwpn)s on zFCP "
"device %(devnum)s (%(e)s)."
msgstr ""
"Не удалось прочитать атрибут «failed» c LUN %(fcplun)s у WWPN %(wwpn)s на "
"zFCP-устройстве %(devnum)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:203
#, python-format
msgid ""
"Failed LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s removed "
"again."
msgstr ""
"Находящийся в состоянии сбоя LUN %(fcplun)s у WWPN %(wwpn)s на zFCP-"
"устройстве %(devnum)s снова отключён."

#: pyanaconda/storage/zfcp.py:260
#, python-format
msgid ""
"Could not correctly delete SCSI device of zFCP %(devnum)s %(wwpn)s "
"%(fcplun)s (%(e)s)."
msgstr ""
"Не удалось корректно удалить SCSI-устройство, относящееся к zFCP %(devnum)s "
"%(wwpn)s %(fcplun)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:269
#, python-format
msgid ""
"Could not remove LUN %(fcplun)s at WWPN %(wwpn)s on zFCP device %(devnum)s "
"(%(e)s)."
msgstr ""
"Не удалось удалить LUN %(fcplun)s с WWPN %(wwpn)s на zFCP-устройстве "
"%(devnum)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:287
#, python-format
msgid "Could not remove WWPN %(wwpn)s on zFCP device %(devnum)s (%(e)s)."
msgstr ""
"Не удалось удалить WWPN %(wwpn)s на zFCP-устройстве %(devnum)s (%(e)s)."

#: pyanaconda/storage/zfcp.py:313
#, python-format
msgid "Could not set zFCP device %(devnum)s offline (%(e)s)."
msgstr ""
"Не удалось перевести zFCP-устройство %(devnum)s в автономный режим (%(e)s)."

#: pyanaconda/ui/lib/space.py:33
#, python-format
msgid ""
"Not enough space in filesystems for the current software selection. An "
"additional %s is needed."
msgstr ""

#: pyanaconda/ui/tui/hubs/progress.py:37
msgid "Installation Hub"
msgstr "Узел установки"

#: pyanaconda/ui/tui/hubs/progress.py:117
msgid "\tInstallation complete.  Press return to quit"
msgstr "\tУстановка завершена.  Нажмите Enter для выхода"

#: pyanaconda/ui/tui/hubs/summary.py:32
msgid "Install hub"
msgstr "Узел установки"

#: pyanaconda/ui/tui/hubs/summary.py:38
msgid "Starting automated install"
msgstr "Запуск автоматической установки..."

#: pyanaconda/ui/tui/hubs/__init__.py:43
msgid "Default HUB title"
msgstr "Название узла по умолчанию"

#: pyanaconda/ui/tui/hubs/__init__.py:104
#: pyanaconda/ui/tui/simpleline/base.py:301
msgid "c"
msgstr "c"

#: pyanaconda/ui/tui/hubs/__init__.py:107
msgid "Please complete all spokes before continuing"
msgstr "Заполните все поля, прежде чем продолжить"

#: pyanaconda/ui/tui/simpleline/base.py:306
msgid "q"
msgstr "q"

#: pyanaconda/ui/tui/simpleline/base.py:308
msgid "Do you really want to quit?"
msgstr "Действительно хотите выйти?"

#: pyanaconda/ui/tui/simpleline/base.py:407
msgid "  Please make your choice from above ['q' to quit | 'c' to continue]: "
msgstr "Выберите ['q' для выхода | 'c' для продолжения]: "

#: pyanaconda/ui/tui/spokes/askvnc.py:32
msgid "VNC"
msgstr "VNC"

#: pyanaconda/ui/tui/spokes/askvnc.py:43
msgid ""
"X was unable to start on your machine.  Would you like to start VNC to "
"connect to this computer from another computer and perform a graphical "
"install or continue with a text mode install?"
msgstr ""
"Невозможно запустить графическую подсистему X на вашей машине. Запустить VNC "
"для подключения к данному компьютеру с другой машины и выполнения установки "
"в графическом режиме или продолжить установку в текстовом режиме?"

#: pyanaconda/ui/tui/spokes/askvnc.py:95
msgid "VNC Password"
msgstr "Пароль VNC"

#: pyanaconda/ui/tui/spokes/askvnc.py:104
msgid ""
"Please provide VNC password. You will have to type it twice. \n"
"Leave blank for no password"
msgstr ""
"Введите пароль VNC. Его потребуется напечатать дважды.\n"
"Пустой ввод означает работу без пароля."

#: pyanaconda/ui/tui/spokes/askvnc.py:123
#: pyanaconda/ui/tui/spokes/password.py:64
msgid "Password: "
msgstr "Пароль:"

#: pyanaconda/ui/tui/spokes/askvnc.py:124
#: pyanaconda/ui/tui/spokes/password.py:65
msgid "Password (confirm): "
msgstr "Пароль (подтверждение):"

#: pyanaconda/ui/tui/spokes/askvnc.py:127
msgid "Passwords do not match!"
msgstr "Пароли не совпадают!"

#: pyanaconda/ui/tui/spokes/askvnc.py:130
msgid "The password must be at least six characters long."
msgstr "Пароль должен содержать не менее 6 символов."

#: pyanaconda/ui/tui/spokes/password.py:35
msgid "Set root password"
msgstr "Установите пароль root"

#: pyanaconda/ui/tui/spokes/password.py:49
msgid "Password is set."
msgstr "Пароль установлен."

#: pyanaconda/ui/tui/spokes/password.py:51
msgid "Root account is disabled."
msgstr "Пользователь root заблокирован."

#: pyanaconda/ui/tui/spokes/password.py:53
msgid "Password is not set."
msgstr "Пароль не установлен."

#: pyanaconda/ui/tui/spokes/password.py:58
msgid "Please select new root password. You will have to type it twice."
msgstr "Выберите новый пароль root. Его потребуется ввести дважды."

#: pyanaconda/ui/tui/spokes/password.py:76
#, python-format
msgid "You have provided a weak password: %s. "
msgstr "Указанный пароль слишком прост: %s. "

#: pyanaconda/ui/tui/spokes/password.py:77
msgid ""
"\n"
"Would you like to use it anyway?"
msgstr ""
"\n"
"Хотите всё равно его использовать?"

#: pyanaconda/ui/tui/spokes/storage.py:47
msgid "Use All Space"
msgstr "Использовать все пространство"

#: pyanaconda/ui/tui/spokes/storage.py:48
msgid "Replace Existing Linux system(s)"
msgstr "Заменить существующую систему(мы) Linux"

#: pyanaconda/ui/tui/spokes/storage.py:49
msgid "Use Free Space"
msgstr "Использовать свободное пространство"

#: pyanaconda/ui/tui/spokes/storage.py:92
msgid "Install Destination"
msgstr "Место установки"

#: pyanaconda/ui/tui/spokes/storage.py:120
#: pyanaconda/ui/gui/spokes/storage.py:439
msgid "No disks selected"
msgstr "Ни одного диска не выбрано"

#: pyanaconda/ui/tui/spokes/storage.py:127
#: pyanaconda/ui/gui/spokes/storage.py:446
msgid "Error checking storage configuration"
msgstr "Ошибка при  проверке настроек накопителей"

#: pyanaconda/ui/tui/spokes/storage.py:130
#: pyanaconda/ui/gui/spokes/storage.py:448
msgid "Automatic partitioning selected"
msgstr "Выбрано автоматическое разбиение диска"

#: pyanaconda/ui/tui/spokes/storage.py:132
#: pyanaconda/ui/gui/spokes/storage.py:450
msgid "Custom partitioning selected"
msgstr "Выбрано собственное разбиение диска"

#: pyanaconda/ui/tui/spokes/storage.py:168
#: pyanaconda/ui/gui/spokes/storage.py:582
msgid ""
"No disks detected.  Please shut down the computer, connect at least one "
"disk, and restart to complete installation."
msgstr ""
"Ни один диск не обнаружен. Выключите компьютер и подключите хотя бы один "
"диск. После этого можно вновь начать установку."

#: pyanaconda/ui/tui/spokes/storage.py:170
#: pyanaconda/ui/gui/spokes/storage.py:584
msgid "No disks selected; please select at least one disk to install to."
msgstr "Ни один диск не выбран; необходим хотя бы один диск для установки."

#: pyanaconda/ui/tui/spokes/storage.py:185
#: pyanaconda/ui/gui/spokes/source.py:671
#: pyanaconda/ui/gui/spokes/storage.py:514
msgid "Probing storage..."
msgstr "Проверка устройств хранения..."

#: pyanaconda/ui/tui/spokes/storage.py:263
msgid "Generating updated storage configuration"
msgstr "Создание обновленной конфигурации устройств хранения"

#: pyanaconda/ui/tui/spokes/storage.py:268
#, python-format
msgid "storage configuration failed: %s"
msgstr "Ошибка настройки хранилища: %s"

#: pyanaconda/ui/tui/spokes/storage.py:277
#: pyanaconda/ui/gui/spokes/storage.py:307
msgid "Checking storage configuration..."
msgstr "Проверка настроек накопителей..."

#: pyanaconda/ui/tui/spokes/storage.py:311
msgid "Autopartitioning Options"
msgstr "Настройки автоматического создания разделов"

#: pyanaconda/ui/tui/spokes/storage.py:342
msgid ""
"Installation requires partitioning of your hard drive.  Select what space to "
"use for the install target."
msgstr ""
"Для установки необходимо разбиение жесткого диска на разделы.  Выберите, "
"сколько места потребуется для установки целевой системы."

#: pyanaconda/ui/tui/spokes/time.py:30
msgid "Timezone settings"
msgstr "Настройка временных зон"

#: pyanaconda/ui/tui/spokes/time.py:53 pyanaconda/ui/tui/spokes/time.py:55
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:379
#: pyanaconda/ui/gui/spokes/datetime_spoke.py:384
#, python-format
msgid "%s timezone"
msgstr "Часовой пояс %s"

#: pyanaconda/ui/tui/spokes/time.py:57
msgid "Timezone is not set."
msgstr "Временная зона не задана"

#: pyanaconda/ui/tui/spokes/time.py:65
#, python-format
msgid "Available timezones in region %s"
msgstr "Доступные временные зоны в регионе %s"

#: pyanaconda/ui/tui/spokes/time.py:68
msgid "Available regions"
msgstr "Доступные регионы"

#: pyanaconda/ui/tui/spokes/time.py:131
msgid ""
"Please select the timezone.\n"
"Use numbers or type names directly [b to region list, q to quit]: "
msgstr ""
"Выберите временную зону.\n"
"Используйте цифры или непосредственно введите название [b для списка "
"регионов, q для выхода]: "

#: pyanaconda/ui/tui/spokes/__init__.py:44
msgid "Default spoke title"
msgstr "Стандартное название для запоминания"

#: pyanaconda/ui/tui/spokes/__init__.py:54
msgid "testing status..."
msgstr "проверка состояния..."

#: pyanaconda/ui/tui/__init__.py:58
msgid "Press enter to exit."
msgstr "Нажмите Enter для выхода."

#: pyanaconda/ui/tui/__init__.py:67
msgid "Question"
msgstr "Вопрос"

#: pyanaconda/ui/tui/__init__.py:90
msgid "Please respond 'yes' or 'no': "
msgstr "Отвечайте 'да' или 'нет': "

#: pyanaconda/ui/tui/__init__.py:93
msgid "yes"
msgstr "да"

#: pyanaconda/ui/tui/__init__.py:98
msgid "no"
msgstr "нет"

#: pyanaconda/ui/gui/__init__.py:144
msgid "_Exit Installer"
msgstr "В_ыход из программы установки"

#: pyanaconda/ui/gui/__init__.py:153 pyanaconda/ui/gui/spokes/software.py:333
#: pyanaconda/ui/gui/spokes/storage.py:770 pyanaconda/ui/gui/main.glade:36
#: pyanaconda/ui/gui/hubs/summary.glade:77 widgets/src/StandaloneWindow.c:52
msgid "_Quit"
msgstr "В_ыход "

#: pyanaconda/ui/gui/__init__.py:169
msgid "_No"
msgstr "_Нет"

#: pyanaconda/ui/gui/__init__.py:169
msgid "_Yes"
msgstr "_Да"

#: pyanaconda/ui/gui/categories/__init__.py:44
msgid "DEFAULT TITLE"
msgstr "НАЗВАНИЕ ПО УМОЛЧАНИЮ"

#: pyanaconda/ui/gui/categories/localization.py:31
msgid "LOCALIZATION"
msgstr "РЕГИОНАЛЬНЫЕ НАСТРОЙКИ"

#: pyanaconda/ui/gui/categories/software.py:31
msgid "SOFTWARE"
msgstr "ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ"

#: pyanaconda/ui/gui/categories/storage.py:32
msgid "STORAGE"
msgstr "НОСИТЕЛИ"

#: pyanaconda/ui/gui/categories/user_settings.py:32
msgid "USER SETTINGS"
msgstr ""

#: pyanaconda/ui/gui/hubs/__init__.py:226
msgid ""
"When all items marked with this icon are complete, installation will "
"automatically continue."
msgstr ""
"Когда все элементы, отмеченные этим значком будут заполнены, установка "
"автоматически продолжится."

#: pyanaconda/ui/gui/hubs/__init__.py:228
msgid ""
"Please complete items marked with this icon before continuing to the next "
"step."
msgstr ""
"Заполните элементы, отмеченные этим значком, прежде чем перейти к следующему "
"шагу."

#: pyanaconda/ui/gui/hubs/progress.py:254
msgid "Complete!"
msgstr "Готово!"

#: pyanaconda/ui/gui/spokes/custom.py:99
#, python-format
msgid "New %s %s Installation"
msgstr "Новая установка %s %s"

#: pyanaconda/ui/gui/spokes/custom.py:100
msgid "Create a new volume group ..."
msgstr "Создать группу томов..."

#: pyanaconda/ui/gui/spokes/custom.py:101
msgid ""
"Storage configuration reset due to unrecoverable error. Click for details."
msgstr "Настройки хранилища сброшены из-за неустранимой ошибки. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:103
msgid "Device reconfiguration failed. Click for details."
msgstr "Перенастройка устройства не удалась. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:106
msgid "Please enter a valid mountpoint."
msgstr "Укажите правильную точку монтирования."

#: pyanaconda/ui/gui/spokes/custom.py:107
msgid "That mount point is invalid. Try something else?"
msgstr "Это неверная точка монтирования. Попробовать ещё?"

#: pyanaconda/ui/gui/spokes/custom.py:108
msgid "That mount point is already in use. Try something else?"
msgstr "Эта точка монтирования уже используется. Попробовать ещё?"

#: pyanaconda/ui/gui/spokes/custom.py:120
msgid "LVM"
msgstr "LVM"

#: pyanaconda/ui/gui/spokes/custom.py:121
msgid "RAID"
msgstr "RAID"

#: pyanaconda/ui/gui/spokes/custom.py:122
msgid "Standard Partition"
msgstr "Обычный раздел"

#: pyanaconda/ui/gui/spokes/custom.py:123
msgid "BTRFS"
msgstr "BTRFS"

#: pyanaconda/ui/gui/spokes/custom.py:124
#: pyanaconda/ui/gui/spokes/custom.glade:2088
#: pyanaconda/ui/gui/spokes/custom.glade:2289
#: pyanaconda/ui/gui/spokes/lib/resize.glade:140
msgid "Disk"
msgstr "Диск"

#: pyanaconda/ui/gui/spokes/custom.py:439
#: pyanaconda/ui/gui/spokes/custom.glade:389
msgid "MANUAL PARTITIONING"
msgstr "РАЗМЕТКА ВРУЧНУЮ"

#: pyanaconda/ui/gui/spokes/custom.py:636
#, python-format
msgid "%d storage device selected"
msgid_plural "%d storage devices selected"
msgstr[0] "%d накопитель выбран"
msgstr[1] "%d накопителя выбрано"
msgstr[2] "%d накопителей выбрано"

#: pyanaconda/ui/gui/spokes/custom.py:789
#: pyanaconda/ui/gui/spokes/network.py:585
#: pyanaconda/ui/gui/spokes/network.py:1001
msgid "Unknown"
msgstr "Неизвестный"

#: pyanaconda/ui/gui/spokes/custom.py:818
msgid ""
"The 'swap' area on your computer is used by the operating\n"
"system when running low on memory."
msgstr "Раздел «swap» используется операционной системой при нехватке памяти."

#: pyanaconda/ui/gui/spokes/custom.py:821
msgid ""
"The 'boot' area on your computer is where files needed\n"
"to start the operating system are stored."
msgstr ""
"Раздел «boot» используется для хранения файлов, необходимых\n"
"для запуска операционой системы."

#: pyanaconda/ui/gui/spokes/custom.py:824
msgid ""
"The 'root' area on your computer is where core system\n"
"files and applications are stored."
msgstr "В разделе «root» хранятся файлы приложений и системы."

#: pyanaconda/ui/gui/spokes/custom.py:827
msgid ""
"The 'home' area on your computer is where all your personal\n"
"data is stored."
msgstr "В разделе «home» хранятся данные пользователей."

#: pyanaconda/ui/gui/spokes/custom.py:830
msgid ""
"The BIOS boot partition is required to enable booting\n"
"from GPT-partitioned disks on BIOS hardware."
msgstr ""
"Раздел «BIOS boot» требуется для загрузки системы с дисков\n"
"с разметкой GPT на оборудовании с BIOS."

#: pyanaconda/ui/gui/spokes/custom.py:833
msgid ""
"The PReP boot partition is required as part of the\n"
"bootloader configuration on some PPC platforms."
msgstr ""
"На некоторых платформах PPC для размещения\n"
"конфигурации загрузчика требуется раздел PReP."

#: pyanaconda/ui/gui/spokes/custom.py:995
#, python-format
msgid "/boot/efi must be on a device of type %s"
msgstr "/boot/efi должен быть на устройстве типа %s"

#: pyanaconda/ui/gui/spokes/custom.py:999
#, python-format
msgid "%s must be on a device of type %s"
msgstr "%s должен быть на устройстве типа %s"

#: pyanaconda/ui/gui/spokes/custom.py:1002
#: pyanaconda/ui/gui/spokes/custom.py:1004
#, python-format
msgid "%s cannot be encrypted"
msgstr "%s не может быть зашифрован"

#: pyanaconda/ui/gui/spokes/custom.py:1008
#, python-format
msgid "Devices of type %s require a valid RAID level selection."
msgstr ""
"Использование устройств типа %s требует определения надлежащего уровня RAID."

#: pyanaconda/ui/gui/spokes/custom.py:1014
msgid ""
"The RAID level you have selected requires more disks than you currently have "
"selected."
msgstr ""
"Для выбранного уровня RAID требуется больше дисков, чем доступно на данный "
"момент."

#: pyanaconda/ui/gui/spokes/custom.py:1173
msgid "Device resize request failed. Click for details."
msgstr "Запрос на изменение размера устройства не выполнен. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:1227
#, python-format
msgid "Specified name %s already in use."
msgstr "Имя %s уже используется."

#: pyanaconda/ui/gui/spokes/custom.py:1294
msgid "Device reformat request failed. Click for details."
msgstr "Запрос на переформатирование устройства не выполнен. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:1558
msgid "This file system does not support labels."
msgstr "Данная файловая система не поддерживает метки."

#: pyanaconda/ui/gui/spokes/custom.py:1576
msgid "This file system may not be resized."
msgstr "Для данной файловой системы не может быть изменен размер."

#: pyanaconda/ui/gui/spokes/custom.py:1848
#, python-format
msgid "Added new %s to existing container %s."
msgstr "%s добавлен к существующему контейнеру %s."

#: pyanaconda/ui/gui/spokes/custom.py:1856
msgid "Failed to add new device. Click for details."
msgstr "Не удалось добавить новое устройство. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:1862
msgid "Invalid partition size set. Use a valid integer."
msgstr ""
"Недопустимый размер раздела. Необходимо указать корректное целое число."

#: pyanaconda/ui/gui/spokes/custom.py:1882
msgid "Device removal request failed. Click for details."
msgstr "Запрос на удаление устройства не выполнен. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:2077
#, python-format
msgid "Volume Group name %s is already in use. Not saving changes."
msgstr "Группа томов %s уже используется. Изменения не будут сохранены."

#: pyanaconda/ui/gui/spokes/custom.py:2168
#, python-format
msgid ""
"This Software RAID array is missing %d of %d member partitions. You can "
"remove it or select a different device."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.py:2174
#, python-format
msgid ""
"This LVM Volume Group is missing %d of %d physical volumes. You can remove "
"it or select a different device."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.py:2247
msgid "No disks selected."
msgstr "Не выбран ни один диск."

#: pyanaconda/ui/gui/spokes/custom.py:2253
msgid "Not enough free space on selected disks."
msgstr "Недостаточно свободного места на выбранных дисках."

#: pyanaconda/ui/gui/spokes/custom.py:2259
msgid "Automatic partitioning failed. Click for details."
msgstr "Автоматическое разбиение не удалось. Подробнее…"

#: pyanaconda/ui/gui/spokes/custom.py:2499
msgid "Failed to unlock encrypted block device. Click for details"
msgstr ""
"Не удалось расшифровать блочное устройство. Нажмите для получения подробных "
"сведений"

#: pyanaconda/ui/gui/spokes/custom.py:2522
#, python-format
msgid ""
"You have chosen to manually set up the filesystems for your new "
"%(productName)s installation. Before you begin, you might want to take a "
"minute to learn the lay of the land. Quite a bit has changed.\n"
"\n"
"The most important change is that creation of new filesystems has been "
"streamlined. You no longer have to build complex devices like LVM logical "
"volumes in stages (physical volume, then volume group, then logical volume) "
"-- now you just create a logical volume and we'll handle the legwork of "
"setting up the physical volumes and volume group to contain it. We'll also "
"handle adjusting the volume group as you add, remove, and resize logical "
"volumes so you don't have to worry about the mundane details.\n"
"\n"
"\n"
"Screen Layout\n"
"\n"
"The left-hand side of the screen shows the OS installations we were able to "
"find on this computer. The new %(productName)s installation is at the top of "
"the list. You can click on the names of the installations to see what "
"filesystems they contain.\n"
"\n"
"Below the various installations and mountpoints on the left-hand side there "
"are buttons to add a new filesystem, remove the selected filesystem, or "
"configure the selected filesystem.\n"
"\n"
"The right-hand side of the screen is where you can customize the currently-"
"selected mountpoint.\n"
"\n"
"On the bottom-left you will see a summary of the disks you have chosen to "
"use for the installation. You can click on the blue text to see more "
"detailed information about your selected disks.\n"
"\n"
"\n"
"How to create a new filesystem on a new device\n"
"\n"
"1. Click on the + button.\n"
"2. Enter the mountpoint and size. (Hint: Hover the mouse pointer over either "
"of the text entry areas for help.)\n"
"3. Select the new mountpoint under \"New %(productName)s Installation\" on "
"the left-hand side of the screen and customize it to suit your needs.\n"
"\n"
"\n"
"How to reformat a device/filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem from the left-hand side of the screen.\n"
"2. Click on the \"Customize\" expander in the mountpoint customization area "
"on the right-hand side of the screen.\n"
"3. Activate the \"Reformat\" checkbutton, select a filesystem type and, if "
"applicable, enter a mountpoint above in the \"Mountpoint\" text entry area.\n"
"4. Click on \"Apply changes\"\n"
"\n"
"\n"
"How to set a mountpoint for a filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem from the left-hand side of the screen.\n"
"2. Enter a mountpoint in the \"Mountpoint\" text entry area in the "
"mountpoint customization area.\n"
"3. Click on \"Apply changes\"\n"
"\n"
"\n"
"How to remove a filesystem that already exists on your disk\n"
"\n"
"1. Select the filesystem you wish to remove on the left-hand side of the "
"screen.\n"
"2. Click the - button.\n"
"\n"
"Hint: Removing a device that already exists on your disk from the \"New "
"%(productName)s Installation\" does not remove it from the disk. It only "
"resets that device to its original state. To remove a device that already "
"exists on your disk, you must select it from under any of the other detected "
"installations (or \"Unknown\") and hit the - button.\n"
"\n"
"\n"
"Tips and hints\n"
"\n"
"You can enter sizes for new filesystems that are greater than the total "
"available free space. The installer will come as close as possible to the "
"size you request.\n"
"\n"
"By default, new devices use any/all of your selected disks.\n"
"\n"
"You can change which disks a new device may be allocated from by clicking "
"the configure button (the one with a tools graphic) while that device is "
"selected.\n"
"\n"
"When adding a new mountpoint by clicking the + button, leave the size entry "
"blank to make the new device use all available free space.\n"
"\n"
"When you remove the last device from a container device like an LVM volume "
"group, we will automatically remove that container device to make room for "
"new devices.\n"
"\n"
"When the last partition is removed from a disk, that disk may be "
"reinitialized with a new partition table if we think there is a more "
"appropriate type for that disk.\n"
msgstr ""

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:56
msgid "Note: pool servers may not be available all the time"
msgstr "Замечание: буферные серверы могут быть не всегда доступны"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:296
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:31
msgid "DATE & TIME"
msgstr "ДАТА И ВРЕМЯ"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:381
msgid "Invalid timezone"
msgstr "Неверный часовой пояс"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:813
msgid "You need to set up networking first if you want to use NTP"
msgstr "Для использования NTP нужно сначала настроить сеть"

#: pyanaconda/ui/gui/spokes/datetime_spoke.py:817
msgid "You have no working NTP server configured"
msgstr "Не настроено ещё не одного рабочего сервера NTP"

#: pyanaconda/ui/gui/spokes/keyboard.py:40
#, python-format
msgid "%s to switch layouts."
msgstr "%s для переключения раскладок."

#: pyanaconda/ui/gui/spokes/keyboard.py:261
msgid "KEYBOARD"
msgstr "КЛАВИАТУРА"

#: pyanaconda/ui/gui/spokes/keyboard.py:318
msgid "Testing layouts configuration not available."
msgstr "Нельзя опробовать раскладки клавиатур."

#: pyanaconda/ui/gui/spokes/keyboard.py:372
msgid "Layout switching not configured."
msgstr "Переключение раскладки не настроено."

#: pyanaconda/ui/gui/spokes/network.py:92
msgid "Status unknown (missing)"
msgstr "Статус неивестен (не найден)"

#: pyanaconda/ui/gui/spokes/network.py:96
msgid "Status unknown"
msgstr "Статус неивестен"

#: pyanaconda/ui/gui/spokes/network.py:98
msgid "Unmanaged"
msgstr "Неуправляемый"

#: pyanaconda/ui/gui/spokes/network.py:101
msgid "Firmware missing"
msgstr "Прошивка не найдена"

#: pyanaconda/ui/gui/spokes/network.py:104
msgid "Cable unplugged"
msgstr "Кабель не подсоединён"

#: pyanaconda/ui/gui/spokes/network.py:106
msgid "Unavailable"
msgstr "Недоступно"

#: pyanaconda/ui/gui/spokes/network.py:108
msgid "Disconnected"
msgstr "Отключён"

#: pyanaconda/ui/gui/spokes/network.py:113
msgid "Connecting"
msgstr "Подключение"

#: pyanaconda/ui/gui/spokes/network.py:115
msgid "Authentication required"
msgstr "Требуется проверка подлинности"

#: pyanaconda/ui/gui/spokes/network.py:117
msgid "Connected"
msgstr "Подключен"

#: pyanaconda/ui/gui/spokes/network.py:119
msgid "Disconnecting"
msgstr "Отключение"

#: pyanaconda/ui/gui/spokes/network.py:121
msgid "Connection failed"
msgstr "Ошибка подключения"

#: pyanaconda/ui/gui/spokes/network.py:574
msgid "unplugged"
msgstr "не подсоединён"

#: pyanaconda/ui/gui/spokes/network.py:587
msgid "Ethernet"
msgstr "Ethernet"

#: pyanaconda/ui/gui/spokes/network.py:589
msgid "Wireless"
msgstr "Беспроводное"

#: pyanaconda/ui/gui/spokes/network.py:683
#: pyanaconda/ui/gui/spokes/network.glade:349
#: pyanaconda/ui/gui/spokes/network.glade:702
msgid "IPv4 Address"
msgstr "Адрес IPv4:"

#: pyanaconda/ui/gui/spokes/network.py:684
#: pyanaconda/ui/gui/spokes/network.glade:363
#: pyanaconda/ui/gui/spokes/network.glade:716
#: pyanaconda/ui/gui/spokes/network.glade:1335
msgid "IPv6 Address"
msgstr "IPv6 Адрес"

#: pyanaconda/ui/gui/spokes/network.py:686
#: pyanaconda/ui/gui/spokes/network.py:688
#: pyanaconda/ui/gui/spokes/network.glade:1321
msgid "IP Address"
msgstr "IP-адрес"

#: pyanaconda/ui/gui/spokes/network.py:753
#, python-format
msgid "%d Mb/s"
msgstr "%d Мб/с"

#: pyanaconda/ui/gui/spokes/network.py:930
msgid "WEP"
msgstr "WEP"

#: pyanaconda/ui/gui/spokes/network.py:933
msgid "WPA"
msgstr "WPA"

#: pyanaconda/ui/gui/spokes/network.py:936
msgid "WPA2"
msgstr "WPA2"

#: pyanaconda/ui/gui/spokes/network.py:940
msgid "Enterprise"
msgstr "Enterprise"

#: pyanaconda/ui/gui/spokes/network.py:945 widgets/src/SpokeSelector.c:54
msgid "None"
msgstr "Нет"

#: pyanaconda/ui/gui/spokes/network.py:967
#: pyanaconda/ui/gui/spokes/network.glade:37
#: pyanaconda/ui/gui/spokes/network.glade:109
msgid "NETWORK CONFIGURATION"
msgstr "НАСТРОЙКА СЕТИ"

#: pyanaconda/ui/gui/spokes/network.py:1005
msgid "Connecting..."
msgstr "Подключение..."

#: pyanaconda/ui/gui/spokes/network.py:1007
msgid "Disconnecting..."
msgstr "Отключение..."

#: pyanaconda/ui/gui/spokes/network.py:1014
#, python-format
msgid "Wireless connected to %s"
msgstr "Установлено беспроводное соединение с %s"

#: pyanaconda/ui/gui/spokes/network.py:1017
#, python-format
msgid "Wired (%s) connected"
msgstr "Проводное (%s) подключено"

#: pyanaconda/ui/gui/spokes/network.py:1027
#, python-format
msgid "Connected: %s"
msgstr "Подключено: %s"

#: pyanaconda/ui/gui/spokes/network.py:1029
msgid "Not connected"
msgstr "Не подключен"

#: pyanaconda/ui/gui/spokes/network.py:1032
#: pyanaconda/ui/gui/spokes/network.glade:2085
msgid "No network devices available"
msgstr "Сетевые устройства недоступны."

#: pyanaconda/ui/gui/spokes/network.py:1072
#: pyanaconda/ui/gui/spokes/network.py:1142
#, python-format
msgid "Hostname is not valid: %s"
msgstr ""

#: pyanaconda/ui/gui/spokes/password.py:48
#: pyanaconda/ui/gui/spokes/password.glade:9
msgid "ROOT PASSWORD"
msgstr "ПАРОЛЬ ROOT"

#: pyanaconda/ui/gui/spokes/password.py:77
msgid "Error setting root password"
msgstr "Ошибка при задании пароля root"

#: pyanaconda/ui/gui/spokes/password.py:79
msgid "Root password is set"
msgstr "Пароль root задан"

#: pyanaconda/ui/gui/spokes/password.py:81
msgid "Root account is disabled"
msgstr "Учетная запись пользователя root отключена"

#: pyanaconda/ui/gui/spokes/password.py:83
msgid "Root password is not set"
msgstr "Пароль root не установлен"

#: pyanaconda/ui/gui/spokes/password.py:103
msgid "You must provide and confirm a password."
msgstr "Необходимо ввести и подтвердить пароль."

#: pyanaconda/ui/gui/spokes/password.py:113
#, python-format
msgid "You have provided a weak password: %s.  Press Done again to use anyway."
msgstr ""
"Указанный пароль слишком прост: %s.  Нажмите «Готово» ещё раз, чтобы всё "
"равно его использовать."

#: pyanaconda/ui/gui/spokes/software.py:53
#: pyanaconda/ui/gui/spokes/software.glade:31
msgid "SOFTWARE SELECTION"
msgstr "ВЫБОР ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ"

#: pyanaconda/ui/gui/spokes/software.py:107
#: pyanaconda/ui/gui/spokes/source.py:612
msgid "Checking software dependencies..."
msgstr "Проверка зависимостей ПО..."

#: pyanaconda/ui/gui/spokes/software.py:113
msgid "Error checking software dependencies"
msgstr "Ошибка при проверке зависимостей"

#: pyanaconda/ui/gui/spokes/software.py:150
msgid "Error checking software selection"
msgstr "Ошибка при проверке выбора программного обеспечения"

#: pyanaconda/ui/gui/spokes/software.py:153
msgid "Installation source not set up"
msgstr "Источник установки не настроен"

#: pyanaconda/ui/gui/spokes/software.py:156
msgid "Source changed - please verify"
msgstr ""

#: pyanaconda/ui/gui/spokes/software.py:164
msgid "Custom software selected"
msgstr "Свой выбор программного обеспечения"

#: pyanaconda/ui/gui/spokes/software.py:166
#: pyanaconda/ui/gui/spokes/source.py:597
#: pyanaconda/ui/gui/spokes/source.py:630
msgid "Nothing selected"
msgstr "Ничего не выбрано"

#: pyanaconda/ui/gui/spokes/software.py:175
#: pyanaconda/ui/gui/spokes/source.py:50
msgid "Downloading package metadata..."
msgstr "Загрузка метаданных пакета..."

#: pyanaconda/ui/gui/spokes/software.py:181
msgid "Downloading group metadata..."
msgstr "Загрузка метаданных группы..."

#: pyanaconda/ui/gui/spokes/software.py:215
#: pyanaconda/ui/gui/spokes/source.py:589
msgid "No installation source available"
msgstr "Нет доступных источников для установки"

#: pyanaconda/ui/gui/spokes/software.py:265
msgid "Error checking software dependencies.  Click for details."
msgstr ""
"Ошибка при проверке зависимостей ПО. Нажмите для получения подробных "
"сведений."

#: pyanaconda/ui/gui/spokes/software.py:329
msgid ""
"The following software marked for installation has errors.  This is likely "
"caused by an error with\n"
"your installation source.  You can attempt to remove these packages from "
"your installation.\n"
"change your installation source, or quit the installer."
msgstr ""
"Следующее программное обеспечение, отмеченное для установки, содержит "
"ошибки.  Вероятно, это вызвано ошибкой источника установки.  Можно "
"попытаться удалить эти пакеты из установки.\n"
"смените источник установки или выйдите из установщика."

#: pyanaconda/ui/gui/spokes/software.py:333
#: pyanaconda/ui/gui/spokes/storage.glade:613
#: pyanaconda/ui/gui/spokes/source.glade:592
#: pyanaconda/ui/gui/spokes/custom.glade:91
#: pyanaconda/ui/gui/spokes/custom.glade:341
#: pyanaconda/ui/gui/spokes/custom.glade:1956
#: pyanaconda/ui/gui/spokes/custom.glade:2194 pyanaconda/ui/gui/main.glade:20
msgid "_Cancel"
msgstr "_Отмена"

#: pyanaconda/ui/gui/spokes/software.py:334
msgid "_Remove Packages"
msgstr "_Удалить пакеты"

#: pyanaconda/ui/gui/spokes/software.py:335
msgid "_Modify Software Source"
msgstr "_Изменить источник ПО"

#: pyanaconda/ui/gui/spokes/source.py:49
msgid "Setting up installation source..."
msgstr "Настройка источника установки..."

#: pyanaconda/ui/gui/spokes/source.py:51
msgid "Error downloading package metadata..."
msgstr "Ошибка загрузки метаданных пакета..."

#: pyanaconda/ui/gui/spokes/source.py:144
msgid "This media is good to install from."
msgstr "Этот носитель подходит для установки."

#: pyanaconda/ui/gui/spokes/source.py:146
msgid "This media is not good to install from."
msgstr "Этот носитель не подходит для установки."

#: pyanaconda/ui/gui/spokes/source.py:347
msgid "Getting info about requested repository"
msgstr "Получение информации о запрашиваемом репозитории"

#: pyanaconda/ui/gui/spokes/source.py:370
#: pyanaconda/ui/gui/spokes/source.glade:257
msgid "enter URL of your desired repository"
msgstr "введите адрес нужного репозитория"

#: pyanaconda/ui/gui/spokes/source.py:428
#: pyanaconda/ui/gui/spokes/source.glade:827
msgid "INSTALLATION SOURCE"
msgstr "ИСТОЧНИК УСТАНОВКИ"

#: pyanaconda/ui/gui/spokes/source.py:561
msgid "Failed to set up install source"
msgstr "Не удалось настроить источник для установки"

#: pyanaconda/ui/gui/spokes/source.py:563
#: pyanaconda/ui/gui/spokes/source.py:577
msgid "Failed to set up install source, check the repo url"
msgstr ""
"Не удалось настроить источник для установки, проверьте адрес репозитория"

#: pyanaconda/ui/gui/spokes/source.py:565
msgid "Failed to set up install source, check the repo url and proxy settings"
msgstr ""
"Не удалось настроить источник для установки, проверьте адрес репозитория и "
"настройки прокси"

#: pyanaconda/ui/gui/spokes/source.py:614
msgid "Not ready"
msgstr "Не готово"

#: pyanaconda/ui/gui/spokes/source.py:616
#: pyanaconda/ui/gui/spokes/source.py:625
msgid "Error setting up software source"
msgstr "Ошибка при настройке источника программного обеспечения"

#: pyanaconda/ui/gui/spokes/source.py:620
#, python-format
msgid "NFS server %s"
msgstr "Сервер NFS %s"

#: pyanaconda/ui/gui/spokes/source.py:622
msgid "CD/DVD drive"
msgstr "Привод CD/DVD"

#: pyanaconda/ui/gui/spokes/source.py:628
msgid "Closest mirror"
msgstr "Ближайшее зеркало"

#: pyanaconda/ui/gui/spokes/storage.py:151
#, python-format
msgid ""
"You have plenty of space to install <b>%s</b>, so we can automatically\n"
"configure the rest of the installation for you.\n"
"\n"
"You're all set!"
msgstr ""

#: pyanaconda/ui/gui/spokes/storage.py:170
#, python-format
msgid ""
"Your current <b>%s</b> software selection requires <b>%s</b> of available "
"space."
msgstr ""
"Для текущего <b>%s</b> выбора программного обеспечения необходимо <b>%s</b> "
"свободного пространства."

#: pyanaconda/ui/gui/spokes/storage.py:243
#, python-format
msgid ""
"%s\n"
"The disks you've selected have the following amounts of free space:"
msgstr ""
"%s\n"
"Выбранные диски имеют следующее количество свободного места:"

#: pyanaconda/ui/gui/spokes/storage.py:252
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>, but we can help "
"you\n"
"reclaim space by shrinking or removing existing partitions."
msgstr ""
"<b>Недостаточно свободного места для установки %s</b>, но можно\n"
"освободить место, сократив или удалив существующие разделы."

#: pyanaconda/ui/gui/spokes/storage.py:274
#, python-format
msgid ""
"%s\n"
"You don't have enough space available to install <b>%s</b>, even if you used "
"all of the free space\n"
"available on the selected disks."
msgstr ""
"%s\n"
"Не достаточно места для установки <b>%s</b>, даже если использовать всё "
"свободное пространство,\n"
"имеющееся на выбранных дисках."

#: pyanaconda/ui/gui/spokes/storage.py:285
#, python-format
msgid ""
"<b>You don't have enough space available to install %s</b>, even if you used "
"all of the free space\n"
"available on the selected disks.  You could add more disks for additional "
"space,\n"
"modify your software selection to install a smaller version of <b>%s</b>, or "
"quit the installer."
msgstr ""
"<b>Не достаточно места для установки %s</b>, даже если использовать всё "
"свободное пространство,\n"
"имеющееся на выбранных дисках.  Можно добавить диски для дополнительного "
"пространства,\n"
"изменить выбор программного обеспечения для получения меньшей по размеру "
"версии <b>%s</b>, или покинуть установщик."

#: pyanaconda/ui/gui/spokes/storage.py:325
#: pyanaconda/ui/gui/spokes/storage.glade:844
msgid "INSTALLATION DESTINATION"
msgstr "МЕСТО УСТАНОВКИ"

#: pyanaconda/ui/gui/spokes/storage.py:397
msgid "Saving storage configuration..."
msgstr "Сохранение конфигурации накопителей данных…"

#: pyanaconda/ui/gui/spokes/storage.py:404
msgid "Failed to save storage configuration..."
msgstr "Не удалось сохранить конфигурацию накопителей данных…"

#: pyanaconda/ui/gui/spokes/storage.py:496
msgid "Error checking storage configuration.  Click for details."
msgstr ""
"Ошибка при проверке конфигурации устройств хранения.  Нажмите для получения "
"подробных сведений."

#: pyanaconda/ui/gui/spokes/storage.py:575
#, python-format
msgid "%d disk selected; %s capacity; %s free"
msgid_plural "%d disks selected; %s capacity; %s free"
msgstr[0] "Выбран %d диск; емкость: %s; доступно: %s"
msgstr[1] "Выбрано %d диска; емкость: %s; доступно: %s"
msgstr[2] "Выбрано %d дисков; емкость: %s; доступно: %s"

#: pyanaconda/ui/gui/spokes/storage.py:627
msgid ""
"You have chosen to skip bootloader installation.  Your system may not be "
"bootable."
msgstr ""
"Вы решили пропустить установку загрузчика. Это может привести к тому, что "
"загрузка системы будет невозможна."

#: pyanaconda/ui/gui/spokes/storage.py:767
msgid ""
"The following errors were encountered when checking your storage "
"configuration.  You can modify your storage layout\n"
"or quit the installer."
msgstr ""
"Следующие ошибки были встречены при проверке конфигурации устройств "
"хранения.  Можете изменить схему устройств хранения\n"
"или выйти из программы установки."

#: pyanaconda/ui/gui/spokes/storage.py:770
msgid "_Modify Storage Layout"
msgstr "_Изменить схему дисков"

#: pyanaconda/ui/gui/spokes/welcome.py:310
msgid "LANGUAGE"
msgstr "ЯЗЫК"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:130
msgid "DATA"
msgstr "ДАННЫЕ"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:135
msgid "SYSTEM"
msgstr "СИСТЕМА"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:235
#, python-format
msgid "You haven't created any mount points for your %s %s installation yet:"
msgstr "Не создано ещё ни одной точки монтирования для установки %s %s:"

#: pyanaconda/ui/gui/spokes/lib/accordion.py:240
msgid "Click here to create them automatically."
msgstr "Нажмите для автоматического создания."

#: pyanaconda/ui/gui/spokes/lib/accordion.py:250
msgid "Or, create new mount points below with the '+' icon."
msgstr "Или же создайте новые точки монтирования ниже, нажав на значок '+' ."

#: pyanaconda/ui/gui/spokes/lib/cart.py:138
#, python-format
msgid ""
"<b>%d disk; %s capacity; %s free space</b> (unpartitioned and in filesystems)"
msgid_plural ""
"<b>%d disks; %s capacity; %s free space</b> (unpartitioned and in "
"filesystems)"
msgstr[0] ""
"<b>%d диск; емкость: %s; доступно: %s</b> (не занято разделами и файловыми "
"системами)"
msgstr[1] ""
"<b>%d диска; емкость: %s; доступно: %s</b> (не занято разделами и файловыми "
"системами)"
msgstr[2] ""
"<b>%d дисков; емкость: %s; доступно: %s</b> (не занято разделами и файловыми "
"системами)"

#: pyanaconda/ui/gui/spokes/lib/cart.py:190
msgid "_Do not install bootloader"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/cart.py:192
#: pyanaconda/ui/gui/spokes/lib/cart.glade:190
msgid "_Set as Boot Device"
msgstr "_Назначить загрузочное устройство"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:38
#, python-format
msgid ""
"Warning: Your current keyboard layout is <b>%s</b>.If you change your "
"keyboard layout, you may not be able to decrypt your disks after install."
msgstr ""
"Предупреждение: Текущая раскладка клавиатуры — <b>%s</b>. Если изменить "
"раскладку, то после уставновки это может помешать расшифровке дисков."

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:42
#, python-format
msgid "You have provided a weak passphrase: %s"
msgstr "Указанный пароль слишком прост: %s"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:43
msgid "Passphrases do not match."
msgstr "Пароли не совпадают."

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:116
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:165
msgid "Weak"
msgstr "Простой"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:119
msgid "Fair"
msgstr "Нормальный"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:122
msgid "Good"
msgstr "Хороший"

#: pyanaconda/ui/gui/spokes/lib/passphrase.py:125
msgid "Strong"
msgstr "Сложный"

#: pyanaconda/ui/gui/spokes/lib/resize.py:46
#: pyanaconda/ui/gui/spokes/lib/resize.glade:216
msgid "Preserve"
msgstr "Сохранить"

#: pyanaconda/ui/gui/spokes/lib/resize.py:47
msgid "Shrink"
msgstr "Ужать"

#: pyanaconda/ui/gui/spokes/lib/resize.py:48
#: pyanaconda/ui/gui/spokes/lib/resize.glade:228
msgid "Delete"
msgstr "Удалить"

#: pyanaconda/ui/gui/spokes/lib/resize.py:134
msgid "Whole disks are not editable."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/resize.py:151
msgid "This device contains the installation source."
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/resize.py:158
#, python-format
msgid "%s of %s"
msgstr "%s из %s"

#: pyanaconda/ui/gui/spokes/lib/resize.py:175
msgid ""
"You don't have enough free space available for this installation.\n"
"\n"
"You can remove existing filesystems you no longer need to free up space for "
"this installation.  Removing a filesystem will permanently delete all of the "
"data it contains."
msgstr ""
"Для этой установки не хватает свободного места.\n"
"\n"
"Чтобы освободить место, можно удалить ненужные файловые системы, но это "
"приведёт к полному удалению всех данных, которые в них находятся."

#: pyanaconda/ui/gui/spokes/lib/resize.py:191
#, python-format
msgid "<b>%s disk; %s reclaimable space</b> (in filesystems)"
msgid_plural "<b>%s disks; %s reclaimable space</b> (in filesystems)"
msgstr[0] "<b>%s диск; %s доступного места</b> (в файловых системах)"
msgstr[1] "<b>%s диска; %s доступного места</b> (в файловых системах)"
msgstr[2] "<b>%s дисков; %s доступного места</b> (в файловых системах)"

#: pyanaconda/ui/gui/spokes/lib/resize.py:197
#, python-format
msgid "Total selected space to reclaim: <b>%s</b>"
msgstr "Всего выбрано места для высвобождения: <b>%s</b>"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:87
msgid "Region:"
msgstr "Регион:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:120
msgid "City:"
msgstr "Город:"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:164
msgid "Network Time"
msgstr "Сетевое время"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:257
#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:289
msgid "00"
msgstr "00"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:273
msgid ":"
msgstr ":"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:401
msgid " "
msgstr " "

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:417
msgid "PM"
msgstr "PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:461
msgid "24-hour"
msgstr "24 часа"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:479
msgid "AM/PM"
msgstr "AM/PM"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:646
msgid "Add and mark for usage NTP servers"
msgstr "Добавить и отметить для использования NTP серверы"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:727
msgid "Hostname"
msgstr "Имя сервера"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:742
msgid "Working"
msgstr "В процессе"

#: pyanaconda/ui/gui/spokes/datetime_spoke.glade:750
msgid "Use"
msgstr "Использовать"

#: pyanaconda/ui/gui/spokes/network.glade:78
msgid ""
"We'll need network access to fetch information about your location and to "
"make software\n"
"updates available for you."
msgstr ""
"Необходим доступ к сети, что бы получать информацию о местонахождении и "
"сделать\n"
"доступными обновления для программного обеспечения."

#: pyanaconda/ui/gui/spokes/network.glade:321
#: pyanaconda/ui/gui/spokes/network.glade:674
msgid "Hardware Address"
msgstr "Аппаратный адрес"

#: pyanaconda/ui/gui/spokes/network.glade:335
#: pyanaconda/ui/gui/spokes/network.glade:688
#: pyanaconda/ui/gui/spokes/network.glade:1176
msgid "Speed"
msgstr "Скорость"

#: pyanaconda/ui/gui/spokes/network.glade:377
msgid "Subnet Mask"
msgstr "Маска подсети"

#: pyanaconda/ui/gui/spokes/network.glade:391
#: pyanaconda/ui/gui/spokes/network.glade:730
#: pyanaconda/ui/gui/spokes/network.glade:1349
msgid "Default Route"
msgstr "Маршрут по умолчанию"

#: pyanaconda/ui/gui/spokes/network.glade:406
#: pyanaconda/ui/gui/spokes/network.glade:745
#: pyanaconda/ui/gui/spokes/network.glade:1364
msgid "DNS"
msgstr "DNS"

#: pyanaconda/ui/gui/spokes/network.glade:553
msgid "C_onfigure..."
msgstr "Н_астроить..."

#: pyanaconda/ui/gui/spokes/network.glade:867
msgid "Security"
msgstr "Безопасность"

#: pyanaconda/ui/gui/spokes/network.glade:881
msgid "_Network Name"
msgstr "_Сетевое имя"

#: pyanaconda/ui/gui/spokes/network.glade:897
msgid "Network Name"
msgstr "Сетевое имя"

#: pyanaconda/ui/gui/spokes/network.glade:911
msgid "Security Key"
msgstr "Ключ безопасности"

#: pyanaconda/ui/gui/spokes/network.glade:1001
msgid "_Use as Hotspot..."
msgstr "_Использовать как точку доступа..."

#: pyanaconda/ui/gui/spokes/network.glade:1020
msgid "_Stop Hotspot..."
msgstr "_Остановить точку доступа..."

#: pyanaconda/ui/gui/spokes/network.glade:1039
#: pyanaconda/ui/gui/spokes/network.glade:1391
#: pyanaconda/ui/gui/spokes/network.glade:1676
msgid "_Configure..."
msgstr "_Настроить..."

#: pyanaconda/ui/gui/spokes/network.glade:1162
msgid "IMEI"
msgstr "IMEI"

#: pyanaconda/ui/gui/spokes/network.glade:1190
msgid "Provider"
msgstr "Поставщик услуг"

#: pyanaconda/ui/gui/spokes/network.glade:1504
msgid "VPN Type"
msgstr "Тип VPN"

#: pyanaconda/ui/gui/spokes/network.glade:1518
msgid "Gateway"
msgstr "Шлюз"

#: pyanaconda/ui/gui/spokes/network.glade:1532
msgid "Group Name"
msgstr "Имя группы"

#: pyanaconda/ui/gui/spokes/network.glade:1546
msgid "Group Password"
msgstr "Пароль группы"

#: pyanaconda/ui/gui/spokes/network.glade:1560
msgid "Username"
msgstr "Имя пользователя"

#: pyanaconda/ui/gui/spokes/network.glade:1803
msgid "_Method"
msgstr "_Метод"

#: pyanaconda/ui/gui/spokes/network.glade:1831
msgid "_Configuration URL"
msgstr "_Настройки адреса"

#: pyanaconda/ui/gui/spokes/network.glade:1861
msgid "_HTTP Proxy"
msgstr "_HTTP Proxy"

#: pyanaconda/ui/gui/spokes/network.glade:1877
msgid "H_TTPS Proxy"
msgstr "H_TTPS Proxy"

#: pyanaconda/ui/gui/spokes/network.glade:1893
msgid "_FTP Proxy"
msgstr "_FTP Proxy"

#: pyanaconda/ui/gui/spokes/network.glade:1909
msgid "_Socks Host"
msgstr "_Узел socks"

#: pyanaconda/ui/gui/spokes/network.glade:2153
msgid "Unlock"
msgstr "Разблокировать"

#: pyanaconda/ui/gui/spokes/network.glade:2173
msgid "Air_plane Mode"
msgstr "Ре_жим полёта"

#: pyanaconda/ui/gui/spokes/network.glade:2207
msgid "Hostname:"
msgstr ""

#: pyanaconda/ui/gui/spokes/software.glade:86
msgid "Choose your environment"
msgstr "Выберите среду"

#: pyanaconda/ui/gui/spokes/software.glade:106
msgid "Choose your add-ons"
msgstr "Выберите дополнения"

#: pyanaconda/ui/gui/spokes/software.glade:143
#: pyanaconda/ui/gui/spokes/software.glade:158
#: pyanaconda/ui/gui/spokes/software.glade:215
#: pyanaconda/ui/gui/spokes/software.glade:230
msgid "column"
msgstr "колонка"

#: pyanaconda/ui/gui/spokes/software.glade:266
msgid "_Add custom add-on..."
msgstr "_Добавить пользовательское дополнение..."

#: pyanaconda/ui/gui/spokes/storage.glade:26
#: pyanaconda/ui/gui/spokes/storage.glade:221
msgid "Cancel & _add more disks"
msgstr "Отменить и _добавить больше дисков"

#: pyanaconda/ui/gui/spokes/storage.glade:79
#: pyanaconda/ui/gui/spokes/storage.glade:293
#: pyanaconda/ui/gui/spokes/storage.glade:650
msgid "INSTALLATION OPTIONS"
msgstr "ПАРАМЕТРЫ УСТАНОВКИ"

#: pyanaconda/ui/gui/spokes/storage.glade:96
#: pyanaconda/ui/gui/spokes/storage.glade:327
#: pyanaconda/ui/gui/spokes/storage.glade:806
msgid "Here we'll describe what your options are."
msgstr "Здесь описываются варианты выбора."

#: pyanaconda/ui/gui/spokes/storage.glade:122
#: pyanaconda/ui/gui/spokes/storage.glade:477
msgid "<b>Partition type:</b>"
msgstr "<b>Тип раздела:</b>"

#: pyanaconda/ui/gui/spokes/storage.glade:155
#: pyanaconda/ui/gui/spokes/storage.glade:510
msgid "Partition scheme configuration"
msgstr "Конфигурация схемы разделов"

#: pyanaconda/ui/gui/spokes/storage.glade:170
msgid "Let me customize the _partitioning of the disks instead."
msgstr "Я хочу сам настроить разбиение разделов на дисках."

#: pyanaconda/ui/gui/spokes/storage.glade:238
#: pyanaconda/ui/gui/spokes/storage.glade:594
msgid "_Modify software selection"
msgstr "_Изменить выбор программного обеспечения"

#: pyanaconda/ui/gui/spokes/storage.glade:242
#: pyanaconda/ui/gui/spokes/storage.glade:598
msgid "Please wait... software metadata still loading."
msgstr "Подождите… Всё ещё загружаются метаданные ПО."

#: pyanaconda/ui/gui/spokes/storage.glade:257
msgid "Reclaim _space"
msgstr "Перераспределить _пространство"

#: pyanaconda/ui/gui/spokes/storage.glade:310
#: pyanaconda/ui/gui/spokes/storage.glade:666
msgid ""
"Here we'll describe how much space is needed for the current software "
"selection."
msgstr ""
"Здесь описывается, сколько места нужно для текущего выбора программного "
"обеспечения."

#: pyanaconda/ui/gui/spokes/storage.glade:353
#: pyanaconda/ui/gui/spokes/storage.glade:692
msgid "disk free"
msgstr "диск чист"

#: pyanaconda/ui/gui/spokes/storage.glade:371
#: pyanaconda/ui/gui/spokes/storage.glade:709
msgid "Free space available for use."
msgstr "Свободное пространство, доступное для использования."

#: pyanaconda/ui/gui/spokes/storage.glade:389
#: pyanaconda/ui/gui/spokes/storage.glade:727
msgid "fs free"
msgstr "фс свободна"

#: pyanaconda/ui/gui/spokes/storage.glade:407
#: pyanaconda/ui/gui/spokes/storage.glade:745
msgid "Free space unavailable but reclaimable from existing partitions."
msgstr "Свободного места нет, но его можно получить из существующих разделов."

#: pyanaconda/ui/gui/spokes/storage.glade:425
#: pyanaconda/ui/gui/spokes/storage.glade:763
msgid "disks size"
msgstr "размер дисков"

#: pyanaconda/ui/gui/spokes/storage.glade:443
#: pyanaconda/ui/gui/spokes/storage.glade:781
msgid "Space in selected disks reclaimable by deleting existing partitions."
msgstr ""
"Место на выбранных дисках можно высвободить путём удаления существующих "
"разделов."

#: pyanaconda/ui/gui/spokes/storage.glade:525
msgid "I don't need help; let me customize disk _partitioning."
msgstr "Помощь не нужна. Настройка _разделов будет выполнена вручную"

#: pyanaconda/ui/gui/spokes/storage.glade:577
msgid "_Quit installer"
msgstr "_Выйти из установщика"

#: pyanaconda/ui/gui/spokes/storage.glade:891
msgid "Local Standard Disks"
msgstr "Локальные стандартные диски"

#: pyanaconda/ui/gui/spokes/storage.glade:972
msgid "Full disk summary and options..."
msgstr "Полная сводка данных о дисках и опциях…"

#: pyanaconda/ui/gui/spokes/storage.glade:997
#: pyanaconda/ui/gui/spokes/custom.glade:1900
msgid "summary"
msgstr "сводка"

#: pyanaconda/ui/gui/spokes/storage.glade:1011
msgid "Encrypt my data. I'll set a passphrase later."
msgstr "Шифровать данные. Пароль будет установлен позднее."

#: pyanaconda/ui/gui/spokes/keyboard.glade:68
msgid "ADD A KEYBOARD LAYOUT"
msgstr "ДОБАВИТЬ РАСКЛАДКУ КЛАВИАТУРЫ"

#: pyanaconda/ui/gui/spokes/keyboard.glade:85
msgid "You may add a keyboard layout by selecting it below:"
msgstr "Можно добавить раскладку клавиатуры, выбрав её ниже:"

#: pyanaconda/ui/gui/spokes/keyboard.glade:121
msgid "Name"
msgstr "Имя"

#: pyanaconda/ui/gui/spokes/keyboard.glade:182
msgid "KEYBOARD LAYOUT"
msgstr "РАСКЛАДКА КЛАВИАТУРЫ"

#: pyanaconda/ui/gui/spokes/keyboard.glade:223
msgid ""
"Which keyboard layouts would you like to use on this system?  You may move "
"any layout to the top of the list to select it as the default."
msgstr ""
"Какую раскладку клавиатуры использовать на этой системе? Раскладка, "
"передвинутая на верх списка, будет использоваться по умолчанию."

#: pyanaconda/ui/gui/spokes/keyboard.glade:262
msgid ""
"Changes here will only apply to the installed system. Use the desktop's tool "
"to configure the keyboard for the installation process."
msgstr ""

#: pyanaconda/ui/gui/spokes/keyboard.glade:319
msgid "name"
msgstr "имя"

#: pyanaconda/ui/gui/spokes/keyboard.glade:355
msgid "Add layout"
msgstr "Добавить раскладку"

#: pyanaconda/ui/gui/spokes/keyboard.glade:370
msgid "Remove layout"
msgstr "Удалить раскладку"

#: pyanaconda/ui/gui/spokes/keyboard.glade:385
msgid "Move selected layout up"
msgstr "Передвинуть выбранную раскладку вверх"

#: pyanaconda/ui/gui/spokes/keyboard.glade:400
msgid "Move selected layout down"
msgstr "Передвинуть выбранную раскладку вниз"

#: pyanaconda/ui/gui/spokes/keyboard.glade:416
msgid "Preview layout"
msgstr "Посмотреть раскладку"

#: pyanaconda/ui/gui/spokes/keyboard.glade:453
msgid "Test the selected layout below:"
msgstr ""

#: pyanaconda/ui/gui/spokes/keyboard.glade:492
msgid "Alt + Shift to switch layouts."
msgstr "Alt + Shift для переключения раскладок."

#: pyanaconda/ui/gui/spokes/keyboard.glade:506
msgid "_Options"
msgstr "_Параметры"

#: pyanaconda/ui/gui/spokes/keyboard.glade:623
msgid "LAYOUT SWITCHING OPTIONS"
msgstr "ПАРАМЕТРЫ ПЕРЕКЛЮЧЕНИЯ РАСКЛАДКИ"

#: pyanaconda/ui/gui/spokes/keyboard.glade:640
msgid ""
"Which combination(s) would you prefer for switching between keyboard layouts?"
msgstr "Выберите комбинацию клавиш для переключения раскладки."

#: pyanaconda/ui/gui/spokes/keyboard.glade:676
msgid "use"
msgstr "использование"

#: pyanaconda/ui/gui/spokes/keyboard.glade:689
msgid "description"
msgstr "описание"

#: pyanaconda/ui/gui/spokes/password.glade:52
msgid "Root Password:"
msgstr "Пароль root:"

#: pyanaconda/ui/gui/spokes/password.glade:67
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:127
msgid "Confirm:"
msgstr "Подтверждение:"

#: pyanaconda/ui/gui/spokes/password.glade:123
msgid ""
"The root account is used for administering the system.  Enter a password for "
"the root user."
msgstr ""
"Учетная запись администратора (root) предназначена для управления системой. "
"Введите пароль root."

#: pyanaconda/ui/gui/spokes/source.glade:35
#: pyanaconda/ui/gui/spokes/source.glade:607
msgid "_Add"
msgstr "_Добавить"

#: pyanaconda/ui/gui/spokes/source.glade:66
msgid "ADD A CUSTOM ADD-ON"
msgstr "ДОБАВИТЬ ВЫБРАННЫЕ ДОПОЛНЕНИЯ"

#: pyanaconda/ui/gui/spokes/source.glade:82
msgid "Where is the yum repository for your add-on?"
msgstr "Где расположен репозиторий yum для этого дополнения?"

#: pyanaconda/ui/gui/spokes/source.glade:140
msgid "Repository"
msgstr "Репозиторий"

#: pyanaconda/ui/gui/spokes/source.glade:189
msgid "Fedora People Repositories"
msgstr "Репозитории Fedora People"

#: pyanaconda/ui/gui/spokes/source.glade:306
msgid "Standard YUM repository:"
msgstr "Стандартный репозиторий YUM:"

#: pyanaconda/ui/gui/spokes/source.glade:439 widgets/src/SpokeWindow.c:46
msgid "_Done"
msgstr "Готово"

#: pyanaconda/ui/gui/spokes/source.glade:472
msgid "MEDIA VERIFICATION"
msgstr "ПРОВЕРКА НОСИТЕЛЕЙ"

#: pyanaconda/ui/gui/spokes/source.glade:499
msgid "Verifying media, please wait..."
msgstr "Проверка носителей, подождите..."

#: pyanaconda/ui/gui/spokes/source.glade:635
msgid "_Enable HTTP Proxy"
msgstr "_Разрешить HTTP Proxy"

#: pyanaconda/ui/gui/spokes/source.glade:668
msgid "<b>Proxy URL</b>"
msgstr "<b>Адрес прокси</b>"

#: pyanaconda/ui/gui/spokes/source.glade:683
msgid "<span size=\"small\"><b>Example:</b> squid.mysite.org:3128</span>"
msgstr "<span size=\"small\"><b>Пример:</b> squid.mysite.org:3128</span>"

#: pyanaconda/ui/gui/spokes/source.glade:716
msgid "_Use Authentication"
msgstr "_Использовать проверку подлинности"

#: pyanaconda/ui/gui/spokes/source.glade:743
msgid "<b>Username</b>"
msgstr "<b>Имя пользователя</b>"

#: pyanaconda/ui/gui/spokes/source.glade:758
msgid "<b>Password</b>"
msgstr "<b>Пароль</b>"

#: pyanaconda/ui/gui/spokes/source.glade:869
msgid "Which installation source would you like to use?"
msgstr "Выберите источник установки"

#: pyanaconda/ui/gui/spokes/source.glade:883
msgid "_Auto-detected install media:"
msgstr "_Автоматически обнаруженный установочный носитель:"

#: pyanaconda/ui/gui/spokes/source.glade:938
#: pyanaconda/ui/gui/spokes/source.glade:1031
msgid "_Verify"
msgstr "_Проверить"

#: pyanaconda/ui/gui/spokes/source.glade:961
msgid "_ISO file:"
msgstr "_ISO-файл:"

#: pyanaconda/ui/gui/spokes/source.glade:988
msgid "Device:"
msgstr "Устройство:"

#: pyanaconda/ui/gui/spokes/source.glade:1016
msgid "_Choose an ISO"
msgstr "_Выбрать ISO"

#: pyanaconda/ui/gui/spokes/source.glade:1054
msgid "On the _network:"
msgstr "По _сети"

#: pyanaconda/ui/gui/spokes/source.glade:1129
msgid "_Proxy setup..."
msgstr "_Настройки прокси..."

#: pyanaconda/ui/gui/spokes/source.glade:1147
msgid "This URL refers to a _mirror list."
msgstr ""

#: pyanaconda/ui/gui/spokes/source.glade:1182
msgid "NFS mount options:"
msgstr "Параметры монтирования NFS:"

#: pyanaconda/ui/gui/spokes/source.glade:1195
#: pyanaconda/ui/gui/spokes/source.glade:1196
msgid "This field is optional."
msgstr "Это поле не является обязательным."

#: pyanaconda/ui/gui/spokes/welcome.glade:21
msgid "_Get me out of here!"
msgstr "_Уйти отсюда!"

#: pyanaconda/ui/gui/spokes/welcome.glade:35
msgid "_I accept my fate."
msgstr "_Продолжить"

#: pyanaconda/ui/gui/spokes/welcome.glade:66
msgid "This is unstable, pre-release software."
msgstr "Стабильность предварительной версии дистрибутива не гарантируется"

#: pyanaconda/ui/gui/spokes/welcome.glade:99
msgid ""
"You wake up inside an OS installer in Timbuktu, and it's six months in the "
"future.  But, there are bugs.  Bugs everywhere.  Bugs you must live with.  "
"This OS of the future isn't a stable OS you can rely on.  It's for testing "
"purposes only."
msgstr ""
"Вы оказались в установщике непонятной ОС из будущего. Пока в ней множество "
"ошибок, с которыми придется мириться. Эта система не является той, на "
"которую можно положиться. Пока она предназначена только для тестирования."

#: pyanaconda/ui/gui/spokes/welcome.glade:251
msgid "WELCOME TO %s %s."
msgstr "ДОБРО ПОЖАЛОВАТЬ В %s %s."

#: pyanaconda/ui/gui/spokes/welcome.glade:269
msgid "What language would you like to use during the installation process?"
msgstr "Какой язык вы хотите использовать в процессе установки?"

#: pyanaconda/ui/gui/spokes/welcome.glade:319
msgid "nativeName"
msgstr "родноеНазвание"

#: pyanaconda/ui/gui/spokes/welcome.glade:335
msgid "englishName"
msgstr "английскоеНазвание"

#: pyanaconda/ui/gui/spokes/welcome.glade:389
msgid "Set _keyboard to default layout for selected language."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:8
#: pyanaconda/ui/gui/spokes/custom.glade:1741
msgid "Help"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:106
msgid "_Add mount point"
msgstr "_Добавить точку монтирования"

#: pyanaconda/ui/gui/spokes/custom.glade:139
msgid "<b>Desired Capacity:</b>"
msgstr "<b>Требуемый размер:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:154
#: pyanaconda/ui/gui/spokes/custom.glade:558
msgid "<b>Mount Point:</b>"
msgstr "<b>Точка монтирования:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:170
msgid "ADD A NEW MOUNT POINT"
msgstr "ДОБАВИТЬ НОВУЮ ТОЧКУ МОНТИРОВАНИЯ"

#: pyanaconda/ui/gui/spokes/custom.glade:188
msgid ""
"More customization options are available\n"
"after creating the mount point below."
msgstr ""
"Дополнительные настройки станут доступными\n"
"после создания этой точки монтирования."

#: pyanaconda/ui/gui/spokes/custom.glade:206
msgid "eg: \"/\", \"/home\", \"swap\" (minus the quotation marks)"
msgstr "напр.: «/», «/home», «swap» (без кавычек)"

#: pyanaconda/ui/gui/spokes/custom.glade:239
msgid ""
"That mount point is already in\n"
"use.  Try something else?"
msgstr ""
"Эта точка монтирования уже\n"
"используется. Выбрать другую?"

#: pyanaconda/ui/gui/spokes/custom.glade:265
msgid "eg: \"20 GB\", \"500mb\" (minus the quotation marks)"
msgstr "например: «20 Гб», «500 Мб» (без кавычек)"

#: pyanaconda/ui/gui/spokes/custom.glade:308
msgid "Are you sure you want to delete all of the data on %s?"
msgstr "Удалить все данные с %s?"

#: pyanaconda/ui/gui/spokes/custom.glade:322
msgid "Delete all other filesystems in the %s root as well."
msgstr "Удалить файловые системы в корне %s."

#: pyanaconda/ui/gui/spokes/custom.glade:357
msgid "_Delete It"
msgstr "_Удалить"

#: pyanaconda/ui/gui/spokes/custom.glade:390
msgid "_Back to destination selection"
msgstr "_Назад к выбору получателя"

#: pyanaconda/ui/gui/spokes/custom.glade:476
msgid ""
"When you create mount points for your %s %s install,\n"
"you'll be able to view their details here."
msgstr ""
"При создании точек монтирования для установки %s %s\n"
"можно просмотреть сведения о них здесь."

#: pyanaconda/ui/gui/spokes/custom.glade:499
#: pyanaconda/ui/gui/spokes/custom.glade:1362
#: pyanaconda/ui/gui/spokes/custom.glade:1504
#: pyanaconda/ui/gui/spokes/custom.glade:1591
msgid "Selected Device"
msgstr "Выбранное устройство"

#: pyanaconda/ui/gui/spokes/custom.glade:517
#: pyanaconda/ui/gui/spokes/custom.glade:1380
#: pyanaconda/ui/gui/spokes/custom.glade:1522
#: pyanaconda/ui/gui/spokes/custom.glade:1609
msgid "Device description"
msgstr "Описание устройства"

#: pyanaconda/ui/gui/spokes/custom.glade:588
msgid "<b>Label:</b>"
msgstr "<b>Метка:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:604
msgid "<b>Desired Capacity (MB):</b>"
msgstr "<b>Требуемый размер (Мб):</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:651
#: pyanaconda/ui/gui/spokes/custom.glade:2036
msgid "Name:"
msgstr "Имя:"

#: pyanaconda/ui/gui/spokes/custom.glade:712
msgid "<b>Device Type:</b>"
msgstr "<b>Тип устройства:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:727
msgid "<b>File System:</b>"
msgstr "<b>Файловая система:</b>"

#: pyanaconda/ui/gui/spokes/custom.glade:773
msgid "_Encrypt"
msgstr "Зашифровать"

#: pyanaconda/ui/gui/spokes/custom.glade:806
#: pyanaconda/ui/gui/spokes/custom.glade:903
#: pyanaconda/ui/gui/spokes/custom.glade:1144
msgid "Redundancy (mirror)"
msgstr "Избыточность (зеркало)"

#: pyanaconda/ui/gui/spokes/custom.glade:825
#: pyanaconda/ui/gui/spokes/custom.glade:868
#: pyanaconda/ui/gui/spokes/custom.glade:922
#: pyanaconda/ui/gui/spokes/custom.glade:965
#: pyanaconda/ui/gui/spokes/custom.glade:1008
#: pyanaconda/ui/gui/spokes/custom.glade:1052
#: pyanaconda/ui/gui/spokes/custom.glade:1084
#: pyanaconda/ui/gui/spokes/custom.glade:1163
#: pyanaconda/ui/gui/spokes/custom.glade:1206
msgid "(-0Gb)"
msgstr "(-0Гб)"

#: pyanaconda/ui/gui/spokes/custom.glade:850
#: pyanaconda/ui/gui/spokes/custom.glade:947
#: pyanaconda/ui/gui/spokes/custom.glade:1188
msgid "Optimized performance (stripe)"
msgstr "Оптимизированная производительность (чередование)"

#: pyanaconda/ui/gui/spokes/custom.glade:990
msgid "Error detection (parity)"
msgstr "Обнаружение ошибок (четности)"

#: pyanaconda/ui/gui/spokes/custom.glade:1034
msgid "Distributed"
msgstr "Распределенный"

#: pyanaconda/ui/gui/spokes/custom.glade:1065
msgid "Redundant"
msgstr "Избыточный"

#: pyanaconda/ui/gui/spokes/custom.glade:1243
msgid "Reformat"
msgstr "Форматировать заново"

#: pyanaconda/ui/gui/spokes/custom.glade:1262
msgid "Volume Group:"
msgstr "Группа томов:"

#: pyanaconda/ui/gui/spokes/custom.glade:1291
msgid "Modify ..."
msgstr "Изменить..."

#: pyanaconda/ui/gui/spokes/custom.glade:1310
msgid "_Customize..."
msgstr "Настроить"

#: pyanaconda/ui/gui/spokes/custom.glade:1323
msgid "_Apply Changes"
msgstr "_Применить"

#: pyanaconda/ui/gui/spokes/custom.glade:1414
msgid ""
"This device is encrypted and cannot be read without a valid passphrase. You "
"may unlock it below."
msgstr ""
"Устройство зашифровано, его данные недоступны без пароля. Ниже его можно "
"разблокировать."

#: pyanaconda/ui/gui/spokes/custom.glade:1435
#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:97
msgid "Passphrase:"
msgstr "Пароль:"

#: pyanaconda/ui/gui/spokes/custom.glade:1461
msgid "_Unlock"
msgstr "_Разблокировать"

#: pyanaconda/ui/gui/spokes/custom.glade:1556
msgid ""
"This device cannot be edited directly. You can remove it or select a "
"different device."
msgstr ""
"Это устройство не может быть изменено напрямую. Следует его удалить и "
"добавить другое устройство."

#: pyanaconda/ui/gui/spokes/custom.glade:1644
msgid ""
"This %s device is missing %d of %d %s. You can remove it or select a "
"different device."
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:1690
msgid "Add a new mountpoint."
msgstr "Добавить точку монтирования"

#: pyanaconda/ui/gui/spokes/custom.glade:1691
msgid "addButton"
msgstr "Кнопка добавления"

#: pyanaconda/ui/gui/spokes/custom.glade:1708
msgid "Remove the selected mountpoint(s.)"
msgstr "Удалить выбранные точки монтирования."

#: pyanaconda/ui/gui/spokes/custom.glade:1709
msgid "removeButton"
msgstr "Кнопка удаления"

#: pyanaconda/ui/gui/spokes/custom.glade:1726
msgid "Configure selected mountpoint."
msgstr "Настроить точку монтирования."

#: pyanaconda/ui/gui/spokes/custom.glade:1727
msgid "configureButton"
msgstr "Кнопка настройки"

#: pyanaconda/ui/gui/spokes/custom.glade:1742
msgid "Click for help"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:1790
msgid "<span size=\"small\" foreground=\"white\">AVAILABLE SPACE</span>"
msgstr ""
"<span size=\"small\" foreground=\"white\">ДОСТУПНОЕ ПРОСТРАНСТВО</span>"

#: pyanaconda/ui/gui/spokes/custom.glade:1842
msgid "<span size=\"small\" foreground=\"white\">TOTAL SPACE</span>"
msgstr "<span size=\"small\" foreground=\"white\">ВСЕГО ПРОСТРАНСТВА</span>"

#: pyanaconda/ui/gui/spokes/custom.glade:1881
msgid "_Finish Partitioning"
msgstr "_Завершить разбиение"

#: pyanaconda/ui/gui/spokes/custom.glade:1971
msgid "_Save"
msgstr "_Сохранить"

#: pyanaconda/ui/gui/spokes/custom.glade:2003
msgid "CONFIGURE VOLUME GROUP"
msgstr "НАСТРОЙКА ГРУППЫ ТОМОВ"

#: pyanaconda/ui/gui/spokes/custom.glade:2018
msgid ""
"Please create a name for your volume group and select at least one disk "
"below."
msgstr "Определите имя для группы томов и выберите как минимум один диск."

#: pyanaconda/ui/gui/spokes/custom.glade:2101
#: pyanaconda/ui/gui/spokes/custom.glade:2302
#: pyanaconda/ui/gui/spokes/lib/cart.glade:138
msgid "Capacity"
msgstr "Объем"

#: pyanaconda/ui/gui/spokes/custom.glade:2114
#: pyanaconda/ui/gui/spokes/custom.glade:2315
#: pyanaconda/ui/gui/spokes/lib/cart.glade:151
msgid "Free"
msgstr "Своб."

#: pyanaconda/ui/gui/spokes/custom.glade:2127
#: pyanaconda/ui/gui/spokes/custom.glade:2328
msgid "ID"
msgstr "ID"

#: pyanaconda/ui/gui/spokes/custom.glade:2209
msgid "_Select"
msgstr ""

#: pyanaconda/ui/gui/spokes/custom.glade:2241
msgid "CONFIGURE MOUNT POINT"
msgstr "НАСТРОЙКА ТОЧКИ МОНТИРОВАНИЯ"

#: pyanaconda/ui/gui/spokes/custom.glade:2256
msgid "Select one or more disks this device may reside on."
msgstr "Укажите диски, на которых может располагаться устройство."

#: pyanaconda/ui/gui/spokes/lib/cart.glade:25
#: pyanaconda/ui/gui/spokes/lib/cart.glade:79
msgid "SELECTED DISKS"
msgstr "ВЫБРАННЫЕ ДИСКИ"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:43
msgid "_Close"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/cart.glade:111
msgid "Boot"
msgstr "Загрузка"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:125
msgid "Description"
msgstr "Описание"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:163
msgid "Id"
msgstr "Идентификатор"

#: pyanaconda/ui/gui/spokes/lib/cart.glade:207
msgid "_Remove"
msgstr ""

#: pyanaconda/ui/gui/spokes/lib/cart.glade:235
msgid "Disk summary goes here"
msgstr "Сводная информация по диску"

#: pyanaconda/ui/gui/spokes/lib/detailederror.glade:24
msgid "An unknown error occurred during installation.  Details are below."
msgstr ""
"Во время установки произошла неизвестная ошибка.  Подробности приводятся "
"ниже."

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:20
msgid "DISK ENCRYPTION PASSPHRASE"
msgstr "ПАРОЛЬ ШИФРОВАНИЯ ДИСКА"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:52
msgid "Save Passphrase"
msgstr "Сохранить пароль"

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:77
msgid ""
"You have chosen to encrypt some of your data. You will need to create a "
"passphrase that you will use to access your data when you start your "
"computer."
msgstr ""
"Вы выбрали шифрование данных. Необходимо создать пароль доступа при запуске "
"операционной системы."

#: pyanaconda/ui/gui/spokes/lib/passphrase.glade:212
msgid "keymap warning label"
msgstr "метка предупреждения раскладки"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:58
msgid "_Reclaim space"
msgstr "_Вернуть пространство"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:92
msgid "RECLAIM DISK SPACE"
msgstr "ВЕРНУТЬ ПРОСТРАНСТВО"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:109
msgid "Description goes here."
msgstr "Описание"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:151
msgid "Filesystem"
msgstr "Файловая система"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:162
msgid "Reclaimable Space"
msgstr "Место для возврата"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:184
msgid "Action"
msgstr "Действие"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:249
msgid "<b>%s disks; %s reclaimable space</b> (in filesystems)"
msgstr "<b>%s дисков; место для возврата: %s</ b> (в файловых системах)"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:264
msgid "Total selected space to reclaim:  <b>%s</b>"
msgstr "Всего выбрано места для возрата: <b>%s</b>"

#: pyanaconda/ui/gui/spokes/lib/resize.glade:279
msgid "Installation requires a total of <b>%s</b> for system data."
msgstr "Установка требует <b>%s</b> для системных данных."

#: pyanaconda/ui/gui/main.glade:80
msgid ""
"Are you sure you wish to quit the\n"
"installation process?"
msgstr ""
"Действительно прервать\n"
"процесс установки?"

#: pyanaconda/ui/gui/hubs/summary.glade:11
msgid "INSTALLATION SUMMARY"
msgstr "ОБЗОР УСТАНОВКИ"

#: pyanaconda/ui/gui/hubs/summary.glade:95
msgid "_Begin Installation"
msgstr "_Начать установку"

#: pyanaconda/ui/gui/hubs/progress.glade:9
msgid "CONFIGURATION"
msgstr "КОНФИГУРАЦИЯ"

#: pyanaconda/ui/gui/hubs/progress.glade:128
msgid ""
"%s is now successfully installed on your system, but some configuration "
"still needs to be done. \n"
"Finish it and then click the Finish configuration button please."
msgstr ""
"%s успешно установлена на ваш компьютер, но требуется выполнить некоторую "
"настройку.\n"
"Завершите её и нажмите на кнопку «Завершить настройку»."

#: pyanaconda/ui/gui/hubs/progress.glade:140
msgid "_Finish configuration"
msgstr "Завершить настройку"

#: pyanaconda/ui/gui/hubs/progress.glade:181
msgid ""
"%s is now successfully installed on your system and ready\n"
"for you to use!  Go ahead and reboot to start using it!"
msgstr ""
"%s успешно установлена на компьютер и готова\n"
"к использованию!  Перезагрузите систему и начните использовать её!"

#: pyanaconda/ui/gui/hubs/progress.glade:193
msgid "_Reboot"
msgstr "_Перезагрузить"

#: widgets/src/BaseWindow.c:85
msgid "DISTRIBUTION INSTALLATION"
msgstr "УСТАНОВКА ДИСТРИБУТИВА"

#: widgets/src/BaseWindow.c:86
msgid "SPOKE NAME"
msgstr "Название для запоминания"

#: widgets/src/BaseWindow.c:87
msgid "PRE-RELEASE / TESTING"
msgstr "ПРЕДВАРИТЕЛЬНЫЙ ВЫПУСК / ТЕСТИРУЕМАЯ ВЕРСИЯ"

#: widgets/src/DiskOverview.c:50
msgid "New Device"
msgstr "Новое устройство"

#: widgets/src/DiskOverview.c:52
msgid "0 MB"
msgstr "0 Мб"

#: widgets/src/MountpointSelector.c:48
msgid "Root"
msgstr "Корень"

#: widgets/src/MountpointSelector.c:49
msgid "0 GB"
msgstr "0 Гб"

#: widgets/src/SpokeSelector.c:55
msgid "New Selector"
msgstr "Новый выбор"

#: data/liveinst/gnome/fedora-welcome:64
msgid "Welcome to Fedora"
msgstr "Добро пожаловать в Fedora"

#: data/liveinst/gnome/fedora-welcome:93
msgid "Try Fedora"
msgstr "Попробуйте Fedora"

#: data/liveinst/gnome/fedora-welcome:111
msgid ""
"You are currently running Fedora from live media.\n"
"You can install Fedora now, or choose \"Install to Hard Drive\" in the "
"Activities Overview at any later time."
msgstr ""
"Fedora запущена с установочного диска.\n"
"Вы можете установить Fedora сейчас или в любое время выбрать «Установить на "
"жесткий диск» в меню «Обзор»."

#: data/liveinst/gnome/fedora-welcome:129
msgid ""
"You can choose \"Install to Hard Drive\"\n"
"in the Activities Overview at any later time."
msgstr ""
"Вы можете в любое время выбрать «Установить на жесткий диск»\n"
"в пункте «Обзор»."

#: data/liveinst/gnome/fedora-welcome:132
msgid "Close"
msgstr "Закрыть"

#: data/liveinst/liveinst.desktop.in.h:1
msgid "Install to Hard Drive"
msgstr "Установить на жёсткий диск"

#: data/liveinst/liveinst.desktop.in.h:2
msgid "Install"
msgstr "Установить"

#: data/liveinst/liveinst.desktop.in.h:3
msgid "Install the live CD to your hard disk"
msgstr "Установить Live CD на жёсткий диск."

#: liveinst:5
msgid "Starting Install to Hard Drive"
msgstr "Начинается установка на жёсткий диск"
